// vp_test5.cg

uniform float3 lightDir : lightDir;

void main(float4 opos : ATTR0,
          float3 normal : ATTR2,
          float4 dcolor : ATTR3,
          out float4 hpos : HPOS,
          out float4 color : COLOR)
{
    hpos = opos;
    if (opos.x > opos.y) {
        color = dcolor.wzyx;
    } else {
        color = float4(dcolor.xyz*dot(normal, lightDir), dcolor.w);
    }
} // main



