#!/bin/sh

set -e
DBSCRPATH=/opt/dcgm-mgmt-agent

case "$1" in
    configure)
        # EXECUTE MY BASH COMMAND
        mkdir $DBSCRPATH/db
	python $DBSCRPATH/cosmosdb.py -k serial_number -v 12345
	python $DBSCRPATH/cosmosdb.py -k cloud_managed 		-v yes
	python $DBSCRPATH/cosmosdb.py -k cloud_group 		-v na
	python $DBSCRPATH/cosmosdb.py -k sw_version 		-v 1.0.1
	python $DBSCRPATH/cosmosdb.py -k serial_number 		-v 12345
	python $DBSCRPATH/cosmosdb.py -k cloud_status 		-v disconnected
	python $DBSCRPATH/cosmosdb.py -k gpu_configuration 	-v 4
	python $DBSCRPATH/cosmosdb.py -k model_name 		-v db2
	python $DBSCRPATH/cosmosdb.py -k eula_accepted 		-v no
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
        exit 0
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#update-alternatives --install /usr/bin/fakeroot fakeroot /usr/bin/fakeroot-ng 5 \
#        --slave /usr/share/man/man1/fakeroot.1.gz \
#            fakeroot.1.gz /usr/share/man/man1/fakeroot-ng.1.gz

exit 0
