#!/bin/bash

set -e

if [[ $# -ne 1 ]]; then
    echo "Usage: decodemle mods.mle" >&2
    exit 1
fi

if [[ ! -f $1 ]]; then
    echo "File $1 does not exist" >&2
    exit 1
fi

PROTOC="$P4ROOT"/sw/tools/linux/mods/protobuf/protoc_3.11.4

if [[ ! -x $PROTOC ]]; then
    echo "$PROTOC does not exist or is not exelwtable" >&2
    exit 1
fi

MLE_DIR="$P4ROOT/sw/dev/gpu_drv/chips_a/diag/mle"

if [[ ! -f $MLE_DIR/mle.proto ]]; then
    echo "$MLE_DIR/mle.proto not found" >&2
    exit 1
fi

exec "$PROTOC" --decode=MLE "--proto_path=$MLE_DIR" mle.proto < "$1"
