#
# LWIDIA_COPYRIGHT_BEGIN
#
# Copyright 2016-2020 by LWPU Corporation.  All rights reserved.  All
# information contained herein is proprietary and confidential to LWPU
# Corporation.  Any use, reproduction, or disclosure without the written
# permission of LWPU Corporation is prohibited.
#
# LWIDIA_COPYRIGHT_END
#

LW_MODS_MODULE := preproc_test bin

include $(LW_SOURCE)/drivers/common/build/lwCommon.lwmk

LW_INCLUDES += $(LW_DIAG_SOURCE)/mods
LW_INCLUDES += $(LW_SDK_SOURCE)
LW_INCLUDES += $(LW_TOOLS)/mods/boost2

SOURCES += preproc_test.cpp

ifeq ($(LW_TARGET_OS), Linux)
    LDFLAGS += -ldl -lpthread
endif

ifeq ($(LW_TARGET_OS), QNX)
    LDFLAGS += -lsocket
endif

ifeq ($(LW_TARGET_OS_FAMILY), Windows)
    BIN_LDFLAGS += ws2_32.lib crypt32.lib selwr32.lib gdi32.lib user32.lib
endif

LW_WARNINGS_AS_ERRORS  := 1
LW_AGGRESSIVE_WARNINGS := 1

######################################################################
# Make a private copy of lwdiag_utils to ensure that it was compiled
# together with the preprocessor test.  We must avoid using the
# checked-in version of liblwdiag_utils!!!
LW_MODS_LIBS += preproclwdiag

ifeq ($(LW_TARGET_OS_FAMILY), Windows)
    BIN_LDFLAGS += -LIBPATH:$(OUTPUTDIR)
else
    BIN_LDFLAGS += -L$(OUTPUTDIR)
endif

ifeq ($(LW_OUTPUT_ROOT),)
    LWDIAG_LOCATION = ../$(OUTPUTDIR)
else
    LWDIAG_LOCATION = $(OUTPUTDIR_ABSOLUTE)/..
endif

$(MODS_FULL_TARGET_PATH): $(OUTPUTDIR)/libpreproclwdiag$(LIBSUFFIX)

$(OUTPUTDIR)/libpreproclwdiag$(LIBSUFFIX): $(LWDIAG_LOCATION)/liblwdiag_utils$(LIBSUFFIX)
	$(COPY) $< $@

$(LWDIAG_LOCATION)/liblwdiag_utils$(LIBSUFFIX):
	$(MAKE) -C .. -f makefile.lwmk $*
######################################################################

test: $(MODS_FULL_TARGET_PATH)
	@PATH=/bin:/usr/bin ./run_preproc_tests.sh $(OUTPUTDIR_ABSOLUTE)/$(MODS_TARGET_FILE)

.PHONY: test

include $(LW_SOURCE)/drivers/common/build/lwCommonRules.lwmk
