###############################################################################
#
# Copyright (c) 2020, LWPU CORPORATION.  All Rights Reserved.
#
# LWPU CORPORATION and its licensors retain all intellectual property
# and proprietary rights in and to this software, related documentation
# and any modifications thereto.  Any use, reproduction, disclosure or
# distribution of this software and related documentation without an express
# license agreement from LWPU CORPORATION is strictly prohibited.
#
# tmake for SW Mobile component makefile
#
###############################################################################

ifdef LW_COMPONENT_FLAG_LWTEST_LIBRARY_SECTION
include $(LW_BUILD_START_COMPONENT)

LW_COMPONENT_NAME := aftermath-unit-test

# Test frame work sources
LW_COMPONENT_SOURCES := \
  ../common/src/AftermathTest.cpp \
  ../common/src/AftermathTestEmpty.cpp \
  ../common/src/AftermathTestLogging.cpp \
  ../common/src/AftermathTestMain.cpp \
  ../common/src/AftermathTestUtils.cpp \
  ../common/src/AftermathTestUtilsDisplay.cpp \
  ../common/src/AftermathTestUtilsLWN.cpp

# Test sources
LW_COMPONENT_SOURCES += \
  src/AftermathTestEventMarkerManager.cpp \
  src/AftermathTestFileStreaming.cpp \
  src/AftermathTestFileSystem.cpp \
  src/AftermathTestLinkedList.cpp \
  src/AftermathTestNxgcdReader.cpp

# Tested implementations
LW_COMPONENT_SOURCES += \
  $(LW_SOURCE)/gpu/drv/drivers/lwn/devtools/aftermath/aftermath-target/src/AftermathCheckpoints.cpp \
  $(LW_SOURCE)/gpu/drv/drivers/lwn/devtools/aftermath/aftermath-target/src/AftermathCmdMemoryTracking.cpp \
  $(LW_SOURCE)/gpu/drv/drivers/lwn/devtools/aftermath/aftermath-target/src/AftermathDataCollection.cpp \
  $(LW_SOURCE)/gpu/drv/drivers/lwn/devtools/aftermath/aftermath-target/src/AftermathDevtoolsAllocator.cpp \
  $(LW_SOURCE)/gpu/drv/drivers/lwn/devtools/aftermath/aftermath-target/src/AftermathFileStreaming.cpp \
  $(LW_SOURCE)/gpu/drv/drivers/lwn/devtools/aftermath/aftermath-target/src/AftermathFileSystem.cpp \
  $(LW_SOURCE)/gpu/drv/drivers/lwn/devtools/aftermath/aftermath-target/src/AftermathGlobals.cpp \
  $(LW_SOURCE)/gpu/drv/drivers/lwn/devtools/aftermath/aftermath-target/src/AftermathLogging.cpp \
  $(LW_SOURCE)/gpu/drv/drivers/lwn/devtools/aftermath/aftermath-target/src/AftermathNxgcdReader.cpp \
  $(LW_SOURCE)/gpu/drv/drivers/lwn/devtools/aftermath/aftermath-target/src/AftermathResourceTracking.cpp \
  $(LW_SOURCE)/gpu/drv/drivers/lwn/devtools/aftermath/aftermath-target/src/AftermathStateTracking.cpp \
  $(LW_SOURCE)/gpu/drv/drivers/lwn/devtools/aftermath/aftermath-target/src/AftermathEventListener.cpp \
  $(LW_SOURCE)/gpu/drv/drivers/lwn/devtools/aftermath/aftermath-target/src/AftermathTarget.cpp

LW_COMPONENT_INCLUDES := \
  ../common/inc \
  $(LW_SOURCE)/core/include \
  $(LW_SOURCE)/gpu/drv/drivers/common/inc \
  $(LW_SOURCE)/gpu/drv/drivers/lwn \
  $(LW_SOURCE)/gpu/drv/drivers/lwn/include \
  $(LW_SOURCE)/gpu/drv/drivers/lwn/interface \
  $(LW_SOURCE)/gpu/drv/drivers/lwn/interface/lwnExt \
  $(LW_SOURCE)/gpu/drv/drivers/lwn/public \
  $(LW_SOURCE)/gpu/drv/drivers/lwn/public/lwn \
  $(LW_SOURCE)/gpu/drv/drivers/lwn/devtools \
  $(LW_SOURCE)/gpu/drv/drivers/lwn/devtools/aftermath/aftermath-target/inc \
  $(LW_SOURCE)/gpu/drv/sdk/lwpu/inc

LW_COMPONENT_NEEDED_INTERFACE_DIRS := \
  $(LW_INTERFACE_CORE_LWOS) \
  $(LW_INTERFACE_GPU_GRAPHICS_LWN)

LW_COMPONENT_CFLAGS += -DLWN_ONLY -DLW_RMAPI_TEGRA

LW_COMPONENT_POST_PROCESS_INPUT += \
  ../common/build/aftermath-test.desc

ifeq ($(LW_TARGET_ARCH),hos_64)
LW_COMPONENT_POST_PROCESS_INPUT += \
  ../common/build/aftermath-test.aarch64.lp64.nmeta
else
LW_COMPONENT_POST_PROCESS_INPUT += \
  ../common/build/aftermath-test.arm.ilp32.nmeta
endif

include $(LW_BUILD_DYNAMIC_EXELWTABLE)
endif
