// fp50_tbf_exp.cg - tex-blend-fog for exponential fog.

float4 main(float4 color : COLOR0,
            float4 tex0 : TEX0,
            float fogfactor : FOG,
            sampler2D texture0,
            uniform float4 fogcolor : FOGCOLOR,
            uniform float fogpower : FOGPOWER) : COLOR
{
    float4 tcolor, result;
    float ff;

    tcolor = tex2D(texture0, tex0.xy)*color;
    ff = exp2(fogfactor*fogpower);
    // result = tcolor*(1 - ff) + ff*fogcolor;
    result = ff*(fogcolor - tcolor) + tcolor;
    return result;
} // main


