// fp50_tex.cg - Try some TEX instructions

float4 main(float4 color : COLOR0,
            float4 tex0 : TEX0,
            float4 tex1 : TEX1,
            float4 tex2 : TEX2,
            float4 tex3 : TEX3,
            sampler1D texture0,
            sampler2D texture1,
            sampler3D texture2,
            samplerLWBE texture3) : COLOR
{
    float4 tcolor1D, tcolor2D, tcolor3D, tcolorLWBE, result;

    tcolor1D = tex1D(texture0, tex0.x);
    tcolor2D = tex2D(texture1, tex1.xy);
    tcolor3D = tex3D(texture2, tex2.xyz);
    tcolorLWBE = texLWBE(texture3, tex3.xyz);
    result = (tcolor1D*tcolor2D + tcolor3D)*tcolorLWBE;
    return result;
} // main


