// fp50_lwbe.cg - Try some lwbemap textures.

float4 main(float4 color : COLOR0,
            float4 tex0 : TEX0,
            float4 tex1 : TEX1,
            float4 tex2 : TEX2,
            float4 tex3 : TEX3,
            samplerLWBE texture0,
            samplerLWBE texture1) : COLOR
{
    float4 tcolor1, tcolor2, result;

    tcolor1 = texLWBE(texture0, tex0.xyz);
    tcolor2 = texLWBEproj(texture1, tex1.xyzw);
    result = tcolor1*tcolor2;
    return result;
} // main



