// fp50_8.cg - Multiple reference to same texture coords.

float4 main(float4 color : COLOR0,
            float4 tex0 : TEX0,
            float fogfactor : FOG,
            sampler2D texture0,
            sampler2D texture1,
            uniform float4 fogcolor : FOGCOLOR,
            uniform float fogpower : FOGPOWER) : COLOR
{
    float4 tcolor, tcolor2, result;

    tcolor = tex2D(texture0, tex0.xy);
    tcolor2 = tex2D(texture1, tex0.xy);
    result = tcolor + tcolor2;
    return result;
} // main


