// fp50_f2f.cg - Various uses of the f2f instruction

float4 main(float4 color : COLOR0,
            float4 tex0 : TEX0,
            float fogfactor : FOG,
            sampler2D texture0,
            uniform float4 fogcolor : FOGCOLOR) : COLOR
{
    float4 tcolor, result;

    tcolor = tex2D(texture0, tex0.xy);
    result = floor(tcolor)*ceil(color);
    result = clamp(result, 0, 1);
    return result;
} // main


