// fp50_txp.cg - Try some TXP instructions

float4 main(float4 color : COLOR0,
            float4 tex0 : TEX0,
            float4 tex1 : TEX1,
            float4 tex2 : TEX2,
            float4 tex3 : TEX3,
            sampler1D texture0,
            sampler2D texture1,
            sampler3D texture2,
            samplerLWBE texture3) : COLOR
{
    float4 tcolor1D, tcolor2D, tcolor3D, tcolorLWBE, result;

    tcolor1D = tex1Dproj(texture0, tex0.xw);
    tcolor2D = tex2Dproj(texture1, tex1.xyw);
    tcolor3D = tex3Dproj(texture2, tex2.xyzw);
    tcolorLWBE = texLWBEproj(texture3, tex3.xyzw);
    result = (tcolor1D*tcolor2D + tcolor3D)*tcolorLWBE;
    return result;
} // main


