// fp50_int4.cg - try some integer operations.

__internal int max(int, int);
__internal int min(int, int);
__internal int abs(int);

float4 main(float4 color : COLOR0,
            uniform int4 arg1 : INTVALS_1) : COLOR
{
    int4 tcolor;
    float4 result;

    tcolor.x = max((int) color.x, arg1.x);
    tcolor.y = min((int) color.y, arg1.y);
    tcolor.z = abs(arg1.z);
    tcolor.w = -abs(arg1.w);
    result = (float4) tcolor;
    return result;
} // main


