// fp50_tbf.cg - tex-blend-fog for linear fog

float4 main(float4 color : COLOR0,
            float4 tex0 : TEX0,
            float fogfactor : FOG,
            sampler2D texture0,
            uniform float4 fogcolor : FOGCOLOR) : COLOR
{
    float4 tcolor, result;

    tcolor = tex2D(texture0, tex0.xy)*color;
    // result = tcolor*(1 - fogfactor) + fogfactor*fogcolor;
    result = fogfactor*(fogcolor - tcolor) + tcolor;
    return result;
} // main


