// fp50_trans.cg - Try som transcendental functions

float4 main(float4 color : COLOR0,
            float4 tex0 : TEX0,
            float fogfactor : FOG,
            sampler2D texture0,
            uniform float4 fogcolor : FOGCOLOR,
            uniform float fogpower : FOGPOWER) : COLOR
{
    float4 tcolor, result;
    float ff;

    tcolor = tex2D(texture0, tex0.xy)*color;
    ff = exp2(fogfactor*fogpower);
    ff = log2(tcolor.x)*ff + sin(tcolor.y)*cos(tcolor.z);
    ff = pow(ff, tcolor.w);
    result = ff*(fogcolor - tcolor) + tcolor;
    return result;
} // main


