// fp50_const.cg - Constants

float4 main(float4 color : COLOR0,
            float4 tex0 : TEX0,
            float fogfactor : FOG,
            sampler2D texture0,
            sampler2D texture1,
            uniform float4 fogcolor : FOGCOLOR,
            uniform float fogpower : FOGPOWER) : COLOR
{
    float4 tcolor, tcolor2, result;

    // tcolor = tex2D(texture0, tex0.xy);
    // tcolor = tex2D(texture0, tex0.xy);
    // result = tcolor*float4(1.1, 2.2, 3.3, 4.4);
    result = color*float4(1.1, 2.2, 3.3, 4.4);
    return result;
} // main


