// fp50_int3.cg - try some integer operations.

float4 main(float4 color : COLOR0,
            uniform int4 arg1 : INTVALS_1) : COLOR
{
    int4 tcolor;
    float4 result;

    tcolor.x = (int) color.x & arg1.x;
    tcolor.y = (int) color.y | arg1.y;
    tcolor.z = (int) color.z ^ arg1.z;
    tcolor.w = ~((int) color.w);
    result = (float4) tcolor;
    return result;
} // main


