/* _LWRM_COPYRIGHT_BEGIN_
 *
 * Copyright 2003-2011 by LWPU Corporation.  All rights reserved.  All
 * information contained herein is proprietary and confidential to LWPU
 * Corporation.  Any use, reproduction, or disclosure without the written
 * permission of LWPU Corporation is prohibited.
 *
 * _LWRM_COPYRIGHT_END_
 */

/* This file is autogenerated by ref2h.pl.  Do not edit */


#ifndef CLASS_IDS_H_INC
#define CLASS_IDS_H_INC

#define LW_HOST1X_CLASS_ID                      0x01

#define LW_VIDEO_ENCODE_MPEG_CLASS_ID           0x20
#define LW_VIDEO_ENCODE_MSENC_CLASS_ID          0x21

#define LW_VIDEO_STREAMING_VI_CLASS_ID          0x30
#define LW_VIDEO_STREAMING_EPP_CLASS_ID         0x31
#define LW_VIDEO_STREAMING_ISP_CLASS_ID         0x32
#define LW_VIDEO_STREAMING_VCI_CLASS_ID         0x33
#define LW_VIDEO_STREAMING_ISPB_CLASS_ID        0x34

#define LW_GRAPHICS_2D_DOWNLOAD_CLASS_ID        0x50
#define LW_GRAPHICS_2D_CLASS_ID                 0x51
#define LW_GRAPHICS_2D_SB_CLASS_ID              0x52
#define LW_GRAPHICS_2D_DOWNLOAD_CTX1_CLASS_ID   0x54
#define LW_GRAPHICS_2D_CTX1_CLASS_ID            0x55
#define LW_GRAPHICS_2D_SB_CTX1_CLASS_ID         0x56
#define LW_GRAPHICS_2D_DOWNLOAD_CTX2_CLASS_ID   0x58
#define LW_GRAPHICS_2D_SB_CTX2_CLASS_ID         0x5A

#define LW_GRAPHICS_VS_CLASS_ID                 0x5C
#define LW_GRAPHICS_VIC_CLASS_ID                0x5D

#define LW_GRAPHICS_3D_CLASS_ID                 0x60
#define LW_GRAPHICS_GPU_CLASS_ID                0x61

#define LW_DISPLAY_CLASS_ID                     0x70
#define LW_DISPLAYB_CLASS_ID                    0x71
#define LW_DISPLAYC_CLASS_ID                    0x72
#define LW_DISP_CLASS_ID                        0x70
#define LW_DISPB_CLASS_ID                       0x71
#define LW_DISPC_CLASS_ID                       0x72
#define LW_HDMI_CLASS_ID                        0x77
#define LW_DISPLAY_TVO_CLASS_ID                 0x78
#define LW_DISPLAY_DSI_CLASS_ID                 0x79
#define LW_DISPLAY_DSIB_CLASS_ID                0x7A
#define LW_SOR_CLASS_ID                         0x7B
#define LW_SOR1_CLASS_ID                        0x7C
#define LW_DPAUX_CLASS_ID                       0x7D

#define LW_GRAPHICS_VG_CLASS_ID                 0xD0

#endif
