/*
* _LWRM_COPYRIGHT_BEGIN_
*
* Copyright 2011-2015 by LWPU Corporation.  All rights reserved.  All
* information contained herein is proprietary and confidential to LWPU
* Corporation.  Any use, reproduction, or disclosure without the written
* permission of LWPU Corporation is prohibited.
*
* _LWRM_COPYRIGHT_END_
*/

#pragma once

//
// This file was generated with FINN, an LWPU coding tool.
// Source file: ctrl/ctrla26f.finn
//
#if (!defined(LWRM_UNPUBLISHED) || LWRM_UNPUBLISHED == 1)
//
// Please edit the original FINN IDL file to create desired edits in this header
// See https://confluence.lwpu.com/display/CORERM/FINN for more info on how to
// edit FINN.
//
#endif // (!defined(LWRM_UNPUBLISHED) || LWRM_UNPUBLISHED == 1)




/* GK20A_GPFIFO control commands and parameters */

#include "ctrl/ctrlxxxx.h"
#include "ctrl/ctrla06f.h"          /* A26F is partially derived from A06F */
#include "ctrl/ctrl906f.h"          /* A26F is partially derived from 906F */
#define LWA26F_CTRL_CMD(cat,idx)  \
    LWXXXX_CTRL_CMD(0xA26F, LWA26F_CTRL_##cat, idx)

/* GK20A_GPFIFO command categories (6bits) */
#define LWA26F_CTRL_RESERVED (0x00)
#define LWA26F_CTRL_GPFIFO   (0x01)
#define LWA26F_CTRL_EVENT    (0x02)

/*
 * LWA26F_CTRL_CMD_NULL
 *
 * This command does nothing.
 * This command does not take any parameters.
 *
 * Possible status values returned are:
 *   LW_OK
 */
#define LWA26F_CTRL_CMD_NULL (0xa26f0000) /* finn: Evaluated from "(FINN_KEPLER_CHANNEL_GPFIFO_C_RESERVED_INTERFACE_ID << 8) | 0x0" */





/*
 * LWA26F_CTRL_GET_CLASS_ENGINEID
 *
 * Please see description of LW906F_CTRL_GET_CLASS_ENGINEID for more information.
 *   
 */
#define LWA26F_CTRL_GET_CLASS_ENGINEID (0xa26f0101) /* finn: Evaluated from "(FINN_KEPLER_CHANNEL_GPFIFO_C_GPFIFO_INTERFACE_ID << 8) | 0x1" */

typedef LW906F_CTRL_GET_CLASS_ENGINEID_PARAMS LWA26F_CTRL_GET_CLASS_ENGINEID_PARAMS;

// FINN PORT: The below type was generated by the FINN port to
// ensure that all API's have a unique structure associated
// with them!
#define LWA26F_CTRL_GET_CLASS_ENGINEID_FINN_PARAMS_MESSAGE_ID (0x1U)

typedef struct LWA26F_CTRL_GET_CLASS_ENGINEID_FINN_PARAMS {
    LWA26F_CTRL_GET_CLASS_ENGINEID_PARAMS params;
} LWA26F_CTRL_GET_CLASS_ENGINEID_FINN_PARAMS;



/*
 * LWA26F_CTRL_RESET_CHANNEL
 *
 * Please see description of LWA06F_CTRL_CMD_RESET_CHANNEL for more information. 
 *
 */
#define LWA26F_CTRL_CMD_RESET_CHANNEL (0xa26f0102) /* finn: Evaluated from "(FINN_KEPLER_CHANNEL_GPFIFO_C_GPFIFO_INTERFACE_ID << 8) | 0x2" */
typedef LWA06F_CTRL_CMD_RESET_CHANNEL_PARAMS LWA26F_CTRL_CMD_RESET_CHANNEL_PARAMS;

// FINN PORT: The below type was generated by the FINN port to
// ensure that all API's have a unique structure associated
// with them!
#define LWA26F_CTRL_CMD_RESET_CHANNEL_FINN_PARAMS_MESSAGE_ID (0x2U)

typedef struct LWA26F_CTRL_CMD_RESET_CHANNEL_FINN_PARAMS {
    LWA26F_CTRL_CMD_RESET_CHANNEL_PARAMS params;
} LWA26F_CTRL_CMD_RESET_CHANNEL_FINN_PARAMS;



/*
 * LWA26F_CTRL_CMD_GPFIFO_SCHEDULE
 *
 * Please see description of LWA06F_CTRL_CMD_GPFIFO_SCHEDULE for more information.
 *
 */
#define LWA26F_CTRL_CMD_GPFIFO_SCHEDULE (0xa26f0103) /* finn: Evaluated from "(FINN_KEPLER_CHANNEL_GPFIFO_C_GPFIFO_INTERFACE_ID << 8) | 0x3" */
typedef LWA06F_CTRL_GPFIFO_SCHEDULE_PARAMS LWA26F_CTRL_GPFIFO_SCHEDULE_PARAMS;

// FINN PORT: The below type was generated by the FINN port to
// ensure that all API's have a unique structure associated
// with them!
#define LWA26F_CTRL_CMD_GPFIFO_SCHEDULE_FINN_PARAMS_MESSAGE_ID (0x3U)

typedef struct LWA26F_CTRL_CMD_GPFIFO_SCHEDULE_FINN_PARAMS {
    LWA26F_CTRL_GPFIFO_SCHEDULE_PARAMS params;
} LWA26F_CTRL_CMD_GPFIFO_SCHEDULE_FINN_PARAMS;



/*
 * LWA26F_CTRL_CMD_BIND
 *
 * Please see description of LWA06F_CTRL_CMD_BIND for more information.
 */
#define LWA26F_CTRL_CMD_BIND (0xa26f0104) /* finn: Evaluated from "(FINN_KEPLER_CHANNEL_GPFIFO_C_GPFIFO_INTERFACE_ID << 8) | 0x4" */

typedef LWA06F_CTRL_BIND_PARAMS LWA26F_CTRL_BIND_PARAMS;

// FINN PORT: The below type was generated by the FINN port to
// ensure that all API's have a unique structure associated
// with them!
#define LWA26F_CTRL_CMD_BIND_FINN_PARAMS_MESSAGE_ID (0x4U)

typedef struct LWA26F_CTRL_CMD_BIND_FINN_PARAMS {
    LWA26F_CTRL_BIND_PARAMS params;
} LWA26F_CTRL_CMD_BIND_FINN_PARAMS;



/*
 * LWA26F_CTRL_CMD_EVENT_SET_NOTIFICATION
 *
 * Please see description of LWA06F_CTRL_CMD_EVENT_SET_NOTIFICATION for more information.
*/


#define LWA26F_CTRL_CMD_EVENT_SET_NOTIFICATION (0xa26f0205) /* finn: Evaluated from "(FINN_KEPLER_CHANNEL_GPFIFO_C_EVENT_INTERFACE_ID << 8) | 0x5" */

typedef LWA06F_CTRL_EVENT_SET_NOTIFICATION_PARAMS LWA26F_CTRL_EVENT_SET_NOTIFICATION_PARAMS;

// FINN PORT: The below type was generated by the FINN port to
// ensure that all API's have a unique structure associated
// with them!
#define LWA26F_CTRL_CMD_EVENT_SET_NOTIFICATION_FINN_PARAMS_MESSAGE_ID (0x5U)

typedef struct LWA26F_CTRL_CMD_EVENT_SET_NOTIFICATION_FINN_PARAMS {
    LWA26F_CTRL_EVENT_SET_NOTIFICATION_PARAMS params;
} LWA26F_CTRL_CMD_EVENT_SET_NOTIFICATION_FINN_PARAMS;



/* valid action values */
#define LWA26F_CTRL_EVENT_SET_NOTIFICATION_ACTION_DISABLE LWA06F_CTRL_EVENT_SET_NOTIFICATION_ACTION_DISABLE
#define LWA26F_CTRL_EVENT_SET_NOTIFICATION_ACTION_SINGLE  LWA06F_CTRL_EVENT_SET_NOTIFICATION_ACTION_SINGLE
#define LWA26F_CTRL_EVENT_SET_NOTIFICATION_ACTION_REPEAT  LWA06F_CTRL_EVENT_SET_NOTIFICATION_ACTION_REPEAT

/*
 * LWA26F_CTRL_CMD_EVENT_SET_TRIGGER
 *
 * Please see description of LWA06F_CTRL_CMD_EVENT_SET_TRIGGER for more information.
 */
#define LWA26F_CTRL_CMD_EVENT_SET_TRIGGER                 (0xa26f0206) /* finn: Evaluated from "(FINN_KEPLER_CHANNEL_GPFIFO_C_EVENT_INTERFACE_ID << 8) | 0x6" */





/*
 * LWA26F_CTRL_CMD_GET_MMU_FAULT_INFO
 *
 * Please see description of LW906F_CTRL_CMD_GET_MMU_FAULT_INFO for more information.
 *   
 */
#define LWA26F_CTRL_CMD_GET_MMU_FAULT_INFO (0xa26f0107) /* finn: Evaluated from "(FINN_KEPLER_CHANNEL_GPFIFO_C_GPFIFO_INTERFACE_ID << 8) | 0x7" */

typedef LW906F_CTRL_GET_MMU_FAULT_INFO_PARAMS LWA26F_CTRL_GET_MMU_FAULT_INFO_PARAMS;

// FINN PORT: The below type was generated by the FINN port to
// ensure that all API's have a unique structure associated
// with them!
#define LWA26F_CTRL_CMD_GET_MMU_FAULT_INFO_FINN_PARAMS_MESSAGE_ID (0x7U)

typedef struct LWA26F_CTRL_CMD_GET_MMU_FAULT_INFO_FINN_PARAMS {
    LW_DECLARE_ALIGNED(LWA26F_CTRL_GET_MMU_FAULT_INFO_PARAMS params, 8);
} LWA26F_CTRL_CMD_GET_MMU_FAULT_INFO_FINN_PARAMS;



/* _ctrla26f.h_ */
