// cp50_6.cg - Simple compute program.  References LMEM, GMEM and GRF

float lmemory[20] : local;
float gmemory3[20] : global[3];
float fast[10] : shared;

void main(uniform float4 gcolor : GCOLOR)
{
    float4 color;

    color = gcolor;
    lmemory[10] = color.z;
    fast[0] = gmemory3[0];
    fast[1] = fast[0]*color.y + lmemory[10];
    fast[1] = fast[1] + fast[2];
    gmemory3[1] = fast[1];
} // main

