// cp50_5.cg - Simple compute program.  4, 8, 12, and 16 byte refs.

float a : global;
float2 b : global[2];
float3 c : global[3];
float4 d : global[4];
float4 result : global[9];

void main(uniform float4 gcolor : GCOLOR)
{
    float4 color;

    color = gcolor;
    color.x = color.x*a;
    color.xy = color.xy*b;
    color.xyz = color.xzy*c;
    color = color*d;
    result = color;
} // main

