// cp50_iread2.cg - Indexed reads of all memory types.

float lmem[10] : local;
float2 lmem2[10] : local;
// float3 lmem3[10] : local; // Cg front-end barfs on this
float4 lmem4[10] : local;
float4 answer : global;

void main(uniform float4 gcolor : GCOLOR,
          uniform int4 ii : INDEX,
          uniform int4 jj : INDEX2)
{
    float4 color;

    color = gcolor;
    color.x    += lmem[ii.x];
    color.xy   += lmem2[ii.y];
    color.z    += lmem2[ii.z].x;
    color.w    += lmem2[ii.w].y; // Optimizer barfs on this
//  color.xyz  += lmem3[jj.x];
    color.xyzw += lmem4[jj.y];
    color.w    += lmem4[jj.z].w;
    answer = color;
} // main

