// cp50_iread1.cg - Indexed reads of all memory types.

float lmem[10] : local;
float gmem3[10] : global[3];
float4 answer: global[3];
float fast[10] : shared;

void main(uniform float4 gcolor : GCOLOR,
          uniform int4 index : INDEX)
{
    float4 color;

    color = gcolor;
    color.x += gmem3[index.x];
    color.y += lmem[index.y];
    color.z += fast[index.z];
    answer = color;
} // main

