int imem : global;
float fmem : global;
unsigned int umem : global;
float result : global;
float result2 : global;

void main (
           uniform int x              : shared,
           uniform int y              : shared,
           uniform int threadCount    : shared,
           varying int tid            : thread_id) 
{
    int a;
    float b;
    unsigned int c;

    a = imem;
    if (!a)
        result = 2;
    if (a)
        result = 3;
    b = fmem;
    if (!b)
        result = 5;
    if (b)
        result = 7;
    c = umem;
    if (!c)
        result = 11;
    if (c)
        result = 13;
}
