#!/usr/bin/python
import sys

#*****************************************************************************
# This script generates a !.nact file from LWNtest SrcList.inc file to avoid 
# missing update of the !.nact file
#
# ARG[1] is the template name
# ARG[2] is the file to be generated (i.e. !.nact.gen)
# ARG[3]  contains a string of all source files from SrcList.inc

try:
    template = open(sys.argv[1], 'r')
except IOError:
    print ("FATAL: couldn't open template %s for reading." % sys.argv[1])
    exit(0)

try:
    f = open(sys.argv[2], 'w')
except IOError:
    print ("FATAL: couldn't open %s for writing." % sys.argv[2])
    exit(0)

f.write("# /* THIS FILE IS AUTOMATICALLY GENERATED - DO NOT EDIT */\n")
f.write("# /* EDIT SRCFILE.INC AND LWMAKE @GENERATE TO REFRESH THIS */\n")
f.write("LwnTestCommon = Constants\n")
f.write("{\n")
f.write("   SrcFiles=List(\n")


# last item in list must not have a comma
source_list = str(sys.argv[3]).split()
last_item = len(source_list) - 1
for i, source in enumerate(source_list):
   if i != last_item:
       f.write('        f"%s",\n' % source)
   else:
       f.write('        f"%s"\n' % source)

f.write("   );\n")
f.write("}\n")
f.write("\n")

f.write(template.read())

f.close()
template.close()
