#!/bin/bash
#SBATCH --ntasks-per-node=1
#SBATCH --time=06:00:00
#SBATCH --exclusive
#SBATCH --partition=batch

source ~/lwca-11.2.sh
cd ~/lwtensor
source elw.sh
cd test/regression/contraction

#export LWTENSOR_DISABLE_LWBLAS=1

#srun --cpu-bind=cores ./run.sh 0&
srun --cpu-bind=cores ./run.sh 0&
srun --cpu-bind=cores ./run.sh 1&
srun --cpu-bind=cores ./run.sh 2&
srun --cpu-bind=cores ./run.sh 3&
srun --cpu-bind=cores ./run.sh 4&

wait
