/*
 * LWIDIA_COPYRIGHT_BEGIN
 *
 * Copyright 2020 by LWPU Corporation.  All rights reserved.
 * All information contained herein is proprietary and confidential to LWPU
 * Corporation.  Any use, reproduction, or disclosure without the written
 * permission of LWPU Corporation is prohibited.
 *
 * LWIDIA_COPYRIGHT_END
 */

// A simple application to read/write protobuf messages would perform the following
// steps
//
// 1. Create a protobuf definition file
// 2. Use protobuf.py to process the protobuf definition file into headers for
//    writing messages, reading messages, and a structure for storing the results
// 3. Create a file for parsing the messages that includes pbreader.h, pbreader_parse.h,
//    and the reader and struct files generated by protobuf.py
//
// See the simple example under the example directory

#pragma once

namespace ProtobufCommon
{
    // Supported protobuf wire types
    enum class Wire
    {
        VarInt = 0,
        Double = 1,
        Bytes  = 2,
        Rsvd3  = 3, // deprecated in protobuf v3
        Rsvd4  = 4, // deprecated in protobuf v3
        Float  = 5
    };
}
