// TLOG_T(+3): Cg shader: 
#pragma option(unroll none)
#define i2f intBitsToFloat
void main( out float4 oColor : COLOR,
           out float oDepth : DEPTH  )
{
    float4 R1 = 0;
    float4 R0 = 0;


    //  MOVr r1.z, const;
    // const values (approx): 0.5 0.5 0.5 0.5 
    float4 const0 = {i2f(0x3f000000), i2f(0x3f000000), i2f(0x3f000000), i2f(0x3f000000)};
    R1 = 0;
    R1.z = (const0).z;

    //  MOVr r0, const;
    // const values (approx): 0 1 0 1 
    float4 const1 = {i2f(0x0), i2f(0x3f800000), i2f(0x0), i2f(0x3f800000)};
    R0 = const1;

    oDepth = R1.z;
        oColor = R0;
}
// TLOG_T(+3): Command Line: -profile fpf -nofastmath -po cimm,hexfp,ubank=14 -po sm40 -po hint=2
