// TLOG_T(+3): Cg shader: 
#pragma option(unroll none)
#define i2f intBitsToFloat
void main( out float4 oColor : COLOR,
           float4 i_wPos : WPOS,
           out float oDepth : DEPTH  )
{
    float4 R1 = 0;
float4 R0 = 0;
    

    //  ADDr r1.z, f[WPOS], const;
    // const values (approx): 0 0 0.8 0 
    float4 const0 = {i2f(0x0), i2f(0x0), i2f(0x3f4ccccd), i2f(0x0)};
    R1 = 0;
    R1.z = (i_wPos + const0).z;

    oDepth = R1.z;
        oColor = R0;
}
// TLOG_T(+3): Command Line: -profile fpf -nofastmath -po cimm,hexfp,ubank=14 -po sm40 -po hint=2
