// TLOG_T(+3): Cg shader: 
void main(float4 fCOLOR0 : COLOR0,
          float4 fTEXCOORD0 : TEXCOORD0,
          out float4 H0 : COLOR,
          uniform samplerLWBE TEX0 : TEXUNIT0) {
    float4 H2;
    float4 H3;
    H2      = texLWBEproj(TEX0, fTEXCOORD0);
    H3.xyz  = lerp(fCOLOR0.xyz, H2.xyz, H2.www);
    H3.w    = fCOLOR0.w;
    H0      = H3;
    return;
};
// TLOG_T(+3): Command Line: -profile fpf -nofastmath -po cimm,hexfp,ubank=14 -po sm40 -po hint=2
