###############################################################################
#
# Copyright (c) 2020, LWPU CORPORATION.  All Rights Reserved.
#
# LWPU CORPORATION and its licensors retain all intellectual property
# and proprietary rights in and to this software, related documentation
# and any modifications thereto.  Any use, reproduction, disclosure or
# distribution of this software and related documentation without an express
# license agreement from LWPU CORPORATION is strictly prohibited.
#
# tmake for SW Mobile component makefile
#
###############################################################################

ifdef LW_COMPONENT_FLAG_LWTEST_LIBRARY_SECTION
include $(LW_BUILD_START_COMPONENT)

LW_COMPONENT_NAME := aftermath-api-test

# Test frame work sources
LW_COMPONENT_SOURCES := \
  ../common/src/AftermathTest.cpp \
  ../common/src/AftermathTestEmpty.cpp \
  ../common/src/AftermathTestLogging.cpp \
  ../common/src/AftermathTestMain.cpp \
  ../common/src/AftermathTestUtils.cpp \
  ../common/src/AftermathTestUtilsDisplay.cpp \
  ../common/src/AftermathTestUtilsLWN.cpp

# Test sources
LW_COMPONENT_SOURCES += \
  src/AftermathTestAPI.cpp

LW_COMPONENT_CFLAGS += -DDEFER_INIT_GRAPHICS

LW_COMPONENT_INCLUDES := \
  ../common/inc \
  $(LW_SOURCE)/core/include \
  $(LW_SOURCE)/gpu/drv/drivers/lwn \
  $(LW_SOURCE)/gpu/drv/drivers/lwn/interface/lwnExt \
  $(LW_SOURCE)/gpu/drv/drivers/lwn/public \
  $(LW_SOURCE)/gpu/drv/drivers/lwn/public/lwn \
  $(LW_SOURCE)/gpu/drv/drivers/lwn/devtools \
  $(LW_SOURCE)/gpu/drv/sdk/lwpu/inc

LW_COMPONENT_NEEDED_INTERFACE_DIRS := \
  $(LW_INTERFACE_CORE_LWOS) \
  $(LW_INTERFACE_GPU_GRAPHICS_LWN) \
  $(LW_INTERFACE_GPU_GRAPHICS_LWN)/../devtools/aftermath/aftermath-target

LW_COMPONENT_POST_PROCESS_INPUT += \
  ../common/build/aftermath-test.desc

ifeq ($(LW_TARGET_ARCH),hos_64)
LW_COMPONENT_POST_PROCESS_INPUT += \
  ../common/build/aftermath-test.aarch64.lp64.nmeta
else
LW_COMPONENT_POST_PROCESS_INPUT += \
  ../common/build/aftermath-test.arm.ilp32.nmeta
endif

include $(LW_BUILD_DYNAMIC_EXELWTABLE)
endif
