// This file is automatically generated by {{$name}} - DO NOT EDIT!
//
// Provides access to {{$ENGINE}} Hal interfaces.
//
// Profile:  {{$PROFILE}}
// Haldef:   {{$DEF_FILE}}
// Template: {{$TEMPLATE_FILE}}
//

#ifndef _G_{{$ENGINE}}HAL_H_
#define _G_{{$ENGINE}}HAL_H_

//
// Typedefs for {{$ENGINE}} public object interfaces.
//

{{ OBJECT_INTERFACE_FUNCTION_TYPEDEFS() }}
//
// {{$ENGINE}}'s object-level *non-static* interface functions (static ones are below)
//
{{ OBJ_INTERFACE_PROTOTYPES(':NON_STATIC') }}
//
// Typedefs for {{$ENGINE}} HAL interfaces.
//

{{ HAL_INTERFACE_FUNCTION_TYPEDEFS() }}

//
// struct to access {{$ENGINE}}'s hal interfaces, eg:  p{{$Engine}}->hal.{{$engine}}ReadFoo(pGpu, p{{$Engine}})
//

{{ HAL_ENGINE_INTERFACE_TYPEDEF() }}

//
// global {{$ENGINE}}_LWHAL_IFACES object to be able to access this engine functions 
// MAX number of GPUs are allowed for hybrid GPUs
// eg: extern {{$ENGINE}}_LWHAL_IFACES {{$engine}}[MAX_GPUS];
//
{{ LWWATCH_HAL_IFACE_OBJECT() }}

#endif  // _G_{{$ENGINE}}HAL_H_
