#
# This file is automatically generated by {{$name}} - DO NOT EDIT!
#
# A makefile equivalent of {{$name}}.h
#
# Profile:  {{$PROFILE}}
# Template: {{$TEMPLATE_FILE}}
#

{{ CHIP_MAKEVARS() }}

#
# CHIP's and CHIP families
#
{{ CHIP_DEFINES(":ALL:INCLUDE_CHIP_FAMILIES") }}

#
# Features - enabled or disabled
#
{{ GROUP_DEFINES("FEATURES", ":ALL") }}
{{ GROUP_SPECIALS ("FEATURES") }}

#
# Engines - enabled or disabled
#
{{ GROUP_DEFINES("ENGINES", ":ALL") }}
{{ GROUP_SPECIALS ("ENGINES") }}

#
# Cleanup whitespace for all vars defined above that have comments.
# The whitespace between the value and the beginning of the comment
# becomes part of the value of the variable.  So a line like:
#
#    {{$XXCFG}}_VAR  = 1    # this is special var
#
# will cause {{$XXCFG}}_VAR to have a value of '1     ' which prevents simple
# expressions like:
#
#    ifeq (1,$({{$XXCFG}}_VAR)
#
# from working.   This sequence fixes it.
#
{{ CLEANUP_MAKEVARS() }}

#
# makefiles can test $({{$XXCFG}}_INITIALIZED) to ensure {{$name}}.mk
# has been included
#
{{$XXCFG}}_INITIALIZED := 1

