%%
 % Copyright (c) 2020, LWPU CORPORATION.  All rights reserved.
 %
 % LWPU CORPORATION and its licensors retain all intellectual property
 % and proprietary rights in and to this software, related documentation
 % and any modifications thereto.  Any use, reproduction, disclosure or
 % distribution of this software and related documentation without an express
 % license agreement from LWPU CORPORATION is strictly prohibited.
 %%

h5File  = H5F.create('struct_example.h5', 'H5F_ACC_TRUNC', 'H5P_DEFAULT', 'H5P_DEFAULT');
A = struct('one_as_double',  1,         ...
           'two_as_single',  single(2), ...
           'three_as_uint8', uint8(3),  ...
           'four_as_uint16', uint16(4), ...
           'five_as_uint32', uint32(5), ...
           'six_as_int8',    int8(6),   ...
           'seven_as_int16', int16(7),  ...
           'eight_as_int32', int32(8),  ...
           'nine_as_int64',  int64(9));

hdf5_write_lw(h5File, 'A', A);

H5F.close(h5File);
