apiVersion: batch/v1
kind: Job
metadata:
  name: 5gphy-gen
spec:
  template:
    spec:
      nodeName: sc-sdgx-759.lwpu.com
      hostNetwork: true
      containers:
      - name: 5gphy-gen
        image: gitlab-master.lwpu.com:5005/gputelecom/dpdk/5gphy-gen
        command: ["/LWRAN/lwPHYTools/build/lwPHYTools_generator", "-l", "0-8", "-w", "05:00.0", "--", "-b", "256", "-c", "1", "-e", "65536", "-g", "0", "-m", "0", "-p", "1024", "-f", "/LWRAN/h5/input_list.txt", "-o"]
        selwrityContext:
          privileged: true
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /hugepages
          name: hugepage
        resources:
          limits:
            hugepages-1Gi: 16Gi
            memory: 20Gi
          requests:
            memory: 20Gi      
      volumes:
      - name: hugepage
        emptyDir:
          medium: HugePages
      restartPolicy: Never
      imagePullSecrets:
        - name: "gputelecom-dpdk"
  backoffLimit: 1

