// do not change, this file is automatically generated.
// NOTE: this file should be included by only one file
//       thus, no #ifndef, #endif.



// This file is generated with  
// ./clparser -S -I cl857c.h -sc disp_dsi_sc_gt214.h 



// FIELD DESCRIPTORS-----------------------------------
static desc_t lw857c_desc_3_0[] = {
    { "DISABLE", 0 },
    { "ENABLE", 1 },
};
static desc_t lw857c_desc_3_1[] = {
    { "DISABLE", 0 },
    { "ENABLE", 1 },
};
static desc_t lw857c_desc_4_0[] = {
    { "NON_TEARING", 0 },
    { "IMMEDIATE", 1 },
    { "ON_LINE", 2 },
};
static desc_t lw857c_desc_4_4[] = {
    { "MONO", 0 },
    { "STEREO", 1 },
    { "SPEC_FLIP", 2 },
};
static desc_t lw857c_desc_9_0[] = {
    { "WRITE", 0 },
    { "WRITE_AWAKEN", 1 },
};
static desc_t lw857c_desc_12_0[] = {
    { "DISABLE", 0 },
    { "USE_CORE_LUT", 1 },
    { "ENABLE", 3 },
};
static desc_t lw857c_desc_12_1[] = {
    { "LORES", 0 },
    { "HIRES", 1 },
};
static desc_t lw857c_desc_14_0[] = {
    { "DISABLE", 0 },
    { "ENABLE", 1 },
};
static desc_t lw857c_desc_14_1[] = {
    { "LORES", 0 },
    { "HIRES", 1 },
};
static desc_t lw857c_desc_17_0[] = {
    { "OFF", 0 },
    { "STRIP_INTERLEAVE", 1 },
    { "FRAME_INTERLEAVE", 2 },
    { "FRAME_AND_STRIP_INTERLEAVE", 3 },
};
static desc_t lw857c_desc_18_0[] = {
    { "DISABLE", 0 },
    { "ENABLE", 1 },
};
static desc_t lw857c_desc_18_1[] = {
    { "OFF", 0 },
    { "FOS_2CHIP", 1 },
    { "FOS_4CHIP", 2 },
    { "FRAME_INTERLEAVE_FOS_4CHIP", 8 },
};
static desc_t lw857c_desc_18_2[] = {
    { "X1", 0 },
    { "X2", 1 },
    { "X4", 2 },
};
static desc_t lw857c_desc_18_3[] = {
    { "D1", 0 },
    { "D2", 1 },
    { "D4", 2 },
};
static desc_t lw857c_desc_18_4[] = {
    { "LINEAR", 0 },
    { "GAMMA", 1 },
    { "NONE", 3 },
};
static desc_t lw857c_desc_19_0[] = {
    { "DISABLE", 0 },
    { "ENABLE", 1 },
};
static desc_t lw857c_desc_25_0[] = {
    { "ONE_GOB", 0 },
    { "TWO_GOBS", 1 },
    { "FOUR_GOBS", 2 },
    { "EIGHT_GOBS", 3 },
    { "SIXTEEN_GOBS", 4 },
    { "THIRTYTWO_GOBS", 5 },
};
static desc_t lw857c_desc_25_2[] = {
    { "BLOCKLINEAR", 0 },
    { "PITCH", 1 },
};
static desc_t lw857c_desc_26_0[] = {
    { "I8", 30 },
    { "VOID16", 31 },
    { "VOID32", 46 },
    { "RF16_GF16_BF16_AF16", 202 },
    { "A8R8G8B8", 207 },
    { "A2B10G10R10", 209 },
    { "A8B8G8R8", 213 },
    { "R5G6B5", 232 },
    { "A1R5G5B5", 233 },
};
static desc_t lw857c_desc_26_1[] = {
    { "X1_AA", 0 },
    { "X4_AA", 2 },
};
static desc_t lw857c_desc_26_2[] = {
    { "LINEAR", 0 },
    { "SRGB", 1 },
};
static desc_t lw857c_desc_26_3[] = {
    { "FRM", 0 },
    { "FLD1", 1 },
    { "FLD2", 2 },
};


// FIELDS-----------------------------------
static flds_t lw857c_flds_0[] = {
    { "PTR", 11, 2, 0, 0 },
};
static flds_t lw857c_flds_1[] = {
    { "PTR", 11, 2, 0, 0 },
};
static flds_t lw857c_flds_2[] = {
    { "LINE", 15, 0, 0, 0 },
};
static flds_t lw857c_flds_3[] = {
    { "INTERLOCK_WITH_CORE", 0, 0, 2, lw857c_desc_3_0 },
    { "RESET_SPEC_FLIP_SEQ", 12, 12, 2, lw857c_desc_3_1 },
};
static flds_t lw857c_flds_4[] = {
    { "BEGIN_MODE", 9, 8, 3, lw857c_desc_4_0 },
    { "MIN_PRESENT_INTERVAL", 7, 4, 0, 0 },
    { "BEGIN_LINE", 30, 16, 0, 0 },
    { "ON_LINE_MARGIN", 15, 10, 0, 0 },
    { "MODE", 1, 0, 3, lw857c_desc_4_4 },
};
static flds_t lw857c_flds_5[] = {
    { "OFFSET", 11, 2, 0, 0 },
};
static flds_t lw857c_flds_9[] = {
    { "MODE", 30, 30, 2, lw857c_desc_9_0 },
    { "OFFSET", 11, 2, 0, 0 },
};
static flds_t lw857c_flds_12[] = {
    { "ENABLE", 31, 30, 3, lw857c_desc_12_0 },
    { "MODE", 29, 29, 2, lw857c_desc_12_1 },
    { "ORIGIN", 7, 2, 0, 0 },
};
static flds_t lw857c_flds_14[] = {
    { "ENABLE", 31, 31, 2, lw857c_desc_14_0 },
    { "MODE", 30, 30, 2, lw857c_desc_14_1 },
    { "ORIGIN", 7, 2, 0, 0 },
};
static flds_t lw857c_flds_17[] = {
    { "MODE", 1, 0, 4, lw857c_desc_17_0 },
    { "RENDER_START", 16, 2, 0, 0 },
    { "RENDER_STOP", 31, 17, 0, 0 },
};
static flds_t lw857c_flds_18[] = {
    { "EXTENSION_ENABLE", 31, 31, 2, lw857c_desc_18_0 },
    { "MODE", 3, 0, 4, lw857c_desc_18_1 },
    { "INPUT_PIXEL_WEIGHT", 9, 8, 3, lw857c_desc_18_2 },
    { "OUTPUT_PIXEL_WEIGHT", 13, 12, 3, lw857c_desc_18_3 },
    { "ARITHMETIC_MODE", 17, 16, 3, lw857c_desc_18_4 },
};
static flds_t lw857c_flds_19[] = {
    { "USE_GAIN_OFS", 0, 0, 2, lw857c_desc_19_0 },
};
static flds_t lw857c_flds_20[] = {
    { "GAIN", 15, 0, 0, 0 },
    { "OFS", 31, 16, 0, 0 },
};
static flds_t lw857c_flds_24[] = {
    { "WIDTH", 14, 0, 0, 0 },
    { "HEIGHT", 30, 16, 0, 0 },
};
static flds_t lw857c_flds_25[] = {
    { "BLOCK_HEIGHT", 3, 0, 6, lw857c_desc_25_0 },
    { "PITCH", 17, 8, 0, 0 },
    { "MEMORY_LAYOUT", 20, 20, 2, lw857c_desc_25_2 },
};
static flds_t lw857c_flds_26[] = {
    { "FORMAT", 15, 8, 9, lw857c_desc_26_0 },
    { "SUPER_SAMPLE", 1, 0, 2, lw857c_desc_26_1 },
    { "GAMMA", 2, 2, 2, lw857c_desc_26_2 },
    { "LAYOUT", 5, 4, 3, lw857c_desc_26_3 },
    { "RESERVED0", 22, 16, 0, 0 },
    { "RESERVED1", 24, 24, 0, 0 },
};


// SUBSTRUCTS-----------------------------------
static substruct_t subst_lw857c_surface = { "SURFACE", 32, 2 };


// METHODS-----------------------------------
static mthds_t lw857c_mthds[] = {
    { "PUT", 4, 1, 0x0, 0, 1, lw857c_flds_0, 0, 0x0, 0x0, 0x0, 0x0 },
    { "GET", 4, 1, 0x4, 0, 1, lw857c_flds_1, 0, 0x0, 0x0, 0x0, 0x0 },
    { "GET_SCANLINE", 4, 1, 0x10, 0, 1, lw857c_flds_2, 0, 0x0, 0x0, 0x0, 0x0 },
    { "UPDATE", 4, 1, 0x80, 0, 2, lw857c_flds_3, 0, 0x0, 0x0, 0x0, 0x0 },
    { "SET_PRESENT_CONTROL", 4, 1, 0x84, 0, 5, lw857c_flds_4, 1, 0x6108c4, 0x540, 0x0, 0x0 },
    { "SET_SEMAPHORE_CONTROL", 4, 1, 0x88, 0, 1, lw857c_flds_5, 1, 0x6108d0, 0x540, 0x0, 0x0 },
    { "SET_SEMAPHORE_ACQUIRE", 4, 1, 0x8c, 0, 0, 0, 1, 0x6108dc, 0x540, 0x0, 0x0 },
    { "SET_SEMAPHORE_RELEASE", 4, 1, 0x90, 0, 0, 0, 1, 0x6108e4, 0x540, 0x0, 0x0 },
    { "SET_CONTEXT_DMA_SEMAPHORE", 4, 1, 0x94, 0, 0, 0, 1, 0x610884, 0x540, 0x0, 0x0 },
    { "SET_NOTIFIER_CONTROL", 4, 1, 0xa0, 0, 2, lw857c_flds_9, 1, 0x6108a0, 0x540, 0x0, 0x0 },
    { "SET_CONTEXT_DMA_NOTIFIER", 4, 1, 0xa4, 0, 0, 0, 1, 0x610878, 0x540, 0x0, 0x0 },
    { "SET_CONTEXT_DMAS_ISO", 4, 4, 0xc0, 0, 0, 0, 1, 0x61086c, 0x540, 0x0, 0x0 },
    { "SET_BASE_LUT_LO", 4, 1, 0xe0, 0, 3, lw857c_flds_12, 1, 0x610858, 0x540, 0x0, 0x0 },
    { "SET_BASE_LUT_HI", 4, 1, 0xe4, 0, 0, 0, 1, 0x610860, 0x540, 0x0, 0x0 },
    { "SET_OUTPUT_LUT_LO", 4, 1, 0xe8, 0, 3, lw857c_flds_14, 1, 0x6108ac, 0x540, 0x0, 0x0 },
    { "SET_OUTPUT_LUT_HI", 4, 1, 0xec, 0, 0, 0, 1, 0x6108b4, 0x540, 0x0, 0x0 },
    { "SET_CONTEXT_DMA_LUT", 4, 1, 0xfc, 0, 0, 0, 1, 0x610824, 0x540, 0x0, 0x0 },
    { "SET_DIST_RENDER_CONTROL", 4, 1, 0x100, 0, 3, lw857c_flds_17, 1, 0x610894, 0x540, 0x0, 0x0 },
    { "SET_DIST_RENDER_EXTEND_CONTROL", 4, 1, 0x104, 0, 5, lw857c_flds_18, 1, 0x61082c, 0x540, 0x0, 0x0 },
    { "SET_PROCESSING", 4, 1, 0x110, 0, 1, lw857c_flds_19, 1, 0x6108bc, 0x540, 0x0, 0x0 },
    { "SET_COLWERSION", 4, 1, 0x114, 0, 2, lw857c_flds_20, 1, 0x61088c, 0x540, 0x0, 0x0 },
    { "SET_SPARE", 4, 1, 0x7bc, 0, 0, 0, 0, 0x0, 0x0, 0x0, 0x0 },
    { "SET_SPARE_NOOP", 4, 16, 0x7c0, 0, 0, 0, 0, 0x0, 0x0, 0x0, 0x0 },
    { "SURFACE_SET_OFFSET", 4, 2, 0x800, &subst_lw857c_surface, 0, 0, 1, 0x6108f0, 0x540, 0x30, 0xc },
    { "SURFACE_SET_SIZE", 4, 1, 0x808, &subst_lw857c_surface, 2, lw857c_flds_24, 1, 0x61090c, 0x540, 0x30, 0x0 },
    { "SURFACE_SET_STORAGE", 4, 1, 0x80c, &subst_lw857c_surface, 3, lw857c_flds_25, 1, 0x610914, 0x540, 0x30, 0x0 },
    { "SURFACE_SET_PARAMS", 4, 1, 0x810, &subst_lw857c_surface, 6, lw857c_flds_26, 1, 0x610904, 0x540, 0x30, 0x0 },
};


#define num_lw857c_mthds (27)
// ---------------------EOF--------------------
