// do not change, this file is automatically generated.
// NOTE: this file should be included by only one file
//       thus, no #ifndef, #endif.



// This file is generated with  
// ./clparser -S -I cl857e.h -sc disp_dsi_sc_gt214.h 



// FIELD DESCRIPTORS-----------------------------------
static desc_t lw857e_desc_2_0[] = {
    { "DISABLE", 0 },
    { "ENABLE", 1 },
};
static desc_t lw857e_desc_3_0[] = {
    { "ASAP", 0 },
    { "TIMESTAMP", 3 },
};
static desc_t lw857e_desc_8_0[] = {
    { "WRITE", 0 },
    { "WRITE_AWAKEN", 1 },
};
static desc_t lw857e_desc_11_0[] = {
    { "DISABLE", 0 },
    { "ENABLE", 1 },
};
static desc_t lw857e_desc_11_1[] = {
    { "LORES", 0 },
    { "HIRES", 1 },
};
static desc_t lw857e_desc_17_0[] = {
    { "SOURCE_COLOR_VALUE_KEYING", 0 },
    { "DESTINATION_COLOR_VALUE_KEYING", 1 },
    { "OPAQUE_SUSPEND_BASE", 2 },
};
static desc_t lw857e_desc_28_0[] = {
    { "ONE_GOB", 0 },
    { "TWO_GOBS", 1 },
    { "FOUR_GOBS", 2 },
    { "EIGHT_GOBS", 3 },
    { "SIXTEEN_GOBS", 4 },
    { "THIRTYTWO_GOBS", 5 },
};
static desc_t lw857e_desc_28_2[] = {
    { "BLOCKLINEAR", 0 },
    { "PITCH", 1 },
};
static desc_t lw857e_desc_29_0[] = {
    { "VE8YO8UE8YE8", 40 },
    { "YO8VE8YE8UE8", 41 },
    { "A2B10G10R10", 209 },
    { "A8R8G8B8", 207 },
    { "A1R5G5B5", 233 },
};
static desc_t lw857e_desc_29_1[] = {
    { "RGB", 0 },
    { "YUV_601", 1 },
    { "YUV_709", 2 },
};


// FIELDS-----------------------------------
static flds_t lw857e_flds_0[] = {
    { "PTR", 11, 2, 0, 0 },
};
static flds_t lw857e_flds_1[] = {
    { "PTR", 11, 2, 0, 0 },
};
static flds_t lw857e_flds_2[] = {
    { "INTERLOCK_WITH_CORE", 0, 0, 2, lw857e_desc_2_0 },
};
static flds_t lw857e_flds_3[] = {
    { "BEGIN_MODE", 1, 0, 2, lw857e_desc_3_0 },
    { "MIN_PRESENT_INTERVAL", 7, 4, 0, 0 },
};
static flds_t lw857e_flds_6[] = {
    { "OFFSET", 11, 2, 0, 0 },
};
static flds_t lw857e_flds_8[] = {
    { "MODE", 30, 30, 2, lw857e_desc_8_0 },
    { "OFFSET", 11, 2, 0, 0 },
};
static flds_t lw857e_flds_11[] = {
    { "ENABLE", 30, 30, 2, lw857e_desc_11_0 },
    { "MODE", 29, 29, 2, lw857e_desc_11_1 },
    { "ORIGIN", 7, 2, 0, 0 },
};
static flds_t lw857e_flds_14[] = {
    { "X", 14, 0, 0, 0 },
    { "Y", 30, 16, 0, 0 },
};
static flds_t lw857e_flds_15[] = {
    { "WIDTH", 14, 0, 0, 0 },
    { "HEIGHT", 30, 16, 0, 0 },
};
static flds_t lw857e_flds_16[] = {
    { "WIDTH", 14, 0, 0, 0 },
};
static flds_t lw857e_flds_17[] = {
    { "MODE", 3, 0, 3, lw857e_desc_17_0 },
};
static flds_t lw857e_flds_27[] = {
    { "WIDTH", 14, 0, 0, 0 },
    { "HEIGHT", 30, 16, 0, 0 },
};
static flds_t lw857e_flds_28[] = {
    { "BLOCK_HEIGHT", 3, 0, 6, lw857e_desc_28_0 },
    { "PITCH", 17, 8, 0, 0 },
    { "MEMORY_LAYOUT", 20, 20, 2, lw857e_desc_28_2 },
};
static flds_t lw857e_flds_29[] = {
    { "FORMAT", 15, 8, 5, lw857e_desc_29_0 },
    { "COLOR_SPACE", 1, 0, 3, lw857e_desc_29_1 },
    { "RESERVED0", 22, 16, 0, 0 },
    { "RESERVED1", 24, 24, 0, 0 },
};


// SUBSTRUCTS-----------------------------------
static substruct_t subst_lw857e_surface = { "SURFACE", 32, 1 };


// METHODS-----------------------------------
static mthds_t lw857e_mthds[] = {
    { "PUT", 4, 1, 0x0, 0, 1, lw857e_flds_0, 0, 0x0, 0x0, 0x0, 0x0 },
    { "GET", 4, 1, 0x4, 0, 1, lw857e_flds_1, 0, 0x0, 0x0, 0x0, 0x0 },
    { "UPDATE", 4, 1, 0x80, 0, 1, lw857e_flds_2, 0, 0x0, 0x0, 0x0, 0x0 },
    { "SET_PRESENT_CONTROL", 4, 1, 0x84, 0, 2, lw857e_flds_3, 1, 0x6109a0, 0x540, 0x0, 0x0 },
    { "SET_SEMAPHORE_ACQUIRE", 4, 1, 0x88, 0, 0, 0, 1, 0x6109c0, 0x540, 0x0, 0x0 },
    { "SET_SEMAPHORE_RELEASE", 4, 1, 0x8c, 0, 0, 0, 1, 0x6109c8, 0x540, 0x0, 0x0 },
    { "SET_SEMAPHORE_CONTROL", 4, 1, 0x90, 0, 1, lw857e_flds_6, 1, 0x6109b4, 0x540, 0x0, 0x0 },
    { "SET_CONTEXT_DMA_SEMAPHORE", 4, 1, 0x94, 0, 0, 0, 1, 0x610970, 0x540, 0x0, 0x0 },
    { "SET_NOTIFIER_CONTROL", 4, 1, 0xa0, 0, 2, lw857e_flds_8, 1, 0x610998, 0x540, 0x0, 0x0 },
    { "SET_CONTEXT_DMA_NOTIFIER", 4, 1, 0xa4, 0, 0, 0, 1, 0x610964, 0x540, 0x0, 0x0 },
    { "SET_CONTEXT_DMA_LUT", 4, 1, 0xb0, 0, 0, 0, 1, 0x610c98, 0x540, 0x0, 0x0 },
    { "SET_OVERLAY_LUT_LO", 4, 1, 0xb4, 0, 3, lw857e_flds_11, 1, 0x610ca4, 0x540, 0x0, 0x0 },
    { "SET_OVERLAY_LUT_HI", 4, 1, 0xb8, 0, 0, 0, 1, 0x610cac, 0x540, 0x0, 0x0 },
    { "SET_CONTEXT_DMA_ISO", 4, 1, 0xc0, 0, 0, 0, 1, 0x610958, 0x540, 0x0, 0x0 },
    { "SET_POINT_IN", 4, 1, 0xe0, 0, 2, lw857e_flds_14, 1, 0x6109a8, 0x540, 0x0, 0x0 },
    { "SET_SIZE_IN", 4, 1, 0xe4, 0, 2, lw857e_flds_15, 1, 0x6109d0, 0x540, 0x0, 0x0 },
    { "SET_SIZE_OUT", 4, 1, 0xe8, 0, 1, lw857e_flds_16, 1, 0x6109d8, 0x540, 0x0, 0x0 },
    { "SET_COMPOSITION_CONTROL", 4, 1, 0x100, 0, 1, lw857e_flds_17, 1, 0x61094c, 0x540, 0x0, 0x0 },
    { "SET_KEY_COLOR", 4, 1, 0x104, 0, 0, 0, 1, 0x610984, 0x540, 0x0, 0x0 },
    { "SET_KEY_MASK", 4, 1, 0x108, 0, 0, 0, 1, 0x61098c, 0x540, 0x0, 0x0 },
    { "SET_TIMESTAMP_ORIGIN_LO", 4, 1, 0x130, 0, 0, 0, 1, 0x610c18, 0x540, 0x0, 0x0 },
    { "SET_TIMESTAMP_ORIGIN_HI", 4, 1, 0x134, 0, 0, 0, 1, 0x610c24, 0x540, 0x0, 0x0 },
    { "SET_UPDATE_TIMESTAMP_LO", 4, 1, 0x138, 0, 0, 0, 1, 0x6109ec, 0x540, 0x0, 0x0 },
    { "SET_UPDATE_TIMESTAMP_HI", 4, 1, 0x13c, 0, 0, 0, 1, 0x610c30, 0x540, 0x0, 0x0 },
    { "SET_SPARE", 4, 1, 0x7bc, 0, 0, 0, 0, 0x0, 0x0, 0x0, 0x0 },
    { "SET_SPARE_NOOP", 4, 16, 0x7c0, 0, 0, 0, 0, 0x0, 0x0, 0x0, 0x0 },
    { "SURFACE_SET_OFFSET", 4, 1, 0x800, &subst_lw857e_surface, 0, 0, 1, 0x6109f8, 0x540, 0x0, 0x0 },
    { "SURFACE_SET_SIZE", 4, 1, 0x808, &subst_lw857e_surface, 2, lw857e_flds_27, 1, 0x610a08, 0x540, 0x0, 0x0 },
    { "SURFACE_SET_STORAGE", 4, 1, 0x80c, &subst_lw857e_surface, 3, lw857e_flds_28, 1, 0x610a10, 0x540, 0x0, 0x0 },
    { "SURFACE_SET_PARAMS", 4, 1, 0x810, &subst_lw857e_surface, 4, lw857e_flds_29, 1, 0x610a00, 0x540, 0x0, 0x0 },
};


#define num_lw857e_mthds (30)
// ---------------------EOF--------------------
