// do not change, this file is automatically generated.
// NOTE: this file should be included by only one file
//       thus, no #ifndef, #endif.



// This file is generated with  
// ./clparser -S -I cl857d.h -sc disp_dsi_sc_gt214.h 



// FIELD DESCRIPTORS-----------------------------------
static desc_t lw857d_desc_2_0[] = {
    { "DISABLE", 0 },
    { "ENABLE", 1 },
};
static desc_t lw857d_desc_2_1[] = {
    { "DISABLE", 0 },
    { "ENABLE", 1 },
};
static desc_t lw857d_desc_2_2[] = {
    { "DISABLE", 0 },
    { "ENABLE", 1 },
};
static desc_t lw857d_desc_2_3[] = {
    { "DISABLE", 0 },
    { "ENABLE", 1 },
};
static desc_t lw857d_desc_2_4[] = {
    { "DISABLE", 0 },
    { "ENABLE", 1 },
};
static desc_t lw857d_desc_2_5[] = {
    { "DISABLE", 0 },
    { "ENABLE", 1 },
};
static desc_t lw857d_desc_2_6[] = {
    { "DISABLE", 0 },
    { "ENABLE", 1 },
};
static desc_t lw857d_desc_2_7[] = {
    { "DISABLE", 0 },
    { "ENABLE", 1 },
};
static desc_t lw857d_desc_2_8[] = {
    { "FALSE", 0 },
    { "TRUE", 1 },
};
static desc_t lw857d_desc_2_9[] = {
    { "FALSE", 0 },
    { "TRUE", 1 },
};
static desc_t lw857d_desc_2_10[] = {
    { "FALSE", 0 },
    { "TRUE", 1 },
};
static desc_t lw857d_desc_3_0[] = {
    { "WRITE", 0 },
    { "WRITE_AWAKEN", 1 },
};
static desc_t lw857d_desc_3_2[] = {
    { "DISABLE", 0 },
    { "ENABLE", 1 },
};
static desc_t lw857d_desc_8_0[] = {
    { "NONE", 0 },
    { "HEAD0", 1 },
    { "HEAD1", 2 },
};
static desc_t lw857d_desc_8_1[] = {
    { "NONE", 0 },
    { "SUBHEAD0", 1 },
    { "SUBHEAD1", 2 },
    { "BOTH", 3 },
};
static desc_t lw857d_desc_8_2[] = {
    { "ACTIVE_RASTER", 0 },
    { "COMPLETE_RASTER", 1 },
    { "NON_ACTIVE_RASTER", 2 },
};
static desc_t lw857d_desc_8_3[] = {
    { "RGB_CRT", 0 },
    { "CPST_NTSC_M", 1 },
    { "CPST_NTSC_J", 2 },
    { "CPST_PAL_BDGHI", 3 },
    { "CPST_PAL_M", 4 },
    { "CPST_PAL_N", 5 },
    { "CPST_PAL_CN", 6 },
    { "COMP_NTSC_M", 7 },
    { "COMP_NTSC_J", 8 },
    { "COMP_PAL_BDGHI", 9 },
    { "COMP_PAL_M", 10 },
    { "COMP_PAL_N", 11 },
    { "COMP_PAL_CN", 12 },
    { "COMP_480P_60", 13 },
    { "COMP_576P_50", 14 },
    { "COMP_720P_50", 15 },
    { "COMP_720P_60", 16 },
    { "COMP_1080I_50", 17 },
    { "COMP_1080I_60", 18 },
    { "CUSTOM", 63 },
};
static desc_t lw857d_desc_8_4[] = {
    { "DISABLE", 0 },
    { "LEVEL_1", 1 },
    { "LEVEL_2", 2 },
    { "LEVEL_3", 3 },
};
static desc_t lw857d_desc_8_5[] = {
    { "FALSE", 0 },
    { "TRUE", 1 },
};
static desc_t lw857d_desc_9_0[] = {
    { "POSITIVE_TRUE", 0 },
    { "NEGATIVE_TRUE", 1 },
};
static desc_t lw857d_desc_9_1[] = {
    { "POSITIVE_TRUE", 0 },
    { "NEGATIVE_TRUE", 1 },
};
static desc_t lw857d_desc_10_0[] = {
    { "BW_3_375", 0 },
    { "BW_6_75", 1 },
};
static desc_t lw857d_desc_10_1[] = {
    { "GN_0", 0 },
    { "GN_0_0625", 1 },
    { "GN_0_125", 2 },
    { "GN_0_25", 3 },
    { "GN_0_5", 4 },
    { "GN_1_0", 5 },
};
static desc_t lw857d_desc_10_2[] = {
    { "GN_0", 0 },
    { "GN_0_0625", 1 },
    { "GN_0_125", 2 },
    { "GN_0_25", 3 },
    { "GN_0_5", 4 },
    { "GN_1_0", 5 },
};
static desc_t lw857d_desc_11_0[] = {
    { "RGB_CRT", 0 },
    { "CPST_NTSC_M", 1 },
    { "CPST_NTSC_J", 2 },
    { "CPST_PAL_BDGHI", 3 },
    { "CPST_PAL_M", 4 },
    { "CPST_PAL_N", 5 },
    { "CPST_PAL_CN", 6 },
    { "COMP_NTSC_M", 7 },
    { "COMP_NTSC_J", 8 },
    { "COMP_PAL_BDGHI", 9 },
    { "COMP_PAL_M", 10 },
    { "COMP_PAL_N", 11 },
    { "COMP_PAL_CN", 12 },
    { "COMP_480P_60", 13 },
    { "COMP_576P_50", 14 },
    { "COMP_720P_50", 15 },
    { "COMP_720P_60", 16 },
    { "COMP_1080I_50", 17 },
    { "COMP_1080I_60", 18 },
    { "CUSTOM", 63 },
};
static desc_t lw857d_desc_11_1[] = {
    { "RGB", 0 },
    { "YUV", 1 },
};
static desc_t lw857d_desc_11_2[] = {
    { "DISABLE", 0 },
    { "ENABLE", 1 },
};
static desc_t lw857d_desc_11_3[] = {
    { "DISABLE", 0 },
    { "ENABLE", 1 },
};
static desc_t lw857d_desc_11_4[] = {
    { "DISABLE", 0 },
    { "ENABLE", 1 },
};
static desc_t lw857d_desc_11_5[] = {
    { "NONE", 0 },
    { "NARROW_358", 1 },
    { "WIDE_358", 2 },
    { "NARROW_443", 3 },
    { "WIDE_443", 4 },
};
static desc_t lw857d_desc_11_6[] = {
    { "BW_0_6", 0 },
    { "BW_1_4", 1 },
};
static desc_t lw857d_desc_11_7[] = {
    { "NARROW", 0 },
    { "WIDE", 1 },
};
static desc_t lw857d_desc_11_8[] = {
    { "NARROW", 0 },
    { "WIDE", 1 },
};
static desc_t lw857d_desc_12_0[] = {
    { "NONE", 0 },
    { "HEAD0", 1 },
    { "HEAD1", 2 },
};
static desc_t lw857d_desc_12_1[] = {
    { "NONE", 0 },
    { "SUBHEAD0", 1 },
    { "SUBHEAD1", 2 },
    { "BOTH", 3 },
};
static desc_t lw857d_desc_12_2[] = {
    { "ACTIVE_RASTER", 0 },
    { "COMPLETE_RASTER", 1 },
    { "NON_ACTIVE_RASTER", 2 },
};
static desc_t lw857d_desc_12_3[] = {
    { "LVDS_LWSTOM", 0 },
    { "SINGLE_TMDS_A", 1 },
    { "SINGLE_TMDS_B", 2 },
    { "SINGLE_TMDS_AB", 3 },
    { "DUAL_SINGLE_TMDS", 4 },
    { "DUAL_TMDS", 5 },
    { "SDI_OUT", 6 },
    { "DDI_OUT", 7 },
    { "DP_A", 8 },
    { "DP_B", 9 },
    { "CUSTOM", 15 },
};
static desc_t lw857d_desc_12_4[] = {
    { "POSITIVE_TRUE", 0 },
    { "NEGATIVE_TRUE", 1 },
};
static desc_t lw857d_desc_12_5[] = {
    { "POSITIVE_TRUE", 0 },
    { "NEGATIVE_TRUE", 1 },
};
static desc_t lw857d_desc_12_6[] = {
    { "POSITIVE_TRUE", 0 },
    { "NEGATIVE_TRUE", 1 },
};
static desc_t lw857d_desc_12_7[] = {
    { "DEFAULT", 0 },
    { "BPP_16_422", 1 },
    { "BPP_18_444", 2 },
    { "BPP_20_422", 3 },
    { "BPP_24_422", 4 },
    { "BPP_24_444", 5 },
    { "BPP_30_444", 6 },
    { "BPP_32_422", 7 },
    { "BPP_36_444", 8 },
    { "BPP_48_444", 9 },
};
static desc_t lw857d_desc_13_0[] = {
    { "NONE", 0 },
    { "HEAD0", 1 },
    { "HEAD1", 2 },
};
static desc_t lw857d_desc_13_1[] = {
    { "NONE", 0 },
    { "SUBHEAD0", 1 },
    { "SUBHEAD1", 2 },
    { "BOTH", 3 },
};
static desc_t lw857d_desc_13_2[] = {
    { "ACTIVE_RASTER", 0 },
    { "COMPLETE_RASTER", 1 },
    { "NON_ACTIVE_RASTER", 2 },
};
static desc_t lw857d_desc_13_3[] = {
    { "EXT_TMDS_ENC", 0 },
    { "EXT_TV_ENC", 1 },
    { "EXT_SDI_SD_ENC", 2 },
    { "EXT_SDI_HD_ENC", 3 },
    { "DIST_RENDER_OUT", 4 },
    { "DIST_RENDER_IN", 5 },
    { "DIST_RENDER_INOUT", 6 },
};
static desc_t lw857d_desc_13_4[] = {
    { "POSITIVE_TRUE", 0 },
    { "NEGATIVE_TRUE", 1 },
};
static desc_t lw857d_desc_13_5[] = {
    { "POSITIVE_TRUE", 0 },
    { "NEGATIVE_TRUE", 1 },
};
static desc_t lw857d_desc_13_6[] = {
    { "POSITIVE_TRUE", 0 },
    { "NEGATIVE_TRUE", 1 },
};
static desc_t lw857d_desc_13_7[] = {
    { "DEFAULT", 0 },
    { "BPP_16_422", 1 },
    { "BPP_18_444", 2 },
    { "BPP_20_422", 3 },
    { "BPP_24_422", 4 },
    { "BPP_24_444", 5 },
    { "BPP_30_444", 6 },
    { "BPP_32_422", 7 },
    { "BPP_36_444", 8 },
    { "BPP_48_444", 9 },
};
static desc_t lw857d_desc_14_1[] = {
    { "DISABLE", 0 },
    { "ENABLE", 1 },
};
static desc_t lw857d_desc_15_1[] = {
    { "CLK_25", 0 },
    { "CLK_28", 1 },
    { "CLK_LWSTOM", 2 },
};
static desc_t lw857d_desc_15_2[] = {
    { "FALSE", 0 },
    { "TRUE", 1 },
};
static desc_t lw857d_desc_15_3[] = {
    { "FALSE", 0 },
    { "TRUE", 1 },
};
static desc_t lw857d_desc_16_0[] = {
    { "DISABLE", 0 },
    { "ENABLE", 1 },
};
static desc_t lw857d_desc_16_1[] = {
    { "PROGRESSIVE", 0 },
    { "INTERLACED", 1 },
};
static desc_t lw857d_desc_16_2[] = {
    { "NO_LOCK", 0 },
    { "FRAME_LOCK", 1 },
    { "RASTER_LOCK", 3 },
};
static desc_t lw857d_desc_16_3[] = {
    { "INTERNAL", 0 },
    { "LOCK_PIN_0", 1 },
    { "LOCK_PIN_1", 2 },
    { "LOCK_PIN_2", 3 },
    { "LOCK_PIN_3", 4 },
};
static desc_t lw857d_desc_16_5[] = {
    { "NO_LOCK", 0 },
    { "FRAME_LOCK", 1 },
    { "RASTER_LOCK", 3 },
};
static desc_t lw857d_desc_16_6[] = {
    { "INTERNAL", 0 },
    { "LOCK_PIN_0", 1 },
    { "LOCK_PIN_1", 2 },
    { "LOCK_PIN_2", 3 },
    { "LOCK_PIN_3", 4 },
};
static desc_t lw857d_desc_16_7[] = {
    { "DISABLE", 0 },
    { "ENABLE", 1 },
};
static desc_t lw857d_desc_16_8[] = {
    { "INTERNAL", 0 },
    { "LOCK_PIN_0", 1 },
    { "LOCK_PIN_1", 2 },
    { "LOCK_PIN_2", 3 },
    { "LOCK_PIN_3", 4 },
};
static desc_t lw857d_desc_16_9[] = {
    { "STEREO_PIN", 0 },
    { "BLUE_LINE", 1 },
};
static desc_t lw857d_desc_16_10[] = {
    { "INTERNAL", 0 },
    { "LOCK_PIN_0", 1 },
    { "LOCK_PIN_1", 2 },
    { "LOCK_PIN_2", 3 },
    { "LOCK_PIN_3", 4 },
};
static desc_t lw857d_desc_26_0[] = {
    { "CORE", 0 },
    { "BASE", 1 },
    { "OVERLAY", 2 },
};
static desc_t lw857d_desc_26_1[] = {
    { "FALSE", 0 },
    { "TRUE", 1 },
};
static desc_t lw857d_desc_26_2[] = {
    { "FALSE", 0 },
    { "TRUE", 1 },
};
static desc_t lw857d_desc_26_3[] = {
    { "FALSE", 0 },
    { "TRUE", 1 },
};
static desc_t lw857d_desc_26_4[] = {
    { "NONE", 0 },
    { "DAC0", 1 },
    { "DAC1", 2 },
    { "DAC2", 3 },
    { "SOR0", 4 },
    { "SOR1", 5 },
    { "PIOR0", 6 },
    { "PIOR1", 7 },
    { "PIOR2", 8 },
    { "SOR2", 9 },
    { "SOR3", 10 },
};
static desc_t lw857d_desc_26_5[] = {
    { "NONE", 0 },
    { "DAC0", 1 },
    { "DAC1", 2 },
    { "DAC2", 3 },
    { "SOR0", 4 },
    { "SOR1", 5 },
    { "PIOR0", 6 },
    { "PIOR1", 7 },
    { "PIOR2", 8 },
    { "SOR2", 9 },
    { "SOR3", 10 },
};
static desc_t lw857d_desc_26_6[] = {
    { "DISABLE", 0 },
    { "ENABLE", 1 },
};
static desc_t lw857d_desc_27_0[] = {
    { "DISABLE", 0 },
    { "ENABLE", 1 },
};
static desc_t lw857d_desc_29_0[] = {
    { "DISABLE", 0 },
    { "ENABLE", 1 },
};
static desc_t lw857d_desc_29_1[] = {
    { "LORES", 0 },
    { "HIRES", 1 },
};
static desc_t lw857d_desc_31_0[] = {
    { "DISABLE", 0 },
    { "ENABLE", 1 },
};
static desc_t lw857d_desc_31_1[] = {
    { "LORES", 0 },
    { "HIRES", 1 },
};
static desc_t lw857d_desc_36_0[] = {
    { "ONE_GOB", 0 },
    { "TWO_GOBS", 1 },
    { "FOUR_GOBS", 2 },
    { "EIGHT_GOBS", 3 },
    { "SIXTEEN_GOBS", 4 },
    { "THIRTYTWO_GOBS", 5 },
};
static desc_t lw857d_desc_36_2[] = {
    { "BLOCKLINEAR", 0 },
    { "PITCH", 1 },
};
static desc_t lw857d_desc_37_0[] = {
    { "I8", 30 },
    { "VOID16", 31 },
    { "VOID32", 46 },
    { "RF16_GF16_BF16_AF16", 202 },
    { "A8R8G8B8", 207 },
    { "A2B10G10R10", 209 },
    { "A8B8G8R8", 213 },
    { "R5G6B5", 232 },
    { "A1R5G5B5", 233 },
};
static desc_t lw857d_desc_37_1[] = {
    { "X1_AA", 0 },
    { "X4_AA", 2 },
};
static desc_t lw857d_desc_37_2[] = {
    { "LINEAR", 0 },
    { "SRGB", 1 },
};
static desc_t lw857d_desc_39_0[] = {
    { "DISABLE", 0 },
    { "ENABLE", 1 },
};
static desc_t lw857d_desc_39_1[] = {
    { "A1R5G5B5", 0 },
    { "A8R8G8B8", 1 },
};
static desc_t lw857d_desc_39_2[] = {
    { "W32_H32", 0 },
    { "W64_H64", 1 },
};
static desc_t lw857d_desc_39_5[] = {
    { "ALPHA_BLEND", 0 },
    { "PREMULT_ALPHA_BLEND", 1 },
    { "XOR", 2 },
};
static desc_t lw857d_desc_39_6[] = {
    { "NONE", 0 },
    { "SUBHEAD0", 1 },
    { "SUBHEAD1", 2 },
    { "BOTH", 3 },
};
static desc_t lw857d_desc_42_0[] = {
    { "DISABLE", 0 },
    { "ENABLE", 1 },
};
static desc_t lw857d_desc_42_1[] = {
    { "DITHER_TO_6_BITS", 0 },
    { "DITHER_TO_8_BITS", 1 },
};
static desc_t lw857d_desc_42_2[] = {
    { "DYNAMIC_ERR_ACC", 0 },
    { "STATIC_ERR_ACC", 1 },
    { "DYNAMIC_2X2", 2 },
    { "STATIC_2X2", 3 },
};
static desc_t lw857d_desc_43_0[] = {
    { "TAPS_1", 0 },
    { "TAPS_2", 1 },
    { "TAPS_3", 2 },
    { "TAPS_3_ADAPTIVE", 3 },
    { "TAPS_5", 4 },
};
static desc_t lw857d_desc_43_1[] = {
    { "TAPS_1", 0 },
    { "TAPS_2", 1 },
    { "TAPS_8", 2 },
};
static desc_t lw857d_desc_44_0[] = {
    { "RGB", 0 },
    { "YUV_601", 1 },
    { "YUV_709", 2 },
};
static desc_t lw857d_desc_44_1[] = {
    { "AUTO", 0 },
    { "ON", 1 },
};
static desc_t lw857d_desc_44_4[] = {
    { "HARD", 0 },
    { "NTSC", 1 },
    { "PAL", 2 },
};
static desc_t lw857d_desc_44_5[] = {
    { "VESA", 0 },
    { "CEA", 1 },
};
static desc_t lw857d_desc_50_0[] = {
    { "FALSE", 0 },
    { "TRUE", 1 },
};
static desc_t lw857d_desc_50_1[] = {
    { "FALSE", 0 },
    { "TRUE", 1 },
};
static desc_t lw857d_desc_50_2[] = {
    { "BPP_8", 0 },
    { "BPP_16", 1 },
    { "BPP_32", 3 },
    { "BPP_64", 5 },
};
static desc_t lw857d_desc_50_3[] = {
    { "X1_AA", 0 },
    { "X4_AA", 2 },
};
static desc_t lw857d_desc_51_0[] = {
    { "FALSE", 0 },
    { "TRUE", 1 },
};
static desc_t lw857d_desc_51_1[] = {
    { "BPP_16", 1 },
    { "BPP_32", 3 },
};
static desc_t lw857d_desc_52_0[] = {
    { "DISABLE", 0 },
    { "ENABLE", 1 },
};


// FIELDS-----------------------------------
static flds_t lw857d_flds_0[] = {
    { "PTR", 11, 2, 0, 0 },
};
static flds_t lw857d_flds_1[] = {
    { "PTR", 11, 2, 0, 0 },
};
static flds_t lw857d_flds_2[] = {
    { "INTERLOCK_WITH_LWRSOR0", 0, 0, 2, lw857d_desc_2_0 },
    { "INTERLOCK_WITH_LWRSOR1", 8, 8, 2, lw857d_desc_2_1 },
    { "INTERLOCK_WITH_BASE0", 1, 1, 2, lw857d_desc_2_2 },
    { "INTERLOCK_WITH_BASE1", 9, 9, 2, lw857d_desc_2_3 },
    { "INTERLOCK_WITH_OVERLAY0", 2, 2, 2, lw857d_desc_2_4 },
    { "INTERLOCK_WITH_OVERLAY1", 10, 10, 2, lw857d_desc_2_5 },
    { "INTERLOCK_WITH_OVERLAY_IMM0", 3, 3, 2, lw857d_desc_2_6 },
    { "INTERLOCK_WITH_OVERLAY_IMM1", 11, 11, 2, lw857d_desc_2_7 },
    { "NOT_DRIVER_FRIENDLY", 31, 31, 2, lw857d_desc_2_8 },
    { "NOT_DRIVER_UNFRIENDLY", 30, 30, 2, lw857d_desc_2_9 },
    { "INHIBIT_INTERRUPTS", 29, 29, 2, lw857d_desc_2_10 },
};
static flds_t lw857d_flds_3[] = {
    { "MODE", 30, 30, 2, lw857d_desc_3_0 },
    { "OFFSET", 11, 2, 0, 0 },
    { "NOTIFY", 31, 31, 2, lw857d_desc_3_2 },
};
static flds_t lw857d_flds_8[] = {
    { "OWNER", 3, 0, 3, lw857d_desc_8_0 },
    { "SUB_OWNER", 5, 4, 4, lw857d_desc_8_1 },
    { "CRC_MODE", 7, 6, 3, lw857d_desc_8_2 },
    { "PROTOCOL", 13, 8, 20, lw857d_desc_8_3 },
    { "MACROVISION", 19, 16, 4, lw857d_desc_8_4 },
    { "ILWALIDATE_FIRST_FIELD", 14, 14, 2, lw857d_desc_8_5 },
};
static flds_t lw857d_flds_9[] = {
    { "HSYNC", 0, 0, 2, lw857d_desc_9_0 },
    { "VSYNC", 1, 1, 2, lw857d_desc_9_1 },
    { "RESERVED", 31, 2, 0, 0 },
};
static flds_t lw857d_flds_10[] = {
    { "NOISE_FILTER_BANDPASS", 7, 7, 2, lw857d_desc_10_0 },
    { "NOISE_GAIN", 2, 0, 6, lw857d_desc_10_1 },
    { "SHARPEN_GAIN", 6, 4, 6, lw857d_desc_10_2 },
    { "NOISE_THRSH", 15, 8, 0, 0 },
    { "SHARPEN_THRSH", 23, 16, 0, 0 },
    { "TINT", 31, 24, 0, 0 },
};
static flds_t lw857d_flds_11[] = {
    { "PROTOCOL", 5, 0, 20, lw857d_desc_11_0 },
    { "COMP_FORMAT", 6, 6, 2, lw857d_desc_11_1 },
    { "ENABLE_SYNC_ON_R", 7, 7, 2, lw857d_desc_11_2 },
    { "ENABLE_SYNC_ON_G", 8, 8, 2, lw857d_desc_11_3 },
    { "ENABLE_SYNC_ON_B", 9, 9, 2, lw857d_desc_11_4 },
    { "LUMA_NOTCH", 12, 10, 5, lw857d_desc_11_5 },
    { "CHROMA_BW_NARROW", 13, 13, 2, lw857d_desc_11_6 },
    { "CPST_FILTER", 15, 15, 2, lw857d_desc_11_7 },
    { "COMP_FILTER", 16, 16, 2, lw857d_desc_11_8 },
};
static flds_t lw857d_flds_12[] = {
    { "OWNER", 3, 0, 3, lw857d_desc_12_0 },
    { "SUB_OWNER", 5, 4, 4, lw857d_desc_12_1 },
    { "CRC_MODE", 7, 6, 3, lw857d_desc_12_2 },
    { "PROTOCOL", 11, 8, 11, lw857d_desc_12_3 },
    { "HSYNC_POLARITY", 12, 12, 2, lw857d_desc_12_4 },
    { "VSYNC_POLARITY", 13, 13, 2, lw857d_desc_12_5 },
    { "DE_SYNC_POLARITY", 14, 14, 2, lw857d_desc_12_6 },
    { "PIXEL_DEPTH", 19, 16, 10, lw857d_desc_12_7 },
};
static flds_t lw857d_flds_13[] = {
    { "OWNER", 3, 0, 3, lw857d_desc_13_0 },
    { "SUB_OWNER", 5, 4, 4, lw857d_desc_13_1 },
    { "CRC_MODE", 7, 6, 3, lw857d_desc_13_2 },
    { "PROTOCOL", 11, 8, 7, lw857d_desc_13_3 },
    { "HSYNC_POLARITY", 12, 12, 2, lw857d_desc_13_4 },
    { "VSYNC_POLARITY", 13, 13, 2, lw857d_desc_13_5 },
    { "DE_SYNC_POLARITY", 14, 14, 2, lw857d_desc_13_6 },
    { "PIXEL_DEPTH", 19, 16, 10, lw857d_desc_13_7 },
};
static flds_t lw857d_flds_14[] = {
    { "MIN_PRESENT_INTERVAL", 3, 0, 0, 0 },
    { "USE_BEGIN_FIELD", 8, 8, 2, lw857d_desc_14_1 },
    { "BEGIN_FIELD", 6, 4, 0, 0 },
};
static flds_t lw857d_flds_15[] = {
    { "FREQUENCY", 21, 0, 0, 0 },
    { "MODE", 23, 22, 3, lw857d_desc_15_1 },
    { "ADJ1000DIV1001", 24, 24, 2, lw857d_desc_15_2 },
    { "NOT_DRIVER", 25, 25, 2, lw857d_desc_15_3 },
};
static flds_t lw857d_flds_16[] = {
    { "ZAPHOD", 0, 0, 2, lw857d_desc_16_0 },
    { "STRUCTURE", 2, 1, 2, lw857d_desc_16_1 },
    { "SLAVE_LOCK_MODE", 7, 6, 3, lw857d_desc_16_2 },
    { "SLAVE_LOCK_PIN", 10, 8, 5, lw857d_desc_16_3 },
    { "SLAVE_LOCKOUT_WINDOW", 14, 11, 0, 0 },
    { "MASTER_LOCK_MODE", 19, 18, 3, lw857d_desc_16_5 },
    { "MASTER_LOCK_PIN", 22, 20, 5, lw857d_desc_16_6 },
    { "FLIP_LOCK", 23, 23, 2, lw857d_desc_16_7 },
    { "FLIP_LOCK_PIN", 26, 24, 5, lw857d_desc_16_8 },
    { "STEREO_SIGNAL", 28, 27, 2, lw857d_desc_16_9 },
    { "STEREO_PIN", 31, 29, 5, lw857d_desc_16_10 },
};
static flds_t lw857d_flds_17[] = {
    { "X", 14, 0, 0, 0 },
    { "Y", 30, 16, 0, 0 },
};
static flds_t lw857d_flds_18[] = {
    { "RED", 9, 0, 0, 0 },
    { "GRN", 19, 10, 0, 0 },
    { "BLU", 29, 20, 0, 0 },
};
static flds_t lw857d_flds_19[] = {
    { "WIDTH", 14, 0, 0, 0 },
    { "HEIGHT", 30, 16, 0, 0 },
};
static flds_t lw857d_flds_20[] = {
    { "X", 14, 0, 0, 0 },
    { "Y", 30, 16, 0, 0 },
};
static flds_t lw857d_flds_21[] = {
    { "X", 14, 0, 0, 0 },
    { "Y", 30, 16, 0, 0 },
};
static flds_t lw857d_flds_22[] = {
    { "X", 14, 0, 0, 0 },
    { "Y", 30, 16, 0, 0 },
};
static flds_t lw857d_flds_23[] = {
    { "YSTART", 14, 0, 0, 0 },
    { "YEND", 30, 16, 0, 0 },
};
static flds_t lw857d_flds_24[] = {
    { "DURATION", 11, 0, 0, 0 },
};
static flds_t lw857d_flds_25[] = {
    { "RED", 9, 0, 0, 0 },
    { "GREEN", 19, 10, 0, 0 },
    { "BLUE", 29, 20, 0, 0 },
};
static flds_t lw857d_flds_26[] = {
    { "CONTROLLING_CHANNEL", 7, 4, 3, lw857d_desc_26_0 },
    { "EXPECT_BUFFER_COLLAPSE", 12, 12, 2, lw857d_desc_26_1 },
    { "TIMESTAMP_MODE", 13, 13, 2, lw857d_desc_26_2 },
    { "FLIPLOCK_MODE", 14, 14, 2, lw857d_desc_26_3 },
    { "PRIMARY_OUTPUT", 19, 16, 11, lw857d_desc_26_4 },
    { "SECONDARY_OUTPUT", 27, 24, 11, lw857d_desc_26_5 },
    { "CRC_DURING_SNOOZE", 15, 15, 2, lw857d_desc_26_6 },
};
static flds_t lw857d_flds_27[] = {
    { "COMPUTE", 0, 0, 2, lw857d_desc_27_0 },
};
static flds_t lw857d_flds_29[] = {
    { "ENABLE", 31, 31, 2, lw857d_desc_29_0 },
    { "MODE", 30, 30, 2, lw857d_desc_29_1 },
    { "ORIGIN", 7, 2, 0, 0 },
};
static flds_t lw857d_flds_31[] = {
    { "ENABLE", 31, 31, 2, lw857d_desc_31_0 },
    { "MODE", 30, 30, 2, lw857d_desc_31_1 },
    { "ORIGIN", 7, 2, 0, 0 },
};
static flds_t lw857d_flds_35[] = {
    { "WIDTH", 14, 0, 0, 0 },
    { "HEIGHT", 30, 16, 0, 0 },
};
static flds_t lw857d_flds_36[] = {
    { "BLOCK_HEIGHT", 3, 0, 6, lw857d_desc_36_0 },
    { "PITCH", 17, 8, 0, 0 },
    { "MEMORY_LAYOUT", 20, 20, 2, lw857d_desc_36_2 },
};
static flds_t lw857d_flds_37[] = {
    { "FORMAT", 15, 8, 9, lw857d_desc_37_0 },
    { "SUPER_SAMPLE", 1, 0, 2, lw857d_desc_37_1 },
    { "GAMMA", 2, 2, 2, lw857d_desc_37_2 },
    { "RESERVED0", 22, 16, 0, 0 },
    { "RESERVED1", 24, 24, 0, 0 },
};
static flds_t lw857d_flds_39[] = {
    { "ENABLE", 31, 31, 2, lw857d_desc_39_0 },
    { "FORMAT", 25, 24, 2, lw857d_desc_39_1 },
    { "SIZE", 26, 26, 2, lw857d_desc_39_2 },
    { "HOT_SPOT_X", 13, 8, 0, 0 },
    { "HOT_SPOT_Y", 21, 16, 0, 0 },
    { "COMPOSITION", 29, 28, 3, lw857d_desc_39_5 },
    { "SUB_OWNER", 5, 4, 4, lw857d_desc_39_6 },
};
static flds_t lw857d_flds_42[] = {
    { "ENABLE", 0, 0, 2, lw857d_desc_42_0 },
    { "BITS", 2, 1, 2, lw857d_desc_42_1 },
    { "MODE", 6, 3, 4, lw857d_desc_42_2 },
    { "PHASE", 8, 7, 0, 0 },
};
static flds_t lw857d_flds_43[] = {
    { "VERTICAL_TAPS", 2, 0, 5, lw857d_desc_43_0 },
    { "HORIZONTAL_TAPS", 4, 3, 3, lw857d_desc_43_1 },
    { "HRESPONSE_BIAS", 23, 16, 0, 0 },
    { "VRESPONSE_BIAS", 31, 24, 0, 0 },
};
static flds_t lw857d_flds_44[] = {
    { "COLOR_SPACE", 1, 0, 3, lw857d_desc_44_0 },
    { "CHROMA_LPF", 2, 2, 2, lw857d_desc_44_1 },
    { "SAT_COS", 19, 8, 0, 0 },
    { "SAT_SINE", 31, 20, 0, 0 },
    { "TRANSITION", 4, 3, 3, lw857d_desc_44_4 },
    { "DYNAMIC_RANGE", 5, 5, 2, lw857d_desc_44_5 },
};
static flds_t lw857d_flds_45[] = {
    { "X", 14, 0, 0, 0 },
    { "Y", 30, 16, 0, 0 },
};
static flds_t lw857d_flds_46[] = {
    { "WIDTH", 14, 0, 0, 0 },
    { "HEIGHT", 30, 16, 0, 0 },
};
static flds_t lw857d_flds_47[] = {
    { "X", 15, 0, 0, 0 },
    { "Y", 31, 16, 0, 0 },
};
static flds_t lw857d_flds_48[] = {
    { "WIDTH", 14, 0, 0, 0 },
    { "HEIGHT", 30, 16, 0, 0 },
};
static flds_t lw857d_flds_49[] = {
    { "WIDTH", 14, 0, 0, 0 },
    { "HEIGHT", 30, 16, 0, 0 },
};
static flds_t lw857d_flds_50[] = {
    { "USABLE", 0, 0, 2, lw857d_desc_50_0 },
    { "DIST_RENDER_USABLE", 4, 4, 2, lw857d_desc_50_1 },
    { "PIXEL_DEPTH", 11, 8, 4, lw857d_desc_50_2 },
    { "SUPER_SAMPLE", 13, 12, 2, lw857d_desc_50_3 },
};
static flds_t lw857d_flds_51[] = {
    { "USABLE", 0, 0, 2, lw857d_desc_51_0 },
    { "PIXEL_DEPTH", 11, 8, 2, lw857d_desc_51_1 },
};
static flds_t lw857d_flds_52[] = {
    { "USE_GAIN_OFS", 0, 0, 2, lw857d_desc_52_0 },
};
static flds_t lw857d_flds_53[] = {
    { "GAIN", 15, 0, 0, 0 },
    { "OFS", 31, 16, 0, 0 },
};


// SUBSTRUCTS-----------------------------------
static substruct_t subst_lw857d_dac = { "DAC", 128, 3 };
static substruct_t subst_lw857d_sor = { "SOR", 64, 4 };
static substruct_t subst_lw857d_pior = { "PIOR", 64, 3 };
static substruct_t subst_lw857d_head = { "HEAD", 1024, 2 };


// METHODS-----------------------------------
static mthds_t lw857d_mthds[] = {
    { "PUT", 4, 1, 0x0, 0, 1, lw857d_flds_0, 0, 0x0, 0x0, 0x0, 0x0 },
    { "GET", 4, 1, 0x4, 0, 1, lw857d_flds_1, 0, 0x0, 0x0, 0x0, 0x0 },
    { "UPDATE", 4, 1, 0x80, 0, 11, lw857d_flds_2, 0, 0x0, 0x0, 0x0, 0x0 },
    { "SET_NOTIFIER_CONTROL", 4, 1, 0x84, 0, 3, lw857d_flds_3, 1, 0x610bb8, 0x0, 0x0, 0x0 },
    { "SET_CONTEXT_DMA_NOTIFIER", 4, 1, 0x88, 0, 0, 0, 1, 0x610b9c, 0x0, 0x0, 0x0 },
    { "GET_CAPABILITIES", 4, 1, 0x8c, 0, 0, 0, 0, 0x0, 0x0, 0x0, 0x0 },
    { "SET_SPARE", 4, 1, 0x3bc, 0, 0, 0, 0, 0x0, 0x0, 0x0, 0x0 },
    { "SET_SPARE_NOOP", 4, 16, 0x3c0, 0, 0, 0, 0, 0x0, 0x0, 0x0, 0x0 },
    { "DAC_SET_CONTROL", 4, 1, 0x400, &subst_lw857d_dac, 6, lw857d_flds_8, 1, 0x610b58, 0x0, 0x8, 0x0 },
    { "DAC_SET_POLARITY", 4, 1, 0x404, &subst_lw857d_dac, 3, lw857d_flds_9, 1, 0x610bdc, 0x0, 0x8, 0x0 },
    { "DAC_SET_ENCODE_QUALITY", 4, 1, 0x420, &subst_lw857d_dac, 6, lw857d_flds_10, 1, 0x610bc4, 0x0, 0x8, 0x0 },
    { "DAC_UPDATE_ENCODER_PRESET", 4, 1, 0x47c, &subst_lw857d_dac, 9, lw857d_flds_11, 0, 0x0, 0x0, 0x0, 0x0 },
    { "SOR_SET_CONTROL", 4, 1, 0x600, &subst_lw857d_sor, 8, lw857d_flds_12, 1, 0x610794, 0x0, 0x8, 0x0 },
    { "PIOR_SET_CONTROL", 4, 1, 0x700, &subst_lw857d_pior, 8, lw857d_flds_13, 1, 0x610b80, 0x0, 0x8, 0x0 },
    { "HEAD_SET_PRESENT_CONTROL", 4, 1, 0x800, &subst_lw857d_head, 3, lw857d_flds_14, 1, 0x610ad8, 0x540, 0x0, 0x0 },
    { "HEAD_SET_PIXEL_CLOCK", 4, 1, 0x804, &subst_lw857d_head, 4, lw857d_flds_15, 1, 0x610ad0, 0x540, 0x0, 0x0 },
    { "HEAD_SET_CONTROL", 4, 1, 0x808, &subst_lw857d_head, 11, lw857d_flds_16, 1, 0x610a48, 0x540, 0x0, 0x0 },
    { "HEAD_SET_LOCK_OFFSET", 4, 1, 0x80c, &subst_lw857d_head, 2, lw857d_flds_17, 1, 0x610a78, 0x540, 0x0, 0x0 },
    { "HEAD_SET_OVERSCAN_COLOR", 4, 1, 0x810, &subst_lw857d_head, 3, lw857d_flds_18, 1, 0x610ac0, 0x540, 0x0, 0x0 },
    { "HEAD_SET_RASTER_SIZE", 4, 1, 0x814, &subst_lw857d_head, 2, lw857d_flds_19, 1, 0x610af8, 0x540, 0x0, 0x0 },
    { "HEAD_SET_RASTER_SYNC_END", 4, 1, 0x818, &subst_lw857d_head, 2, lw857d_flds_20, 1, 0x610b00, 0x540, 0x0, 0x0 },
    { "HEAD_SET_RASTER_BLANK_END", 4, 1, 0x81c, &subst_lw857d_head, 2, lw857d_flds_21, 1, 0x610ae8, 0x540, 0x0, 0x0 },
    { "HEAD_SET_RASTER_BLANK_START", 4, 1, 0x820, &subst_lw857d_head, 2, lw857d_flds_22, 1, 0x610af0, 0x540, 0x0, 0x0 },
    { "HEAD_SET_RASTER_VERT_BLANK2", 4, 1, 0x824, &subst_lw857d_head, 2, lw857d_flds_23, 1, 0x610b08, 0x540, 0x0, 0x0 },
    { "HEAD_SET_RASTER_VERT_BLANK_DMI", 4, 1, 0x828, &subst_lw857d_head, 1, lw857d_flds_24, 1, 0x610b10, 0x540, 0x0, 0x0 },
    { "HEAD_SET_DEFAULT_BASE_COLOR", 4, 1, 0x82c, &subst_lw857d_head, 3, lw857d_flds_25, 1, 0x610a68, 0x540, 0x0, 0x0 },
    { "HEAD_SET_CRC_CONTROL", 4, 1, 0x830, &subst_lw857d_head, 7, lw857d_flds_26, 1, 0x610a60, 0x540, 0x0, 0x0 },
    { "HEAD_SET_LEGACY_CRC_CONTROL", 4, 1, 0x834, &subst_lw857d_head, 1, lw857d_flds_27, 1, 0x610bf4, 0x540, 0x0, 0x0 },
    { "HEAD_SET_CONTEXT_DMA_CRC", 4, 1, 0x838, &subst_lw857d_head, 0, 0, 1, 0x610a40, 0x540, 0x0, 0x0 },
    { "HEAD_SET_BASE_LUT_LO", 4, 1, 0x840, &subst_lw857d_head, 3, lw857d_flds_29, 1, 0x610a24, 0x540, 0x0, 0x0 },
    { "HEAD_SET_BASE_LUT_HI", 4, 1, 0x844, &subst_lw857d_head, 0, 0, 1, 0x610a2c, 0x540, 0x0, 0x0 },
    { "HEAD_SET_OUTPUT_LUT_LO", 4, 1, 0x848, &subst_lw857d_head, 3, lw857d_flds_31, 1, 0x610aa8, 0x540, 0x0, 0x0 },
    { "HEAD_SET_OUTPUT_LUT_HI", 4, 1, 0x84c, &subst_lw857d_head, 0, 0, 1, 0x610ab0, 0x540, 0x0, 0x0 },
    { "HEAD_SET_CONTEXT_DMA_LUT", 4, 1, 0x85c, &subst_lw857d_head, 0, 0, 1, 0x610c5c, 0x540, 0x0, 0x0 },
    { "HEAD_SET_OFFSET", 4, 2, 0x860, &subst_lw857d_head, 0, 0, 1, 0x610a84, 0x540, 0xc, 0x0 },
    { "HEAD_SET_SIZE", 4, 1, 0x868, &subst_lw857d_head, 2, lw857d_flds_35, 1, 0x610b18, 0x540, 0x0, 0x0 },
    { "HEAD_SET_STORAGE", 4, 1, 0x86c, &subst_lw857d_head, 3, lw857d_flds_36, 1, 0x610b20, 0x540, 0x0, 0x0 },
    { "HEAD_SET_PARAMS", 4, 1, 0x870, &subst_lw857d_head, 5, lw857d_flds_37, 1, 0x610ac8, 0x540, 0x0, 0x0 },
    { "HEAD_SET_CONTEXT_DMAS_ISO", 4, 2, 0x874, &subst_lw857d_head, 0, 0, 1, 0x610a38, 0x540, 0x0, 0x218 },
    { "HEAD_SET_CONTROL_LWRSOR", 4, 1, 0x880, &subst_lw857d_head, 7, lw857d_flds_39, 1, 0x610a58, 0x540, 0x0, 0x0 },
    { "HEAD_SET_OFFSET_LWRSOR", 4, 1, 0x884, &subst_lw857d_head, 0, 0, 1, 0x610a9c, 0x540, 0x0, 0x0 },
    { "HEAD_SET_CONTEXT_DMA_LWRSOR", 4, 1, 0x89c, &subst_lw857d_head, 0, 0, 1, 0x610c68, 0x540, 0x0, 0x0 },
    { "HEAD_SET_DITHER_CONTROL", 4, 1, 0x8a0, &subst_lw857d_head, 4, lw857d_flds_42, 1, 0x610a70, 0x540, 0x0, 0x0 },
    { "HEAD_SET_CONTROL_OUTPUT_SCALER", 4, 1, 0x8a4, &subst_lw857d_head, 4, lw857d_flds_43, 1, 0x610a50, 0x540, 0x0, 0x0 },
    { "HEAD_SET_PROCAMP", 4, 1, 0x8a8, &subst_lw857d_head, 6, lw857d_flds_44, 1, 0x610ae0, 0x540, 0x0, 0x0 },
    { "HEAD_SET_VIEWPORT_POINT_IN", 4, 2, 0x8c0, &subst_lw857d_head, 2, lw857d_flds_45, 1, 0x610b28, 0x540, 0x8, 0x0 },
    { "HEAD_SET_VIEWPORT_SIZE_IN", 4, 1, 0x8c8, &subst_lw857d_head, 2, lw857d_flds_46, 1, 0x610b40, 0x540, 0x0, 0x0 },
    { "HEAD_SET_VIEWPORT_POINT_OUT_ADJUST", 4, 1, 0x8d4, &subst_lw857d_head, 2, lw857d_flds_47, 1, 0x610b38, 0x540, 0x0, 0x0 },
    { "HEAD_SET_VIEWPORT_SIZE_OUT", 4, 1, 0x8d8, &subst_lw857d_head, 2, lw857d_flds_48, 1, 0x610b48, 0x540, 0x0, 0x0 },
    { "HEAD_SET_VIEWPORT_SIZE_OUT_MIN", 4, 1, 0x8dc, &subst_lw857d_head, 2, lw857d_flds_49, 1, 0x610b50, 0x540, 0x0, 0x0 },
    { "HEAD_SET_BASE_CHANNEL_USAGE_BOUNDS", 4, 1, 0x900, &subst_lw857d_head, 4, lw857d_flds_50, 1, 0x610a18, 0x540, 0x0, 0x0 },
    { "HEAD_SET_OVERLAY_USAGE_BOUNDS", 4, 1, 0x904, &subst_lw857d_head, 2, lw857d_flds_51, 1, 0x610ab8, 0x540, 0x0, 0x0 },
    { "HEAD_SET_PROCESSING", 4, 1, 0x910, &subst_lw857d_head, 1, lw857d_flds_52, 1, 0x610c70, 0x540, 0x0, 0x0 },
    { "HEAD_SET_COLWERSION", 4, 1, 0x914, &subst_lw857d_head, 2, lw857d_flds_53, 1, 0x610c78, 0x540, 0x0, 0x0 },
    { "HEAD_SET_SPARE", 4, 1, 0xbbc, &subst_lw857d_head, 0, 0, 0, 0x0, 0x0, 0x0, 0x0 },
    { "HEAD_SET_SPARE_NOOP", 4, 16, 0xbc0, &subst_lw857d_head, 0, 0, 0, 0x0, 0x0, 0x0, 0x0 },
};


#define num_lw857d_mthds (56)
// ---------------------EOF--------------------
