// do not change, this file is automatically generated.
// NOTE: this file should be included by only one file
//       thus, no #ifndef, #endif.





// This file is generated with  
// ./clparser -I clc37b.h 


// FIELD DESCRIPTORS-----------------------------------
static desc_t lwc37b_desc_2_0[] = {
    { "FALSE", 0 },
    { "TRUE", 1 },
};
static desc_t lwc37b_desc_2_1[] = {
    { "DISABLE", 0 },
    { "ENABLE", 1 },
};


// FIELDS-----------------------------------
static flds_t lwc37b_flds_0[] = {
    { "PTR", 9, 0, 0, 0 },
};
static flds_t lwc37b_flds_1[] = {
    { "PTR", 9, 0, 0, 0 },
};
static flds_t lwc37b_flds_2[] = {
    { "RELEASE_ELV", 0, 0, 2, lwc37b_desc_2_0 },
    { "INTERLOCK_WITH_WINDOW", 1, 1, 2, lwc37b_desc_2_1 },
};
static flds_t lwc37b_flds_3[] = {
    { "X", 15, 0, 0, 0 },
    { "Y", 31, 16, 0, 0 },
};


// METHODS-----------------------------------
static mthds_t lwc37b_mthds[] = {
    { "PUT", 4, 1, 0x0, 0, 1, lwc37b_flds_0, 0, 0x0, 0x0, 0x0, 0x0 },
    { "GET", 4, 1, 0x4, 0, 1, lwc37b_flds_1, 0, 0x0, 0x0, 0x0, 0x0 },
    { "UPDATE", 4, 1, 0x200, 0, 2, lwc37b_flds_2, 0, 0x0, 0x0, 0x0, 0x0 },
    { "SET_POINT_OUT", 4, 2, 0x208, 0, 2, lwc37b_flds_3, 0, 0x0, 0x0, 0x0, 0x0 },
};


#define num_lwc37b_mthds (4)


//------------- EOF -------------
