################################### tell Emacs this is a -*- makefile-gmake -*-
#
# Copyright (c) 2021 LWPU CORPORATION.  All Rights Reserved.
#
# LWPU CORPORATION and its licensors retain all intellectual property
# and proprietary rights in and to this software, related documentation
# and any modifications thereto.  Any use, reproduction, disclosure or
# distribution of this software and related documentation without an express
# license agreement from LWPU CORPORATION is strictly prohibited.
#
# lwscibuf test exelwtable makefile fragment
#
###############################################################################

ifdef LW_COMPONENT_FLAG_LWMAKE_EXELWTABLE_SECTION
    include $(LW_BUILD_START_COMPONENT)

    LW_COMPONENT_NAME                    := test_lwscibuf_kpi

    LW_COMPONENT_FLAG_IS_TEST            := 1

    include $(LW_BUILD_LWMAKE_EXELWTABLE)
endif

# variable cleanup
# Local Variables:
# indent-tabs-mode: t
# tab-width: 8
# End:
# vi: set tabstop=8 noexpandtab:
