################################### tell Emacs this is a -*- makefile-gmake -*-
#
# Copyright (c) 2019-2022 LWPU CORPORATION.  All Rights Reserved.
#
# LWPU CORPORATION and its licensors retain all intellectual property
# and proprietary rights in and to this software, related documentation
# and any modifications thereto.  Any use, reproduction, disclosure or
# distribution of this software and related documentation without an express
# license agreement from LWPU CORPORATION is strictly prohibited.
#
# tmake for SW Mobile
#
# Component makefile for lwscibuf_submit, lwscisync_submit, lwscistream_submit,
# run_lwscibuf_kpi.sh, run_lwscisync_kpi.sh and run_lwscistream_kpi.sh
#
###############################################################################

ifdef LW_COMPONENT_FLAG_LWTEST_EXELWTABLE_SECTION
include $(LW_BUILD_START_COMPONENT)

LW_COMPONENT_NAME := lwscibuf_submit

systemimage:: $(LW_SYSTEMIMAGE_TEST_EXELWTABLE_DIR)/$(LW_COMPONENT_NAME)

$(LW_SYSTEMIMAGE_TEST_EXELWTABLE_DIR)/$(LW_COMPONENT_NAME): $(LW_COMPONENT_DIR)/$(LW_COMPONENT_NAME)
	$(CP) $< $@

endif

ifdef LW_COMPONENT_FLAG_LWTEST_EXELWTABLE_SECTION
include $(LW_BUILD_START_COMPONENT)

LW_COMPONENT_NAME := lwscistream_submit

systemimage:: $(LW_SYSTEMIMAGE_TEST_EXELWTABLE_DIR)/$(LW_COMPONENT_NAME)

$(LW_SYSTEMIMAGE_TEST_EXELWTABLE_DIR)/$(LW_COMPONENT_NAME): $(LW_COMPONENT_DIR)/$(LW_COMPONENT_NAME)
	$(CP) $< $@

endif

ifdef LW_COMPONENT_FLAG_LWTEST_EXELWTABLE_SECTION
include $(LW_BUILD_START_COMPONENT)

LW_COMPONENT_NAME := lwscisync_submit

systemimage:: $(LW_SYSTEMIMAGE_TEST_EXELWTABLE_DIR)/$(LW_COMPONENT_NAME)

$(LW_SYSTEMIMAGE_TEST_EXELWTABLE_DIR)/$(LW_COMPONENT_NAME): $(LW_COMPONENT_DIR)/$(LW_COMPONENT_NAME)
	$(CP) $< $@

endif

ifdef LW_COMPONENT_FLAG_LWTEST_EXELWTABLE_SECTION
include $(LW_BUILD_START_COMPONENT)

LW_COMPONENT_NAME := run_lwscibuf_kpi.sh
RELATIVE_SRC_PATH := ../../lwscibuf/kpi/$(LW_COMPONENT_NAME)

systemimage:: $(LW_SYSTEMIMAGE_TEST_EXELWTABLE_DIR)/$(LW_COMPONENT_NAME)

$(LW_SYSTEMIMAGE_TEST_EXELWTABLE_DIR)/$(LW_COMPONENT_NAME): $(LW_COMPONENT_DIR)/$(RELATIVE_SRC_PATH)
	$(CP) $< $@

endif

ifdef LW_COMPONENT_FLAG_LWTEST_EXELWTABLE_SECTION
include $(LW_BUILD_START_COMPONENT)

LW_COMPONENT_NAME := run_lwscisync_kpi.sh
RELATIVE_SRC_PATH := ../../lwscisync/kpi/kpi/$(LW_COMPONENT_NAME)

systemimage:: $(LW_SYSTEMIMAGE_TEST_EXELWTABLE_DIR)/$(LW_COMPONENT_NAME)

$(LW_SYSTEMIMAGE_TEST_EXELWTABLE_DIR)/$(LW_COMPONENT_NAME): $(LW_COMPONENT_DIR)/$(RELATIVE_SRC_PATH)
	$(CP) $< $@

endif

ifdef LW_COMPONENT_FLAG_LWTEST_EXELWTABLE_SECTION
include $(LW_BUILD_START_COMPONENT)

LW_COMPONENT_NAME := run_lwscistream_kpi.sh
RELATIVE_SRC_PATH := ../../lwscistream/kpi_tests/$(LW_COMPONENT_NAME)

systemimage:: $(LW_SYSTEMIMAGE_TEST_EXELWTABLE_DIR)/$(LW_COMPONENT_NAME)

$(LW_SYSTEMIMAGE_TEST_EXELWTABLE_DIR)/$(LW_COMPONENT_NAME): $(LW_COMPONENT_DIR)/$(RELATIVE_SRC_PATH)
	$(CP) $< $@

endif

# Local Variables:
# indent-tabs-mode: t
# tab-width: 8
# End:
# vi: set tabstop=8 noexpandtab:
