; generated by perfsim fixed function pixel shader
ps_2_0
dcl_pp t0
dcl_2d s0

; color: CGITSSOpModulate TSSArgLwrrent TSSArgTexture TSSArgTFactor
; alpha: CGITSSOpModulate TSSArgLwrrent TSSArgTexture TSSArgTFactor
texld_pp r2, t0, s0
mul_pp r0.rgb, r2,c0
mul_pp r0.a, r2,c1
mov oC0, r0

