USE_NEW_PROJECT_MK := 1
SOLNDIR:=.
# Update ROOTDIR according to Bug 200494750.
ROOTDIR	?= $(realpath $(or\
	,${VULCAN_TOOLKIT_BASE}\
	,../../..))

ifndef PROFILE
  include $(ROOTDIR)/build/getprofile.mk
  include $(ROOTDIR)/build/config/$(PROFILE).mk
endif

PROJECTS += lwtensor

#test.build: lwtensor
#	${MAKE} -C test BUILD_GPGPU=1
#
#test.clean:
#	${MAKE} -C test clean BUILD_GPGPU=1
#
#all: test.build
#
#.DEFAULT_GOAL := all
#
#clean: test.clean

include ${ROOTDIR}/build/common.mk
