#!/bin/sh
set -e

# This is a workaround for a seeming bug in the debhelper version running on the
# builder. It should not be copied when we switch to a new build process

chmod -R 755 /usr/local/dcgm
