//
// LWIDIA_COPYRIGHT_BEGIN
//
// Copyright 2021 by LWPU Corporation.  All rights reserved.  All
// information contained herein is proprietary and confidential to LWPU
// Corporation.  Any use, reproduction, or disclosure without the written
// permission of LWPU Corporation is prohibited.
//
// LWIDIA_COPYRIGHT_END
//
// AUTO GENERATED FILE -- DO NOT EDIT 
// Command: ../../../../class/bin/dx_driver_method_table.pl kepler_inline_to_memory_b


    { 0x0000, "SET_OBJECT",                                                                     MF_ACTION, MVT_DWORD, NULL},
    { 0x0100, "NO_OPERATION",                                                                   MF_ACTION, MVT_DWORD, NULL},
    { 0x0104, "SET_NOTIFY_A",                                                                     MF_NONE, MVT_DWORD, NULL},
    { 0x0108, "SET_NOTIFY_B",                                                                     MF_NONE, MVT_DWORD, NULL},
    { 0x010c, "NOTIFY",                                                                         MF_ACTION, MVT_DWORD, NULL},
    { 0x0110, "WAIT_FOR_IDLE",                                                           MF_WFI|MF_ACTION, MVT_DWORD, NULL},
    { 0x0130, "SET_GLOBAL_RENDER_ENABLE_A",                                                       MF_NONE, MVT_DWORD, NULL},
    { 0x0134, "SET_GLOBAL_RENDER_ENABLE_B",                                                       MF_NONE, MVT_DWORD, NULL},
    { 0x0138, "SET_GLOBAL_RENDER_ENABLE_C",                                                     MF_ACTION, MVT_DWORD, NULL},
    { 0x013c, "SEND_GO_IDLE",                                                                   MF_ACTION, MVT_DWORD, NULL},
    { 0x0140, "PM_TRIGGER",                                                                     MF_ACTION, MVT_DWORD, NULL},
    { 0x0144, "PM_TRIGGER_WFI",                                                          MF_WFI|MF_ACTION, MVT_DWORD, NULL},
    { 0x0150, "SET_INSTRUMENTATION_METHOD_HEADER",                                                MF_NONE, MVT_DWORD, NULL},
    { 0x0154, "SET_INSTRUMENTATION_METHOD_DATA",                                                  MF_NONE, MVT_DWORD, NULL},
    { 0x0180, "LINE_LENGTH_IN",                                                                   MF_NONE, MVT_DWORD, NULL},
    { 0x0184, "LINE_COUNT",                                                                       MF_NONE, MVT_DWORD, NULL},
    { 0x0188, "OFFSET_OUT_UPPER",                                                                 MF_NONE, MVT_DWORD, NULL},
    { 0x018c, "OFFSET_OUT",                                                                       MF_NONE, MVT_DWORD, NULL},
    { 0x0190, "PITCH_OUT",                                                                        MF_NONE, MVT_DWORD, NULL},
    { 0x0194, "SET_DST_BLOCK_SIZE",                                                               MF_NONE, MVT_DWORD, NULL},
    { 0x0198, "SET_DST_WIDTH",                                                                    MF_NONE, MVT_DWORD, NULL},
    { 0x019c, "SET_DST_HEIGHT",                                                                   MF_NONE, MVT_DWORD, NULL},
    { 0x01a0, "SET_DST_DEPTH",                                                                    MF_NONE, MVT_DWORD, NULL},
    { 0x01a4, "SET_DST_LAYER",                                                                    MF_NONE, MVT_DWORD, NULL},
    { 0x01a8, "SET_DST_ORIGIN_BYTES_X",                                                           MF_NONE, MVT_DWORD, NULL},
    { 0x01ac, "SET_DST_ORIGIN_SAMPLES_Y",                                                         MF_NONE, MVT_DWORD, NULL},
    { 0x01b0, "LAUNCH_DMA",                                                                     MF_ACTION, MVT_DWORD, NULL},
    { 0x01b4, "LOAD_INLINE_DATA",                                                               MF_ACTION, MVT_DWORD, NULL},
    { 0x01dc, "SET_I2M_SEMAPHORE_A",                                                              MF_NONE, MVT_DWORD, NULL},
    { 0x01e0, "SET_I2M_SEMAPHORE_B",                                                              MF_NONE, MVT_DWORD, NULL},
    { 0x01e4, "SET_I2M_SEMAPHORE_C",                                                              MF_NONE, MVT_DWORD, NULL},
    { 0x01f0, "SET_I2M_SPARE_NOOP00",                                                             MF_NONE, MVT_DWORD, NULL},
    { 0x01f4, "SET_I2M_SPARE_NOOP01",                                                             MF_NONE, MVT_DWORD, NULL},
    { 0x01f8, "SET_I2M_SPARE_NOOP02",                                                             MF_NONE, MVT_DWORD, NULL},
    { 0x01fc, "SET_I2M_SPARE_NOOP03",                                                             MF_NONE, MVT_DWORD, NULL},
    { 0x0200, "SET_FALCON00",                                                                     MF_NONE, MVT_DWORD, NULL},
    { 0x0204, "SET_FALCON01",                                                                     MF_NONE, MVT_DWORD, NULL},
    { 0x0208, "SET_FALCON02",                                                                     MF_NONE, MVT_DWORD, NULL},
    { 0x020c, "SET_FALCON03",                                                                     MF_NONE, MVT_DWORD, NULL},
    { 0x0210, "SET_FALCON04",                                                                     MF_NONE, MVT_DWORD, NULL},
    { 0x0214, "SET_FALCON05",                                                                     MF_NONE, MVT_DWORD, NULL},
    { 0x0218, "SET_FALCON06",                                                                     MF_NONE, MVT_DWORD, NULL},
    { 0x021c, "SET_FALCON07",                                                                     MF_NONE, MVT_DWORD, NULL},
    { 0x0220, "SET_FALCON08",                                                                     MF_NONE, MVT_DWORD, NULL},
    { 0x0224, "SET_FALCON09",                                                                     MF_NONE, MVT_DWORD, NULL},
    { 0x0228, "SET_FALCON10",                                                                     MF_NONE, MVT_DWORD, NULL},
    { 0x022c, "SET_FALCON11",                                                                     MF_NONE, MVT_DWORD, NULL},
    { 0x0230, "SET_FALCON12",                                                                     MF_NONE, MVT_DWORD, NULL},
    { 0x0234, "SET_FALCON13",                                                                     MF_NONE, MVT_DWORD, NULL},
    { 0x0238, "SET_FALCON14",                                                                     MF_NONE, MVT_DWORD, NULL},
    { 0x023c, "SET_FALCON15",                                                                     MF_NONE, MVT_DWORD, NULL},
    { 0x0240, "SET_FALCON16",                                                                     MF_NONE, MVT_DWORD, NULL},
    { 0x0244, "SET_FALCON17",                                                                     MF_NONE, MVT_DWORD, NULL},
    { 0x0248, "SET_FALCON18",                                                                     MF_NONE, MVT_DWORD, NULL},
    { 0x024c, "SET_FALCON19",                                                                     MF_NONE, MVT_DWORD, NULL},
    { 0x0250, "SET_FALCON20",                                                                     MF_NONE, MVT_DWORD, NULL},
    { 0x0254, "SET_FALCON21",                                                                     MF_NONE, MVT_DWORD, NULL},
    { 0x0258, "SET_FALCON22",                                                                     MF_NONE, MVT_DWORD, NULL},
    { 0x025c, "SET_FALCON23",                                                                     MF_NONE, MVT_DWORD, NULL},
    { 0x0260, "SET_FALCON24",                                                                     MF_NONE, MVT_DWORD, NULL},
    { 0x0264, "SET_FALCON25",                                                                     MF_NONE, MVT_DWORD, NULL},
    { 0x0268, "SET_FALCON26",                                                                     MF_NONE, MVT_DWORD, NULL},
    { 0x026c, "SET_FALCON27",                                                                     MF_NONE, MVT_DWORD, NULL},
    { 0x0270, "SET_FALCON28",                                                                     MF_NONE, MVT_DWORD, NULL},
    { 0x0274, "SET_FALCON29",                                                                     MF_NONE, MVT_DWORD, NULL},
    { 0x0278, "SET_FALCON30",                                                                     MF_NONE, MVT_DWORD, NULL},
    { 0x027c, "SET_FALCON31",                                                                     MF_NONE, MVT_DWORD, NULL},
    { 0x1550, "SET_RENDER_ENABLE_A",                                                              MF_NONE, MVT_DWORD, NULL},
    { 0x1554, "SET_RENDER_ENABLE_B",                                                              MF_NONE, MVT_DWORD, NULL},
    { 0x1558, "SET_RENDER_ENABLE_C",                                                            MF_ACTION, MVT_DWORD, NULL},
    { 0x1944, "SET_RENDER_ENABLE_OVERRIDE",                                                       MF_NONE, MVT_DWORD, NULL},
    { 0x3400, "SET_MME_SHADOW_SCRATCH(0)",                                                        MF_NONE, MVT_DWORD, NULL},
    { 0x3404, "SET_MME_SHADOW_SCRATCH(1)",                                                        MF_NONE, MVT_DWORD, NULL},
    { 0x3408, "SET_MME_SHADOW_SCRATCH(2)",                                                        MF_NONE, MVT_DWORD, NULL},
    { 0x340c, "SET_MME_SHADOW_SCRATCH(3)",                                                        MF_NONE, MVT_DWORD, NULL},
    { 0x3410, "SET_MME_SHADOW_SCRATCH(4)",                                                        MF_NONE, MVT_DWORD, NULL},
    { 0x3414, "SET_MME_SHADOW_SCRATCH(5)",                                                        MF_NONE, MVT_DWORD, NULL},
    { 0x3418, "SET_MME_SHADOW_SCRATCH(6)",                                                        MF_NONE, MVT_DWORD, NULL},
    { 0x341c, "SET_MME_SHADOW_SCRATCH(7)",                                                        MF_NONE, MVT_DWORD, NULL},
    { 0 }
