/*
* _LWRM_COPYRIGHT_BEGIN_
*
* Copyright 2021 by LWPU Corporation.  All rights reserved.  All
* information contained herein is proprietary and confidential to LWPU
* Corporation.  Any use, reproduction, or disclosure without the written
* permission of LWPU Corporation is prohibited.
*
* _LWRM_COPYRIGHT_END_
*/

// AUTO GENERATED -- DO NOT EDIT - this file automatically generated by refhdr2class.pl
// Command: ../../../../../../../../bin/manuals/refhdr2class.pl clc361.h c361 VOLTA_USERMODE_A --search_str=LW_USERMODE --input_file=lw_ref_dev_usermode.h --zero_based_offsets --add_size_defines


#ifndef _clc361_h_
#define _clc361_h_

#ifdef __cplusplus
extern "C" {
#endif

#define VOLTA_USERMODE_A (0xc361)

#define LWC361                                                 0x0081ffff:0x00810000
#define LWC361_LW_USERMODE__SIZE    65536
#define LWC361_CFG0                                                       0x00000000
#define LWC361_CFG0_USERMODE_CLASS_ID                                           15:0
#define LWC361_CFG0_USERMODE_CLASS_ID_VALUE                               0x0000c361
#define LWC361_TIME_0                                                     0x00000080
#define LWC361_TIME_0_NSEC                                                      31:5
#define LWC361_TIME_1                                                     0x00000084
#define LWC361_TIME_1_NSEC                                                      28:0
#define LWC361_NOTIFY_CHANNEL_PENDING                                     0x00000090
#define LWC361_NOTIFY_CHANNEL_PENDING_ID                                        31:0

#ifdef __cplusplus
};     /* extern "C" */
#endif

#endif /* _clc361_h_ */
