/*
* _LWRM_COPYRIGHT_BEGIN_
*
* Copyright 2022 by LWPU Corporation.  All rights reserved.  All
* information contained herein is proprietary and confidential to LWPU
* Corporation.  Any use, reproduction, or disclosure without the written
* permission of LWPU Corporation is prohibited.
*
* _LWRM_COPYRIGHT_END_
*/

// AUTO GENERATED -- DO NOT EDIT - this file automatically generated by refhdr2class.pl
// Command: ../../../../../../../../bin/manuals/refhdr2class.pl clc561.h c561 AMPERE_USERMODE_A --search_str=LW_VIRTUAL_FUNCTION --exclude_regex=LW_VIRTUAL_FUNCTION_PRIV --exclude_regex=VFALIAS --exclude_regex=FULL_PHYS_OFFSET --exclude_regex=MSCG_BLOCK --input_file=lw_ref_dev_vm.h --zero_based_offsets --add_size_defines


#ifndef _clc561_h_
#define _clc561_h_

#ifdef __cplusplus
extern "C" {
#endif

#define AMPERE_USERMODE_A (0xc561)

#define LWC561                                                      0x0000ffff:0x00000000
#define LWC561_AMPERE_USERMODE_A__SIZE                                              65536
#define LWC561_CFG0                                                            0x00000000
#define LWC561_CFG0_USERMODE_CLASS_ID                                                15:0
#define LWC561_CFG0_USERMODE_CLASS_ID_VALUE                                        0xc561
#define LWC561_TIME_0                                                          0x00000080
#define LWC561_TIME_0_NSEC                                                           31:5
#define LWC561_TIME_1                                                          0x00000084
#define LWC561_TIME_1_NSEC                                                           28:0
#define LWC561_DOORBELL                                                        0x00000090
#define LWC561_DOORBELL_HANDLE                                                       31:0
#define LWC561_ERR_CONT                                                        0x00000094
#define LWC561_ERR_CONT_GRAPHICS                                                      0:0
#define LWC561_ERR_CONT_GRAPHICS_NOT_PENDING                                          0x0
#define LWC561_ERR_CONT_GRAPHICS_PENDING                                              0x1
#define LWC561_ERR_CONT_MMU_ECC                                                       1:1
#define LWC561_ERR_CONT_MMU_ECC_NOT_PENDING                                           0x0
#define LWC561_ERR_CONT_MMU_ECC_PENDING                                               0x1
#define LWC561_ERR_CONT_LWLINK_0                                                      2:2
#define LWC561_ERR_CONT_LWLINK_0_NOT_PENDING                                          0x0
#define LWC561_ERR_CONT_LWLINK_0_PENDING                                              0x1
#define LWC561_ERR_CONT_LWLINK_1                                                      3:3
#define LWC561_ERR_CONT_LWLINK_1_NOT_PENDING                                          0x0
#define LWC561_ERR_CONT_LWLINK_1_PENDING                                              0x1
#define LWC561_ERR_CONT_LTC                                                           4:4
#define LWC561_ERR_CONT_LTC_NOT_PENDING                                               0x0
#define LWC561_ERR_CONT_LTC_PENDING                                                   0x1
#define LWC561_ERR_CONT_PFB                                                           5:5
#define LWC561_ERR_CONT_PFB_NOT_PENDING                                               0x0
#define LWC561_ERR_CONT_PFB_PENDING                                                   0x1
#define LWC561_ERR_CONT_FBHUB_0                                                       6:6
#define LWC561_ERR_CONT_FBHUB_0_NOT_PENDING                                           0x0
#define LWC561_ERR_CONT_FBHUB_0_PENDING                                               0x1
#define LWC561_ERR_CONT_SMC_ENG_HW_IMPL                                              15:8
#define LWC561_ERR_CONT_SMC_ENG(i)                                        ((i)+8):((i)+8)
#define LWC561_ERR_CONT_SMC_ENG__SIZE_1                                                 8
#define LWC561_ERR_CONT_SMC_ENG_NOT_PENDING                                           0x0
#define LWC561_ERR_CONT_SMC_ENG_PENDING                                               0x1

#ifdef __cplusplus
};     /* extern "C" */
#endif

#endif /* _clc561_h_ */
