/*
* _LWRM_COPYRIGHT_BEGIN_
*
* Copyright 2022 by LWPU Corporation.  All rights reserved.  All
* information contained herein is proprietary and confidential to LWPU
* Corporation.  Any use, reproduction, or disclosure without the written
* permission of LWPU Corporation is prohibited.
*
* _LWRM_COPYRIGHT_END_
*/

// AUTO GENERATED -- DO NOT EDIT - this file automatically generated by refhdr2class.pl
// Command: ../../../../../../../../bin/manuals/refhdr2class.pl clc863.h c863 HOPPER_MMU_VIDMEM_ACCESS_BIT_BUFFER --search_str=LW_MMU_VIDMEM_ACCESS_BIT_BUF --input_file=lw_ref_dev_mmu_vidmem_access_bits.h


#ifndef _clc863_h_
#define _clc863_h_

#ifdef __cplusplus
extern "C" {
#endif

#define HOPPER_MMU_VIDMEM_ACCESS_BIT_BUFFER (0xc863)

#define LWC863                                                                           
#define LWC863_ENTRY                                                0x000003ff:0x00000000
#define LWC863_SIZE                                                                  1024
#define LWC863_NUM_RANGE_CHECKERS                                                       8
#define LWC863_ENTRY_ACCESS_BITS(i)                     MW((((i)*512)+255):(((i)*512)+0))
#define LWC863_ENTRY_ACCESS_BITS__SIZE_1                                        1024 / 64
#define LWC863_ENTRY_VALID(i)                         MW((((i)*512)+511):(((i)*512)+511))
#define LWC863_ENTRY_VALID__SIZE_1                                              1024 / 64
#define LWC863_ENTRY_GPC_DISABLE(i)                             MW(((i)+7936):((i)+7936))
#define LWC863_ENTRY_GPC_DISABLE__SIZE_1                                               64
#define LWC863_ENTRY_GPC_DISABLE_TRUE                                                 0x1
#define LWC863_ENTRY_GPC_DISABLE_FALSE                                                0x0
#define LWC863_ENTRY_HUB_DISABLE(i)                             MW(((i)+8000):((i)+8000))
#define LWC863_ENTRY_HUB_DISABLE__SIZE_1                                               32
#define LWC863_ENTRY_HUB_DISABLE_TRUE                                                 0x1
#define LWC863_ENTRY_HUB_DISABLE_FALSE                                                0x0
#define LWC863_ENTRY_HSCE_DISABLE(i)                            MW(((i)+8032):((i)+8032))
#define LWC863_ENTRY_HSCE_DISABLE__SIZE_1                                              16
#define LWC863_ENTRY_HSCE_DISABLE_TRUE                                                0x1
#define LWC863_ENTRY_HSCE_DISABLE_FALSE                                               0x0
#define LWC863_ENTRY_LINK_DISABLE(i)                            MW(((i)+8048):((i)+8048))
#define LWC863_ENTRY_LINK_DISABLE__SIZE_1                                              16
#define LWC863_ENTRY_LINK_DISABLE_TRUE                                                0x1
#define LWC863_ENTRY_LINK_DISABLE_FALSE                                               0x0

#ifdef __cplusplus
};     /* extern "C" */
#endif

#endif /* _clc863_h_ */
