/* _LWRM_COPYRIGHT_BEGIN_
 *
 * Copyright 2003-2016 by LWPU Corporation.  All rights reserved.  All
 * information contained herein is proprietary and confidential to LWPU
 * Corporation.  Any use, reproduction, or disclosure without the written
 * permission of LWPU Corporation is prohibited.
 *
 * _LWRM_COPYRIGHT_END_
 */

/* This file is autogenerated by ref2h.pl.  Do not edit */
// AUTO GENERATED -- DO NOT EDIT

/*
* _LWRM_COPYRIGHT_BEGIN_
*
* Copyright 2015 by LWPU Corporation.  All rights reserved.  All
* information contained herein is proprietary and confidential to LWPU
* Corporation.  Any use, reproduction, or disclosure without the written
* permission of LWPU Corporation is prohibited.
*
* _LWRM_COPYRIGHT_END_
*/

#ifndef _clc871_h_
#define _clc871_h_

#ifdef __cplusplus
extern "C" {
#endif

#define LWC871_DISP_SF_USER (0x000C871)

typedef volatile struct {
    LwU32 dispSfUserOffset[0x400];    /* LW_PDISP_SF_USER   0x000D0FFF:0x000D0000 */
} _LwC871DispSfUser, LwC871DispSfUserMap;

#define LWC871_SF_HDMI_INFO_IDX_AVI_INFOFRAME                             0x00000000 /*       */
#define LWC871_SF_HDMI_INFO_IDX_GCP                                       0x00000001 /*       */
#define LWC871_SF_HDMI_INFO_IDX_ACR                                       0x00000002 /*       */
#define LWC871_SF_HDMI_INFO_CTRL(i,j)                 (0x000E0000-0x000E0000+(i)*1024+(j)*64) /* RW-4A */
#define LWC871_SF_HDMI_INFO_CTRL__SIZE_1                                         8 /*       */
#define LWC871_SF_HDMI_INFO_CTRL__SIZE_2                                         3 /*       */
#define LWC871_SF_HDMI_INFO_CTRL_ENABLE                                        0:0 /* RWIVF */
#define LWC871_SF_HDMI_INFO_CTRL_ENABLE_NO                              0x00000000 /* RWI-V */
#define LWC871_SF_HDMI_INFO_CTRL_ENABLE_YES                             0x00000001 /* RW--V */
#define LWC871_SF_HDMI_INFO_CTRL_ENABLE_DIS                             0x00000000 /* RW--V */
#define LWC871_SF_HDMI_INFO_CTRL_ENABLE_EN                              0x00000001 /* RW--V */
#define LWC871_SF_HDMI_INFO_CTRL_OTHER                                         4:4 /* RWIVF */
#define LWC871_SF_HDMI_INFO_CTRL_OTHER_DIS                              0x00000000 /* RWI-V */
#define LWC871_SF_HDMI_INFO_CTRL_OTHER_EN                               0x00000001 /* RW--V */
#define LWC871_SF_HDMI_INFO_CTRL_SINGLE                                        8:8 /* RWIVF */
#define LWC871_SF_HDMI_INFO_CTRL_SINGLE_DIS                             0x00000000 /* RWI-V */
#define LWC871_SF_HDMI_INFO_CTRL_SINGLE_EN                              0x00000001 /* RW--V */
#define LWC871_SF_HDMI_INFO_CTRL_CHKSUM_HW                                     9:9 /* RWIVF */
#define LWC871_SF_HDMI_INFO_CTRL_CHKSUM_HW_ENABLE                       0x00000001 /* RW--V */
#define LWC871_SF_HDMI_INFO_CTRL_CHKSUM_HW_EN                           0x00000001 /* RW--V */
#define LWC871_SF_HDMI_INFO_CTRL_CHKSUM_HW_DISABLE                      0x00000000 /* RW--V */
#define LWC871_SF_HDMI_INFO_CTRL_CHKSUM_HW_DIS                          0x00000000 /* RW--V */
#define LWC871_SF_HDMI_INFO_CTRL_CHKSUM_HW_INIT                         0x00000001 /* RWI-V */
#define LWC871_SF_HDMI_INFO_CTRL_HBLANK                                      12:12 /* RWIVF */
#define LWC871_SF_HDMI_INFO_CTRL_HBLANK_DIS                             0x00000000 /* RWI-V */
#define LWC871_SF_HDMI_INFO_CTRL_HBLANK_EN                              0x00000001 /* RW--V */
#define LWC871_SF_HDMI_INFO_CTRL_VIDEO_FMT                                   16:16 /* RWIVF */
#define LWC871_SF_HDMI_INFO_CTRL_VIDEO_FMT_SW_CONTROLLED                0x00000000 /* RW--V */
#define LWC871_SF_HDMI_INFO_CTRL_VIDEO_FMT_HW_CONTROLLED                0x00000001 /* RW--V */
#define LWC871_SF_HDMI_INFO_CTRL_VIDEO_FMT_INIT                         0x00000001 /* RWI-V */
#define LWC871_SF_HDMI_INFO_STATUS(i,j)               (0x000E0004-0x000E0000+(i)*1024+(j)*64) /* R--4A */
#define LWC871_SF_HDMI_INFO_STATUS__SIZE_1                                       8 /*       */
#define LWC871_SF_HDMI_INFO_STATUS__SIZE_2                                       3 /*       */
#define LWC871_SF_HDMI_INFO_STATUS_SENT                                        0:0 /* R--VF */
#define LWC871_SF_HDMI_INFO_STATUS_SENT_DONE                            0x00000001 /* R---V */
#define LWC871_SF_HDMI_INFO_STATUS_SENT_WAITING                         0x00000000 /* R---V */
#define LWC871_SF_HDMI_INFO_HEADER(i,j)               (0x000E0008-0x000E0000+(i)*1024+(j)*64) /* RW-4A */
#define LWC871_SF_HDMI_INFO_HEADER__SIZE_1                                       8 /*       */
#define LWC871_SF_HDMI_INFO_HEADER__SIZE_2                                       3 /*       */
#define LWC871_SF_HDMI_INFO_HEADER_HB0                                         7:0 /* RWIVF */
#define LWC871_SF_HDMI_INFO_HEADER_HB0_INIT                             0x00000000 /* RWI-V */
#define LWC871_SF_HDMI_INFO_HEADER_HB1                                        15:8 /* RWIVF */
#define LWC871_SF_HDMI_INFO_HEADER_HB1_INIT                             0x00000000 /* RWI-V */
#define LWC871_SF_HDMI_INFO_HEADER_HB2                                       23:16 /* RWIVF */
#define LWC871_SF_HDMI_INFO_HEADER_HB2_INIT                             0x00000000 /* RWI-V */
#define LWC871_SF_HDMI_INFO_SUBPACK0_LOW(i,j)         (0x000E000C-0x000E0000+(i)*1024+(j)*64) /* RW-4A */
#define LWC871_SF_HDMI_INFO_SUBPACK0_LOW__SIZE_1                                 8 /*       */
#define LWC871_SF_HDMI_INFO_SUBPACK0_LOW__SIZE_2                                 3 /*       */
#define LWC871_SF_HDMI_INFO_SUBPACK0_LOW_PB0                                   7:0 /* RWIVF */
#define LWC871_SF_HDMI_INFO_SUBPACK0_LOW_PB0_INIT                       0x00000000 /* RWI-V */
#define LWC871_SF_HDMI_INFO_SUBPACK0_LOW_PB1                                  15:8 /* RWIVF */
#define LWC871_SF_HDMI_INFO_SUBPACK0_LOW_PB1_INIT                       0x00000000 /* RWI-V */
#define LWC871_SF_HDMI_INFO_SUBPACK0_LOW_PB2                                 23:16 /* RWIVF */
#define LWC871_SF_HDMI_INFO_SUBPACK0_LOW_PB2_INIT                       0x00000000 /* RWI-V */
#define LWC871_SF_HDMI_INFO_SUBPACK0_LOW_PB3                                 31:24 /* RWIVF */
#define LWC871_SF_HDMI_INFO_SUBPACK0_LOW_PB3_INIT                       0x00000000 /* RWI-V */
#define LWC871_SF_HDMI_INFO_SUBPACK0_HIGH(i,j)        (0x000E0010-0x000E0000+(i)*1024+(j)*64) /* RW-4A */
#define LWC871_SF_HDMI_INFO_SUBPACK0_HIGH__SIZE_1                                8 /*       */
#define LWC871_SF_HDMI_INFO_SUBPACK0_HIGH__SIZE_2                                3 /*       */
#define LWC871_SF_HDMI_INFO_SUBPACK0_HIGH_PB4                                  7:0 /* RWIVF */
#define LWC871_SF_HDMI_INFO_SUBPACK0_HIGH_PB4_INIT                      0x00000000 /* RWI-V */
#define LWC871_SF_HDMI_INFO_SUBPACK0_HIGH_PB5                                 15:8 /* RWIVF */
#define LWC871_SF_HDMI_INFO_SUBPACK0_HIGH_PB5_INIT                      0x00000000 /* RWI-V */
#define LWC871_SF_HDMI_INFO_SUBPACK0_HIGH_PB6                                23:16 /* RWIVF */
#define LWC871_SF_HDMI_INFO_SUBPACK0_HIGH_PB6_INIT                      0x00000000 /* RWI-V */
#define LWC871_SF_HDMI_INFO_SUBPACK1_LOW(i,j)         (0x000E0014-0x000E0000+(i)*1024+(j)*64) /* RW-4A */
#define LWC871_SF_HDMI_INFO_SUBPACK1_LOW__SIZE_1                                 8 /*       */
#define LWC871_SF_HDMI_INFO_SUBPACK1_LOW__SIZE_2                                 3 /*       */
#define LWC871_SF_HDMI_INFO_SUBPACK1_LOW_PB7                                   7:0 /* RWIVF */
#define LWC871_SF_HDMI_INFO_SUBPACK1_LOW_PB7_INIT                       0x00000000 /* RWI-V */
#define LWC871_SF_HDMI_INFO_SUBPACK1_LOW_PB8                                  15:8 /* RWIVF */
#define LWC871_SF_HDMI_INFO_SUBPACK1_LOW_PB8_INIT                       0x00000000 /* RWI-V */
#define LWC871_SF_HDMI_INFO_SUBPACK1_LOW_PB9                                 23:16 /* RWIVF */
#define LWC871_SF_HDMI_INFO_SUBPACK1_LOW_PB9_INIT                       0x00000000 /* RWI-V */
#define LWC871_SF_HDMI_INFO_SUBPACK1_LOW_PB10                                31:24 /* RWIVF */
#define LWC871_SF_HDMI_INFO_SUBPACK1_LOW_PB10_INIT                      0x00000000 /* RWI-V */
#define LWC871_SF_HDMI_INFO_SUBPACK1_HIGH(i,j)        (0x000E0018-0x000E0000+(i)*1024+(j)*64) /* RW-4A */
#define LWC871_SF_HDMI_INFO_SUBPACK1_HIGH__SIZE_1                                8 /*       */
#define LWC871_SF_HDMI_INFO_SUBPACK1_HIGH__SIZE_2                                3 /*       */
#define LWC871_SF_HDMI_INFO_SUBPACK1_HIGH_PB11                                 7:0 /* RWIVF */
#define LWC871_SF_HDMI_INFO_SUBPACK1_HIGH_PB11_INIT                     0x00000000 /* RWI-V */
#define LWC871_SF_HDMI_INFO_SUBPACK1_HIGH_PB12                                15:8 /* RWIVF */
#define LWC871_SF_HDMI_INFO_SUBPACK1_HIGH_PB12_INIT                     0x00000000 /* RWI-V */
#define LWC871_SF_HDMI_INFO_SUBPACK1_HIGH_PB13                               23:16 /* RWIVF */
#define LWC871_SF_HDMI_INFO_SUBPACK1_HIGH_PB13_INIT                     0x00000000 /* RWI-V */
#define LWC871_SF_HDMI_INFO_SUBPACK2_LOW(i,j)         (0x000E001C-0x000E0000+(i)*1024+(j)*64) /* RW-4A */
#define LWC871_SF_HDMI_INFO_SUBPACK2_LOW__SIZE_1                                 8 /*       */
#define LWC871_SF_HDMI_INFO_SUBPACK2_LOW__SIZE_2                                 3 /*       */
#define LWC871_SF_HDMI_INFO_SUBPACK2_LOW_PB14                                  7:0 /* RWIVF */
#define LWC871_SF_HDMI_INFO_SUBPACK2_LOW_PB14_INIT                      0x00000000 /* RWI-V */
#define LWC871_SF_HDMI_INFO_SUBPACK2_LOW_PB15                                 15:8 /* RWIVF */
#define LWC871_SF_HDMI_INFO_SUBPACK2_LOW_PB15_INIT                      0x00000000 /* RWI-V */
#define LWC871_SF_HDMI_INFO_SUBPACK2_LOW_PB16                                23:16 /* RWIVF */
#define LWC871_SF_HDMI_INFO_SUBPACK2_LOW_PB16_INIT                      0x00000000 /* RWI-V */
#define LWC871_SF_HDMI_INFO_SUBPACK2_LOW_PB17                                31:24 /* RWIVF */
#define LWC871_SF_HDMI_INFO_SUBPACK2_LOW_PB17_INIT                      0x00000000 /* RWI-V */
#define LWC871_SF_HDMI_INFO_SUBPACK2_HIGH(i,j)        (0x000E0020-0x000E0000+(i)*1024+(j)*64) /* RW-4A */
#define LWC871_SF_HDMI_INFO_SUBPACK2_HIGH__SIZE_1                                8 /*       */
#define LWC871_SF_HDMI_INFO_SUBPACK2_HIGH__SIZE_2                                3 /*       */
#define LWC871_SF_HDMI_INFO_SUBPACK2_HIGH_PB18                                 7:0 /* RWIVF */
#define LWC871_SF_HDMI_INFO_SUBPACK2_HIGH_PB18_INIT                     0x00000000 /* RWI-V */
#define LWC871_SF_HDMI_INFO_SUBPACK2_HIGH_PB19                                15:8 /* RWIVF */
#define LWC871_SF_HDMI_INFO_SUBPACK2_HIGH_PB19_INIT                     0x00000000 /* RWI-V */
#define LWC871_SF_HDMI_INFO_SUBPACK2_HIGH_PB20                               23:16 /* RWIVF */
#define LWC871_SF_HDMI_INFO_SUBPACK2_HIGH_PB20_INIT                     0x00000000 /* RWI-V */
#define LWC871_SF_HDMI_INFO_SUBPACK3_LOW(i,j)         (0x000E0024-0x000E0000+(i)*1024+(j)*64) /* RW-4A */
#define LWC871_SF_HDMI_INFO_SUBPACK3_LOW__SIZE_1                                 8 /*       */
#define LWC871_SF_HDMI_INFO_SUBPACK3_LOW__SIZE_2                                 3 /*       */
#define LWC871_SF_HDMI_INFO_SUBPACK3_LOW_PB21                                  7:0 /* RWIVF */
#define LWC871_SF_HDMI_INFO_SUBPACK3_LOW_PB21_INIT                      0x00000000 /* RWI-V */
#define LWC871_SF_HDMI_INFO_SUBPACK3_LOW_PB22                                 15:8 /* RWIVF */
#define LWC871_SF_HDMI_INFO_SUBPACK3_LOW_PB22_INIT                      0x00000000 /* RWI-V */
#define LWC871_SF_HDMI_INFO_SUBPACK3_LOW_PB23                                23:16 /* RWIVF */
#define LWC871_SF_HDMI_INFO_SUBPACK3_LOW_PB23_INIT                      0x00000000 /* RWI-V */
#define LWC871_SF_HDMI_INFO_SUBPACK3_LOW_PB24                                31:24 /* RWIVF */
#define LWC871_SF_HDMI_INFO_SUBPACK3_LOW_PB24_INIT                      0x00000000 /* RWI-V */
#define LWC871_SF_HDMI_INFO_SUBPACK3_HIGH(i,j)        (0x000E0028-0x000E0000+(i)*1024+(j)*64) /* RW-4A */
#define LWC871_SF_HDMI_INFO_SUBPACK3_HIGH__SIZE_1                                8 /*       */
#define LWC871_SF_HDMI_INFO_SUBPACK3_HIGH__SIZE_2                                3 /*       */
#define LWC871_SF_HDMI_INFO_SUBPACK3_HIGH_PB25                                 7:0 /* RWIVF */
#define LWC871_SF_HDMI_INFO_SUBPACK3_HIGH_PB25_INIT                     0x00000000 /* RWI-V */
#define LWC871_SF_HDMI_INFO_SUBPACK3_HIGH_PB26                                15:8 /* RWIVF */
#define LWC871_SF_HDMI_INFO_SUBPACK3_HIGH_PB26_INIT                     0x00000000 /* RWI-V */
#define LWC871_SF_HDMI_INFO_SUBPACK3_HIGH_PB27                               23:16 /* RWIVF */
#define LWC871_SF_HDMI_INFO_SUBPACK3_HIGH_PB27_INIT                     0x00000000 /* RWI-V */
#define LWC871_SF_HDMI_AVI_INFOFRAME_CTRL(i)                    (0x000E0000-0x000E0000+(i)*1024) /* RW-4A */
#define LWC871_SF_HDMI_AVI_INFOFRAME_CTRL__SIZE_1                                   8 /*       */
#define LWC871_SF_HDMI_AVI_INFOFRAME_CTRL_ENABLE                                  0:0 /* RWIVF */
#define LWC871_SF_HDMI_AVI_INFOFRAME_CTRL_ENABLE_NO                        0x00000000 /* RWI-V */
#define LWC871_SF_HDMI_AVI_INFOFRAME_CTRL_ENABLE_YES                       0x00000001 /* RW--V */
#define LWC871_SF_HDMI_AVI_INFOFRAME_CTRL_ENABLE_DIS                       0x00000000 /* RW--V */
#define LWC871_SF_HDMI_AVI_INFOFRAME_CTRL_ENABLE_EN                        0x00000001 /* RW--V */
#define LWC871_SF_HDMI_AVI_INFOFRAME_CTRL_OTHER                                   4:4 /* RWIVF */
#define LWC871_SF_HDMI_AVI_INFOFRAME_CTRL_OTHER_DIS                        0x00000000 /* RWI-V */
#define LWC871_SF_HDMI_AVI_INFOFRAME_CTRL_OTHER_EN                         0x00000001 /* RW--V */
#define LWC871_SF_HDMI_AVI_INFOFRAME_CTRL_SINGLE                                  8:8 /* RWIVF */
#define LWC871_SF_HDMI_AVI_INFOFRAME_CTRL_SINGLE_DIS                       0x00000000 /* RWI-V */
#define LWC871_SF_HDMI_AVI_INFOFRAME_CTRL_SINGLE_EN                        0x00000001 /* RW--V */
#define LWC871_SF_HDMI_AVI_INFOFRAME_CTRL_CHKSUM_HW                               9:9 /* RWIVF */
#define LWC871_SF_HDMI_AVI_INFOFRAME_CTRL_CHKSUM_HW_ENABLE                 0x00000001 /* RW--V */
#define LWC871_SF_HDMI_AVI_INFOFRAME_CTRL_CHKSUM_HW_DISABLE                0x00000000 /* RW--V */
#define LWC871_SF_HDMI_AVI_INFOFRAME_CTRL_CHKSUM_HW_INIT                   0x00000001 /* RWI-V */
#define LWC871_SF_HDMI_AVI_INFOFRAME_STATUS(i)                  (0x000E0004-0x000E0000+(i)*1024) /* R--4A */
#define LWC871_SF_HDMI_AVI_INFOFRAME_STATUS__SIZE_1                                 8 /*       */
#define LWC871_SF_HDMI_AVI_INFOFRAME_STATUS_SENT                                  0:0 /* R-IVF */
#define LWC871_SF_HDMI_AVI_INFOFRAME_STATUS_SENT_DONE                      0x00000001 /* R---V */
#define LWC871_SF_HDMI_AVI_INFOFRAME_STATUS_SENT_WAITING                   0x00000000 /* R---V */
#define LWC871_SF_HDMI_AVI_INFOFRAME_STATUS_SENT_INIT                      0x00000000 /* R-I-V */
#define LWC871_SF_HDMI_AVI_INFOFRAME_HEADER(i)                  (0x000E0008-0x000E0000+(i)*1024) /* RW-4A */
#define LWC871_SF_HDMI_AVI_INFOFRAME_HEADER__SIZE_1                                 8 /*       */
#define LWC871_SF_HDMI_AVI_INFOFRAME_HEADER_HB0                                   7:0 /* RWIVF */
#define LWC871_SF_HDMI_AVI_INFOFRAME_HEADER_HB0_INIT                       0x00000000 /* RWI-V */
#define LWC871_SF_HDMI_AVI_INFOFRAME_HEADER_HB1                                  15:8 /* RWIVF */
#define LWC871_SF_HDMI_AVI_INFOFRAME_HEADER_HB1_INIT                       0x00000000 /* RWI-V */
#define LWC871_SF_HDMI_AVI_INFOFRAME_HEADER_HB2                                 23:16 /* RWIVF */
#define LWC871_SF_HDMI_AVI_INFOFRAME_HEADER_HB2_INIT                       0x00000000 /* RWI-V */
#define LWC871_SF_HDMI_AVI_INFOFRAME_SUBPACK0_LOW(i)            (0x000E000C-0x000E0000+(i)*1024) /* RW-4A */
#define LWC871_SF_HDMI_AVI_INFOFRAME_SUBPACK0_LOW__SIZE_1                           8 /*       */
#define LWC871_SF_HDMI_AVI_INFOFRAME_SUBPACK0_LOW_PB0                             7:0 /* RWIVF */
#define LWC871_SF_HDMI_AVI_INFOFRAME_SUBPACK0_LOW_PB0_INIT                 0x00000000 /* RWI-V */
#define LWC871_SF_HDMI_AVI_INFOFRAME_SUBPACK0_LOW_PB1                            15:8 /* RWIVF */
#define LWC871_SF_HDMI_AVI_INFOFRAME_SUBPACK0_LOW_PB1_INIT                 0x00000000 /* RWI-V */
#define LWC871_SF_HDMI_AVI_INFOFRAME_SUBPACK0_LOW_PB2                           23:16 /* RWIVF */
#define LWC871_SF_HDMI_AVI_INFOFRAME_SUBPACK0_LOW_PB2_INIT                 0x00000000 /* RWI-V */
#define LWC871_SF_HDMI_AVI_INFOFRAME_SUBPACK0_LOW_PB3                           31:24 /* RWIVF */
#define LWC871_SF_HDMI_AVI_INFOFRAME_SUBPACK0_LOW_PB3_INIT                 0x00000000 /* RWI-V */
#define LWC871_SF_HDMI_AVI_INFOFRAME_SUBPACK0_HIGH(i)           (0x000E0010-0x000E0000+(i)*1024) /* RW-4A */
#define LWC871_SF_HDMI_AVI_INFOFRAME_SUBPACK0_HIGH__SIZE_1                          8 /*       */
#define LWC871_SF_HDMI_AVI_INFOFRAME_SUBPACK0_HIGH_PB4                            7:0 /* RWIVF */
#define LWC871_SF_HDMI_AVI_INFOFRAME_SUBPACK0_HIGH_PB4_INIT                0x00000000 /* RWI-V */
#define LWC871_SF_HDMI_AVI_INFOFRAME_SUBPACK0_HIGH_PB5                           15:8 /* RWIVF */
#define LWC871_SF_HDMI_AVI_INFOFRAME_SUBPACK0_HIGH_PB5_INIT                0x00000000 /* RWI-V */
#define LWC871_SF_HDMI_AVI_INFOFRAME_SUBPACK0_HIGH_PB6                          23:16 /* RWIVF */
#define LWC871_SF_HDMI_AVI_INFOFRAME_SUBPACK0_HIGH_PB6_INIT                0x00000000 /* RWI-V */
#define LWC871_SF_HDMI_AVI_INFOFRAME_SUBPACK1_LOW(i)            (0x000E0014-0x000E0000+(i)*1024) /* RW-4A */
#define LWC871_SF_HDMI_AVI_INFOFRAME_SUBPACK1_LOW__SIZE_1                           8 /*       */
#define LWC871_SF_HDMI_AVI_INFOFRAME_SUBPACK1_LOW_PB7                             7:0 /* RWIVF */
#define LWC871_SF_HDMI_AVI_INFOFRAME_SUBPACK1_LOW_PB7_INIT                 0x00000000 /* RWI-V */
#define LWC871_SF_HDMI_AVI_INFOFRAME_SUBPACK1_LOW_PB8                            15:8 /* RWIVF */
#define LWC871_SF_HDMI_AVI_INFOFRAME_SUBPACK1_LOW_PB8_INIT                 0x00000000 /* RWI-V */
#define LWC871_SF_HDMI_AVI_INFOFRAME_SUBPACK1_LOW_PB9                           23:16 /* RWIVF */
#define LWC871_SF_HDMI_AVI_INFOFRAME_SUBPACK1_LOW_PB9_INIT                 0x00000000 /* RWI-V */
#define LWC871_SF_HDMI_AVI_INFOFRAME_SUBPACK1_LOW_PB10                          31:24 /* RWIVF */
#define LWC871_SF_HDMI_AVI_INFOFRAME_SUBPACK1_LOW_PB10_INIT                0x00000000 /* RWI-V */
#define LWC871_SF_HDMI_AVI_INFOFRAME_SUBPACK1_HIGH(i)           (0x000E0018-0x000E0000+(i)*1024) /* RW-4A */
#define LWC871_SF_HDMI_AVI_INFOFRAME_SUBPACK1_HIGH__SIZE_1                          8 /*       */
#define LWC871_SF_HDMI_AVI_INFOFRAME_SUBPACK1_HIGH_PB11                           7:0 /* RWIVF */
#define LWC871_SF_HDMI_AVI_INFOFRAME_SUBPACK1_HIGH_PB11_INIT               0x00000000 /* RWI-V */
#define LWC871_SF_HDMI_AVI_INFOFRAME_SUBPACK1_HIGH_PB12                          15:8 /* RWIVF */
#define LWC871_SF_HDMI_AVI_INFOFRAME_SUBPACK1_HIGH_PB12_INIT               0x00000000 /* RWI-V */
#define LWC871_SF_HDMI_AVI_INFOFRAME_SUBPACK1_HIGH_PB13                         23:16 /* RWIVF */
#define LWC871_SF_HDMI_AVI_INFOFRAME_SUBPACK1_HIGH_PB13_INIT               0x00000000 /* RWI-V */
#define LWC871_SF_HDMI_AVI_INFOFRAME_SUBPACK2_LOW(i)            (0x000E001C-0x000E0000+(i)*1024) /* RW-4A */
#define LWC871_SF_HDMI_AVI_INFOFRAME_SUBPACK2_LOW__SIZE_1                           8 /*       */
#define LWC871_SF_HDMI_AVI_INFOFRAME_SUBPACK2_LOW_PB14                             7:0 /* RWIVF */
#define LWC871_SF_HDMI_AVI_INFOFRAME_SUBPACK2_LOW_PB14_INIT                 0x00000000 /* RWI-V */
#define LWC871_SF_HDMI_AVI_INFOFRAME_SUBPACK2_LOW_PB15                            15:8 /* RWIVF */
#define LWC871_SF_HDMI_AVI_INFOFRAME_SUBPACK2_LOW_PB15_INIT                 0x00000000 /* RWI-V */
#define LWC871_SF_HDMI_AVI_INFOFRAME_SUBPACK2_LOW_PB16                           23:16 /* RWIVF */
#define LWC871_SF_HDMI_AVI_INFOFRAME_SUBPACK2_LOW_PB16_INIT                 0x00000000 /* RWI-V */
#define LWC871_SF_HDMI_AVI_INFOFRAME_SUBPACK2_LOW_PB17                           31:24 /* RWIVF */
#define LWC871_SF_HDMI_AVI_INFOFRAME_SUBPACK2_LOW_PB17_INIT                 0x00000000 /* RWI-V */
#define LWC871_SF_HDMI_GCP_CTRL(i)                              (0x000E0040-0x000E0000+(i)*1024) /* RW-4A */
#define LWC871_SF_HDMI_GCP_CTRL__SIZE_1                                             8 /*       */
#define LWC871_SF_HDMI_GCP_CTRL_ENABLE                                            0:0 /* RWIVF */
#define LWC871_SF_HDMI_GCP_CTRL_ENABLE_NO                                  0x00000000 /* RWI-V */
#define LWC871_SF_HDMI_GCP_CTRL_ENABLE_YES                                 0x00000001 /* RW--V */
#define LWC871_SF_HDMI_GCP_CTRL_ENABLE_DIS                                 0x00000000 /* RW--V */
#define LWC871_SF_HDMI_GCP_CTRL_ENABLE_EN                                  0x00000001 /* RW--V */
#define LWC871_SF_HDMI_GCP_CTRL_OTHER                                             4:4 /* RWIVF */
#define LWC871_SF_HDMI_GCP_CTRL_OTHER_DIS                                  0x00000000 /* RWI-V */
#define LWC871_SF_HDMI_GCP_CTRL_OTHER_EN                                   0x00000001 /* RW--V */
#define LWC871_SF_HDMI_GCP_CTRL_SINGLE                                            8:8 /* RWIVF */
#define LWC871_SF_HDMI_GCP_CTRL_SINGLE_DIS                                 0x00000000 /* RWI-V */
#define LWC871_SF_HDMI_GCP_CTRL_SINGLE_EN                                  0x00000001 /* RW--V */
#define LWC871_SF_HDMI_GCP_STATUS(i)                            (0x000E0044-0x000E0000+(i)*1024) /* R--4A */
#define LWC871_SF_HDMI_GCP_STATUS__SIZE_1                                           8 /*       */
#define LWC871_SF_HDMI_GCP_STATUS_SENT                                            0:0 /* R-IVF */
#define LWC871_SF_HDMI_GCP_STATUS_SENT_DONE                                0x00000001 /* R---V */
#define LWC871_SF_HDMI_GCP_STATUS_SENT_WAITING                             0x00000000 /* R---V */
#define LWC871_SF_HDMI_GCP_STATUS_SENT_INIT                                0x00000000 /* R-I-V */
#define LWC871_SF_HDMI_GCP_STATUS_ACTIVE_START_PP                                 6:4 /* R--VF */
#define LWC871_SF_HDMI_GCP_STATUS_ACTIVE_START_PP_0                        0x00000004 /* R---V */
#define LWC871_SF_HDMI_GCP_STATUS_ACTIVE_START_PP_1                        0x00000001 /* R---V */
#define LWC871_SF_HDMI_GCP_STATUS_ACTIVE_START_PP_2                        0x00000002 /* R---V */
#define LWC871_SF_HDMI_GCP_STATUS_ACTIVE_START_PP_3                        0x00000003 /* R---V */
#define LWC871_SF_HDMI_GCP_STATUS_ACTIVE_END_PP                                  10:8 /* R--VF */
#define LWC871_SF_HDMI_GCP_STATUS_ACTIVE_END_PP_0                          0x00000004 /* R---V */
#define LWC871_SF_HDMI_GCP_STATUS_ACTIVE_END_PP_1                          0x00000001 /* R---V */
#define LWC871_SF_HDMI_GCP_STATUS_ACTIVE_END_PP_2                          0x00000002 /* R---V */
#define LWC871_SF_HDMI_GCP_STATUS_ACTIVE_END_PP_3                          0x00000003 /* R---V */
#define LWC871_SF_HDMI_GCP_STATUS_VSYNC_START_PP                                14:12 /* R--VF */
#define LWC871_SF_HDMI_GCP_STATUS_VSYNC_START_PP_0                         0x00000004 /* R---V */
#define LWC871_SF_HDMI_GCP_STATUS_VSYNC_START_PP_1                         0x00000001 /* R---V */
#define LWC871_SF_HDMI_GCP_STATUS_VSYNC_START_PP_2                         0x00000002 /* R---V */
#define LWC871_SF_HDMI_GCP_STATUS_VSYNC_START_PP_3                         0x00000003 /* R---V */
#define LWC871_SF_HDMI_GCP_STATUS_VSYNC_END_PP                                  18:16 /* R--VF */
#define LWC871_SF_HDMI_GCP_STATUS_VSYNC_END_PP_0                           0x00000004 /* R---V */
#define LWC871_SF_HDMI_GCP_STATUS_VSYNC_END_PP_1                           0x00000001 /* R---V */
#define LWC871_SF_HDMI_GCP_STATUS_VSYNC_END_PP_2                           0x00000002 /* R---V */
#define LWC871_SF_HDMI_GCP_STATUS_VSYNC_END_PP_3                           0x00000003 /* R---V */
#define LWC871_SF_HDMI_GCP_STATUS_HSYNC_START_PP                                22:20 /* R--VF */
#define LWC871_SF_HDMI_GCP_STATUS_HSYNC_START_PP_0                         0x00000004 /* R---V */
#define LWC871_SF_HDMI_GCP_STATUS_HSYNC_START_PP_1                         0x00000001 /* R---V */
#define LWC871_SF_HDMI_GCP_STATUS_HSYNC_START_PP_2                         0x00000002 /* R---V */
#define LWC871_SF_HDMI_GCP_STATUS_HSYNC_START_PP_3                         0x00000003 /* R---V */
#define LWC871_SF_HDMI_GCP_STATUS_HSYNC_END_PP                                  26:24 /* R--VF */
#define LWC871_SF_HDMI_GCP_STATUS_HSYNC_END_PP_0                           0x00000004 /* R---V */
#define LWC871_SF_HDMI_GCP_STATUS_HSYNC_END_PP_1                           0x00000001 /* R---V */
#define LWC871_SF_HDMI_GCP_STATUS_HSYNC_END_PP_2                           0x00000002 /* R---V */
#define LWC871_SF_HDMI_GCP_STATUS_HSYNC_END_PP_3                           0x00000003 /* R---V */
#define LWC871_SF_HDMI_GCP_SUBPACK(i)                           (0x000E004C-0x000E0000+(i)*1024) /* RW-4A */
#define LWC871_SF_HDMI_GCP_SUBPACK__SIZE_1                                          8 /*       */
#define LWC871_SF_HDMI_GCP_SUBPACK_SB0                                            7:0 /* RWIVF */
#define LWC871_SF_HDMI_GCP_SUBPACK_SB0_INIT                                0x00000001 /* RWI-V */
#define LWC871_SF_HDMI_GCP_SUBPACK_SB0_SET_AVMUTE                          0x00000001 /* RW--V */
#define LWC871_SF_HDMI_GCP_SUBPACK_SB0_CLR_AVMUTE                          0x00000010 /* RW--V */
#define LWC871_SF_HDMI_GCP_SUBPACK_SB1                                           15:8 /* RWIVF */
#define LWC871_SF_HDMI_GCP_SUBPACK_SB1_INIT                                0x00000000 /* RWI-V */
#define LWC871_SF_HDMI_GCP_SUBPACK_SB2                                          23:16 /* RWIVF */
#define LWC871_SF_HDMI_GCP_SUBPACK_SB2_INIT                                0x00000000 /* RWI-V */
#define LWC871_SF_HDMI_GCP_SUBPACK_SB1_CTRL                                     24:24 /* RWIVF */
#define LWC871_SF_HDMI_GCP_SUBPACK_SB1_CTRL_INIT                           0x00000001 /* RWI-V */
#define LWC871_SF_HDMI_GCP_SUBPACK_SB1_CTRL_SW                             0x00000000 /* RW--V */
#define LWC871_SF_HDMI_GCP_SUBPACK_SB1_CTRL_HW                             0x00000001 /* RW--V */
#define LWC871_SF_HDMI_ACR_CTRL(i)                              (0x000E0080-0x000E0000+(i)*1024) /* RW-4A */
#define LWC871_SF_HDMI_ACR_CTRL__SIZE_1                                             8 /*       */
#define LWC871_SF_HDMI_ACR_CTRL_PACKET_ENABLE                                     0:0 /* RWIVF */
#define LWC871_SF_HDMI_ACR_CTRL_PACKET_ENABLE_NO                           0x00000000 /* RWI-V */
#define LWC871_SF_HDMI_ACR_CTRL_PACKET_ENABLE_YES                          0x00000001 /* RW--V */
#define LWC871_SF_HDMI_ACR_CTRL_PACKET_ENABLE_DIS                          0x00000000 /* RW--V */
#define LWC871_SF_HDMI_ACR_CTRL_PACKET_ENABLE_EN                           0x00000001 /* RW--V */
#define LWC871_SF_HDMI_ACR_CTRL_FREQS_ENABLE                                    16:16 /* RWIVF */
#define LWC871_SF_HDMI_ACR_CTRL_FREQS_ENABLE_NO                            0x00000000 /* RW--V */
#define LWC871_SF_HDMI_ACR_CTRL_FREQS_ENABLE_YES                           0x00000001 /* RWI-V */
#define LWC871_SF_HDMI_ACR_CTRL_FREQS_ENABLE_DIS                           0x00000000 /* RW--V */
#define LWC871_SF_HDMI_ACR_CTRL_FREQS_ENABLE_EN                            0x00000001 /* RW--V */
#define LWC871_SF_HDMI_ACR_CTRL_PRIORITY                                        20:20 /* RWIVF */
#define LWC871_SF_HDMI_ACR_CTRL_PRIORITY_INIT                              0x00000000 /* RWI-V */
#define LWC871_SF_HDMI_ACR_CTRL_PRIORITY_HIGH                              0x00000000 /* RW--V */
#define LWC871_SF_HDMI_ACR_CTRL_PRIORITY_LOW                               0x00000001 /* RW--V */
#define LWC871_SF_HDMI_ACR_CTRL_FREQS                                           27:24 /* RWIVF */
#define LWC871_SF_HDMI_ACR_CTRL_FREQS_INIT                                 0x00000002 /* RWI-V */
#define LWC871_SF_HDMI_ACR_CTRL_FREQS_32KHZ                                0x00000003 /* RW--V */
#define LWC871_SF_HDMI_ACR_CTRL_FREQS_44_1KHZ                              0x00000000 /* RW--V */
#define LWC871_SF_HDMI_ACR_CTRL_FREQS_48KHZ                                0x00000002 /* RW--V */
#define LWC871_SF_HDMI_ACR_CTRL_FREQS_88_2KHZ                              0x00000008 /* RW--V */
#define LWC871_SF_HDMI_ACR_CTRL_FREQS_96KHZ                                0x0000000A /* RW--V */
#define LWC871_SF_HDMI_ACR_CTRL_FREQS_176_4KHZ                             0x0000000C /* RW--V */
#define LWC871_SF_HDMI_ACR_CTRL_FREQS_192KHZ                               0x0000000E /* RW--V */
#define LWC871_SF_HDMI_ACR_CTRL_CTS_SOURCE                                      31:31 /* RWIVF */
#define LWC871_SF_HDMI_ACR_CTRL_CTS_SOURCE_INIT                            0x00000001 /* RWI-V */
#define LWC871_SF_HDMI_ACR_CTRL_CTS_SOURCE_HW                              0x00000001 /* RW--V */
#define LWC871_SF_HDMI_ACR_CTRL_CTS_SOURCE_SW                              0x00000000 /* RW--V */
#define LWC871_SF_HDMI_ACR_SUBPACK_IDX_32KHZ                               0x00000000 /*       */
#define LWC871_SF_HDMI_ACR_SUBPACK_IDX_44_1KHZ                             0x00000001 /*       */
#define LWC871_SF_HDMI_ACR_SUBPACK_IDX_88_2KHZ                             0x00000002 /*       */
#define LWC871_SF_HDMI_ACR_SUBPACK_IDX_176_4KHZ                            0x00000003 /*       */
#define LWC871_SF_HDMI_ACR_SUBPACK_IDX_48KHZ                               0x00000004 /*       */
#define LWC871_SF_HDMI_ACR_SUBPACK_IDX_96KHZ                               0x00000005 /*       */
#define LWC871_SF_HDMI_ACR_SUBPACK_IDX_192KHZ                              0x00000006 /*       */
#define LWC871_SF_HDMI_ACR_SUBPACK_LOW(i,j)               (0x000E0088-0x000E0000+(i)*1024+(j)*8) /* RW-4A */
#define LWC871_SF_HDMI_ACR_SUBPACK_LOW__SIZE_1                                      8 /*       */
#define LWC871_SF_HDMI_ACR_SUBPACK_LOW__SIZE_2                                      7 /*       */
#define LWC871_SF_HDMI_ACR_SUBPACK_LOW_SB1                                      31:24 /* RWIVF */
#define LWC871_SF_HDMI_ACR_SUBPACK_LOW_SB1_INIT                            0x00000000 /* RWI-V */
#define LWC871_SF_HDMI_ACR_SUBPACK_LOW_SB2                                      23:16 /* RWIVF */
#define LWC871_SF_HDMI_ACR_SUBPACK_LOW_SB2_INIT                            0x00000000 /* RWI-V */
#define LWC871_SF_HDMI_ACR_SUBPACK_LOW_SB3                                       15:8 /* RWIVF */
#define LWC871_SF_HDMI_ACR_SUBPACK_LOW_SB3_INIT                            0x00000000 /* RWI-V */
#define LWC871_SF_HDMI_ACR_SUBPACK_LOW_CTS                                       31:8 /*       */
#define LWC871_SF_HDMI_ACR_SUBPACK_HIGH(i,j)              (0x000E008C-0x000E0000+(i)*1024+(j)*8) /* RW-4A */
#define LWC871_SF_HDMI_ACR_SUBPACK_HIGH__SIZE_1                                     8 /*       */
#define LWC871_SF_HDMI_ACR_SUBPACK_HIGH__SIZE_2                                     7 /*       */
#define LWC871_SF_HDMI_ACR_SUBPACK_HIGH_SB4                                     23:16 /* RWIVF */
#define LWC871_SF_HDMI_ACR_SUBPACK_HIGH_SB4_INIT                           0x00000000 /* RWI-V */
#define LWC871_SF_HDMI_ACR_SUBPACK_HIGH_SB5                                      15:8 /* RWIVF */
#define LWC871_SF_HDMI_ACR_SUBPACK_HIGH_SB5_INIT                           0x00000000 /* RWI-V */
#define LWC871_SF_HDMI_ACR_SUBPACK_HIGH_SB6                                       7:0 /* RWIVF */
#define LWC871_SF_HDMI_ACR_SUBPACK_HIGH_SB6_INIT                           0x00000000 /* RWI-V */
#define LWC871_SF_HDMI_ACR_SUBPACK_HIGH_N                                        23:0 /*       */
#define LWC871_SF_HDMI_ACR_SUBPACK_HIGH_ENABLE                                  31:31 /* RWIVF */
#define LWC871_SF_HDMI_ACR_SUBPACK_HIGH_ENABLE_NO                          0x00000000 /* RWI-V */
#define LWC871_SF_HDMI_ACR_SUBPACK_HIGH_ENABLE_YES                         0x00000001 /* RW--V */
#define LWC871_SF_HDMI_ACR_SUBPACK_HIGH_ENABLE_DIS                         0x00000000 /* RW--V */
#define LWC871_SF_HDMI_ACR_SUBPACK_HIGH_ENABLE_EN                          0x00000001 /* RW--V */
#define LWC871_SF_HDMI_ACR_0320_SUBPACK_LOW(i)                  (0x000E0088-0x000E0000+(i)*1024) /* RW-4A */
#define LWC871_SF_HDMI_ACR_0320_SUBPACK_LOW__SIZE_1                                 8 /*       */
#define LWC871_SF_HDMI_ACR_0320_SUBPACK_LOW_SB1                                 31:24 /* RWIVF */
#define LWC871_SF_HDMI_ACR_0320_SUBPACK_LOW_SB1_INIT                       0x00000000 /* RWI-V */
#define LWC871_SF_HDMI_ACR_0320_SUBPACK_LOW_SB2                                 23:16 /* RWIVF */
#define LWC871_SF_HDMI_ACR_0320_SUBPACK_LOW_SB2_INIT                       0x00000000 /* RWI-V */
#define LWC871_SF_HDMI_ACR_0320_SUBPACK_LOW_SB3                                  15:8 /* RWIVF */
#define LWC871_SF_HDMI_ACR_0320_SUBPACK_LOW_SB3_INIT                       0x00000000 /* RWI-V */
#define LWC871_SF_HDMI_ACR_0320_SUBPACK_LOW_CTS                                  31:8 /*       */
#define LWC871_SF_HDMI_ACR_0320_SUBPACK_HIGH(i)                 (0x000E008C-0x000E0000+(i)*1024) /* RW-4A */
#define LWC871_SF_HDMI_ACR_0320_SUBPACK_HIGH__SIZE_1                                8 /*       */
#define LWC871_SF_HDMI_ACR_0320_SUBPACK_HIGH_SB6                                  7:0 /* RWIVF */
#define LWC871_SF_HDMI_ACR_0320_SUBPACK_HIGH_SB6_INIT                      0x00000000 /* RWI-V */
#define LWC871_SF_HDMI_ACR_0320_SUBPACK_HIGH_SB5                                 15:8 /* RWIVF */
#define LWC871_SF_HDMI_ACR_0320_SUBPACK_HIGH_SB5_INIT                      0x00000000 /* RWI-V */
#define LWC871_SF_HDMI_ACR_0320_SUBPACK_HIGH_SB4                                23:16 /* RWIVF */
#define LWC871_SF_HDMI_ACR_0320_SUBPACK_HIGH_SB4_INIT                      0x00000000 /* RWI-V */
#define LWC871_SF_HDMI_ACR_0320_SUBPACK_HIGH_N                                   23:0 /*       */
#define LWC871_SF_HDMI_ACR_0320_SUBPACK_HIGH_ENABLE                             31:31 /* RWIVF */
#define LWC871_SF_HDMI_ACR_0320_SUBPACK_HIGH_ENABLE_NO                     0x00000000 /* RWI-V */
#define LWC871_SF_HDMI_ACR_0320_SUBPACK_HIGH_ENABLE_YES                    0x00000001 /* RW--V */
#define LWC871_SF_HDMI_ACR_0320_SUBPACK_HIGH_ENABLE_DIS                    0x00000000 /* RW--V */
#define LWC871_SF_HDMI_ACR_0320_SUBPACK_HIGH_ENABLE_EN                     0x00000001 /* RW--V */
#define LWC871_SF_HDMI_ACR_0441_SUBPACK_LOW(i)                  (0x000E0090-0x000E0000+(i)*1024) /* RW-4A */
#define LWC871_SF_HDMI_ACR_0441_SUBPACK_LOW__SIZE_1                                 8 /*       */
#define LWC871_SF_HDMI_ACR_0441_SUBPACK_LOW_SB3                                  15:8 /* RWIVF */
#define LWC871_SF_HDMI_ACR_0441_SUBPACK_LOW_SB3_INIT                       0x00000000 /* RWI-V */
#define LWC871_SF_HDMI_ACR_0441_SUBPACK_LOW_SB2                                 23:16 /* RWIVF */
#define LWC871_SF_HDMI_ACR_0441_SUBPACK_LOW_SB2_INIT                       0x00000000 /* RWI-V */
#define LWC871_SF_HDMI_ACR_0441_SUBPACK_LOW_SB1                                 31:24 /* RWIVF */
#define LWC871_SF_HDMI_ACR_0441_SUBPACK_LOW_SB1_INIT                       0x00000000 /* RWI-V */
#define LWC871_SF_HDMI_ACR_0441_SUBPACK_LOW_CTS                                  31:8 /*       */
#define LWC871_SF_HDMI_ACR_0441_SUBPACK_HIGH(i)                 (0x000E0094-0x000E0000+(i)*1024) /* RW-4A */
#define LWC871_SF_HDMI_ACR_0441_SUBPACK_HIGH__SIZE_1                                8 /*       */
#define LWC871_SF_HDMI_ACR_0441_SUBPACK_HIGH_SB6                                  7:0 /* RWIVF */
#define LWC871_SF_HDMI_ACR_0441_SUBPACK_HIGH_SB6_INIT                      0x00000000 /* RWI-V */
#define LWC871_SF_HDMI_ACR_0441_SUBPACK_HIGH_SB5                                 15:8 /* RWIVF */
#define LWC871_SF_HDMI_ACR_0441_SUBPACK_HIGH_SB5_INIT                      0x00000000 /* RWI-V */
#define LWC871_SF_HDMI_ACR_0441_SUBPACK_HIGH_SB4                                23:16 /* RWIVF */
#define LWC871_SF_HDMI_ACR_0441_SUBPACK_HIGH_SB4_INIT                      0x00000000 /* RWI-V */
#define LWC871_SF_HDMI_ACR_0441_SUBPACK_HIGH_ENABLE                             31:31 /* RWIVF */
#define LWC871_SF_HDMI_ACR_0441_SUBPACK_HIGH_ENABLE_NO                     0x00000000 /* RWI-V */
#define LWC871_SF_HDMI_ACR_0441_SUBPACK_HIGH_ENABLE_YES                    0x00000001 /* RW--V */
#define LWC871_SF_HDMI_ACR_0441_SUBPACK_HIGH_ENABLE_DIS                    0x00000000 /* RW--V */
#define LWC871_SF_HDMI_ACR_0441_SUBPACK_HIGH_ENABLE_EN                     0x00000001 /* RW--V */
#define LWC871_SF_HDMI_ACR_0882_SUBPACK_LOW(i)                  (0x000E0098-0x000E0000+(i)*1024) /* RW-4A */
#define LWC871_SF_HDMI_ACR_0882_SUBPACK_LOW__SIZE_1                                 8 /*       */
#define LWC871_SF_HDMI_ACR_0882_SUBPACK_LOW_SB3                                  15:8 /* RWIVF */
#define LWC871_SF_HDMI_ACR_0882_SUBPACK_LOW_SB3_INIT                       0x00000000 /* RWI-V */
#define LWC871_SF_HDMI_ACR_0882_SUBPACK_LOW_SB2                                 23:16 /* RWIVF */
#define LWC871_SF_HDMI_ACR_0882_SUBPACK_LOW_SB2_INIT                       0x00000000 /* RWI-V */
#define LWC871_SF_HDMI_ACR_0882_SUBPACK_LOW_SB1                                 31:24 /* RWIVF */
#define LWC871_SF_HDMI_ACR_0882_SUBPACK_LOW_SB1_INIT                       0x00000000 /* RWI-V */
#define LWC871_SF_HDMI_ACR_0882_SUBPACK_LOW_CTS                                  31:8 /*       */
#define LWC871_SF_HDMI_ACR_0882_SUBPACK_HIGH(i)                 (0x000E009C-0x000E0000+(i)*1024) /* RW-4A */
#define LWC871_SF_HDMI_ACR_0882_SUBPACK_HIGH__SIZE_1                                8 /*       */
#define LWC871_SF_HDMI_ACR_0882_SUBPACK_HIGH_SB6                                  7:0 /* RWIVF */
#define LWC871_SF_HDMI_ACR_0882_SUBPACK_HIGH_SB6_INIT                      0x00000000 /* RWI-V */
#define LWC871_SF_HDMI_ACR_0882_SUBPACK_HIGH_SB5                                 15:8 /* RWIVF */
#define LWC871_SF_HDMI_ACR_0882_SUBPACK_HIGH_SB5_INIT                      0x00000000 /* RWI-V */
#define LWC871_SF_HDMI_ACR_0882_SUBPACK_HIGH_SB4                                23:16 /* RWIVF */
#define LWC871_SF_HDMI_ACR_0882_SUBPACK_HIGH_SB4_INIT                      0x00000000 /* RWI-V */
#define LWC871_SF_HDMI_ACR_0882_SUBPACK_HIGH_N                                   23:0 /*       */
#define LWC871_SF_HDMI_ACR_0882_SUBPACK_HIGH_ENABLE                             31:31 /* RWIVF */
#define LWC871_SF_HDMI_ACR_0882_SUBPACK_HIGH_ENABLE_NO                     0x00000000 /* RWI-V */
#define LWC871_SF_HDMI_ACR_0882_SUBPACK_HIGH_ENABLE_YES                    0x00000001 /* RW--V */
#define LWC871_SF_HDMI_ACR_0882_SUBPACK_HIGH_ENABLE_DIS                    0x00000000 /* RW--V */
#define LWC871_SF_HDMI_ACR_0882_SUBPACK_HIGH_ENABLE_EN                     0x00000001 /* RW--V */
#define LWC871_SF_HDMI_ACR_1764_SUBPACK_LOW(i)                  (0x000E00A0-0x000E0000+(i)*1024) /* RW-4A */
#define LWC871_SF_HDMI_ACR_1764_SUBPACK_LOW__SIZE_1                                 8 /*       */
#define LWC871_SF_HDMI_ACR_1764_SUBPACK_LOW_SB3                                  15:8 /* RWIVF */
#define LWC871_SF_HDMI_ACR_1764_SUBPACK_LOW_SB3_INIT                       0x00000000 /* RWI-V */
#define LWC871_SF_HDMI_ACR_1764_SUBPACK_LOW_SB2                                 23:16 /* RWIVF */
#define LWC871_SF_HDMI_ACR_1764_SUBPACK_LOW_SB2_INIT                       0x00000000 /* RWI-V */
#define LWC871_SF_HDMI_ACR_1764_SUBPACK_LOW_SB1                                 31:24 /* RWIVF */
#define LWC871_SF_HDMI_ACR_1764_SUBPACK_LOW_SB1_INIT                       0x00000000 /* RWI-V */
#define LWC871_SF_HDMI_ACR_1764_SUBPACK_LOW_CTS                                  31:8 /*       */
#define LWC871_SF_HDMI_ACR_1764_SUBPACK_HIGH(i)                 (0x000E00A4-0x000E0000+(i)*1024) /* RW-4A */
#define LWC871_SF_HDMI_ACR_1764_SUBPACK_HIGH__SIZE_1                                8 /*       */
#define LWC871_SF_HDMI_ACR_1764_SUBPACK_HIGH_SB6                                  7:0 /* RWIVF */
#define LWC871_SF_HDMI_ACR_1764_SUBPACK_HIGH_SB6_INIT                      0x00000000 /* RWI-V */
#define LWC871_SF_HDMI_ACR_1764_SUBPACK_HIGH_SB5                                 15:8 /* RWIVF */
#define LWC871_SF_HDMI_ACR_1764_SUBPACK_HIGH_SB5_INIT                      0x00000000 /* RWI-V */
#define LWC871_SF_HDMI_ACR_1764_SUBPACK_HIGH_SB4                                23:16 /* RWIVF */
#define LWC871_SF_HDMI_ACR_1764_SUBPACK_HIGH_SB4_INIT                      0x00000000 /* RWI-V */
#define LWC871_SF_HDMI_ACR_1764_SUBPACK_HIGH_N                                   23:0 /*       */
#define LWC871_SF_HDMI_ACR_1764_SUBPACK_HIGH_ENABLE                             31:31 /* RWIVF */
#define LWC871_SF_HDMI_ACR_1764_SUBPACK_HIGH_ENABLE_NO                     0x00000000 /* RWI-V */
#define LWC871_SF_HDMI_ACR_1764_SUBPACK_HIGH_ENABLE_YES                    0x00000001 /* RW--V */
#define LWC871_SF_HDMI_ACR_1764_SUBPACK_HIGH_ENABLE_DIS                    0x00000000 /* RW--V */
#define LWC871_SF_HDMI_ACR_1764_SUBPACK_HIGH_ENABLE_EN                     0x00000001 /* RW--V */
#define LWC871_SF_HDMI_ACR_0480_SUBPACK_LOW(i)                  (0x000E00A8-0x000E0000+(i)*1024) /* RW-4A */
#define LWC871_SF_HDMI_ACR_0480_SUBPACK_LOW__SIZE_1                                 8 /*       */
#define LWC871_SF_HDMI_ACR_0480_SUBPACK_LOW_SB3                                  15:8 /* RWIVF */
#define LWC871_SF_HDMI_ACR_0480_SUBPACK_LOW_SB3_INIT                       0x00000000 /* RWI-V */
#define LWC871_SF_HDMI_ACR_0480_SUBPACK_LOW_SB2                                 23:16 /* RWIVF */
#define LWC871_SF_HDMI_ACR_0480_SUBPACK_LOW_SB2_INIT                       0x00000000 /* RWI-V */
#define LWC871_SF_HDMI_ACR_0480_SUBPACK_LOW_SB1                                 31:24 /* RWIVF */
#define LWC871_SF_HDMI_ACR_0480_SUBPACK_LOW_SB1_INIT                       0x00000000 /* RWI-V */
#define LWC871_SF_HDMI_ACR_0480_SUBPACK_LOW_CTS                                  31:8 /*       */
#define LWC871_SF_HDMI_ACR_0480_SUBPACK_HIGH(i)                 (0x000E00AC-0x000E0000+(i)*1024) /* RW-4A */
#define LWC871_SF_HDMI_ACR_0480_SUBPACK_HIGH__SIZE_1                                8 /*       */
#define LWC871_SF_HDMI_ACR_0480_SUBPACK_HIGH_SB6                                  7:0 /* RWIVF */
#define LWC871_SF_HDMI_ACR_0480_SUBPACK_HIGH_SB6_INIT                      0x00000000 /* RWI-V */
#define LWC871_SF_HDMI_ACR_0480_SUBPACK_HIGH_SB5                                 15:8 /* RWIVF */
#define LWC871_SF_HDMI_ACR_0480_SUBPACK_HIGH_SB5_INIT                      0x00000000 /* RWI-V */
#define LWC871_SF_HDMI_ACR_0480_SUBPACK_HIGH_SB4                                23:16 /* RWIVF */
#define LWC871_SF_HDMI_ACR_0480_SUBPACK_HIGH_SB4_INIT                      0x00000000 /* RWI-V */
#define LWC871_SF_HDMI_ACR_0480_SUBPACK_HIGH_N                                   23:0 /*       */
#define LWC871_SF_HDMI_ACR_0480_SUBPACK_HIGH_ENABLE                             31:31 /* RWIVF */
#define LWC871_SF_HDMI_ACR_0480_SUBPACK_HIGH_ENABLE_NO                     0x00000000 /* RWI-V */
#define LWC871_SF_HDMI_ACR_0480_SUBPACK_HIGH_ENABLE_YES                    0x00000001 /* RW--V */
#define LWC871_SF_HDMI_ACR_0480_SUBPACK_HIGH_ENABLE_DIS                    0x00000000 /* RW--V */
#define LWC871_SF_HDMI_ACR_0480_SUBPACK_HIGH_ENABLE_EN                     0x00000001 /* RW--V */
#define LWC871_SF_HDMI_ACR_0960_SUBPACK_LOW(i)                  (0x000E00B0-0x000E0000+(i)*1024) /* RW-4A */
#define LWC871_SF_HDMI_ACR_0960_SUBPACK_LOW__SIZE_1                                 8 /*       */
#define LWC871_SF_HDMI_ACR_0960_SUBPACK_LOW_SB3                                  15:8 /* RWIVF */
#define LWC871_SF_HDMI_ACR_0960_SUBPACK_LOW_SB3_INIT                       0x00000000 /* RWI-V */
#define LWC871_SF_HDMI_ACR_0960_SUBPACK_LOW_SB2                                 23:16 /* RWIVF */
#define LWC871_SF_HDMI_ACR_0960_SUBPACK_LOW_SB2_INIT                       0x00000000 /* RWI-V */
#define LWC871_SF_HDMI_ACR_0960_SUBPACK_LOW_SB1                                 31:24 /* RWIVF */
#define LWC871_SF_HDMI_ACR_0960_SUBPACK_LOW_SB1_INIT                       0x00000000 /* RWI-V */
#define LWC871_SF_HDMI_ACR_0960_SUBPACK_LOW_CTS                                  31:8 /*       */
#define LWC871_SF_HDMI_ACR_0960_SUBPACK_HIGH(i)                 (0x000E00B4-0x000E0000+(i)*1024) /* RW-4A */
#define LWC871_SF_HDMI_ACR_0960_SUBPACK_HIGH__SIZE_1                                8 /*       */
#define LWC871_SF_HDMI_ACR_0960_SUBPACK_HIGH_SB6                                  7:0 /* RWIVF */
#define LWC871_SF_HDMI_ACR_0960_SUBPACK_HIGH_SB6_INIT                      0x00000000 /* RWI-V */
#define LWC871_SF_HDMI_ACR_0960_SUBPACK_HIGH_SB5                                 15:8 /* RWIVF */
#define LWC871_SF_HDMI_ACR_0960_SUBPACK_HIGH_SB5_INIT                      0x00000000 /* RWI-V */
#define LWC871_SF_HDMI_ACR_0960_SUBPACK_HIGH_SB4                                23:16 /* RWIVF */
#define LWC871_SF_HDMI_ACR_0960_SUBPACK_HIGH_SB4_INIT                      0x00000000 /* RWI-V */
#define LWC871_SF_HDMI_ACR_0960_SUBPACK_HIGH_N                                   23:0 /*       */
#define LWC871_SF_HDMI_ACR_0960_SUBPACK_HIGH_ENABLE                             31:31 /* RWIVF */
#define LWC871_SF_HDMI_ACR_0960_SUBPACK_HIGH_ENABLE_NO                     0x00000000 /* RWI-V */
#define LWC871_SF_HDMI_ACR_0960_SUBPACK_HIGH_ENABLE_YES                    0x00000001 /* RW--V */
#define LWC871_SF_HDMI_ACR_0960_SUBPACK_HIGH_ENABLE_DIS                    0x00000000 /* RW--V */
#define LWC871_SF_HDMI_ACR_0960_SUBPACK_HIGH_ENABLE_EN                     0x00000001 /* RW--V */
#define LWC871_SF_HDMI_ACR_1920_SUBPACK_LOW(i)                  (0x000E00B8-0x000E0000+(i)*1024) /* RW-4A */
#define LWC871_SF_HDMI_ACR_1920_SUBPACK_LOW__SIZE_1                                 8 /*       */
#define LWC871_SF_HDMI_ACR_1920_SUBPACK_LOW_SB3                                  15:8 /* RWIVF */
#define LWC871_SF_HDMI_ACR_1920_SUBPACK_LOW_SB3_INIT                       0x00000000 /* RWI-V */
#define LWC871_SF_HDMI_ACR_1920_SUBPACK_LOW_SB2                                 23:16 /* RWIVF */
#define LWC871_SF_HDMI_ACR_1920_SUBPACK_LOW_SB2_INIT                       0x00000000 /* RWI-V */
#define LWC871_SF_HDMI_ACR_1920_SUBPACK_LOW_SB1                                 31:24 /* RWIVF */
#define LWC871_SF_HDMI_ACR_1920_SUBPACK_LOW_SB1_INIT                       0x00000000 /* RWI-V */
#define LWC871_SF_HDMI_ACR_1920_SUBPACK_LOW_CTS                                  31:8 /*       */
#define LWC871_SF_HDMI_ACR_1920_SUBPACK_HIGH(i)                 (0x000E00BC-0x000E0000+(i)*1024) /* RW-4A */
#define LWC871_SF_HDMI_ACR_1920_SUBPACK_HIGH__SIZE_1                                8 /*       */
#define LWC871_SF_HDMI_ACR_1920_SUBPACK_HIGH_SB6                                  7:0 /* RWIVF */
#define LWC871_SF_HDMI_ACR_1920_SUBPACK_HIGH_SB6_INIT                      0x00000000 /* RWI-V */
#define LWC871_SF_HDMI_ACR_1920_SUBPACK_HIGH_SB5                                 15:8 /* RWIVF */
#define LWC871_SF_HDMI_ACR_1920_SUBPACK_HIGH_SB5_INIT                      0x00000000 /* RWI-V */
#define LWC871_SF_HDMI_ACR_1920_SUBPACK_HIGH_SB4                                23:16 /* RWIVF */
#define LWC871_SF_HDMI_ACR_1920_SUBPACK_HIGH_SB4_INIT                      0x00000000 /* RWI-V */
#define LWC871_SF_HDMI_ACR_1920_SUBPACK_HIGH_N                                   23:0 /*       */
#define LWC871_SF_HDMI_ACR_1920_SUBPACK_HIGH_ENABLE                             31:31 /* RWIVF */
#define LWC871_SF_HDMI_ACR_1920_SUBPACK_HIGH_ENABLE_NO                     0x00000000 /* RWI-V */
#define LWC871_SF_HDMI_ACR_1920_SUBPACK_HIGH_ENABLE_YES                    0x00000001 /* RW--V */
#define LWC871_SF_HDMI_ACR_1920_SUBPACK_HIGH_ENABLE_DIS                    0x00000000 /* RW--V */
#define LWC871_SF_HDMI_ACR_1920_SUBPACK_HIGH_ENABLE_EN                     0x00000001 /* RW--V */
#define LWC871_SF_DP_GENERIC_INFOFRAME_CTRL(i)                  (0x000E00C0-0x000E0000+(i)*1024) /* RW-4A */
#define LWC871_SF_DP_GENERIC_INFOFRAME_CTRL__SIZE_1                                 8 /*       */
#define LWC871_SF_DP_GENERIC_INFOFRAME_CTRL_ENABLE                                0:0 /* RWIVF */
#define LWC871_SF_DP_GENERIC_INFOFRAME_CTRL_ENABLE_YES                     0x00000001 /* RW--V */
#define LWC871_SF_DP_GENERIC_INFOFRAME_CTRL_ENABLE_NO                      0x00000000 /* RW--V */
#define LWC871_SF_DP_GENERIC_INFOFRAME_CTRL_ENABLE_INIT                    0x00000000 /* RWI-V */
#define LWC871_SF_DP_GENERIC_INFOFRAME_CTRL_IMMEDIATE                             1:1 /* RWIVF */
#define LWC871_SF_DP_GENERIC_INFOFRAME_CTRL_IMMEDIATE_INIT                 0x00000000 /* R-I-V */
#define LWC871_SF_DP_GENERIC_INFOFRAME_CTRL_IMMEDIATE_DONE                 0x00000000 /* R---V */
#define LWC871_SF_DP_GENERIC_INFOFRAME_CTRL_IMMEDIATE_PENDING              0x00000001 /* R---V */
#define LWC871_SF_DP_GENERIC_INFOFRAME_CTRL_IMMEDIATE_TRIGGER              0x00000001 /* -W--T */
#define LWC871_SF_DP_GENERIC_INFOFRAME_HEADER(i)                (0x000E00C4-0x000E0000+(i)*1024) /* RW-4A */
#define LWC871_SF_DP_GENERIC_INFOFRAME_HEADER__SIZE_1                               8 /*       */
#define LWC871_SF_DP_GENERIC_INFOFRAME_HEADER_HB0                                 7:0 /* RWIVF */
#define LWC871_SF_DP_GENERIC_INFOFRAME_HEADER_HB0_INIT                     0x00000000 /* RWI-V */
#define LWC871_SF_DP_GENERIC_INFOFRAME_HEADER_HB1                                15:8 /* RWIVF */
#define LWC871_SF_DP_GENERIC_INFOFRAME_HEADER_HB1_INIT                     0x00000000 /* RWI-V */
#define LWC871_SF_DP_GENERIC_INFOFRAME_HEADER_HB2                               23:16 /* RWIVF */
#define LWC871_SF_DP_GENERIC_INFOFRAME_HEADER_HB2_INIT                     0x00000000 /* RWI-V */
#define LWC871_SF_DP_GENERIC_INFOFRAME_HEADER_HB3                               31:24 /* RWIVF */
#define LWC871_SF_DP_GENERIC_INFOFRAME_HEADER_HB3_INIT                     0x00000000 /* RWI-V */
#define LWC871_SF_DP_GENERIC_INFOFRAME_SUBPACK0(i)              (0x000E00C8-0x000E0000+(i)*1024) /* RW-4A */
#define LWC871_SF_DP_GENERIC_INFOFRAME_SUBPACK0__SIZE_1                             8 /*       */
#define LWC871_SF_DP_GENERIC_INFOFRAME_SUBPACK0_DB0                               7:0 /* RWIVF */
#define LWC871_SF_DP_GENERIC_INFOFRAME_SUBPACK0_DB0_INIT                   0x00000000 /* RWI-V */
#define LWC871_SF_DP_GENERIC_INFOFRAME_SUBPACK0_DB1                              15:8 /* RWIVF */
#define LWC871_SF_DP_GENERIC_INFOFRAME_SUBPACK0_DB1_INIT                   0x00000000 /* RWI-V */
#define LWC871_SF_DP_GENERIC_INFOFRAME_SUBPACK0_DB2                             23:16 /* RWIVF */
#define LWC871_SF_DP_GENERIC_INFOFRAME_SUBPACK0_DB2_INIT                   0x00000000 /* RWI-V */
#define LWC871_SF_DP_GENERIC_INFOFRAME_SUBPACK0_DB3                             31:24 /* RWIVF */
#define LWC871_SF_DP_GENERIC_INFOFRAME_SUBPACK0_DB3_INIT                   0x00000000 /* RWI-V */
#define LWC871_SF_DP_GENERIC_INFOFRAME_SUBPACK1(i)              (0x000E00CC-0x000E0000+(i)*1024) /* RW-4A */
#define LWC871_SF_DP_GENERIC_INFOFRAME_SUBPACK1__SIZE_1                             8 /*       */
#define LWC871_SF_DP_GENERIC_INFOFRAME_SUBPACK1_DB4                               7:0 /* RWIVF */
#define LWC871_SF_DP_GENERIC_INFOFRAME_SUBPACK1_DB4_INIT                   0x00000000 /* RWI-V */
#define LWC871_SF_DP_GENERIC_INFOFRAME_SUBPACK1_DB5                              15:8 /* RWIVF */
#define LWC871_SF_DP_GENERIC_INFOFRAME_SUBPACK1_DB5_INIT                   0x00000000 /* RWI-V */
#define LWC871_SF_DP_GENERIC_INFOFRAME_SUBPACK1_DB6                             23:16 /* RWIVF */
#define LWC871_SF_DP_GENERIC_INFOFRAME_SUBPACK1_DB6_INIT                   0x00000000 /* RWI-V */
#define LWC871_SF_DP_GENERIC_INFOFRAME_SUBPACK1_DB7                             31:24 /* RWIVF */
#define LWC871_SF_DP_GENERIC_INFOFRAME_SUBPACK1_DB7_INIT                   0x00000000 /* RWI-V */
#define LWC871_SF_DP_GENERIC_INFOFRAME_SUBPACK2(i)              (0x000E00D0-0x000E0000+(i)*1024) /* RW-4A */
#define LWC871_SF_DP_GENERIC_INFOFRAME_SUBPACK2__SIZE_1                             8 /*       */
#define LWC871_SF_DP_GENERIC_INFOFRAME_SUBPACK2_DB8                               7:0 /* RWIVF */
#define LWC871_SF_DP_GENERIC_INFOFRAME_SUBPACK2_DB8_INIT                   0x00000000 /* RWI-V */
#define LWC871_SF_DP_GENERIC_INFOFRAME_SUBPACK2_DB9                              15:8 /* RWIVF */
#define LWC871_SF_DP_GENERIC_INFOFRAME_SUBPACK2_DB9_INIT                   0x00000000 /* RWI-V */
#define LWC871_SF_DP_GENERIC_INFOFRAME_SUBPACK2_DB10                            23:16 /* RWIVF */
#define LWC871_SF_DP_GENERIC_INFOFRAME_SUBPACK2_DB10_INIT                  0x00000000 /* RWI-V */
#define LWC871_SF_DP_GENERIC_INFOFRAME_SUBPACK2_DB11                            31:24 /* RWIVF */
#define LWC871_SF_DP_GENERIC_INFOFRAME_SUBPACK2_DB11_INIT                  0x00000000 /* RWI-V */
#define LWC871_SF_DP_GENERIC_INFOFRAME_SUBPACK3(i)              (0x000E00D4-0x000E0000+(i)*1024) /* RW-4A */
#define LWC871_SF_DP_GENERIC_INFOFRAME_SUBPACK3__SIZE_1                             8 /*       */
#define LWC871_SF_DP_GENERIC_INFOFRAME_SUBPACK3_DB12                              7:0 /* RWIVF */
#define LWC871_SF_DP_GENERIC_INFOFRAME_SUBPACK3_DB12_INIT                  0x00000000 /* RWI-V */
#define LWC871_SF_DP_GENERIC_INFOFRAME_SUBPACK3_DB13                             15:8 /* RWIVF */
#define LWC871_SF_DP_GENERIC_INFOFRAME_SUBPACK3_DB13_INIT                  0x00000000 /* RWI-V */
#define LWC871_SF_DP_GENERIC_INFOFRAME_SUBPACK3_DB14                            23:16 /* RWIVF */
#define LWC871_SF_DP_GENERIC_INFOFRAME_SUBPACK3_DB14_INIT                  0x00000000 /* RWI-V */
#define LWC871_SF_DP_GENERIC_INFOFRAME_SUBPACK3_DB15                            31:24 /* RWIVF */
#define LWC871_SF_DP_GENERIC_INFOFRAME_SUBPACK3_DB15_INIT                  0x00000000 /* RWI-V */
#define LWC871_SF_DP_GENERIC_INFOFRAME_SUBPACK4(i)              (0x000E00D8-0x000E0000+(i)*1024) /* RW-4A */
#define LWC871_SF_DP_GENERIC_INFOFRAME_SUBPACK4__SIZE_1                             8 /*       */
#define LWC871_SF_DP_GENERIC_INFOFRAME_SUBPACK4_DB16                              7:0 /* RWIVF */
#define LWC871_SF_DP_GENERIC_INFOFRAME_SUBPACK4_DB16_INIT                  0x00000000 /* RWI-V */
#define LWC871_SF_DP_GENERIC_INFOFRAME_SUBPACK4_DB17                             15:8 /* RWIVF */
#define LWC871_SF_DP_GENERIC_INFOFRAME_SUBPACK4_DB17_INIT                  0x00000000 /* RWI-V */
#define LWC871_SF_DP_GENERIC_INFOFRAME_SUBPACK4_DB18                            23:16 /* RWIVF */
#define LWC871_SF_DP_GENERIC_INFOFRAME_SUBPACK4_DB18_INIT                  0x00000000 /* RWI-V */
#define LWC871_SF_DP_GENERIC_INFOFRAME_SUBPACK4_DB19                            31:24 /* RWIVF */
#define LWC871_SF_DP_GENERIC_INFOFRAME_SUBPACK4_DB19_INIT                  0x00000000 /* RWI-V */
#define LWC871_SF_DP_GENERIC_INFOFRAME_SUBPACK5(i)              (0x000E00DC-0x000E0000+(i)*1024) /* RW-4A */
#define LWC871_SF_DP_GENERIC_INFOFRAME_SUBPACK5__SIZE_1                             8 /*       */
#define LWC871_SF_DP_GENERIC_INFOFRAME_SUBPACK5_DB20                              7:0 /* RWIVF */
#define LWC871_SF_DP_GENERIC_INFOFRAME_SUBPACK5_DB20_INIT                  0x00000000 /* RWI-V */
#define LWC871_SF_DP_GENERIC_INFOFRAME_SUBPACK5_DB21                             15:8 /* RWIVF */
#define LWC871_SF_DP_GENERIC_INFOFRAME_SUBPACK5_DB21_INIT                  0x00000000 /* RWI-V */
#define LWC871_SF_DP_GENERIC_INFOFRAME_SUBPACK5_DB22                            23:16 /* RWIVF */
#define LWC871_SF_DP_GENERIC_INFOFRAME_SUBPACK5_DB22_INIT                  0x00000000 /* RWI-V */
#define LWC871_SF_DP_GENERIC_INFOFRAME_SUBPACK5_DB23                            31:24 /* RWIVF */
#define LWC871_SF_DP_GENERIC_INFOFRAME_SUBPACK5_DB23_INIT                  0x00000000 /* RWI-V */
#define LWC871_SF_DP_GENERIC_INFOFRAME_SUBPACK6(i)              (0x000E00E0-0x000E0000+(i)*1024) /* RW-4A */
#define LWC871_SF_DP_GENERIC_INFOFRAME_SUBPACK6__SIZE_1                             8 /*       */
#define LWC871_SF_DP_GENERIC_INFOFRAME_SUBPACK6_DB24                              7:0 /* RWIVF */
#define LWC871_SF_DP_GENERIC_INFOFRAME_SUBPACK6_DB24_INIT                  0x00000000 /* RWI-V */
#define LWC871_SF_DP_GENERIC_INFOFRAME_SUBPACK6_DB25                             15:8 /* RWIVF */
#define LWC871_SF_DP_GENERIC_INFOFRAME_SUBPACK6_DB25_INIT                  0x00000000 /* RWI-V */
#define LWC871_SF_DP_GENERIC_INFOFRAME_SUBPACK6_DB26                            23:16 /* RWIVF */
#define LWC871_SF_DP_GENERIC_INFOFRAME_SUBPACK6_DB26_INIT                  0x00000000 /* RWI-V */
#define LWC871_SF_DP_GENERIC_INFOFRAME_SUBPACK6_DB27                            31:24 /* RWIVF */
#define LWC871_SF_DP_GENERIC_INFOFRAME_SUBPACK6_DB27_INIT                  0x00000000 /* RWI-V */
#define LWC871_SF_DP_GENERIC_INFOFRAME_SUBPACK7(i)              (0x000E00E4-0x000E0000+(i)*1024) /* RW-4A */
#define LWC871_SF_DP_GENERIC_INFOFRAME_SUBPACK7__SIZE_1                             8 /*       */
#define LWC871_SF_DP_GENERIC_INFOFRAME_SUBPACK7_DB28                              7:0 /* RWIVF */
#define LWC871_SF_DP_GENERIC_INFOFRAME_SUBPACK7_DB28_INIT                  0x00000000 /* RWI-V */
#define LWC871_SF_DP_GENERIC_INFOFRAME_SUBPACK7_DB29                             15:8 /* RWIVF */
#define LWC871_SF_DP_GENERIC_INFOFRAME_SUBPACK7_DB29_INIT                  0x00000000 /* RWI-V */
#define LWC871_SF_DP_GENERIC_INFOFRAME_SUBPACK7_DB30                            23:16 /* RWIVF */
#define LWC871_SF_DP_GENERIC_INFOFRAME_SUBPACK7_DB30_INIT                  0x00000000 /* RWI-V */
#define LWC871_SF_DP_GENERIC_INFOFRAME_SUBPACK7_DB31                            31:24 /* RWIVF */
#define LWC871_SF_DP_GENERIC_INFOFRAME_SUBPACK7_DB31_INIT                  0x00000000 /* RWI-V */
#define LWC871_SF_DP_AUDIO_INFOFRAME_CTRL(i)                     (0x000E00F0-0x000E0000+(i)*1024) /* RW-4A */
#define LWC871_SF_DP_AUDIO_INFOFRAME_CTRL__SIZE_1                                    8 /*       */
#define LWC871_SF_DP_AUDIO_INFOFRAME_CTRL_HEADER_OVERRIDE                          4:4 /* RWIVF */
#define LWC871_SF_DP_AUDIO_INFOFRAME_CTRL_HEADER_OVERRIDE_ENABLE            0x00000001 /* RW--V */
#define LWC871_SF_DP_AUDIO_INFOFRAME_CTRL_HEADER_OVERRIDE_DISABLE           0x00000000 /* RW--V */
#define LWC871_SF_DP_AUDIO_INFOFRAME_CTRL_HEADER_OVERRIDE_INIT              0x00000000 /* RWI-V */
#define LWC871_SF_DP_AUDIO_INFOFRAME_HEADER(i)                  (0x000E00F4-0x000E0000+(i)*1024) /* RW-4A */
#define LWC871_SF_DP_AUDIO_INFOFRAME_HEADER__SIZE_1                                 8 /*       */
#define LWC871_SF_DP_AUDIO_INFOFRAME_HEADER_HB0                                   7:0 /* RWIVF */
#define LWC871_SF_DP_AUDIO_INFOFRAME_HEADER_HB0_INIT                       0x00000000 /* RWI-V */
#define LWC871_SF_DP_AUDIO_INFOFRAME_HEADER_HB1                                  15:8 /* RWIVF */
#define LWC871_SF_DP_AUDIO_INFOFRAME_HEADER_HB1_INIT                       0x00000000 /* RWI-V */
#define LWC871_SF_DP_AUDIO_INFOFRAME_HEADER_HB2                                 23:16 /* RWIVF */
#define LWC871_SF_DP_AUDIO_INFOFRAME_HEADER_HB2_INIT                       0x00000000 /* RWI-V */
#define LWC871_SF_DP_AUDIO_INFOFRAME_HEADER_HB3                                 31:24 /* RWIVF */
#define LWC871_SF_DP_AUDIO_INFOFRAME_HEADER_HB3_INIT                       0x00000000 /* RWI-V */
#define LWC871_SF_DP_GENERIC_INFOFRAME1_CTRL(i)                  (0x000E0100-0x000E0000+(i)*1024) /* RW-4A */
#define LWC871_SF_DP_GENERIC_INFOFRAME1_CTRL__SIZE_1                                 8 /*       */
#define LWC871_SF_DP_GENERIC_INFOFRAME1_CTRL_ENABLE                                0:0 /* RWIVF */
#define LWC871_SF_DP_GENERIC_INFOFRAME1_CTRL_ENABLE_YES                     0x00000001 /* RW--V */
#define LWC871_SF_DP_GENERIC_INFOFRAME1_CTRL_ENABLE_NO                      0x00000000 /* RW--V */
#define LWC871_SF_DP_GENERIC_INFOFRAME1_CTRL_ENABLE_INIT                    0x00000000 /* RWI-V */
#define LWC871_SF_DP_GENERIC_INFOFRAME1_CTRL_IMMEDIATE                             1:1 /* RWIVF */
#define LWC871_SF_DP_GENERIC_INFOFRAME1_CTRL_IMMEDIATE_INIT                 0x00000000 /* R-I-V */
#define LWC871_SF_DP_GENERIC_INFOFRAME1_CTRL_IMMEDIATE_DONE                 0x00000000 /* R---V */
#define LWC871_SF_DP_GENERIC_INFOFRAME1_CTRL_IMMEDIATE_PENDING              0x00000001 /* R---V */
#define LWC871_SF_DP_GENERIC_INFOFRAME1_CTRL_IMMEDIATE_TRIGGER              0x00000001 /* -W--T */
#define LWC871_SF_DP_GENERIC_INFOFRAME1_HEADER(i)                (0x000E0104-0x000E0000+(i)*1024) /* RW-4A */
#define LWC871_SF_DP_GENERIC_INFOFRAME1_HEADER__SIZE_1                               8 /*       */
#define LWC871_SF_DP_GENERIC_INFOFRAME1_HEADER_HB0                                 7:0 /* RWIVF */
#define LWC871_SF_DP_GENERIC_INFOFRAME1_HEADER_HB0_INIT                     0x00000000 /* RWI-V */
#define LWC871_SF_DP_GENERIC_INFOFRAME1_HEADER_HB1                                15:8 /* RWIVF */
#define LWC871_SF_DP_GENERIC_INFOFRAME1_HEADER_HB1_INIT                     0x00000000 /* RWI-V */
#define LWC871_SF_DP_GENERIC_INFOFRAME1_HEADER_HB2                               23:16 /* RWIVF */
#define LWC871_SF_DP_GENERIC_INFOFRAME1_HEADER_HB2_INIT                     0x00000000 /* RWI-V */
#define LWC871_SF_DP_GENERIC_INFOFRAME1_HEADER_HB3                               31:24 /* RWIVF */
#define LWC871_SF_DP_GENERIC_INFOFRAME1_HEADER_HB3_INIT                     0x00000000 /* RWI-V */
#define LWC871_SF_DP_GENERIC_INFOFRAME1_SUBPACK0(i)              (0x000E0108-0x000E0000+(i)*1024) /* RW-4A */
#define LWC871_SF_DP_GENERIC_INFOFRAME1_SUBPACK0__SIZE_1                             8 /*       */
#define LWC871_SF_DP_GENERIC_INFOFRAME1_SUBPACK0_DB0                               7:0 /* RWIVF */
#define LWC871_SF_DP_GENERIC_INFOFRAME1_SUBPACK0_DB0_INIT                   0x00000000 /* RWI-V */
#define LWC871_SF_DP_GENERIC_INFOFRAME1_SUBPACK0_DB1                              15:8 /* RWIVF */
#define LWC871_SF_DP_GENERIC_INFOFRAME1_SUBPACK0_DB1_INIT                   0x00000000 /* RWI-V */
#define LWC871_SF_DP_GENERIC_INFOFRAME1_SUBPACK0_DB2                             23:16 /* RWIVF */
#define LWC871_SF_DP_GENERIC_INFOFRAME1_SUBPACK0_DB2_INIT                   0x00000000 /* RWI-V */
#define LWC871_SF_DP_GENERIC_INFOFRAME1_SUBPACK0_DB3                             31:24 /* RWIVF */
#define LWC871_SF_DP_GENERIC_INFOFRAME1_SUBPACK0_DB3_INIT                   0x00000000 /* RWI-V */
#define LWC871_SF_DP_GENERIC_INFOFRAME1_SUBPACK1(i)              (0x000E010C-0x000E0000+(i)*1024) /* RW-4A */
#define LWC871_SF_DP_GENERIC_INFOFRAME1_SUBPACK1__SIZE_1                             8 /*       */
#define LWC871_SF_DP_GENERIC_INFOFRAME1_SUBPACK1_DB4                               7:0 /* RWIVF */
#define LWC871_SF_DP_GENERIC_INFOFRAME1_SUBPACK1_DB4_INIT                   0x00000000 /* RWI-V */
#define LWC871_SF_DP_GENERIC_INFOFRAME1_SUBPACK1_DB5                              15:8 /* RWIVF */
#define LWC871_SF_DP_GENERIC_INFOFRAME1_SUBPACK1_DB5_INIT                   0x00000000 /* RWI-V */
#define LWC871_SF_DP_GENERIC_INFOFRAME1_SUBPACK1_DB6                             23:16 /* RWIVF */
#define LWC871_SF_DP_GENERIC_INFOFRAME1_SUBPACK1_DB6_INIT                   0x00000000 /* RWI-V */
#define LWC871_SF_DP_GENERIC_INFOFRAME1_SUBPACK1_DB7                             31:24 /* RWIVF */
#define LWC871_SF_DP_GENERIC_INFOFRAME1_SUBPACK1_DB7_INIT                   0x00000000 /* RWI-V */
#define LWC871_SF_DP_GENERIC_INFOFRAME1_SUBPACK2(i)              (0x000E0110-0x000E0000+(i)*1024) /* RW-4A */
#define LWC871_SF_DP_GENERIC_INFOFRAME1_SUBPACK2__SIZE_1                             8 /*       */
#define LWC871_SF_DP_GENERIC_INFOFRAME1_SUBPACK2_DB8                               7:0 /* RWIVF */
#define LWC871_SF_DP_GENERIC_INFOFRAME1_SUBPACK2_DB8_INIT                   0x00000000 /* RWI-V */
#define LWC871_SF_DP_GENERIC_INFOFRAME1_SUBPACK2_DB9                              15:8 /* RWIVF */
#define LWC871_SF_DP_GENERIC_INFOFRAME1_SUBPACK2_DB9_INIT                   0x00000000 /* RWI-V */
#define LWC871_SF_DP_GENERIC_INFOFRAME1_SUBPACK2_DB10                            23:16 /* RWIVF */
#define LWC871_SF_DP_GENERIC_INFOFRAME1_SUBPACK2_DB10_INIT                  0x00000000 /* RWI-V */
#define LWC871_SF_DP_GENERIC_INFOFRAME1_SUBPACK2_DB11                            31:24 /* RWIVF */
#define LWC871_SF_DP_GENERIC_INFOFRAME1_SUBPACK2_DB11_INIT                  0x00000000 /* RWI-V */
#define LWC871_SF_DP_GENERIC_INFOFRAME1_SUBPACK3(i)              (0x000E0114-0x000E0000+(i)*1024) /* RW-4A */
#define LWC871_SF_DP_GENERIC_INFOFRAME1_SUBPACK3__SIZE_1                             8 /*       */
#define LWC871_SF_DP_GENERIC_INFOFRAME1_SUBPACK3_DB12                              7:0 /* RWIVF */
#define LWC871_SF_DP_GENERIC_INFOFRAME1_SUBPACK3_DB12_INIT                  0x00000000 /* RWI-V */
#define LWC871_SF_DP_GENERIC_INFOFRAME1_SUBPACK3_DB13                             15:8 /* RWIVF */
#define LWC871_SF_DP_GENERIC_INFOFRAME1_SUBPACK3_DB13_INIT                  0x00000000 /* RWI-V */
#define LWC871_SF_DP_GENERIC_INFOFRAME1_SUBPACK3_DB14                            23:16 /* RWIVF */
#define LWC871_SF_DP_GENERIC_INFOFRAME1_SUBPACK3_DB14_INIT                  0x00000000 /* RWI-V */
#define LWC871_SF_DP_GENERIC_INFOFRAME1_SUBPACK3_DB15                            31:24 /* RWIVF */
#define LWC871_SF_DP_GENERIC_INFOFRAME1_SUBPACK3_DB15_INIT                  0x00000000 /* RWI-V */
#define LWC871_SF_DP_GENERIC_INFOFRAME1_SUBPACK4(i)              (0x000E0118-0x000E0000+(i)*1024) /* RW-4A */
#define LWC871_SF_DP_GENERIC_INFOFRAME1_SUBPACK4__SIZE_1                             8 /*       */
#define LWC871_SF_DP_GENERIC_INFOFRAME1_SUBPACK4_DB16                              7:0 /* RWIVF */
#define LWC871_SF_DP_GENERIC_INFOFRAME1_SUBPACK4_DB16_INIT                  0x00000000 /* RWI-V */
#define LWC871_SF_DP_GENERIC_INFOFRAME1_SUBPACK4_DB17                             15:8 /* RWIVF */
#define LWC871_SF_DP_GENERIC_INFOFRAME1_SUBPACK4_DB17_INIT                  0x00000000 /* RWI-V */
#define LWC871_SF_DP_GENERIC_INFOFRAME1_SUBPACK4_DB18                            23:16 /* RWIVF */
#define LWC871_SF_DP_GENERIC_INFOFRAME1_SUBPACK4_DB18_INIT                  0x00000000 /* RWI-V */
#define LWC871_SF_DP_GENERIC_INFOFRAME1_SUBPACK4_DB19                            31:24 /* RWIVF */
#define LWC871_SF_DP_GENERIC_INFOFRAME1_SUBPACK4_DB19_INIT                  0x00000000 /* RWI-V */
#define LWC871_SF_DP_GENERIC_INFOFRAME1_SUBPACK5(i)              (0x000E011C-0x000E0000+(i)*1024) /* RW-4A */
#define LWC871_SF_DP_GENERIC_INFOFRAME1_SUBPACK5__SIZE_1                             8 /*       */
#define LWC871_SF_DP_GENERIC_INFOFRAME1_SUBPACK5_DB20                              7:0 /* RWIVF */
#define LWC871_SF_DP_GENERIC_INFOFRAME1_SUBPACK5_DB20_INIT                  0x00000000 /* RWI-V */
#define LWC871_SF_DP_GENERIC_INFOFRAME1_SUBPACK5_DB21                             15:8 /* RWIVF */
#define LWC871_SF_DP_GENERIC_INFOFRAME1_SUBPACK5_DB21_INIT                  0x00000000 /* RWI-V */
#define LWC871_SF_DP_GENERIC_INFOFRAME1_SUBPACK5_DB22                            23:16 /* RWIVF */
#define LWC871_SF_DP_GENERIC_INFOFRAME1_SUBPACK5_DB22_INIT                  0x00000000 /* RWI-V */
#define LWC871_SF_DP_GENERIC_INFOFRAME1_SUBPACK5_DB23                            31:24 /* RWIVF */
#define LWC871_SF_DP_GENERIC_INFOFRAME1_SUBPACK5_DB23_INIT                  0x00000000 /* RWI-V */
#define LWC871_SF_DP_GENERIC_INFOFRAME1_SUBPACK6(i)              (0x000E0120-0x000E0000+(i)*1024) /* RW-4A */
#define LWC871_SF_DP_GENERIC_INFOFRAME1_SUBPACK6__SIZE_1                             8 /*       */
#define LWC871_SF_DP_GENERIC_INFOFRAME1_SUBPACK6_DB24                              7:0 /* RWIVF */
#define LWC871_SF_DP_GENERIC_INFOFRAME1_SUBPACK6_DB24_INIT                  0x00000000 /* RWI-V */
#define LWC871_SF_DP_GENERIC_INFOFRAME1_SUBPACK6_DB25                             15:8 /* RWIVF */
#define LWC871_SF_DP_GENERIC_INFOFRAME1_SUBPACK6_DB25_INIT                  0x00000000 /* RWI-V */
#define LWC871_SF_DP_GENERIC_INFOFRAME1_SUBPACK6_DB26                            23:16 /* RWIVF */
#define LWC871_SF_DP_GENERIC_INFOFRAME1_SUBPACK6_DB26_INIT                  0x00000000 /* RWI-V */
#define LWC871_SF_DP_GENERIC_INFOFRAME1_SUBPACK6_DB27                            31:24 /* RWIVF */
#define LWC871_SF_DP_GENERIC_INFOFRAME1_SUBPACK6_DB27_INIT                  0x00000000 /* RWI-V */
#define LWC871_SF_DP_GENERIC_INFOFRAME1_SUBPACK7(i)              (0x000E0124-0x000E0000+(i)*1024) /* RW-4A */
#define LWC871_SF_DP_GENERIC_INFOFRAME1_SUBPACK7__SIZE_1                             8 /*       */
#define LWC871_SF_DP_GENERIC_INFOFRAME1_SUBPACK7_DB28                              7:0 /* RWIVF */
#define LWC871_SF_DP_GENERIC_INFOFRAME1_SUBPACK7_DB28_INIT                  0x00000000 /* RWI-V */
#define LWC871_SF_DP_GENERIC_INFOFRAME1_SUBPACK7_DB29                             15:8 /* RWIVF */
#define LWC871_SF_DP_GENERIC_INFOFRAME1_SUBPACK7_DB29_INIT                  0x00000000 /* RWI-V */
#define LWC871_SF_DP_GENERIC_INFOFRAME1_SUBPACK7_DB30                            23:16 /* RWIVF */
#define LWC871_SF_DP_GENERIC_INFOFRAME1_SUBPACK7_DB30_INIT                  0x00000000 /* RWI-V */
#define LWC871_SF_DP_GENERIC_INFOFRAME1_SUBPACK7_DB31                            31:24 /* RWIVF */
#define LWC871_SF_DP_GENERIC_INFOFRAME1_SUBPACK7_DB31_INIT                  0x00000000 /* RWI-V */
#define LWC871_SF_GENERIC_INFOFRAME_CTRL(i,j)                          (0x000E0130-0x000E0000+(i)*1024+(j)*8) /* RW-4A */
#define LWC871_SF_GENERIC_INFOFRAME_CTRL__SIZE_1                                         8 /*       */
#define LWC871_SF_GENERIC_INFOFRAME_CTRL__SIZE_2                                        10 /*       */
#define LWC871_SF_GENERIC_INFOFRAME_CTRL_ENABLE                                        0:0 /* RWIVF */
#define LWC871_SF_GENERIC_INFOFRAME_CTRL_ENABLE_NO                              0x00000000 /* RWI-V */
#define LWC871_SF_GENERIC_INFOFRAME_CTRL_ENABLE_YES                             0x00000001 /* RW--V */
#define LWC871_SF_GENERIC_INFOFRAME_CTRL_RUN_MODE                                      3:1 /* RWIVF */
#define LWC871_SF_GENERIC_INFOFRAME_CTRL_RUN_MODE_ALWAYS                        0x00000000 /* RWI-V */
#define LWC871_SF_GENERIC_INFOFRAME_CTRL_RUN_MODE_ONCE                          0x00000001 /* RW--V */
#define LWC871_SF_GENERIC_INFOFRAME_CTRL_RUN_MODE_FID_ALWAYS                    0x00000002 /* RW--V */
#define LWC871_SF_GENERIC_INFOFRAME_CTRL_RUN_MODE_FID_ONCE                      0x00000003 /* RW--V */
#define LWC871_SF_GENERIC_INFOFRAME_CTRL_RUN_MODE_FID_TRIGGER                   0x00000004 /* RW--V */
#define LWC871_SF_GENERIC_INFOFRAME_CTRL_LOC                                           5:4 /* RWIVF */
#define LWC871_SF_GENERIC_INFOFRAME_CTRL_LOC_VBLANK                             0x00000000 /* RWI-V */
#define LWC871_SF_GENERIC_INFOFRAME_CTRL_LOC_VSYNC                              0x00000001 /* RW--V */
#define LWC871_SF_GENERIC_INFOFRAME_CTRL_LOC_LINE                               0x00000002 /* RW--V */
#define LWC871_SF_GENERIC_INFOFRAME_CTRL_LOC_LOADV                              0x00000003 /* RW--V */
#define LWC871_SF_GENERIC_INFOFRAME_CTRL_OFFSET                                       10:6 /* RWIVF */
#define LWC871_SF_GENERIC_INFOFRAME_CTRL_OFFSET_INIT                            0x00000000 /* RWI-V */
#define LWC871_SF_GENERIC_INFOFRAME_CTRL_SIZE                                        18:14 /* RWIVF */
#define LWC871_SF_GENERIC_INFOFRAME_CTRL_SIZE_INIT                              0x00000000 /* RWI-V */
#define LWC871_SF_GENERIC_INFOFRAME_CTRL_BUSY                                        22:22 /* R-IVF */
#define LWC871_SF_GENERIC_INFOFRAME_CTRL_BUSY_NO                                0x00000000 /* R-I-V */
#define LWC871_SF_GENERIC_INFOFRAME_CTRL_BUSY_YES                               0x00000001 /* R---V */
#define LWC871_SF_GENERIC_INFOFRAME_CTRL_SENT                                        23:23 /* R-IVF */
#define LWC871_SF_GENERIC_INFOFRAME_CTRL_SENT_NO                                0x00000000 /* R-I-V */
#define LWC871_SF_GENERIC_INFOFRAME_CTRL_SENT_YES                               0x00000001 /* R---V */
#define LWC871_SF_GENERIC_INFOFRAME_CONFIG(i,j)                        (0x000E0134-0x000E0000+(i)*1024+(j)*8) /* RW-4A */
#define LWC871_SF_GENERIC_INFOFRAME_CONFIG__SIZE_1                                       8 /*       */
#define LWC871_SF_GENERIC_INFOFRAME_CONFIG__SIZE_2                                      10 /*       */
#define LWC871_SF_GENERIC_INFOFRAME_CONFIG_FID                                         7:0 /* RWIVF */
#define LWC871_SF_GENERIC_INFOFRAME_CONFIG_FID_INIT                             0x00000000 /* RWI-V */
#define LWC871_SF_GENERIC_INFOFRAME_CONFIG_LINE_ID                                    23:8 /* RWIVF */
#define LWC871_SF_GENERIC_INFOFRAME_CONFIG_LINE_ID_INIT                         0x00000000 /* RWI-V */
#define LWC871_SF_GENERIC_INFOFRAME_CONFIG_LINE_ID_REVERSED                          24:24 /* RWIVF */
#define LWC871_SF_GENERIC_INFOFRAME_CONFIG_LINE_ID_REVERSED_NO                  0x00000000 /* RWI-V */
#define LWC871_SF_GENERIC_INFOFRAME_CONFIG_LINE_ID_REVERSED_YES                 0x00000001 /* RW--V */
#define LWC871_SF_GENERIC_INFOFRAME_CONFIG_CRC_OVERRIDE                              28:28 /* RWIVF */
#define LWC871_SF_GENERIC_INFOFRAME_CONFIG_CRC_OVERRIDE_NO                      0x00000000 /* RWI-V */
#define LWC871_SF_GENERIC_INFOFRAME_CONFIG_CRC_OVERRIDE_YES                     0x00000001 /* RW--V */
#define LWC871_SF_GENERIC_INFOFRAME_CONFIG_HW_CHECKSUM                               29:29 /* RWIVF */
#define LWC871_SF_GENERIC_INFOFRAME_CONFIG_HW_CHECKSUM_NO                       0x00000000 /* RWI-V */
#define LWC871_SF_GENERIC_INFOFRAME_CONFIG_HW_CHECKSUM_YES                      0x00000001 /* RW--V */
#define LWC871_SF_GENERIC_INFOFRAME_CONFIG_NEW                                       30:30 /* RWIVF */
#define LWC871_SF_GENERIC_INFOFRAME_CONFIG_NEW_INIT                             0x00000000 /* R-I-V */
#define LWC871_SF_GENERIC_INFOFRAME_CONFIG_NEW_DONE                             0x00000000 /* R---V */
#define LWC871_SF_GENERIC_INFOFRAME_CONFIG_NEW_PENDING                          0x00000001 /* R---V */
#define LWC871_SF_GENERIC_INFOFRAME_CONFIG_NEW_TRIGGER                          0x00000001 /* -W--T */
#define LWC871_SF_GENERIC_INFOFRAME_CONFIG_MTD_STATE_CTRL                            31:31 /* RWIVF */
#define LWC871_SF_GENERIC_INFOFRAME_CONFIG_MTD_STATE_CTRL_ACT                   0x00000000 /* RWI-V */
#define LWC871_SF_GENERIC_INFOFRAME_CONFIG_MTD_STATE_CTRL_ARM                   0x00000001 /* RW--V */
#define LWC871_SF_GENERIC_INFOFRAME_DATA_CTRL(i)                  (0x000E03F0-0x000E0000+(i)*1024) /* RW-4A */
#define LWC871_SF_GENERIC_INFOFRAME_DATA_CTRL__SIZE_1                                    8 /*       */
#define LWC871_SF_GENERIC_INFOFRAME_DATA_CTRL_OFFSET                                   4:0 /* RWIVF */
#define LWC871_SF_GENERIC_INFOFRAME_DATA_CTRL_OFFSET_INIT                       0x00000000 /* RWI-V */
#define LWC871_SF_GENERIC_INFOFRAME_DATA(i)                  (0x000E03F4-0x000E0000+(i)*1024) /* RW-4A */
#define LWC871_SF_GENERIC_INFOFRAME_DATA__SIZE_1                                          8 /*       */
#define LWC871_SF_GENERIC_INFOFRAME_DATA_BYTE0                                         7:0 /* RWIVF */
#define LWC871_SF_GENERIC_INFOFRAME_DATA_BYTE0_INIT                             0x00000000 /* RWI-V */
#define LWC871_SF_GENERIC_INFOFRAME_DATA_BYTE1                                        15:8 /* RWIVF */
#define LWC871_SF_GENERIC_INFOFRAME_DATA_BYTE1_INIT                             0x00000000 /* RWI-V */
#define LWC871_SF_GENERIC_INFOFRAME_DATA_BYTE2                                       23:16 /* RWIVF */
#define LWC871_SF_GENERIC_INFOFRAME_DATA_BYTE2_INIT                             0x00000000 /* RWI-V */
#define LWC871_SF_GENERIC_INFOFRAME_DATA_BYTE3                                       31:24 /* RWIVF */
#define LWC871_SF_GENERIC_INFOFRAME_DATA_BYTE3_INIT                             0x00000000 /* RWI-V */
#define LWC871_SF_GENERIC_INFOFRAME_MISC_CTRL(i)                  (0x000E03F8-0x000E0000+(i)*1024) /* RW-4A */
#define LWC871_SF_GENERIC_INFOFRAME_MISC_CTRL__SIZE_1                                        8 /*       */
#define LWC871_SF_GENERIC_INFOFRAME_MISC_CTRL_WIN_CHN_SEL                                  0:0 /* RWIVF */
#define LWC871_SF_GENERIC_INFOFRAME_MISC_CTRL_WIN_CHN_SEL_PRIVATE                   0x00000000 /* RWI-V */
#define LWC871_SF_GENERIC_INFOFRAME_MISC_CTRL_WIN_CHN_SEL_PUBLIC                    0x00000001 /* RW--V */
#define LWC871_SF_GENERIC_INFOFRAME_MISC_CTRL_AUDIO_PRIORITY                               1:1 /* RWIVF */
#define LWC871_SF_GENERIC_INFOFRAME_MISC_CTRL_AUDIO_PRIORITY_HIGH                   0x00000000 /* RW--V */
#define LWC871_SF_GENERIC_INFOFRAME_MISC_CTRL_AUDIO_PRIORITY_LOW                    0x00000001 /* RWI-V */

#ifdef __cplusplus
};     /* extern "C" */
#endif

#endif // _clc871_h_
