##############################################################################
# Copyright (c) 2021, LWPU CORPORATION.  All rights reserved.
#
# LWPU CORPORATION and its licensors retain all intellectual property
# and proprietary rights in and to this software, related documentation
# and any modifications thereto.  Any use, reproduction, disclosure or
# distribution of this software and related documentation without an express
# license agreement from LWPU CORPORATION is strictly prohibited.
##############################################################################

##############################################################################
# test_lwscisync_kpi makefile
##############################################################################

##############################################################################
# Identify this module to lwCommon.lwmk so it can decide the build type
##############################################################################
LW_MODULE_BUILD_TYPE_ALIASES = test_lwscisync_kpi
LW_MODULE_LOGGING_NAME = "test_lwscisync_kpi"

include $(LW_SOURCE)/drivers/common/build/lwCommon.lwmk
include $(LW_SOURCE)/drivers/common/build/lwconfig.lwmk

##############################################################################
# Path shorthands
##############################################################################
LWSCI_PATH              := $(LW_SOURCE)/drivers/lwsci
LWSCISYNC_PATH          := $(LWSCI_PATH)/lwscisync
LWSCI_TESTS_PATH        := $(LWSCI_PATH)/tests/
LWSCISYNC_TESTS_PATH  := $(LWSCI_TESTS_PATH)/lwscisync/kpi/kpi

##############################################################################
# build the appropriate LwSciSync stub libraries
##############################################################################
include $(LWSCISYNC_PATH)/lwscisync-dso-stub.lwmk
STUB_DSO_DEPENDS += $(LWSCISYNC_DSO_STUB)
STUB_LDFLAGS += -llwscisync-stub

##############################################################################
# define SOURCES
##############################################################################
LWSCISYNC_TEST_SOURCES := main.cpp

SOURCES += $(addprefix $(LWSCISYNC_TESTS_PATH)/,$(LWSCISYNC_TEST_SOURCES))

##############################################################################
# define LW_INCLUDES
##############################################################################

LW_INCLUDES += $(LWSCI_PATH)/inc/public
LW_INCLUDES += $(LWSCI_PATH)/inc/internal
LW_INCLUDES += $(LWSCI_TESTS_PATH)/common/kpi

# OS specific variants
ifneq ($(LW_TARGET_OS), QNX)
LW_INCLUDES += $(LWSCI_TESTS_PATH)/common/kpi/linux
else
LW_INCLUDES += $(LWSCI_TESTS_PATH)/common/kpi/qnx
endif

LW_INCLUDES += $(OUTPUTDIR)

##############################################################################
# define LW_DEFINES
##############################################################################
# For lwmake builds, lwcfg feature flags are available to LWSCI.
ifdef LWCFG_INITIALIZED
  LW_DEFINES += LWCFG_ENABLED
endif

# Embedded defines this on the command line for their builds.
LW_BUILD_EMBEDDED ?= 0

ifeq ($(LW_BUILD_EMBEDDED),1)
    LW_DEFINES += LW_BUILD_EMBEDDED=1
endif

LW_NEEDS_UNSTRIPPED = 1
LW_SUPPORTS_SEPARATE_DEBUG_INFO = 1

##############################################################################
# library flags
##############################################################################
LDFLAGS += -lm

ifneq ($(LW_TARGET_OS), QNX)
  LDFLAGS += -lrt
  LDFLAGS += -lstdc++
else
  LDFLAGS += -lc++
endif
LDFLAGS += -g
LDFLAGS += -L $(OUTPUTDIR) $(STUB_LDFLAGS)
LDFLAGS += $(BIN_LDFLAGS)

##############################################################################
# link the binary
##############################################################################
TESTAPP := $(OUTPUTDIR)/test_lwscisync_kpi

TESTAPP_LD_TARGET = $(TESTAPP).unstripped
TESTAPP_DEBUG_INFO = $(TESTAPP).debug
$(eval $(call LW_DEBUG_INFO_CMD, \
  $(TESTAPP_LD_TARGET), \
  $(TESTAPP), \
  $(TESTAPP_DEBUG_INFO)))

build: $(TESTAPP)

$(TESTAPP_LD_TARGET): $(OBJECTS) $(STUB_DSO_DEPENDS)
	$(call quiet_cmd,LINK) $(OBJECTS) -o $(TESTAPP_LD_TARGET) $(LDFLAGS)

##############################################################################
# include definitions of tools and build rules
##############################################################################

include $(LW_COMMON)/build/lwCommonRules.lwmk
