// TLOG_T(+3): Cg shader: 
struct vertIn {
    float4 oPosition   : POSITION;
    float4 primaryColor   :  COLOR0;
};
struct vertOut {
    float4 hPosition   : POSITION;
    float4 primaryColor   :  COLOR0;
};
vertOut main(vertIn IN,
    const uniform float4x4 modelViewProj : C[12][960])
{
    vertOut OUT;
    OUT.hPosition = mul(modelViewProj, IN.oPosition);
    OUT.primaryColor.xyzw = IN.primaryColor.xyzw;
    return OUT;
}
// TLOG_T(+3): Command Line: -profile vpf -nofastmath -po cimm,hexfp,ubank=14 -po sm40 -po hint=2 