// TLOG_T(+3): Cg shader: 
#define f2i floatToRawIntBits
#pragma option(unroll none)
    float4 R0 = 0;
uniform float4 u_const_0 : C[15][0];
varying in float4 i_ATTR0 : ATTR0;
varying out float4 o_HPOS : HPOS;
uniform float4 u_const_1 : C[15][16];
uniform float4 u_const_2 : C[15][32];
uniform float4 u_const_3 : C[15][48];
varying in float4 i_ATTR1 : ATTR1;
uniform sampler2D texUnit0 : TEXUNIT0;
varying out float4 o_COL0 : COL0;

void main()
{

    // DP4 o[HPOS].x, v[0], c[0];
    o_HPOS.x = 0;
    o_HPOS.x = (dot( i_ATTR0, u_const_0 ).xxxx).x;

    // DP4 o[HPOS].y, v[0], c[1];
    o_HPOS.y = 0;
    o_HPOS.y = (dot( i_ATTR0, u_const_1 ).xxxx).y;

    // DP4 o[HPOS].z, v[0], c[2];
    o_HPOS.z = 0;
    o_HPOS.z = (dot( i_ATTR0, u_const_2 ).xxxx).z;

    // DP4 o[HPOS].w, v[0], c[3];
    o_HPOS.w = 0;
    o_HPOS.w = (dot( i_ATTR0, u_const_3 ).xxxx).w;

    // TXL R0, v[1], TEX0, 2D;
    R0 = tex2Dlod( texUnit0, i_ATTR1 );

    // MOV o[COL0], R0;
    o_COL0 = R0;
}
// TLOG_T(+3): Command Line: -profile vpf -nofastmath -po cimm,hexfp,ubank=14 -po sm40 -po hint=2
