/* _LWRM_COPYRIGHT_BEGIN_
 *
 * Copyright 2003-2016 by LWPU Corporation.  All rights reserved.  All
 * information contained herein is proprietary and confidential to LWPU
 * Corporation.  Any use, reproduction, or disclosure without the written
 * permission of LWPU Corporation is prohibited.
 *
 * _LWRM_COPYRIGHT_END_
 */

/* This file is autogenerated by ref2h.pl.  Do not edit */


#ifndef CLASS_IDS_H_INC
#define CLASS_IDS_H_INC

#define LW_HOST1X_CLASS_ID                      0x01

#define LW_VIDEO_ENCODE_MPEG_CLASS_ID           0x20
#define LW_VIDEO_ENCODE_LWENC_CLASS_ID          0x21

#define LW_VIDEO_STREAMING_VI_CLASS_ID          0x30
#define LW_VIDEO_STREAMING_EPP_CLASS_ID         0x31
#define LW_VIDEO_STREAMING_ISP_CLASS_ID         0x32
#define LW_VIDEO_STREAMING_VCI_CLASS_ID         0x33
#define LW_VIDEO_STREAMING_ISPB_CLASS_ID        0x34
#define LW_VIDEO_STREAMING_CSI3_CLASS_ID        0x35
#define LW_VIDEO_STREAMING_VII2C_CLASS_ID       0x36
#define LW_VIDEO_STREAMING_VII2C1_CLASS_ID      0x37
#define LW_VIDEO_STREAMING_LWCSI_CLASS_ID       0x38

#define LW_GRAPHICS_2D_DOWNLOAD_CLASS_ID        0x50
#define LW_GRAPHICS_2D_CLASS_ID                 0x51
#define LW_GRAPHICS_2D_SB_CLASS_ID              0x52
#define LW_GRAPHICS_2D_DOWNLOAD_CTX1_CLASS_ID   0x54
#define LW_GRAPHICS_2D_CTX1_CLASS_ID            0x55
#define LW_GRAPHICS_2D_SB_CTX1_CLASS_ID         0x56
#define LW_GRAPHICS_2D_DOWNLOAD_CTX2_CLASS_ID   0x58
#define LW_GRAPHICS_2D_SB_CTX2_CLASS_ID         0x5A

#define LW_GRAPHICS_VIC_CLASS_ID                0x5D

#define LW_GRAPHICS_3D_CLASS_ID                 0x60
#define LW_GRAPHICS_GPU_CLASS_ID                0x61

#define LW_DISPLAY_CLASS_ID                     0x70
#define LW_LWDISPLAY_CLASS_ID                   0x70
#define LW_DISPLAYB_CLASS_ID                    0x71
#define LW_DISPLAYC_CLASS_ID                    0x72
#define LW_DISP_CLASS_ID                        0x70
#define LW_DISPB_CLASS_ID                       0x71
#define LW_DISPC_CLASS_ID                       0x72
#define LW_HDMI_CLASS_ID                        0x77
#define LW_DISPLAY_TVO_CLASS_ID                 0x78
#define LW_DISPLAY_DSI_CLASS_ID                 0x79
#define LW_DISPLAY_DSIB_CLASS_ID                0x7A
#define LW_SOR_CLASS_ID                         0x7B
#define LW_SOR1_CLASS_ID                        0x7C
#define LW_DPAUX_CLASS_ID                       0x7D
#define LW_DPAUX1_CLASS_ID                      0x7E
#define LW_DSIC_CLASS_ID                        0x7F
#define LW_DSID_CLASS_ID                        0x80
#define LW_DSI_CPHY_A_CLASS_ID                  0x81
#define LW_DSI_CPHY_B_CLASS_ID                  0x82
#define LW_DSI_PADCTL                           0x83
#define LW_DSI_PADCTL_CLASS_ID                  0x83

#define LW_LWJPG_CLASS_ID                       0xC0

#define LW_TSEC_CLASS_ID                        0xE0
#define LW_TSECB_CLASS_ID                       0xE1

#define LW_LWDEC_CLASS_ID                       0xF0
#define LW_LWDCT_CLASS_ID                       0x39
#define LW_DCTNR_CLASS_ID                       0x39

#define LW_SE1_CLASS_ID                         0x3A
#define LW_SE2_CLASS_ID                         0x3B
#define LW_SE3_CLASS_ID                         0x3C
#define LW_SE4_CLASS_ID                         0x3D
#define LW_SE5_CLASS_ID                         0x3E
#endif
