/*
 * SPDX-FileCopyrightText: Copyright (c) 2020-2021 LWPU CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: MIT
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

#pragma once

//
// This file was generated with FINN, an LWPU coding tool.
// Source file: ctrl/ctrl0080/ctrl0080internal.finn
//
#if (!defined(LWRM_UNPUBLISHED) || LWRM_UNPUBLISHED == 1)
//
// Please edit the original FINN IDL file to create desired edits in this header
// See https://confluence.lwpu.com/display/CORERM/FINN for more info on how to
// edit FINN.
//
#endif // (!defined(LWRM_UNPUBLISHED) || LWRM_UNPUBLISHED == 1)

#include "ctrl0080perf.h"
#include "ctrl0080gr.h"
#if (!defined(LWRM_PUBLISHED_PENDING_IP_REVIEW) || LWRM_PUBLISHED_PENDING_IP_REVIEW == 1)



#include "ctrl/ctrl0080/ctrl0080base.h"

/*!
 * @ref LW0080_CTRL_CMD_GR_SET_CONTEXT_OVERRIDE
 */
#define LW0080_CTRL_CMD_INTERNAL_GR_SET_CONTEXT_OVERRIDE (0x802001) /* finn: Evaluated from "(FINN_LW01_DEVICE_0_INTERNAL_INTERFACE_ID << 8) | LW0080_CTRL_CMD_INTERNAL_GR_SET_CONTEXT_OVERRIDE_FINN_PARAMS_MESSAGE_ID" */


// FINN PORT: The below type was generated by the FINN port to
// ensure that all API's have a unique structure associated
// with them!
#define LW0080_CTRL_CMD_INTERNAL_GR_SET_CONTEXT_OVERRIDE_FINN_PARAMS_MESSAGE_ID (0x1U)

typedef struct LW0080_CTRL_CMD_INTERNAL_GR_SET_CONTEXT_OVERRIDE_FINN_PARAMS {
    LW_DECLARE_ALIGNED(LW0080_CTRL_CMD_GR_SET_CONTEXT_OVERRIDE_PARAMS params, 8);
} LW0080_CTRL_CMD_INTERNAL_GR_SET_CONTEXT_OVERRIDE_FINN_PARAMS;


/*!
 * @ref LW0080_CTRL_CMD_GR_GET_TPC_PARTITION_MODE
 */
#define LW0080_CTRL_CMD_INTERNAL_GR_GET_TPC_PARTITION_MODE (0x802002) /* finn: Evaluated from "(FINN_LW01_DEVICE_0_INTERNAL_INTERFACE_ID << 8) | LW0080_CTRL_CMD_INTERNAL_GR_GET_TPC_PARTITION_MODE_FINN_PARAMS_MESSAGE_ID" */


// FINN PORT: The below type was generated by the FINN port to
// ensure that all API's have a unique structure associated
// with them!
#define LW0080_CTRL_CMD_INTERNAL_GR_GET_TPC_PARTITION_MODE_FINN_PARAMS_MESSAGE_ID (0x2U)

typedef struct LW0080_CTRL_CMD_INTERNAL_GR_GET_TPC_PARTITION_MODE_FINN_PARAMS {
    LW_DECLARE_ALIGNED(LW0080_CTRL_GR_TPC_PARTITION_MODE_PARAMS params, 8);
} LW0080_CTRL_CMD_INTERNAL_GR_GET_TPC_PARTITION_MODE_FINN_PARAMS;


/*!
 * @ref LW0080_CTRL_CMD_GR_SET_TPC_PARTITION_MODE
 */
#define LW0080_CTRL_CMD_INTERNAL_GR_SET_TPC_PARTITION_MODE (0x802003) /* finn: Evaluated from "(FINN_LW01_DEVICE_0_INTERNAL_INTERFACE_ID << 8) | LW0080_CTRL_CMD_INTERNAL_GR_SET_TPC_PARTITION_MODE_FINN_PARAMS_MESSAGE_ID" */


// FINN PORT: The below type was generated by the FINN port to
// ensure that all API's have a unique structure associated
// with them!
#define LW0080_CTRL_CMD_INTERNAL_GR_SET_TPC_PARTITION_MODE_FINN_PARAMS_MESSAGE_ID (0x3U)

typedef struct LW0080_CTRL_CMD_INTERNAL_GR_SET_TPC_PARTITION_MODE_FINN_PARAMS {
    LW_DECLARE_ALIGNED(LW0080_CTRL_GR_TPC_PARTITION_MODE_PARAMS params, 8);
} LW0080_CTRL_CMD_INTERNAL_GR_SET_TPC_PARTITION_MODE_FINN_PARAMS;


/*!
 * @ref LW0080_CTRL_CMD_PERF_LWDA_LIMIT_SET_CONTROL
 */
#define LW0080_CTRL_CMD_INTERNAL_PERF_LWDA_LIMIT_SET_CONTROL         (0x802009) /* finn: Evaluated from "(FINN_LW01_DEVICE_0_INTERNAL_INTERFACE_ID << 8) | LW0080_CTRL_PERF_LWDA_LIMIT_CONTROL_PARAMS_MESSAGE_ID" */


/*!
 *  This command disables lwca limit activation at teardown of the client.
 */
#define LW0080_CTRL_CMD_INTERNAL_PERF_LWDA_LIMIT_DISABLE             (0x802004) /* finn: Evaluated from "(FINN_LW01_DEVICE_0_INTERNAL_INTERFACE_ID << 8) | 0x4" */

/*!
 * @ref LW0080_CTRL_CMD_PERF_SLI_GPU_BOOST_SYNC_SET_CONTROL
 */
#define LW0080_CTRL_CMD_INTERNAL_PERF_SLI_GPU_BOOST_SYNC_SET_CONTROL (0x802007) /* finn: Evaluated from "(FINN_LW01_DEVICE_0_INTERNAL_INTERFACE_ID << 8) | LW0080_CTRL_PERF_SLI_GPU_BOOST_SYNC_CONTROL_PARAMS_MESSAGE_ID" */

/* !
 * @ref LW0080_CTRL_CMD_FIFO_IDLE_CHANNELS
 */
#define LW0080_CTRL_CMD_INTERNAL_FIFO_IDLE_CHANNELS                  (0x802005) /* finn: Evaluated from "(FINN_LW01_DEVICE_0_INTERNAL_INTERFACE_ID << 8) | 0x5" */

/* ctrl0080internal_h */
#endif // (!defined(LWRM_PUBLISHED_PENDING_IP_REVIEW) || LWRM_PUBLISHED_PENDING_IP_REVIEW == 1)

