##############################################################################
# drivers/lwme/makefile.lwmk
##############################################################################
LW_DISPLAY_BUILD := 1

include $(LW_SOURCE)/drivers/common/build/lwCommon.lwmk

LW_DIR_RELWRSION_ONLY := 1

SUBDIRS := lwmetf

build: $(addsuffix .build,$(SUBDIRS))

include $(LW_SOURCE)/drivers/common/build/lwCommonRules.lwmk
