#!/bin/sh

# lwwatch-config
# just run rmconfig using our config file

# bail on any error
set -e

[ -f lwwatch-config.cfg ]  ||  cd $P4ROOT/sw/dev/gpu_drv/chips_a/apps/lwwatch/config

[ -f lwwatch-config.cfg ]  ||  { echo Cannot find lwwatch-config.cfg >&2; exit 1; }


# NOTE: '--mode lwwatch-config' must be the first argument to rmconfig
exec ${PERL:-perl} $P4ROOT/sw/dev/gpu_drv/chips_a/drivers/common/chip-config/chip-config.pl --mode lwwatch-config --config lwwatch-config.cfg --source-root $P4ROOT/sw/dev/gpu_drv/chips_a/apps/lwwatch  "$@"
