require 'lwtorch'
require 'nn'
ccn2 = {}
include 'ffi.lua'
include 'utils.lua'
include 'Jacobian.lua'

include 'SpatialColwolution.lua'
include 'SpatialColwolutionLocal.lua'
include 'SpatialMaxPooling.lua'
include 'SpatialAvgPooling.lua'
include 'SpatialResizeBilinear.lua'
include 'SpatialCrossMaxPooling.lua'
include 'SpatialContrastNormalization.lua'
include 'SpatialCrossResponseNormalization.lua'
include 'SpatialResponseNormalization.lua'
