#pragma once

//
// This file was generated with FINN, an LWPU coding tool.
//
#if (!defined(LWRM_UNPUBLISHED) || LWRM_UNPUBLISHED == 1)
//
// Please edit the original FINN IDL file to create desired edits in this header
// See https://confluence.lwpu.com/display/CORERM/FINN for more info on how to
// edit FINN.
//
#endif // (!defined(LWRM_UNPUBLISHED) || LWRM_UNPUBLISHED == 1)


#include <lwtypes.h>
#if defined(_MSC_VER)
#pragma warning(disable:4324)
#endif


#include <lwstatus.h>

#define FINN_INTERFACE_ID(T) (T ## _INTERFACE_ID)
#define FINN_MESSAGE_ID(T) (T ## _MESSAGE_ID)

#if (defined(__cplusplus) && __cplusplus >= 201103L) || (defined(_MSVC_LANG) && _MSVC_LANG >= 201103L)
#define FINN_OFFSETOF(T,f) (offsetof(T, f))
#else
#define FINN_OFFSETOF(T,f) ((LwU64)&((T*)0)->f)
#endif

#if !defined(_MSC_VER) && (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 201112L) && !defined(__arm)
#define FINN_PACK_COMPOSITE(b) b __attribute__ ((packed))
#else
#define FINN_PACK_COMPOSITE(b) b
#endif

/*
 * FINN serialization version. A version mismatch indicates incompatibility
 * between the serializer and the deserializer.
 *
 * WARNING: Current serialization version is 0. This is a pre-release version of
 * serialization and is only intended to be used in a driver and client compiled
 * together. DO NOT use this in firmware or versioned clients.
 */
#define FINN_SERIALIZATION_VERSION 0

/*
 * FINN compiler version
 */
#define FINN_VERSION_MAJOR 1
#define FINN_VERSION_MINOR 10
#define FINN_VERSION_PATCH 0

typedef struct FINN_RM_API
{
      LW_DECLARE_ALIGNED(LwU64 fieldmask, 8);
      LW_DECLARE_ALIGNED(LwU64 payloadSize, 8);
      LwU32 message;
      LwU32 interface_id;
      LwU8 payload[1];
} FINN_RM_API;

/*!
 * @brief Serializes an RM API control params struct and copies it into the
 *        serialization buffer as a FINN message.
 *
 * @note  FinnRmApiSerializeDown is for serializing down the call stack.
 *
 *        FinnRmApiSerializeUp is for serializing up the call stack.  It
 *        frees memory allocated by FinnRmApiDeserializeDown.  Use only
 *        when handling RM API control requests.
 *
 * @warning One of these may be unimplemented depending on platform. If both
 *          are implemented, misuse causes memory corruption and memory leaks.
 *
 * @param[in]      interface  FINN interface ID of the param struct.
 * @param[in]      message    FINN message ID of the param struct.
 * @param[in]      src        Pointer to the source param struct from which to
 *                            copy the data.
 * @param[in, out] dst        Double pointer to the destination buffer into
 *                            which to copy the data. *dst will be set to
 *                            *dst + serialized size on success and to the
 *                            location of failed serialization on failure.
 * @param[in]      dst_size   Maximum size of the destination buffer measured in
 *                            `LwU8` units.
 *
 * @retval LW_OK                    Serialization successful.
 * @retval LW_ERR_ILWALID_ARGUMENT  Bad function arguments, invalid union
 *                                  selector, or invalid enum value.
 * @retval LW_ERR_NOT_SUPPORTED     Unserializable or nonexistent ID.
 * @retval LW_ERR_NOT_COMPATIBLE     Container count too large.
 * @retval LW_ERR_OUT_OF_RANGE      Ranged field exceeded bounds.
 * @retval LW_ERR_BUFFER_TOO_SMALL  Destination buffer size too small.
 */
/**@{*/
LW_STATUS FinnRmApiSerializeUp(LwU64 interface, LwU64 message, const void *src, LwU8 **dst, LwLength dst_size);
LW_STATUS FinnRmApiSerializeDown(LwU64 interface, LwU64 message, const void *src, LwU8 **dst, LwLength dst_size);
/**@}*/

/*!
 * @brief The following APIs deserialize a FINN message from the serialization
 *        buffer and copy it into an RM API control params struct.
 *
 * @note  FinnRmApiDeserializeDown is for deserializing down the call stack. It
 *        allocates deep buffers for primitive pointers in the serialization
 *        buffer, assuming that it remains in memory. Use only when handling
 *        RM API control requests.
 *
 *        FinnRmApiDeserializeUp is for deserializing up the call stack. It
 *        copies deep buffers of primitive pointers into the params struct,
 *        assuming that memory is already allocated for them. Use only when
 *        receiving RM API control results.
 *
 * @warning One of these may be unimplemented depending on platform. If both
 *          are implemented, misuse causes memory corruption and memory leaks.
 *
 * @param[in, out] src        Double pointer to the source buffer from which to
 *                            copy the data. *src is set to *src + serialized
 *                            size on success and to the location of failed
 *                            deserialization on failure.
 * @param[in]      src_size   Maximum size of the source buffer measured in
 *                            `LwU8` units.
 * @param[in, out] dst        Pointer to the destination param struct into which
 *                            to copy the data.
 * @param[in]      dst_size   Size of the destination param struct measured in
 *                            `char` units per `sizeof` operator.
 *
 * @retval LW_OK                          Deserialization successful.
 * @retval LW_ERR_ILWALID_ARGUMENT        Bad function arguments, invalid union
 *                                        selector, invalid enum value, or
 *                                        mismatch between expected and actual
 *                                        serialized size.
 * @retval LW_ERR_NOT_SUPPORTED           Unserializable or nonexistent ID.
 * @retval LW_ERR_OUT_OF_RANGE            Ranged field exceeded bounds.
 * @retval LW_ERR_BUFFER_TOO_SMALL        Source/destination buffer too small.
 * @retval LW_ERR_LIB_RM_VERSION_MISMATCH Version mismatch.
 */
/**@{*/
LW_STATUS FinnRmApiDeserializeDown(LwU8 **src, LwLength src_size, void *dst, LwLength dst_size);
LW_STATUS FinnRmApiDeserializeUp(LwU8 * const *src, LwLength src_size, void *dst, LwLength dst_size);
/**@}*/

/*!
 * @brief Callwlates the serialized size of an RM API param struct.
 *
 * @param[in]       interface   FINN interface ID of the param struct.
 * @param[in]       message     FINN message ID of the param struct.
 * @param[in]       src         Pointer to the param struct.
 *
 * @retval          Non-zero serialized size of param struct on success.
 * @retval          0 if the API is unsupported by serialization or src is NULL.
 */
LwU64 FinnRmApiGetSerializedSize(LwU64 interface, LwU64 message, const LwP64 src);

/*!
 * @brief Fetches the unserialized size of an API param struct.
 *
 * @note The size is measured in `char` units like the `sizeof` operator.
 *
 * @param[in]       interface   FINN interface ID of the param struct.
 * @param[in]       message     FINN message ID of the param struct.
 *
 * @retval          Non-zero sizeof param struct on success.
 * @retval          0 if the API is unsupported by serialization.
 */
LwU64 FinnRmApiGetUnserializedSize(LwU64 interface, LwU64 message);



#define FINN_LW01_ROOT_RESERVED_INTERFACE_ID (0x0U)
typedef FINN_RM_API FINN_LW01_ROOT_RESERVED;


#define FINN_LW01_ROOT_CLIENT_INTERFACE_ID (0xdU)
typedef FINN_RM_API FINN_LW01_ROOT_CLIENT;


#if (!defined(LWRM_PUBLISHED_PENDING_IP_REVIEW) || LWRM_PUBLISHED_PENDING_IP_REVIEW == 1)
#define FINN_LW01_ROOT_DIAG_INTERFACE_ID (0x4U)
typedef FINN_RM_API FINN_LW01_ROOT_DIAG;
#endif // (!defined(LWRM_PUBLISHED_PENDING_IP_REVIEW) || LWRM_PUBLISHED_PENDING_IP_REVIEW == 1)



#define FINN_LW01_ROOT_EVENT_INTERFACE_ID (0x5U)
typedef FINN_RM_API FINN_LW01_ROOT_EVENT;


#define FINN_LW01_ROOT_GPU_INTERFACE_ID (0x2U)
typedef FINN_RM_API FINN_LW01_ROOT_GPU;


#if (!defined(LWRM_PUBLISHED_PENDING_IP_REVIEW) || LWRM_PUBLISHED_PENDING_IP_REVIEW == 1)
#define FINN_LW01_ROOT_GPUACCT_INTERFACE_ID (0xbU)
typedef FINN_RM_API FINN_LW01_ROOT_GPUACCT;
#endif // (!defined(LWRM_PUBLISHED_PENDING_IP_REVIEW) || LWRM_PUBLISHED_PENDING_IP_REVIEW == 1)



#if (!defined(LWRM_UNPUBLISHED) || LWRM_UNPUBLISHED == 1)
#define FINN_LW01_ROOT_GSPC_INTERFACE_ID (0x8U)
typedef FINN_RM_API FINN_LW01_ROOT_GSPC;
#endif // (!defined(LWRM_UNPUBLISHED) || LWRM_UNPUBLISHED == 1)



#define FINN_LW01_ROOT_GSYNC_INTERFACE_ID (0x3U)
typedef FINN_RM_API FINN_LW01_ROOT_GSYNC;


#if (!defined(LWRM_PUBLISHED_PENDING_IP_REVIEW) || LWRM_PUBLISHED_PENDING_IP_REVIEW == 1)
#define FINN_LW01_ROOT_LWD_INTERFACE_ID (0x6U)
typedef FINN_RM_API FINN_LW01_ROOT_LWD;
#endif // (!defined(LWRM_PUBLISHED_PENDING_IP_REVIEW) || LWRM_PUBLISHED_PENDING_IP_REVIEW == 1)



#define FINN_LW01_ROOT_PROC_INTERFACE_ID (0x9U)
typedef FINN_RM_API FINN_LW01_ROOT_PROC;


#if (!defined(LWRM_PUBLISHED_PENDING_IP_REVIEW) || LWRM_PUBLISHED_PENDING_IP_REVIEW == 1)
#define FINN_LW01_ROOT_SWINSTR_INTERFACE_ID (0x7U)
typedef FINN_RM_API FINN_LW01_ROOT_SWINSTR;
#endif // (!defined(LWRM_PUBLISHED_PENDING_IP_REVIEW) || LWRM_PUBLISHED_PENDING_IP_REVIEW == 1)



#if (!defined(LWRM_PUBLISHED_PENDING_IP_REVIEW) || LWRM_PUBLISHED_PENDING_IP_REVIEW == 1)
#define FINN_LW01_ROOT_SYNC_GPU_BOOST_INTERFACE_ID (0xaU)
typedef FINN_RM_API FINN_LW01_ROOT_SYNC_GPU_BOOST;
#endif // (!defined(LWRM_PUBLISHED_PENDING_IP_REVIEW) || LWRM_PUBLISHED_PENDING_IP_REVIEW == 1)



#define FINN_LW01_ROOT_SYSTEM_INTERFACE_ID (0x1U)
typedef FINN_RM_API FINN_LW01_ROOT_SYSTEM;


#define FINN_LW01_ROOT_OS_UNIX_INTERFACE_ID (0x3dU)
typedef FINN_RM_API FINN_LW01_ROOT_OS_UNIX;


#if (!defined(LWRM_UNPUBLISHED) || LWRM_UNPUBLISHED == 1)
#define FINN_LW01_ROOT_VGPU_INTERFACE_ID (0xlw)
typedef FINN_RM_API FINN_LW01_ROOT_VGPU;
#endif // (!defined(LWRM_UNPUBLISHED) || LWRM_UNPUBLISHED == 1)



#define FINN_LW01_ROOT_OS_WINDOWS_INTERFACE_ID (0x3fU)
typedef FINN_RM_API FINN_LW01_ROOT_OS_WINDOWS;


#define FINN_LW01_CONTEXT_DMA_RESERVED_INTERFACE_ID (0x200U)
typedef FINN_RM_API FINN_LW01_CONTEXT_DMA_RESERVED;
#define FINN_LW01_CONTEXT_DMA_DMA_INTERFACE_ID (0x201U)
typedef FINN_RM_API FINN_LW01_CONTEXT_DMA_DMA;


#define FINN_LW01_TIMER_RESERVED_INTERFACE_ID (0x400U)
typedef FINN_RM_API FINN_LW01_TIMER_RESERVED;
#define FINN_LW01_TIMER_TMR_INTERFACE_ID (0x401U)
typedef FINN_RM_API FINN_LW01_TIMER_TMR;


#define FINN_FABRIC_MANAGER_SESSION_RESERVED_INTERFACE_ID (0xf00U)
typedef FINN_RM_API FINN_FABRIC_MANAGER_SESSION_RESERVED;
#define FINN_FABRIC_MANAGER_SESSION_FM_INTERFACE_ID (0xf01U)
typedef FINN_RM_API FINN_FABRIC_MANAGER_SESSION_FM;


#define FINN_FABRIC_MANAGER_SESSION_IMEX_INTERFACE_ID (0xf02U)
typedef FINN_RM_API FINN_FABRIC_MANAGER_SESSION_IMEX;


#define FINN_LW0020_GPU_MANAGEMENT_RESERVED_INTERFACE_ID (0x2000U)
typedef FINN_RM_API FINN_LW0020_GPU_MANAGEMENT_RESERVED;
#define FINN_LW0020_GPU_MANAGEMENT_GPU_MGMT_INTERFACE_ID (0x2001U)
typedef FINN_RM_API FINN_LW0020_GPU_MANAGEMENT_GPU_MGMT;


#define FINN_LW01_MEMORY_SYSTEM_RESERVED_INTERFACE_ID (0x3e00U)
typedef FINN_RM_API FINN_LW01_MEMORY_SYSTEM_RESERVED;
#define FINN_LW01_MEMORY_SYSTEM_MEMORY_INTERFACE_ID (0x3e01U)
typedef FINN_RM_API FINN_LW01_MEMORY_SYSTEM_MEMORY;


#define FINN_LW01_ROOT_USER_RESERVED_INTERFACE_ID (0x4100U)
typedef FINN_RM_API FINN_LW01_ROOT_USER_RESERVED;
#define FINN_LW01_ROOT_USER_MEMORY_INTERFACE_ID (0x4101U)
typedef FINN_RM_API FINN_LW01_ROOT_USER_MEMORY;


#define FINN_LW04_DISPLAY_COMMON_RESERVED_INTERFACE_ID (0x7300U)
typedef FINN_RM_API FINN_LW04_DISPLAY_COMMON_RESERVED;


#define FINN_LW04_DISPLAY_COMMON_DFP_INTERFACE_ID (0x7311U)
typedef FINN_RM_API FINN_LW04_DISPLAY_COMMON_DFP;


#define FINN_LW04_DISPLAY_COMMON_DP_INTERFACE_ID (0x7313U)
typedef FINN_RM_API FINN_LW04_DISPLAY_COMMON_DP;


#if (!defined(LWRM_UNPUBLISHED) || LWRM_UNPUBLISHED == 1)
#define FINN_LW04_DISPLAY_COMMON_DPU_INTERFACE_ID (0x7315U)
typedef FINN_RM_API FINN_LW04_DISPLAY_COMMON_DPU;
#endif // (!defined(LWRM_UNPUBLISHED) || LWRM_UNPUBLISHED == 1)



#define FINN_LW04_DISPLAY_COMMON_EVENT_INTERFACE_ID (0x7303U)
typedef FINN_RM_API FINN_LW04_DISPLAY_COMMON_EVENT;


#define FINN_LW04_DISPLAY_COMMON_INTERNAL_INTERFACE_ID (0x7304U)
typedef FINN_RM_API FINN_LW04_DISPLAY_COMMON_INTERNAL;


#if (!defined(LWRM_PUBLISHED_PENDING_IP_REVIEW) || LWRM_PUBLISHED_PENDING_IP_REVIEW == 1)
#define FINN_LW04_DISPLAY_COMMON_PSR_INTERFACE_ID (0x7316U)
typedef FINN_RM_API FINN_LW04_DISPLAY_COMMON_PSR;
#endif // (!defined(LWRM_PUBLISHED_PENDING_IP_REVIEW) || LWRM_PUBLISHED_PENDING_IP_REVIEW == 1)



#define FINN_LW04_DISPLAY_COMMON_SPECIFIC_INTERFACE_ID (0x7302U)
typedef FINN_RM_API FINN_LW04_DISPLAY_COMMON_SPECIFIC;


#define FINN_LW04_DISPLAY_COMMON_STEREO_INTERFACE_ID (0x7317U)
typedef FINN_RM_API FINN_LW04_DISPLAY_COMMON_STEREO;


#if (!defined(LWRM_UNPUBLISHED) || LWRM_UNPUBLISHED == 1)
#define FINN_LW04_DISPLAY_COMMON_SVP_INTERFACE_ID (0x7314U)
typedef FINN_RM_API FINN_LW04_DISPLAY_COMMON_SVP;
#endif // (!defined(LWRM_UNPUBLISHED) || LWRM_UNPUBLISHED == 1)



#define FINN_LW04_DISPLAY_COMMON_SYSTEM_INTERFACE_ID (0x7301U)
typedef FINN_RM_API FINN_LW04_DISPLAY_COMMON_SYSTEM;


#define FINN_LW01_DEVICE_0_RESERVED_INTERFACE_ID (0x8000U)
typedef FINN_RM_API FINN_LW01_DEVICE_0_RESERVED;


#if (!defined(LWRM_PUBLISHED_PENDING_IP_REVIEW) || LWRM_PUBLISHED_PENDING_IP_REVIEW == 1)
#define FINN_LW01_DEVICE_0_BIF_INTERFACE_ID (0x8001U)
typedef FINN_RM_API FINN_LW01_DEVICE_0_BIF;
#endif // (!defined(LWRM_PUBLISHED_PENDING_IP_REVIEW) || LWRM_PUBLISHED_PENDING_IP_REVIEW == 1)



#if (!defined(LWRM_PUBLISHED_PENDING_IP_REVIEW) || LWRM_PUBLISHED_PENDING_IP_REVIEW == 1)
#define FINN_LW01_DEVICE_0_BSP_INTERFACE_ID (0x801lw)
typedef FINN_RM_API FINN_LW01_DEVICE_0_BSP;
#endif // (!defined(LWRM_PUBLISHED_PENDING_IP_REVIEW) || LWRM_PUBLISHED_PENDING_IP_REVIEW == 1)



#if (!defined(LWRM_UNPUBLISHED) || LWRM_UNPUBLISHED == 1)
#define FINN_LW01_DEVICE_0_CIPHER_INTERFACE_ID (0x8012U)
typedef FINN_RM_API FINN_LW01_DEVICE_0_CIPHER;
#endif // (!defined(LWRM_UNPUBLISHED) || LWRM_UNPUBLISHED == 1)



#if (!defined(LWRM_PUBLISHED_PENDING_IP_REVIEW) || LWRM_PUBLISHED_PENDING_IP_REVIEW == 1)
#define FINN_LW01_DEVICE_0_CLK_INTERFACE_ID (0x8010U)
typedef FINN_RM_API FINN_LW01_DEVICE_0_CLK;
#endif // (!defined(LWRM_PUBLISHED_PENDING_IP_REVIEW) || LWRM_PUBLISHED_PENDING_IP_REVIEW == 1)



#define FINN_LW01_DEVICE_0_DMA_INTERFACE_ID (0x8018U)
typedef FINN_RM_API FINN_LW01_DEVICE_0_DMA;


#if (!defined(LWRM_PUBLISHED_PENDING_IP_REVIEW) || LWRM_PUBLISHED_PENDING_IP_REVIEW == 1)
#define FINN_LW01_DEVICE_0_FB_INTERFACE_ID (0x8013U)
typedef FINN_RM_API FINN_LW01_DEVICE_0_FB;
#endif // (!defined(LWRM_PUBLISHED_PENDING_IP_REVIEW) || LWRM_PUBLISHED_PENDING_IP_REVIEW == 1)



#if (!defined(LWRM_PUBLISHED_PENDING_IP_REVIEW) || LWRM_PUBLISHED_PENDING_IP_REVIEW == 1)
#define FINN_LW01_DEVICE_0_FIFO_INTERFACE_ID (0x8017U)
typedef FINN_RM_API FINN_LW01_DEVICE_0_FIFO;
#endif // (!defined(LWRM_PUBLISHED_PENDING_IP_REVIEW) || LWRM_PUBLISHED_PENDING_IP_REVIEW == 1)



#define FINN_LW01_DEVICE_0_GPU_INTERFACE_ID (0x8002U)
typedef FINN_RM_API FINN_LW01_DEVICE_0_GPU;


#define FINN_LW01_DEVICE_0_GR_INTERFACE_ID (0x8011U)
typedef FINN_RM_API FINN_LW01_DEVICE_0_GR;


#if (!defined(LWRM_PUBLISHED_PENDING_IP_REVIEW) || LWRM_PUBLISHED_PENDING_IP_REVIEW == 1)
#define FINN_LW01_DEVICE_0_HOST_INTERFACE_ID (0x8014U)
typedef FINN_RM_API FINN_LW01_DEVICE_0_HOST;
#endif // (!defined(LWRM_PUBLISHED_PENDING_IP_REVIEW) || LWRM_PUBLISHED_PENDING_IP_REVIEW == 1)



#if (!defined(LWRM_PUBLISHED_PENDING_IP_REVIEW) || LWRM_PUBLISHED_PENDING_IP_REVIEW == 1)
#define FINN_LW01_DEVICE_0_INTERNAL_INTERFACE_ID (0x8020U)
typedef FINN_RM_API FINN_LW01_DEVICE_0_INTERNAL;
#endif // (!defined(LWRM_PUBLISHED_PENDING_IP_REVIEW) || LWRM_PUBLISHED_PENDING_IP_REVIEW == 1)



#if (!defined(LWRM_PUBLISHED_PENDING_IP_REVIEW) || LWRM_PUBLISHED_PENDING_IP_REVIEW == 1)
#define FINN_LW01_DEVICE_0_MSENC_INTERFACE_ID (0x801bU)
typedef FINN_RM_API FINN_LW01_DEVICE_0_MSENC;
#endif // (!defined(LWRM_PUBLISHED_PENDING_IP_REVIEW) || LWRM_PUBLISHED_PENDING_IP_REVIEW == 1)



#if (!defined(LWRM_PUBLISHED_PENDING_IP_REVIEW) || LWRM_PUBLISHED_PENDING_IP_REVIEW == 1)
#define FINN_LW01_DEVICE_0_LWJPG_INTERFACE_ID (0x801fU)
typedef FINN_RM_API FINN_LW01_DEVICE_0_LWJPG;
#endif // (!defined(LWRM_PUBLISHED_PENDING_IP_REVIEW) || LWRM_PUBLISHED_PENDING_IP_REVIEW == 1)



#if (!defined(LWRM_PUBLISHED_PENDING_IP_REVIEW) || LWRM_PUBLISHED_PENDING_IP_REVIEW == 1)
#define FINN_LW01_DEVICE_0_PERF_INTERFACE_ID (0x8019U)
typedef FINN_RM_API FINN_LW01_DEVICE_0_PERF;
#endif // (!defined(LWRM_PUBLISHED_PENDING_IP_REVIEW) || LWRM_PUBLISHED_PENDING_IP_REVIEW == 1)



#if (!defined(LWRM_UNPUBLISHED) || LWRM_UNPUBLISHED == 1)
#define FINN_LW01_DEVICE_0_RC_INTERFACE_ID (0x801dU)
typedef FINN_RM_API FINN_LW01_DEVICE_0_RC;
#endif // (!defined(LWRM_UNPUBLISHED) || LWRM_UNPUBLISHED == 1)



#define FINN_LW01_DEVICE_0_OS_UNIX_INTERFACE_ID (0x801eU)
typedef FINN_RM_API FINN_LW01_DEVICE_0_OS_UNIX;


#if (!defined(LWRM_UNPUBLISHED) || LWRM_UNPUBLISHED == 1)
#define FINN_LW01_DEVICE_0_VIDEO_INTERFACE_ID (0x8015U)
typedef FINN_RM_API FINN_LW01_DEVICE_0_VIDEO;
#endif // (!defined(LWRM_UNPUBLISHED) || LWRM_UNPUBLISHED == 1)



#define FINN_LW0090_KERNEL_GRAPHICS_CONTEXT_INTERFACE_ID (0x9001U)
typedef FINN_RM_API FINN_LW0090_KERNEL_GRAPHICS_CONTEXT;


#define FINN_LW01_MEMORY_FABRIC_EXPORT_RESERVED_INTERFACE_ID (0xf400U)
typedef FINN_RM_API FINN_LW01_MEMORY_FABRIC_EXPORT_RESERVED;
#define FINN_LW01_MEMORY_FABRIC_EXPORT_EXPORT_INTERFACE_ID (0xf401U)
typedef FINN_RM_API FINN_LW01_MEMORY_FABRIC_EXPORT_EXPORT;


#define FINN_LW01_MEMORY_FABRIC_IMPORT_RESERVED_INTERFACE_ID (0xf500U)
typedef FINN_RM_API FINN_LW01_MEMORY_FABRIC_IMPORT_RESERVED;
#define FINN_LW01_MEMORY_FABRIC_IMPORT_IMPORT_INTERFACE_ID (0xf501U)
typedef FINN_RM_API FINN_LW01_MEMORY_FABRIC_IMPORT_IMPORT;


#define FINN_LW_MEMORY_FABRIC_RESERVED_INTERFACE_ID (0xf800U)
typedef FINN_RM_API FINN_LW_MEMORY_FABRIC_RESERVED;
#define FINN_LW_MEMORY_FABRIC_FABRIC_INTERFACE_ID (0xf801U)
typedef FINN_RM_API FINN_LW_MEMORY_FABRIC_FABRIC;


#define FINN_LW_MEMORY_FABRIC_IMPORT_V2_RESERVED_INTERFACE_ID (0xf900U)
typedef FINN_RM_API FINN_LW_MEMORY_FABRIC_IMPORT_V2_RESERVED;
#define FINN_LW_MEMORY_FABRIC_IMPORT_V2_IMPORT_INTERFACE_ID (0xf901U)
typedef FINN_RM_API FINN_LW_MEMORY_FABRIC_IMPORT_V2_IMPORT;


#define FINN_LW_MEMORY_FABRIC_EXPORTED_REF_RESERVED_INTERFACE_ID (0xfa00U)
typedef FINN_RM_API FINN_LW_MEMORY_FABRIC_EXPORTED_REF_RESERVED;
#define FINN_LW_MEMORY_FABRIC_EXPORTED_REF_EXPORT_REF_INTERFACE_ID (0xfa01U)
typedef FINN_RM_API FINN_LW_MEMORY_FABRIC_EXPORTED_REF_EXPORT_REF;


#define FINN_LW_MEMORY_FABRIC_IMPORTED_REF_RESERVED_INTERFACE_ID (0xfb00U)
typedef FINN_RM_API FINN_LW_MEMORY_FABRIC_IMPORTED_REF_RESERVED;
#define FINN_LW_MEMORY_FABRIC_IMPORTED_REF_IMPORT_REF_INTERFACE_ID (0xfb01U)
typedef FINN_RM_API FINN_LW_MEMORY_FABRIC_IMPORTED_REF_IMPORT_REF;


#define FINN_LW_MEMORY_MULTICAST_FABRIC_RESERVED_INTERFACE_ID (0xfd00U)
typedef FINN_RM_API FINN_LW_MEMORY_MULTICAST_FABRIC_RESERVED;
#define FINN_LW_MEMORY_MULTICAST_FABRIC_FABRIC_INTERFACE_ID (0xfd01U)
typedef FINN_RM_API FINN_LW_MEMORY_MULTICAST_FABRIC_FABRIC;


#if (!defined(LWRM_UNPUBLISHED) || LWRM_UNPUBLISHED == 1)
#define FINN_LW20_SUBDEVICE_0_ACR_INTERFACE_ID (0x208029U)
typedef FINN_RM_API FINN_LW20_SUBDEVICE_0_ACR;
#endif // (!defined(LWRM_UNPUBLISHED) || LWRM_UNPUBLISHED == 1)



#define FINN_LW20_SUBDEVICE_0_RESERVED_INTERFACE_ID (0x208000U)
typedef FINN_RM_API FINN_LW20_SUBDEVICE_0_RESERVED;


#if (!defined(LWRM_PUBLISHED_PENDING_IP_REVIEW) || LWRM_PUBLISHED_PENDING_IP_REVIEW == 1)
#define FINN_LW20_SUBDEVICE_0_BIOS_INTERFACE_ID (0x208008U)
typedef FINN_RM_API FINN_LW20_SUBDEVICE_0_BIOS;
#endif // (!defined(LWRM_PUBLISHED_PENDING_IP_REVIEW) || LWRM_PUBLISHED_PENDING_IP_REVIEW == 1)



#define FINN_LW20_SUBDEVICE_0_BUS_INTERFACE_ID (0x208018U)
typedef FINN_RM_API FINN_LW20_SUBDEVICE_0_BUS;


#if (!defined(LWRM_PUBLISHED_PENDING_IP_REVIEW) || LWRM_PUBLISHED_PENDING_IP_REVIEW == 1)
#define FINN_LW20_SUBDEVICE_0_CE_INTERFACE_ID (0x20802aU)
typedef FINN_RM_API FINN_LW20_SUBDEVICE_0_CE;
#endif // (!defined(LWRM_PUBLISHED_PENDING_IP_REVIEW) || LWRM_PUBLISHED_PENDING_IP_REVIEW == 1)



#if (!defined(LWRM_UNPUBLISHED) || LWRM_UNPUBLISHED == 1)
#define FINN_LW20_SUBDEVICE_0_CIPHER_INTERFACE_ID (0x208009U)
typedef FINN_RM_API FINN_LW20_SUBDEVICE_0_CIPHER;
#endif // (!defined(LWRM_UNPUBLISHED) || LWRM_UNPUBLISHED == 1)



#if (!defined(LWRM_PUBLISHED_PENDING_IP_REVIEW) || LWRM_PUBLISHED_PENDING_IP_REVIEW == 1)
#endif // (!defined(LWRM_PUBLISHED_PENDING_IP_REVIEW) || LWRM_PUBLISHED_PENDING_IP_REVIEW == 1)



#if (!defined(LWRM_PUBLISHED_PENDING_IP_REVIEW) || LWRM_PUBLISHED_PENDING_IP_REVIEW == 1)
#define FINN_LW20_SUBDEVICE_0_CLK_INTERFACE_ID (0x208010U)
typedef FINN_RM_API FINN_LW20_SUBDEVICE_0_CLK;
#endif // (!defined(LWRM_PUBLISHED_PENDING_IP_REVIEW) || LWRM_PUBLISHED_PENDING_IP_REVIEW == 1)


#if (!defined(LWRM_UNPUBLISHED_OPAQUE) || LWRM_UNPUBLISHED_OPAQUE == 1)
#endif // (!defined(LWRM_UNPUBLISHED_OPAQUE) || LWRM_UNPUBLISHED_OPAQUE == 1)


#if (!defined(LWRM_UNPUBLISHED_OPAQUE) || LWRM_UNPUBLISHED_OPAQUE == 1)
#define FINN_LW20_SUBDEVICE_0_CLK_LEGACY_NON_PRIVILEGED_INTERFACE_ID (0x208090U)
typedef FINN_RM_API FINN_LW20_SUBDEVICE_0_CLK_LEGACY_NON_PRIVILEGED;
#endif // (!defined(LWRM_UNPUBLISHED_OPAQUE) || LWRM_UNPUBLISHED_OPAQUE == 1)


#if (!defined(LWRM_UNPUBLISHED_OPAQUE) || LWRM_UNPUBLISHED_OPAQUE == 1)
#endif // (!defined(LWRM_UNPUBLISHED_OPAQUE) || LWRM_UNPUBLISHED_OPAQUE == 1)


#if (!defined(LWRM_UNPUBLISHED_OPAQUE) || LWRM_UNPUBLISHED_OPAQUE == 1)
#define FINN_LW20_SUBDEVICE_0_CLK_LEGACY_PRIVILEGED_INTERFACE_ID (0x2080D0U)
typedef FINN_RM_API FINN_LW20_SUBDEVICE_0_CLK_LEGACY_PRIVILEGED;
#endif // (!defined(LWRM_UNPUBLISHED_OPAQUE) || LWRM_UNPUBLISHED_OPAQUE == 1)



#if (!defined(LWRM_PUBLISHED_PENDING_IP_REVIEW) || LWRM_PUBLISHED_PENDING_IP_REVIEW == 1)
#define FINN_LW20_SUBDEVICE_0_DMA_INTERFACE_ID (0x208025U)
typedef FINN_RM_API FINN_LW20_SUBDEVICE_0_DMA;
#endif // (!defined(LWRM_PUBLISHED_PENDING_IP_REVIEW) || LWRM_PUBLISHED_PENDING_IP_REVIEW == 1)



#if (!defined(LWRM_UNPUBLISHED) || LWRM_UNPUBLISHED == 1)
#define FINN_LW20_SUBDEVICE_0_DMABUF_INTERFACE_ID (0x20803AU)
typedef FINN_RM_API FINN_LW20_SUBDEVICE_0_DMABUF;
#endif // (!defined(LWRM_UNPUBLISHED) || LWRM_UNPUBLISHED == 1)



#define FINN_LW20_SUBDEVICE_0_ECC_INTERFACE_ID (0x208034U)
typedef FINN_RM_API FINN_LW20_SUBDEVICE_0_ECC;


#define FINN_LW20_SUBDEVICE_0_EVENT_INTERFACE_ID (0x208003U)
typedef FINN_RM_API FINN_LW20_SUBDEVICE_0_EVENT;


#if (!defined(LWRM_PUBLISHED_PENDING_IP_REVIEW) || LWRM_PUBLISHED_PENDING_IP_REVIEW == 1)
#define FINN_LW20_SUBDEVICE_0_FB_INTERFACE_ID (0x208013U)
typedef FINN_RM_API FINN_LW20_SUBDEVICE_0_FB;
#endif // (!defined(LWRM_PUBLISHED_PENDING_IP_REVIEW) || LWRM_PUBLISHED_PENDING_IP_REVIEW == 1)



#if (!defined(LWRM_PUBLISHED_PENDING_IP_REVIEW) || LWRM_PUBLISHED_PENDING_IP_REVIEW == 1)
#define FINN_LW20_SUBDEVICE_0_FIFO_INTERFACE_ID (0x208011U)
typedef FINN_RM_API FINN_LW20_SUBDEVICE_0_FIFO;
#endif // (!defined(LWRM_PUBLISHED_PENDING_IP_REVIEW) || LWRM_PUBLISHED_PENDING_IP_REVIEW == 1)



#if (!defined(LWRM_PUBLISHED_PENDING_IP_REVIEW) || LWRM_PUBLISHED_PENDING_IP_REVIEW == 1)
#define FINN_LW20_SUBDEVICE_0_FLA_INTERFACE_ID (0x208035U)
typedef FINN_RM_API FINN_LW20_SUBDEVICE_0_FLA;
#endif // (!defined(LWRM_PUBLISHED_PENDING_IP_REVIEW) || LWRM_PUBLISHED_PENDING_IP_REVIEW == 1)



#if (!defined(LWRM_PUBLISHED_PENDING_IP_REVIEW) || LWRM_PUBLISHED_PENDING_IP_REVIEW == 1)
#define FINN_LW20_SUBDEVICE_0_FLCN_INTERFACE_ID (0x208031U)
typedef FINN_RM_API FINN_LW20_SUBDEVICE_0_FLCN;
#endif // (!defined(LWRM_PUBLISHED_PENDING_IP_REVIEW) || LWRM_PUBLISHED_PENDING_IP_REVIEW == 1)



#if (!defined(LWRM_UNPUBLISHED) || LWRM_UNPUBLISHED == 1)
#define FINN_LW20_SUBDEVICE_0_FUSE_INTERFACE_ID (0x208002U)
typedef FINN_RM_API FINN_LW20_SUBDEVICE_0_FUSE;
#endif // (!defined(LWRM_UNPUBLISHED) || LWRM_UNPUBLISHED == 1)



#if (!defined(LWRM_PUBLISHED_PENDING_IP_REVIEW) || LWRM_PUBLISHED_PENDING_IP_REVIEW == 1)
#define FINN_LW20_SUBDEVICE_0_GPIO_INTERFACE_ID (0x208023U)
typedef FINN_RM_API FINN_LW20_SUBDEVICE_0_GPIO;
#endif // (!defined(LWRM_PUBLISHED_PENDING_IP_REVIEW) || LWRM_PUBLISHED_PENDING_IP_REVIEW == 1)



#define FINN_LW20_SUBDEVICE_0_GPU_INTERFACE_ID (0x208001U)
typedef FINN_RM_API FINN_LW20_SUBDEVICE_0_GPU;

#if (!defined(LWRM_UNPUBLISHED_OPAQUE) || LWRM_UNPUBLISHED_OPAQUE == 1)
#define FINN_LW20_SUBDEVICE_0_GPU_LEGACY_NON_PRIVILEGED_INTERFACE_ID (0x208081U)
typedef FINN_RM_API FINN_LW20_SUBDEVICE_0_GPU_LEGACY_NON_PRIVILEGED;
#endif // (!defined(LWRM_UNPUBLISHED_OPAQUE) || LWRM_UNPUBLISHED_OPAQUE == 1)



#define FINN_LW20_SUBDEVICE_0_GR_INTERFACE_ID (0x208012U)
typedef FINN_RM_API FINN_LW20_SUBDEVICE_0_GR;


#if (!defined(LWRM_PUBLISHED_PENDING_IP_REVIEW) || LWRM_PUBLISHED_PENDING_IP_REVIEW == 1)
#define FINN_LW20_SUBDEVICE_0_GRMGR_INTERFACE_ID (0x208038U)
typedef FINN_RM_API FINN_LW20_SUBDEVICE_0_GRMGR;
#endif // (!defined(LWRM_PUBLISHED_PENDING_IP_REVIEW) || LWRM_PUBLISHED_PENDING_IP_REVIEW == 1)



#define FINN_LW20_SUBDEVICE_0_GSP_INTERFACE_ID (0x208036U)
typedef FINN_RM_API FINN_LW20_SUBDEVICE_0_GSP;


#if (!defined(LWRM_PUBLISHED_PENDING_IP_REVIEW) || LWRM_PUBLISHED_PENDING_IP_REVIEW == 1)
#define FINN_LW20_SUBDEVICE_0_HSHUB_INTERFACE_ID (0x208041U)
typedef FINN_RM_API FINN_LW20_SUBDEVICE_0_HSHUB;
#endif // (!defined(LWRM_PUBLISHED_PENDING_IP_REVIEW) || LWRM_PUBLISHED_PENDING_IP_REVIEW == 1)



#if (!defined(LWRM_PUBLISHED_PENDING_IP_REVIEW) || LWRM_PUBLISHED_PENDING_IP_REVIEW == 1)
#define FINN_LW20_SUBDEVICE_0_I2C_INTERFACE_ID (0x208006U)
typedef FINN_RM_API FINN_LW20_SUBDEVICE_0_I2C;
#endif // (!defined(LWRM_PUBLISHED_PENDING_IP_REVIEW) || LWRM_PUBLISHED_PENDING_IP_REVIEW == 1)



#if (!defined(LWRM_PUBLISHED_PENDING_IP_REVIEW) || LWRM_PUBLISHED_PENDING_IP_REVIEW == 1)
#endif // (!defined(LWRM_PUBLISHED_PENDING_IP_REVIEW) || LWRM_PUBLISHED_PENDING_IP_REVIEW == 1)



#if (!defined(LWRM_PUBLISHED_PENDING_IP_REVIEW) || LWRM_PUBLISHED_PENDING_IP_REVIEW == 1)
#define FINN_LW20_SUBDEVICE_0_PMGR_INTERFACE_ID (0x208026U)
typedef FINN_RM_API FINN_LW20_SUBDEVICE_0_PMGR;
#endif // (!defined(LWRM_PUBLISHED_PENDING_IP_REVIEW) || LWRM_PUBLISHED_PENDING_IP_REVIEW == 1)



#if (!defined(LWRM_UNPUBLISHED_OPAQUE) || LWRM_UNPUBLISHED_OPAQUE == 1)
#define FINN_LW20_SUBDEVICE_0_PMGR_LEGACY_NON_PRIVILEGED_INTERFACE_ID (0x2080A6U)
typedef FINN_RM_API FINN_LW20_SUBDEVICE_0_PMGR_LEGACY_NON_PRIVILEGED;
#endif // (!defined(LWRM_UNPUBLISHED_OPAQUE) || LWRM_UNPUBLISHED_OPAQUE == 1)



#define FINN_LW20_SUBDEVICE_0_INTERNAL_INTERFACE_ID (0x20800aU)
typedef FINN_RM_API FINN_LW20_SUBDEVICE_0_INTERNAL;


#if (!defined(LWRM_PUBLISHED_PENDING_IP_REVIEW) || LWRM_PUBLISHED_PENDING_IP_REVIEW == 1)
#define FINN_LW20_SUBDEVICE_0_LPWR_INTERFACE_ID (0x208028U)
typedef FINN_RM_API FINN_LW20_SUBDEVICE_0_LPWR;
#endif // (!defined(LWRM_PUBLISHED_PENDING_IP_REVIEW) || LWRM_PUBLISHED_PENDING_IP_REVIEW == 1)



#if (!defined(LWRM_PUBLISHED_PENDING_IP_REVIEW) || LWRM_PUBLISHED_PENDING_IP_REVIEW == 1)
#define FINN_LW20_SUBDEVICE_0_MC_INTERFACE_ID (0x208017U)
typedef FINN_RM_API FINN_LW20_SUBDEVICE_0_MC;
#endif // (!defined(LWRM_PUBLISHED_PENDING_IP_REVIEW) || LWRM_PUBLISHED_PENDING_IP_REVIEW == 1)



#if (!defined(LWRM_PUBLISHED_PENDING_IP_REVIEW) || LWRM_PUBLISHED_PENDING_IP_REVIEW == 1)
#define FINN_LW20_SUBDEVICE_0_NNE_INTERFACE_ID (0x208037U)
typedef FINN_RM_API FINN_LW20_SUBDEVICE_0_NNE;
#endif // (!defined(LWRM_PUBLISHED_PENDING_IP_REVIEW) || LWRM_PUBLISHED_PENDING_IP_REVIEW == 1)



#if (!defined(LWRM_PUBLISHED_PENDING_IP_REVIEW) || LWRM_PUBLISHED_PENDING_IP_REVIEW == 1)
#define FINN_LW20_SUBDEVICE_0_LWD_INTERFACE_ID (0x208024U)
typedef FINN_RM_API FINN_LW20_SUBDEVICE_0_LWD;
#endif // (!defined(LWRM_PUBLISHED_PENDING_IP_REVIEW) || LWRM_PUBLISHED_PENDING_IP_REVIEW == 1)



#if (!defined(LWRM_PUBLISHED_PENDING_IP_REVIEW) || LWRM_PUBLISHED_PENDING_IP_REVIEW == 1)
#define FINN_LW20_SUBDEVICE_0_LWIF_INTERFACE_ID (0x208021U)
typedef FINN_RM_API FINN_LW20_SUBDEVICE_0_LWIF;
#endif // (!defined(LWRM_PUBLISHED_PENDING_IP_REVIEW) || LWRM_PUBLISHED_PENDING_IP_REVIEW == 1)



#if (!defined(LWRM_PUBLISHED_PENDING_IP_REVIEW) || LWRM_PUBLISHED_PENDING_IP_REVIEW == 1)
#define FINN_LW20_SUBDEVICE_0_LWLINK_INTERFACE_ID (0x208030U)
typedef FINN_RM_API FINN_LW20_SUBDEVICE_0_LWLINK;
#endif // (!defined(LWRM_PUBLISHED_PENDING_IP_REVIEW) || LWRM_PUBLISHED_PENDING_IP_REVIEW == 1)



#if (!defined(LWRM_PUBLISHED_PENDING_IP_REVIEW) || LWRM_PUBLISHED_PENDING_IP_REVIEW == 1)
#endif // (!defined(LWRM_PUBLISHED_PENDING_IP_REVIEW) || LWRM_PUBLISHED_PENDING_IP_REVIEW == 1)



#if (!defined(LWRM_PUBLISHED_PENDING_IP_REVIEW) || LWRM_PUBLISHED_PENDING_IP_REVIEW == 1)
#endif // (!defined(LWRM_PUBLISHED_PENDING_IP_REVIEW) || LWRM_PUBLISHED_PENDING_IP_REVIEW == 1)



#if (!defined(LWRM_PUBLISHED_PENDING_IP_REVIEW) || LWRM_PUBLISHED_PENDING_IP_REVIEW == 1)
#define FINN_LW20_SUBDEVICE_0_PERF_INTERFACE_ID (0x208020U)
typedef FINN_RM_API FINN_LW20_SUBDEVICE_0_PERF;
#endif // (!defined(LWRM_PUBLISHED_PENDING_IP_REVIEW) || LWRM_PUBLISHED_PENDING_IP_REVIEW == 1)



#if (!defined(LWRM_UNPUBLISHED_OPAQUE) || LWRM_UNPUBLISHED_OPAQUE == 1)
#define FINN_LW20_SUBDEVICE_0_PERF_LEGACY_NON_PRIVILEGED_INTERFACE_ID (0x2080A0U)
typedef FINN_RM_API FINN_LW20_SUBDEVICE_0_PERF_LEGACY_NON_PRIVILEGED;
#endif // (!defined(LWRM_UNPUBLISHED_OPAQUE) || LWRM_UNPUBLISHED_OPAQUE == 1)



#if (!defined(LWRM_UNPUBLISHED_OPAQUE) || LWRM_UNPUBLISHED_OPAQUE == 1)
#define FINN_LW20_SUBDEVICE_0_PERF_LEGACY_PRIVILEGED_INTERFACE_ID (0x2080E0U)
typedef FINN_RM_API FINN_LW20_SUBDEVICE_0_PERF_LEGACY_PRIVILEGED;
#endif // (!defined(LWRM_UNPUBLISHED_OPAQUE) || LWRM_UNPUBLISHED_OPAQUE == 1)



#if (!defined(LWRM_PUBLISHED_PENDING_IP_REVIEW) || LWRM_PUBLISHED_PENDING_IP_REVIEW == 1)
#define FINN_LW20_SUBDEVICE_0_POWER_INTERFACE_ID (0x208027U)
typedef FINN_RM_API FINN_LW20_SUBDEVICE_0_POWER;
#endif // (!defined(LWRM_PUBLISHED_PENDING_IP_REVIEW) || LWRM_PUBLISHED_PENDING_IP_REVIEW == 1)



#if (!defined(LWRM_PUBLISHED_PENDING_IP_REVIEW) || LWRM_PUBLISHED_PENDING_IP_REVIEW == 1)
#define FINN_LW20_SUBDEVICE_0_RC_INTERFACE_ID (0x208022U)
typedef FINN_RM_API FINN_LW20_SUBDEVICE_0_RC;
#endif // (!defined(LWRM_PUBLISHED_PENDING_IP_REVIEW) || LWRM_PUBLISHED_PENDING_IP_REVIEW == 1)



#if (!defined(LWRM_UNPUBLISHED) || LWRM_UNPUBLISHED == 1)
#define FINN_LW20_SUBDEVICE_0_SPI_INTERFACE_ID (0x20802bU)
typedef FINN_RM_API FINN_LW20_SUBDEVICE_0_SPI;
#endif // (!defined(LWRM_UNPUBLISHED) || LWRM_UNPUBLISHED == 1)



#if (!defined(LWRM_PUBLISHED_PENDING_IP_REVIEW) || LWRM_PUBLISHED_PENDING_IP_REVIEW == 1)
#define FINN_LW20_SUBDEVICE_0_THERMAL_INTERFACE_ID (0x208005U)
typedef FINN_RM_API FINN_LW20_SUBDEVICE_0_THERMAL;
#endif // (!defined(LWRM_PUBLISHED_PENDING_IP_REVIEW) || LWRM_PUBLISHED_PENDING_IP_REVIEW == 1)



#define FINN_LW20_SUBDEVICE_0_TIMER_INTERFACE_ID (0x208004U)
typedef FINN_RM_API FINN_LW20_SUBDEVICE_0_TIMER;


#if (!defined(LWRM_PUBLISHED_PENDING_IP_REVIEW) || LWRM_PUBLISHED_PENDING_IP_REVIEW == 1)
#define FINN_LW20_SUBDEVICE_0_UCODE_FUZZER_INTERFACE_ID (0x208039U)
typedef FINN_RM_API FINN_LW20_SUBDEVICE_0_UCODE_FUZZER;
#endif // (!defined(LWRM_PUBLISHED_PENDING_IP_REVIEW) || LWRM_PUBLISHED_PENDING_IP_REVIEW == 1)



#define FINN_LW20_SUBDEVICE_0_OS_UNIX_INTERFACE_ID (0x20803dU)
typedef FINN_RM_API FINN_LW20_SUBDEVICE_0_OS_UNIX;


#define FINN_LW20_SUBDEVICE_0_VGPU_MGR_INTERNAL_INTERFACE_ID (0x208040U)
typedef FINN_RM_API FINN_LW20_SUBDEVICE_0_VGPU_MGR_INTERNAL;


#if (!defined(LWRM_PUBLISHED_PENDING_IP_REVIEW) || LWRM_PUBLISHED_PENDING_IP_REVIEW == 1)
#define FINN_LW20_SUBDEVICE_0_VOLT_INTERFACE_ID (0x208032U)
typedef FINN_RM_API FINN_LW20_SUBDEVICE_0_VOLT;
#endif // (!defined(LWRM_PUBLISHED_PENDING_IP_REVIEW) || LWRM_PUBLISHED_PENDING_IP_REVIEW == 1)



#if (!defined(LWRM_UNPUBLISHED_OPAQUE) || LWRM_UNPUBLISHED_OPAQUE == 1)
#define FINN_LW20_SUBDEVICE_0_VOLT_LEGACY_NON_PRIVILEGED_INTERFACE_ID (0x2080B2U)
typedef FINN_RM_API FINN_LW20_SUBDEVICE_0_VOLT_LEGACY_NON_PRIVILEGED;
#endif // (!defined(LWRM_UNPUBLISHED_OPAQUE) || LWRM_UNPUBLISHED_OPAQUE == 1)



#if (!defined(LWRM_UNPUBLISHED_OPAQUE) || LWRM_UNPUBLISHED_OPAQUE == 1)
#define FINN_LW20_SUBDEVICE_0_VOLT_LEGACY_PRIVILEGED_INTERFACE_ID (0x2080F2U)
typedef FINN_RM_API FINN_LW20_SUBDEVICE_0_VOLT_LEGACY_PRIVILEGED;
#endif // (!defined(LWRM_UNPUBLISHED_OPAQUE) || LWRM_UNPUBLISHED_OPAQUE == 1)



#if (!defined(LWRM_PUBLISHED_PENDING_IP_REVIEW) || LWRM_PUBLISHED_PENDING_IP_REVIEW == 1)
#define FINN_LW20_SUBDEVICE_0_OS_WINDOWS_INTERFACE_ID (0x20803fU)
typedef FINN_RM_API FINN_LW20_SUBDEVICE_0_OS_WINDOWS;
#endif // (!defined(LWRM_PUBLISHED_PENDING_IP_REVIEW) || LWRM_PUBLISHED_PENDING_IP_REVIEW == 1)



#define FINN_LW2081_BINAPI_RESERVED_INTERFACE_ID (0x208100U)
typedef FINN_RM_API FINN_LW2081_BINAPI_RESERVED;
#define FINN_LW2081_BINAPI_INTERFACE_ID (0x208101U)
typedef FINN_RM_API FINN_LW2081_BINAPI;


#define FINN_LW2082_BINAPI_RESERVED_INTERFACE_ID (0x208200U)
typedef FINN_RM_API FINN_LW2082_BINAPI_RESERVED;
#define FINN_LW2082_BINAPI_INTERFACE_ID (0x208201U)
typedef FINN_RM_API FINN_LW2082_BINAPI;


#define FINN_LW20_SUBDEVICE_DIAG_RESERVED_INTERFACE_ID (0x208f00U)
typedef FINN_RM_API FINN_LW20_SUBDEVICE_DIAG_RESERVED;


#define FINN_LW20_SUBDEVICE_DIAG_BIF_INTERFACE_ID (0x208f07U)
typedef FINN_RM_API FINN_LW20_SUBDEVICE_DIAG_BIF;


#define FINN_LW20_SUBDEVICE_DIAG_BUS_INTERFACE_ID (0x208f18U)
typedef FINN_RM_API FINN_LW20_SUBDEVICE_DIAG_BUS;


#define FINN_LW20_SUBDEVICE_DIAG_CLK_INTERFACE_ID (0x208f08U)
typedef FINN_RM_API FINN_LW20_SUBDEVICE_DIAG_CLK;


#define FINN_LW20_SUBDEVICE_DIAG_DMA_INTERFACE_ID (0x208f14U)
typedef FINN_RM_API FINN_LW20_SUBDEVICE_DIAG_DMA;


#define FINN_LW20_SUBDEVICE_DIAG_EVENT_INTERFACE_ID (0x208f10U)
typedef FINN_RM_API FINN_LW20_SUBDEVICE_DIAG_EVENT;


#define FINN_LW20_SUBDEVICE_DIAG_FB_INTERFACE_ID (0x208f05U)
typedef FINN_RM_API FINN_LW20_SUBDEVICE_DIAG_FB;


#define FINN_LW20_SUBDEVICE_DIAG_FBIO_INTERFACE_ID (0x208f0aU)
typedef FINN_RM_API FINN_LW20_SUBDEVICE_DIAG_FBIO;


#define FINN_LW20_SUBDEVICE_DIAG_FIFO_INTERFACE_ID (0x208f04U)
typedef FINN_RM_API FINN_LW20_SUBDEVICE_DIAG_FIFO;


#define FINN_LW20_SUBDEVICE_DIAG_GPU_INTERFACE_ID (0x208f11U)
typedef FINN_RM_API FINN_LW20_SUBDEVICE_DIAG_GPU;


#define FINN_LW20_SUBDEVICE_DIAG_GR_INTERFACE_ID (0x208f12U)
typedef FINN_RM_API FINN_LW20_SUBDEVICE_DIAG_GR;


#define FINN_LW20_SUBDEVICE_DIAG_GSPMSGTIMING_INTERFACE_ID (0x208f17U)
typedef FINN_RM_API FINN_LW20_SUBDEVICE_DIAG_GSPMSGTIMING;


#define FINN_LW20_SUBDEVICE_DIAG_MC_INTERFACE_ID (0x208f06U)
typedef FINN_RM_API FINN_LW20_SUBDEVICE_DIAG_MC;


#define FINN_LW20_SUBDEVICE_DIAG_MMU_INTERFACE_ID (0x208f0bU)
typedef FINN_RM_API FINN_LW20_SUBDEVICE_DIAG_MMU;


#define FINN_LW20_SUBDEVICE_DIAG_PMGR_INTERFACE_ID (0x208f13U)
typedef FINN_RM_API FINN_LW20_SUBDEVICE_DIAG_PMGR;


#define FINN_LW20_SUBDEVICE_DIAG_PMU_INTERFACE_ID (0x208f0lw)
typedef FINN_RM_API FINN_LW20_SUBDEVICE_DIAG_PMU;


#define FINN_LW20_SUBDEVICE_DIAG_POWER_INTERFACE_ID (0x208f01U)
typedef FINN_RM_API FINN_LW20_SUBDEVICE_DIAG_POWER;


#define FINN_LW20_SUBDEVICE_DIAG_RMFS_INTERFACE_ID (0x208f16U)
typedef FINN_RM_API FINN_LW20_SUBDEVICE_DIAG_RMFS;


#define FINN_LW30_GSYNC_RESERVED_INTERFACE_ID (0x30f100U)
typedef FINN_RM_API FINN_LW30_GSYNC_RESERVED;
#define FINN_LW30_GSYNC_GSYNC_INTERFACE_ID (0x30f101U)
typedef FINN_RM_API FINN_LW30_GSYNC_GSYNC;


#define FINN_LW40_I2C_RESERVED_INTERFACE_ID (0x402c00U)
typedef FINN_RM_API FINN_LW40_I2C_RESERVED;
#define FINN_LW40_I2C_I2C_INTERFACE_ID (0x402c01U)
typedef FINN_RM_API FINN_LW40_I2C_I2C;


#define FINN_LW50_THIRD_PARTY_P2P_P2P_INTERFACE_ID (0x503c01U)
typedef FINN_RM_API FINN_LW50_THIRD_PARTY_P2P_P2P;


#define FINN_LW50_THIRD_PARTY_P2P_RESERVED_INTERFACE_ID (0x503c00U)
typedef FINN_RM_API FINN_LW50_THIRD_PARTY_P2P_RESERVED;


#define FINN_LW50_CHANNEL_GPFIFO_RESERVED_INTERFACE_ID (0x506f00U)
typedef FINN_RM_API FINN_LW50_CHANNEL_GPFIFO_RESERVED;
#define FINN_LW50_CHANNEL_GPFIFO_GPFIFO_INTERFACE_ID (0x506f01U)
typedef FINN_RM_API FINN_LW50_CHANNEL_GPFIFO_GPFIFO;


#define FINN_LW50_DISPLAY_RESERVED_INTERFACE_ID (0x507000U)
typedef FINN_RM_API FINN_LW50_DISPLAY_RESERVED;


#define FINN_LW50_DISPLAY_CHNCTL_INTERFACE_ID (0x507001U)
typedef FINN_RM_API FINN_LW50_DISPLAY_CHNCTL;


#define FINN_LW50_DISPLAY_EVENT_INTERFACE_ID (0x507009U)
typedef FINN_RM_API FINN_LW50_DISPLAY_EVENT;


#define FINN_LW50_DISPLAY_OR_INTERFACE_ID (0x507004U)
typedef FINN_RM_API FINN_LW50_DISPLAY_OR;


#define FINN_LW50_DISPLAY_RG_INTERFACE_ID (0x507002U)
typedef FINN_RM_API FINN_LW50_DISPLAY_RG;


#define FINN_LW50_DISPLAY_SEQ_INTERFACE_ID (0x507003U)
typedef FINN_RM_API FINN_LW50_DISPLAY_SEQ;


#define FINN_LW50_DISPLAY_SYSTEM_INTERFACE_ID (0x507007U)
typedef FINN_RM_API FINN_LW50_DISPLAY_SYSTEM;


#if (!defined(LWRM_PUBLISHED_PENDING_IP_REVIEW) || LWRM_PUBLISHED_PENDING_IP_REVIEW == 1)
#define FINN_LW50_DISPLAY_VERIF_INTERFACE_ID (0x507006U)
typedef FINN_RM_API FINN_LW50_DISPLAY_VERIF;
#endif // (!defined(LWRM_PUBLISHED_PENDING_IP_REVIEW) || LWRM_PUBLISHED_PENDING_IP_REVIEW == 1)



#define FINN_LW50_DEFERRED_API_CLASS_RESERVED_INTERFACE_ID (0x508000U)
typedef FINN_RM_API FINN_LW50_DEFERRED_API_CLASS_RESERVED;
#define FINN_LW50_DEFERRED_API_CLASS_DEFERRED_INTERFACE_ID (0x508001U)
typedef FINN_RM_API FINN_LW50_DEFERRED_API_CLASS_DEFERRED;


#define FINN_GT200_DEBUGGER_RESERVED_INTERFACE_ID (0x83de00U)
typedef FINN_RM_API FINN_GT200_DEBUGGER_RESERVED;


#define FINN_GT200_DEBUGGER_DEBUG_INTERFACE_ID (0x83de03U)
typedef FINN_RM_API FINN_GT200_DEBUGGER_DEBUG;


#define FINN_GT200_DEBUGGER_FIFO_INTERFACE_ID (0x83de02U)
typedef FINN_RM_API FINN_GT200_DEBUGGER_FIFO;


#define FINN_GT200_DEBUGGER_INTERNAL_INTERFACE_ID (0x83de04U)
typedef FINN_RM_API FINN_GT200_DEBUGGER_INTERNAL;


#define FINN_GT212_SUBDEVICE_PMU_RESERVED_INTERFACE_ID (0x85b600U)
typedef FINN_RM_API FINN_GT212_SUBDEVICE_PMU_RESERVED;


#define FINN_GT212_SUBDEVICE_PMU_PMU_INTERFACE_ID (0x85b601U)
typedef FINN_RM_API FINN_GT212_SUBDEVICE_PMU_PMU;


#define FINN_LW9010_VBLANK_CALLBACK_RESERVED_INTERFACE_ID (0x901000U)
typedef FINN_RM_API FINN_LW9010_VBLANK_CALLBACK_RESERVED;
#define FINN_LW9010_VBLANK_CALLBACK_INTERFACE_ID (0x901001U)
typedef FINN_RM_API FINN_LW9010_VBLANK_CALLBACK;


#define FINN_FERMI_CONTEXT_SHARE_A_RESERVED_INTERFACE_ID (0x906700U)
typedef FINN_RM_API FINN_FERMI_CONTEXT_SHARE_A_RESERVED;
#define FINN_FERMI_CONTEXT_SHARE_A_TPC_PARTITION_INTERFACE_ID (0x906701U)
typedef FINN_RM_API FINN_FERMI_CONTEXT_SHARE_A_TPC_PARTITION;
#define FINN_FERMI_CONTEXT_SHARE_A_CWD_WATERMARK_INTERFACE_ID (0x906702U)
typedef FINN_RM_API FINN_FERMI_CONTEXT_SHARE_A_CWD_WATERMARK;


#define FINN_GF100_CHANNEL_GPFIFO_RESERVED_INTERFACE_ID (0x906f00U)
typedef FINN_RM_API FINN_GF100_CHANNEL_GPFIFO_RESERVED;
#define FINN_GF100_CHANNEL_GPFIFO_GPFIFO_INTERFACE_ID (0x906f01U)
typedef FINN_RM_API FINN_GF100_CHANNEL_GPFIFO_GPFIFO;
#define FINN_GF100_CHANNEL_GPFIFO_EVENT_INTERFACE_ID (0x906f02U)
typedef FINN_RM_API FINN_GF100_CHANNEL_GPFIFO_EVENT;


#define FINN_GF100_DISP_SW_RESERVED_INTERFACE_ID (0x907200U)
typedef FINN_RM_API FINN_GF100_DISP_SW_RESERVED;
#define FINN_GF100_DISP_SW_DISP_SW_INTERFACE_ID (0x907201U)
typedef FINN_RM_API FINN_GF100_DISP_SW_DISP_SW;


#define FINN_GF100_TIMED_SEMAPHORE_SW_RESERVED_INTERFACE_ID (0x907400U)
typedef FINN_RM_API FINN_GF100_TIMED_SEMAPHORE_SW_RESERVED;
#define FINN_GF100_TIMED_SEMAPHORE_SW_SEM_INTERFACE_ID (0x907401U)
typedef FINN_RM_API FINN_GF100_TIMED_SEMAPHORE_SW_SEM;


#define FINN_GF100_REMAPPER_RESERVED_INTERFACE_ID (0x907f00U)
typedef FINN_RM_API FINN_GF100_REMAPPER_RESERVED;
#define FINN_GF100_REMAPPER_REMAPPER_INTERFACE_ID (0x907f01U)
typedef FINN_RM_API FINN_GF100_REMAPPER_REMAPPER;


#define FINN_GF100_ZBC_CLEAR_RESERVED_INTERFACE_ID (0x909600U)
typedef FINN_RM_API FINN_GF100_ZBC_CLEAR_RESERVED;
#define FINN_GF100_ZBC_CLEAR_ZBC_INTERFACE_ID (0x909601U)
typedef FINN_RM_API FINN_GF100_ZBC_CLEAR_ZBC;


#define FINN_GF100_PROFILER_RESERVED_INTERFACE_ID (0x90cc00U)
typedef FINN_RM_API FINN_GF100_PROFILER_RESERVED;


#define FINN_GF100_PROFILER_HWPM_INTERFACE_ID (0x90cc01U)
typedef FINN_RM_API FINN_GF100_PROFILER_HWPM;


#define FINN_GF100_PROFILER_LWLINK_INTERFACE_ID (0x90cc02U)
typedef FINN_RM_API FINN_GF100_PROFILER_LWLINK;


#define FINN_GF100_PROFILER_POWER_INTERFACE_ID (0x90cc03U)
typedef FINN_RM_API FINN_GF100_PROFILER_POWER;


#define FINN_LW_EVENT_BUFFER_RESERVED_INTERFACE_ID (0x90cd00U)
typedef FINN_RM_API FINN_LW_EVENT_BUFFER_RESERVED;
#define FINN_LW_EVENT_BUFFER_EVENT_INTERFACE_ID (0x90cd01U)
typedef FINN_RM_API FINN_LW_EVENT_BUFFER_EVENT;


#define FINN_GF100_SUBDEVICE_GRAPHICS_RESERVED_INTERFACE_ID (0x90e000U)
typedef FINN_RM_API FINN_GF100_SUBDEVICE_GRAPHICS_RESERVED;
#define FINN_GF100_SUBDEVICE_GRAPHICS_GRAPHICS_INTERFACE_ID (0x90e001U)
typedef FINN_RM_API FINN_GF100_SUBDEVICE_GRAPHICS_GRAPHICS;


#define FINN_GF100_SUBDEVICE_FB_RESERVED_INTERFACE_ID (0x90e100U)
typedef FINN_RM_API FINN_GF100_SUBDEVICE_FB_RESERVED;
#define FINN_GF100_SUBDEVICE_FB_FB_INTERFACE_ID (0x90e101U)
typedef FINN_RM_API FINN_GF100_SUBDEVICE_FB_FB;


#define FINN_GF100_SUBDEVICE_MASTER_RESERVED_INTERFACE_ID (0x90e600U)
typedef FINN_RM_API FINN_GF100_SUBDEVICE_MASTER_RESERVED;
#define FINN_GF100_SUBDEVICE_MASTER_MASTER_INTERFACE_ID (0x90e601U)
typedef FINN_RM_API FINN_GF100_SUBDEVICE_MASTER_MASTER;


#define FINN_GF100_SUBDEVICE_INFOROM_RESERVED_INTERFACE_ID (0x90e700U)
typedef FINN_RM_API FINN_GF100_SUBDEVICE_INFOROM_RESERVED;
#define FINN_GF100_SUBDEVICE_INFOROM_BBX_INTERFACE_ID (0x90e701U)
typedef FINN_RM_API FINN_GF100_SUBDEVICE_INFOROM_BBX;
#define FINN_GF100_SUBDEVICE_INFOROM_RPR_INTERFACE_ID (0x90e702U)
typedef FINN_RM_API FINN_GF100_SUBDEVICE_INFOROM_RPR;


#define FINN_LW_PHYS_MEM_SUBALLOCATOR_RESERVED_INTERFACE_ID (0x90e800U)
typedef FINN_RM_API FINN_LW_PHYS_MEM_SUBALLOCATOR_RESERVED;
#define FINN_LW_PHYS_MEM_SUBALLOCATOR_PHYS_MEM_SUBALLOCATOR_INTERFACE_ID (0x90e801U)
typedef FINN_RM_API FINN_LW_PHYS_MEM_SUBALLOCATOR_PHYS_MEM_SUBALLOCATOR;


#define FINN_GF100_HDACODEC_RESERVED_INTERFACE_ID (0x90ec00U)
typedef FINN_RM_API FINN_GF100_HDACODEC_RESERVED;
#define FINN_GF100_HDACODEC_HDACODEC_INTERFACE_ID (0x90ec01U)
typedef FINN_RM_API FINN_GF100_HDACODEC_HDACODEC;


#define FINN_FERMI_VASPACE_A_RESERVED_INTERFACE_ID (0x90f100U)
typedef FINN_RM_API FINN_FERMI_VASPACE_A_RESERVED;
#define FINN_FERMI_VASPACE_A_VASPACE_INTERFACE_ID (0x90f101U)
typedef FINN_RM_API FINN_FERMI_VASPACE_A_VASPACE;


#define FINN_KEPLER_CHANNEL_GROUP_A_RESERVED_INTERFACE_ID (0xa06c00U)
typedef FINN_RM_API FINN_KEPLER_CHANNEL_GROUP_A_RESERVED;
#define FINN_KEPLER_CHANNEL_GROUP_A_GPFIFO_INTERFACE_ID (0xa06c01U)
typedef FINN_RM_API FINN_KEPLER_CHANNEL_GROUP_A_GPFIFO;
#define FINN_KEPLER_CHANNEL_GROUP_A_INTERNAL_INTERFACE_ID (0xa06c02U)
typedef FINN_RM_API FINN_KEPLER_CHANNEL_GROUP_A_INTERNAL;


#define FINN_KEPLER_CHANNEL_GPFIFO_A_RESERVED_INTERFACE_ID (0xa06f00U)
typedef FINN_RM_API FINN_KEPLER_CHANNEL_GPFIFO_A_RESERVED;


#define FINN_KEPLER_CHANNEL_GPFIFO_A_EVENT_INTERFACE_ID (0xa06f02U)
typedef FINN_RM_API FINN_KEPLER_CHANNEL_GPFIFO_A_EVENT;



#define FINN_KEPLER_CHANNEL_GPFIFO_A_GPFIFO_INTERFACE_ID (0xa06f01U)
typedef FINN_RM_API FINN_KEPLER_CHANNEL_GPFIFO_A_GPFIFO;


#define FINN_KEPLER_CHANNEL_GPFIFO_A_INTERNAL_INTERFACE_ID (0xa06f03U)
typedef FINN_RM_API FINN_KEPLER_CHANNEL_GPFIFO_A_INTERNAL;


#define FINN_KEPLER_DEVICE_VGPU_RESERVED_INTERFACE_ID (0xa08000U)
typedef FINN_RM_API FINN_KEPLER_DEVICE_VGPU_RESERVED;
#define FINN_KEPLER_DEVICE_VGPU_VGPU_DISPLAY_INTERFACE_ID (0xa08001U)
typedef FINN_RM_API FINN_KEPLER_DEVICE_VGPU_VGPU_DISPLAY;
#define FINN_KEPLER_DEVICE_VGPU_VGPU_MEMORY_INTERFACE_ID (0xa08002U)
typedef FINN_RM_API FINN_KEPLER_DEVICE_VGPU_VGPU_MEMORY;
#define FINN_KEPLER_DEVICE_VGPU_VGPU_OTHERS_INTERFACE_ID (0xa08003U)
typedef FINN_RM_API FINN_KEPLER_DEVICE_VGPU_VGPU_OTHERS;


#define FINN_LWA081_VGPU_CONFIG_VGPU_CONFIG_INTERFACE_ID (0xa08101U)
typedef FINN_RM_API FINN_LWA081_VGPU_CONFIG_VGPU_CONFIG;


#define FINN_LWA082_HOST_VGPU_DEVICE_HOST_VGPU_DEVICE_INTERFACE_ID (0xa08201U)
typedef FINN_RM_API FINN_LWA082_HOST_VGPU_DEVICE_HOST_VGPU_DEVICE;


#define FINN_LWA083_GRID_DISPLAYLESS_RESERVED_INTERFACE_ID (0xa08300U)
typedef FINN_RM_API FINN_LWA083_GRID_DISPLAYLESS_RESERVED;
#define FINN_LWA083_GRID_DISPLAYLESS_VIRTUAL_DISPLAY_INTERFACE_ID (0xa08301U)
typedef FINN_RM_API FINN_LWA083_GRID_DISPLAYLESS_VIRTUAL_DISPLAY;


#define FINN_LWA084_HOST_VGPU_DEVICE_KERNEL_HOST_VGPU_DEVICE_KERNEL_INTERFACE_ID (0xa08401U)
typedef FINN_RM_API FINN_LWA084_HOST_VGPU_DEVICE_KERNEL_HOST_VGPU_DEVICE_KERNEL;


#define FINN_LWENC_SW_SESSION_LWENC_SW_SESSION_INTERFACE_ID (0xa0bc01U)
typedef FINN_RM_API FINN_LWENC_SW_SESSION_LWENC_SW_SESSION;


#define FINN_LWFBC_SW_SESSION_LWFBC_SW_SESSION_INTERFACE_ID (0xa0bd01U)
typedef FINN_RM_API FINN_LWFBC_SW_SESSION_LWFBC_SW_SESSION;


#define FINN_GK110_SUBDEVICE_GRAPHICS_RESERVED_INTERFACE_ID (0xa0e000U)
typedef FINN_RM_API FINN_GK110_SUBDEVICE_GRAPHICS_RESERVED;
#define FINN_GK110_SUBDEVICE_GRAPHICS_GRAPHICS_INTERFACE_ID (0xa0e001U)
typedef FINN_RM_API FINN_GK110_SUBDEVICE_GRAPHICS_GRAPHICS;


#define FINN_GK110_SUBDEVICE_FB_RESERVED_INTERFACE_ID (0xa0e100U)
typedef FINN_RM_API FINN_GK110_SUBDEVICE_FB_RESERVED;
#define FINN_GK110_SUBDEVICE_FB_FB_INTERFACE_ID (0xa0e101U)
typedef FINN_RM_API FINN_GK110_SUBDEVICE_FB_FB;


#define FINN_KEPLER_CHANNEL_GPFIFO_B_RESERVED_INTERFACE_ID (0xa16f00U)
typedef FINN_RM_API FINN_KEPLER_CHANNEL_GPFIFO_B_RESERVED;
#define FINN_KEPLER_CHANNEL_GPFIFO_B_GPFIFO_INTERFACE_ID (0xa16f01U)
typedef FINN_RM_API FINN_KEPLER_CHANNEL_GPFIFO_B_GPFIFO;
#define FINN_KEPLER_CHANNEL_GPFIFO_B_EVENT_INTERFACE_ID (0xa16f02U)
typedef FINN_RM_API FINN_KEPLER_CHANNEL_GPFIFO_B_EVENT;


#define FINN_KEPLER_CHANNEL_GPFIFO_C_RESERVED_INTERFACE_ID (0xa26f00U)
typedef FINN_RM_API FINN_KEPLER_CHANNEL_GPFIFO_C_RESERVED;
#define FINN_KEPLER_CHANNEL_GPFIFO_C_GPFIFO_INTERFACE_ID (0xa26f01U)
typedef FINN_RM_API FINN_KEPLER_CHANNEL_GPFIFO_C_GPFIFO;
#define FINN_KEPLER_CHANNEL_GPFIFO_C_EVENT_INTERFACE_ID (0xa26f02U)
typedef FINN_RM_API FINN_KEPLER_CHANNEL_GPFIFO_C_EVENT;


#define FINN_MAXWELL_FAULT_BUFFER_A_RESERVED_INTERFACE_ID (0xb06900U)
typedef FINN_RM_API FINN_MAXWELL_FAULT_BUFFER_A_RESERVED;
#define FINN_MAXWELL_FAULT_BUFFER_A_FAULTBUFFER_INTERFACE_ID (0xb06901U)
typedef FINN_RM_API FINN_MAXWELL_FAULT_BUFFER_A_FAULTBUFFER;


#define FINN_MAXWELL_CHANNEL_GPFIFO_A_RESERVED_INTERFACE_ID (0xb06f00U)
typedef FINN_RM_API FINN_MAXWELL_CHANNEL_GPFIFO_A_RESERVED;
#define FINN_MAXWELL_CHANNEL_GPFIFO_A_GPFIFO_INTERFACE_ID (0xb06f01U)
typedef FINN_RM_API FINN_MAXWELL_CHANNEL_GPFIFO_A_GPFIFO;
#define FINN_MAXWELL_CHANNEL_GPFIFO_A_EVENT_INTERFACE_ID (0xb06f02U)
typedef FINN_RM_API FINN_MAXWELL_CHANNEL_GPFIFO_A_EVENT;


#define FINN_MAXWELL_PROFILER_RESERVED_INTERFACE_ID (0xb0cc00U)
typedef FINN_RM_API FINN_MAXWELL_PROFILER_RESERVED;


#define FINN_MAXWELL_PROFILER_INTERNAL_INTERFACE_ID (0xb0cc02U)
typedef FINN_RM_API FINN_MAXWELL_PROFILER_INTERNAL;


#define FINN_MAXWELL_PROFILER_PROFILER_INTERFACE_ID (0xb0cc01U)
typedef FINN_RM_API FINN_MAXWELL_PROFILER_PROFILER;


#define FINN_MAXWELL_PROFILER_CONTEXT_RESERVED_INTERFACE_ID (0xb1cc00U)
typedef FINN_RM_API FINN_MAXWELL_PROFILER_CONTEXT_RESERVED;
#define FINN_MAXWELL_PROFILER_CONTEXT_PROFILER_INTERFACE_ID (0xb1cc01U)
typedef FINN_RM_API FINN_MAXWELL_PROFILER_CONTEXT_PROFILER;


#define FINN_MAXWELL_PROFILER_DEVICE_RESERVED_INTERFACE_ID (0xb2cc00U)
typedef FINN_RM_API FINN_MAXWELL_PROFILER_DEVICE_RESERVED;
#define FINN_MAXWELL_PROFILER_DEVICE_PROFILER_INTERFACE_ID (0xb2cc01U)
typedef FINN_RM_API FINN_MAXWELL_PROFILER_DEVICE_PROFILER;


#define FINN_MAXWELL_SEC2_SEC2_INTERFACE_ID (0xb6b901U)
typedef FINN_RM_API FINN_MAXWELL_SEC2_SEC2;


#define FINN_PASCAL_CHANNEL_GPFIFO_A_RESERVED_INTERFACE_ID (0xc06f00U)
typedef FINN_RM_API FINN_PASCAL_CHANNEL_GPFIFO_A_RESERVED;
#define FINN_PASCAL_CHANNEL_GPFIFO_A_GPFIFO_INTERFACE_ID (0xc06f01U)
typedef FINN_RM_API FINN_PASCAL_CHANNEL_GPFIFO_A_GPFIFO;
#define FINN_PASCAL_CHANNEL_GPFIFO_A_EVENT_INTERFACE_ID (0xc06f02U)
typedef FINN_RM_API FINN_PASCAL_CHANNEL_GPFIFO_A_EVENT;


#define FINN_GP100_SUBDEVICE_GRAPHICS_RESERVED_INTERFACE_ID (0xc0e000U)
typedef FINN_RM_API FINN_GP100_SUBDEVICE_GRAPHICS_RESERVED;
#define FINN_GP100_SUBDEVICE_GRAPHICS_GRAPHICS_INTERFACE_ID (0xc0e001U)
typedef FINN_RM_API FINN_GP100_SUBDEVICE_GRAPHICS_GRAPHICS;


#define FINN_GP100_SUBDEVICE_FB_RESERVED_INTERFACE_ID (0xc0e100U)
typedef FINN_RM_API FINN_GP100_SUBDEVICE_FB_RESERVED;
#define FINN_GP100_SUBDEVICE_FB_FB_INTERFACE_ID (0xc0e101U)
typedef FINN_RM_API FINN_GP100_SUBDEVICE_FB_FB;


#define FINN_VOLTA_GSP_GSP_INTERFACE_ID (0xc31001U)
typedef FINN_RM_API FINN_VOLTA_GSP_GSP;


#define FINN_ACCESS_COUNTER_NOTIFY_BUFFER_RESERVED_INTERFACE_ID (0xc36500U)
typedef FINN_RM_API FINN_ACCESS_COUNTER_NOTIFY_BUFFER_RESERVED;
#define FINN_ACCESS_COUNTER_NOTIFY_BUFFER_ACCESS_CNTR_BUFFER_INTERFACE_ID (0xc36501U)
typedef FINN_RM_API FINN_ACCESS_COUNTER_NOTIFY_BUFFER_ACCESS_CNTR_BUFFER;


#define FINN_MMU_FAULT_BUFFER_RESERVED_INTERFACE_ID (0xc36900U)
typedef FINN_RM_API FINN_MMU_FAULT_BUFFER_RESERVED;
#define FINN_MMU_FAULT_BUFFER_MMU_FAULT_BUFFER_INTERFACE_ID (0xc36901U)
typedef FINN_RM_API FINN_MMU_FAULT_BUFFER_MMU_FAULT_BUFFER;


#define FINN_VOLTA_CHANNEL_GPFIFO_A_RESERVED_INTERFACE_ID (0xc36f00U)
typedef FINN_RM_API FINN_VOLTA_CHANNEL_GPFIFO_A_RESERVED;
#define FINN_VOLTA_CHANNEL_GPFIFO_A_GPFIFO_INTERFACE_ID (0xc36f01U)
typedef FINN_RM_API FINN_VOLTA_CHANNEL_GPFIFO_A_GPFIFO;
#define FINN_VOLTA_CHANNEL_GPFIFO_A_EVENT_INTERFACE_ID (0xc36f02U)
typedef FINN_RM_API FINN_VOLTA_CHANNEL_GPFIFO_A_EVENT;


#define FINN_LWC370_DISPLAY_RESERVED_INTERFACE_ID (0xc37000U)
typedef FINN_RM_API FINN_LWC370_DISPLAY_RESERVED;


#define FINN_LWC370_DISPLAY_CHNCTL_INTERFACE_ID (0xc37001U)
typedef FINN_RM_API FINN_LWC370_DISPLAY_CHNCTL;


#define FINN_LWC370_DISPLAY_EVENT_INTERFACE_ID (0xc37009U)
typedef FINN_RM_API FINN_LWC370_DISPLAY_EVENT;


#define FINN_LWC370_DISPLAY_RG_INTERFACE_ID (0xc37002U)
typedef FINN_RM_API FINN_LWC370_DISPLAY_RG;


#define FINN_LWC370_DISPLAY_VERIF_INTERFACE_ID (0xc37006U)
typedef FINN_RM_API FINN_LWC370_DISPLAY_VERIF;


#define FINN_LWC372_DISPLAY_SW_RESERVED_INTERFACE_ID (0xc37200U)
typedef FINN_RM_API FINN_LWC372_DISPLAY_SW_RESERVED;


#define FINN_LWC372_DISPLAY_SW_CHNCTL_INTERFACE_ID (0xc37201U)
typedef FINN_RM_API FINN_LWC372_DISPLAY_SW_CHNCTL;


#if (!defined(LWRM_UNPUBLISHED) || LWRM_UNPUBLISHED == 1)
#define FINN_LWC372_DISPLAY_SW_VERIF_INTERFACE_ID (0xc37202U)
typedef FINN_RM_API FINN_LWC372_DISPLAY_SW_VERIF;
#endif // (!defined(LWRM_UNPUBLISHED) || LWRM_UNPUBLISHED == 1)



#define FINN_GV100_SUBDEVICE_GRAPHICS_RESERVED_INTERFACE_ID (0xc3e000U)
typedef FINN_RM_API FINN_GV100_SUBDEVICE_GRAPHICS_RESERVED;
#define FINN_GV100_SUBDEVICE_GRAPHICS_GRAPHICS_INTERFACE_ID (0xc3e001U)
typedef FINN_RM_API FINN_GV100_SUBDEVICE_GRAPHICS_GRAPHICS;


#define FINN_GV100_SUBDEVICE_FB_RESERVED_INTERFACE_ID (0xc3e100U)
typedef FINN_RM_API FINN_GV100_SUBDEVICE_FB_RESERVED;
#define FINN_GV100_SUBDEVICE_FB_FB_INTERFACE_ID (0xc3e101U)
typedef FINN_RM_API FINN_GV100_SUBDEVICE_FB_FB;


#define FINN_TURING_CHANNEL_GPFIFO_A_RESERVED_INTERFACE_ID (0xc46f00U)
typedef FINN_RM_API FINN_TURING_CHANNEL_GPFIFO_A_RESERVED;
#define FINN_TURING_CHANNEL_GPFIFO_A_GPFIFO_INTERFACE_ID (0xc46f01U)
typedef FINN_RM_API FINN_TURING_CHANNEL_GPFIFO_A_GPFIFO;
#define FINN_TURING_CHANNEL_GPFIFO_A_EVENT_INTERFACE_ID (0xc46f02U)
typedef FINN_RM_API FINN_TURING_CHANNEL_GPFIFO_A_EVENT;


#define FINN_AMPERE_CHANNEL_GPFIFO_A_RESERVED_INTERFACE_ID (0xc56f00U)
typedef FINN_RM_API FINN_AMPERE_CHANNEL_GPFIFO_A_RESERVED;
#define FINN_AMPERE_CHANNEL_GPFIFO_A_GPFIFO_INTERFACE_ID (0xc56f01U)
typedef FINN_RM_API FINN_AMPERE_CHANNEL_GPFIFO_A_GPFIFO;
#define FINN_AMPERE_CHANNEL_GPFIFO_A_EVENT_INTERFACE_ID (0xc56f02U)
typedef FINN_RM_API FINN_AMPERE_CHANNEL_GPFIFO_A_EVENT;


#define FINN_AMPERE_SMC_PARTITION_REF_RESERVED_INTERFACE_ID (0xc63700U)
typedef FINN_RM_API FINN_AMPERE_SMC_PARTITION_REF_RESERVED;
#define FINN_AMPERE_SMC_PARTITION_REF_EXEC_PARTITIONS_INTERFACE_ID (0xc63701U)
typedef FINN_RM_API FINN_AMPERE_SMC_PARTITION_REF_EXEC_PARTITIONS;


#define FINN_AMPERE_SMC_EXEC_PARTITION_REF_RESERVED_INTERFACE_ID (0xc63800U)
typedef FINN_RM_API FINN_AMPERE_SMC_EXEC_PARTITION_REF_RESERVED;
#define FINN_AMPERE_SMC_EXEC_PARTITION_REF_EXEC_PARTITION_INTERFACE_ID (0xc63801U)
typedef FINN_RM_API FINN_AMPERE_SMC_EXEC_PARTITION_REF_EXEC_PARTITION;


#define FINN_MMU_VIDMEM_ACCESS_BIT_BUFFER_RESERVED_INTERFACE_ID (0xc76300U)
typedef FINN_RM_API FINN_MMU_VIDMEM_ACCESS_BIT_BUFFER_RESERVED;
#define FINN_MMU_VIDMEM_ACCESS_BIT_BUFFER_VIDMEM_ACCESS_BIT_BUFFER_INTERFACE_ID (0xc76301U)
typedef FINN_RM_API FINN_MMU_VIDMEM_ACCESS_BIT_BUFFER_VIDMEM_ACCESS_BIT_BUFFER;


#define FINN_HOPPER_CHANNEL_GPFIFO_A_RESERVED_INTERFACE_ID (0xc86f00U)
typedef FINN_RM_API FINN_HOPPER_CHANNEL_GPFIFO_A_RESERVED;
#define FINN_HOPPER_CHANNEL_GPFIFO_A_GPFIFO_INTERFACE_ID (0xc86f01U)
typedef FINN_RM_API FINN_HOPPER_CHANNEL_GPFIFO_A_GPFIFO;
#define FINN_HOPPER_CHANNEL_GPFIFO_A_EVENT_INTERFACE_ID (0xc86f02U)
typedef FINN_RM_API FINN_HOPPER_CHANNEL_GPFIFO_A_EVENT;


#define FINN_LW_CONFIDENTIAL_COMPUTE_RESERVED_INTERFACE_ID (0xcb3300U)
typedef FINN_RM_API FINN_LW_CONFIDENTIAL_COMPUTE_RESERVED;
#define FINN_LW_CONFIDENTIAL_COMPUTE_CONF_COMPUTE_INTERFACE_ID (0xcb3301U)
typedef FINN_RM_API FINN_LW_CONFIDENTIAL_COMPUTE_CONF_COMPUTE;


#if (!defined(LWRM_UNPUBLISHED) || LWRM_UNPUBLISHED == 1)
#define FINN_LW_COUNTER_COLLECTION_UNIT_RESERVED_INTERFACE_ID (0xcbca00U)
typedef FINN_RM_API FINN_LW_COUNTER_COLLECTION_UNIT_RESERVED;
#define FINN_LW_COUNTER_COLLECTION_UNIT_CLW_INTERFACE_ID (0xcbca01U)
typedef FINN_RM_API FINN_LW_COUNTER_COLLECTION_UNIT_CLW;
#endif // (!defined(LWRM_UNPUBLISHED) || LWRM_UNPUBLISHED == 1)



#define FINN_LWE2_SYNCPOINT_BASE_RESERVED_INTERFACE_ID (0xe2ad00U)
typedef FINN_RM_API FINN_LWE2_SYNCPOINT_BASE_RESERVED;
#define FINN_LWE2_SYNCPOINT_BASE_SYNCPOINT_BASE_INTERFACE_ID (0xe2ad01U)
typedef FINN_RM_API FINN_LWE2_SYNCPOINT_BASE_SYNCPOINT_BASE;
