/* _LWRM_COPYRIGHT_BEGIN_
 *
 * Copyright 2012-2019 by LWPU Corporation.  All rights reserved.  All
 * information contained herein is proprietary and confidential to LWPU
 * Corporation.  Any use, reproduction, or disclosure without the written
 * permission of LWPU Corporation is prohibited.
 *
 * _LWRM_COPYRIGHT_END_
 */

#ifndef _LW_REF_DEV_SR_H_
#define _LW_REF_DEV_SR_H_

#define LW_SR                                                       0x000007ff:0x00000000 /* RW--D */
#define LW_SR_SRC_ID0                                                          0x000003a0 /* R--1R */
#define LW_SR_SRC_ID0_DEV_ID_LSB                                                      7:0 /* R-IVF */
#define LW_SR_SRC_ID0_DEV_ID_LSB_INIT                                          0x00000000 /* R-I-V */
#define LW_SR_SRC_ID1                                                          0x000003a1 /* R--1R */
#define LW_SR_SRC_ID1_DEV_ID_MSB                                                      7:0 /* R-IVF */
#define LW_SR_SRC_ID1_DEV_ID_MSB_INIT                                          0x00000000 /* R-I-V */
#define LW_SR_SRC_ID2                                                          0x000003a2 /* R--1R */
#define LW_SR_SRC_ID2_VENDOR_ID                                                       7:0 /* R-IVF */
#define LW_SR_SRC_ID2_VENDOR_ID_INIT                                           0x00000000 /* R-I-V */
#define LW_SR_SRC_ID3                                                          0x000003a3 /* R--1R */
#define LW_SR_SRC_ID3_VERSION                                                         7:0 /* R-IVF */
#define LW_SR_SRC_ID3_VERSION_INIT                                             0x00000000 /* R-I-V */
#define LW_SR_SRC_ID3_VERSION_VER1                                             0x00000001 /* R---V */
#define LW_SR_FRAME_STATS                                                      0x000003a4 /* R--4R */
#define LW_SR_FRAME_STATS_FRAME_COUNT                                                30:0 /* R-IVF */
#define LW_SR_FRAME_STATS_FRAME_COUNT_INIT                                     0x00000000 /* R-I-V */
#define LW_SR_FRAME_STATS_ROLLOVER_DETECT                                           31:31 /* R-IVF */
#define LW_SR_FRAME_STATS_ROLLOVER_DETECT_INIT                                 0x00000000 /* R-I-V */
#define LW_SR_MUTEX_SPRN                                                       0x000003a8 /* R--4R */
#define LW_SR_MUTEX_SPRN_VAL                                                         31:0 /* R-IVF */
#define LW_SR_MUTEX0                                                           0x000003ac /* -W-1R */
#define LW_SR_MUTEX0_VAL                                                              7:0 /* -W-VF */
#define LW_SR_MUTEX1                                                           0x000003ad /* -W-1R */
#define LW_SR_MUTEX1_VAL                                                              7:0 /* -W-VF */
#define LW_SR_MUTEX2                                                           0x000003ae /* -W-1R */
#define LW_SR_MUTEX2_VAL                                                              7:0 /* -W-VF */
#define LW_SR_MUTEX3                                                           0x000003af /* -W-1R */
#define LW_SR_MUTEX3_VAL                                                              7:0 /* -W-VF */
#define LW_SR_NLT_CAPABILITIES0                                                0x00000330 /* R--1R */
#define LW_SR_NLT_CAPABILITIES0_NLT_CAP                                               0:0 /* R-IVF */
#define LW_SR_NLT_CAPABILITIES0_NLT_CAP_INIT                                   0x00000000 /* R-I-V */
#define LW_SR_NLT_CAPABILITIES0_NLT_CAP_NO                                     0x00000000 /* R---V */
#define LW_SR_NLT_CAPABILITIES0_NLT_CAP_YES                                    0x00000001 /* R---V */
#define LW_SR_NLT_CAPABILITIES0_NLT_CONFIG                                            1:1 /* R-IVF */
#define LW_SR_NLT_CAPABILITIES0_NLT_CONFIG_INIT                                0x00000000 /* R-I-V */
#define LW_SR_NLT_CAPABILITIES0_NLT_CONFIG_NO                                  0x00000000 /* R---V */
#define LW_SR_NLT_CAPABILITIES0_NLT_CONFIG_YES                                 0x00000001 /* R---V */
#define LW_SR_NLT_CAPABILITIES0_NLT_CAPABLE_CONFIG                                    2:2 /* R-IVF */
#define LW_SR_NLT_CAPABILITIES0_NLT_CAPABLE_CONFIG_INIT                        0x00000000 /* R-I-V */
#define LW_SR_NLT_CAPABILITIES0_NLT_CAPABLE_CONFIG_NO                          0x00000000 /* R---V */
#define LW_SR_NLT_CAPABILITIES0_NLT_CAPABLE_CONFIG_YES                         0x00000001 /* R---V */
#define LW_SR_NLT_CAPABILITIES1                                                0x00000331 /* R--1R */
#define LW_SR_NLT_CAPABILITIES1_RETENTION_TIME0                                       7:0 /* R-IVF */
#define LW_SR_NLT_CAPABILITIES1_RETENTION_TIME0_INIT                           0x00000000 /* R-I-V */
#define LW_SR_NLT_CAPABILITIES2                                                0x00000332 /* R--1R */
#define LW_SR_NLT_CAPABILITIES2_RETENTION_TIME1                                       7:0 /* R-IVF */
#define LW_SR_NLT_CAPABILITIES2_RETENTION_TIME1_INIT                           0x0000007d /* R-I-V */
#define LW_SR_NLT_CAPABILITIES3                                                0x00000333 /* R--1R */
#define LW_SR_NLT_CAPABILITIES3_RETENTION_TIME2                                       7:0 /* R-IVF */
#define LW_SR_NLT_CAPABILITIES3_RETENTION_TIME2_INIT                           0x00000000 /* R-I-V */
#define LW_SR_SR_CAPABILITIES0                                                 0x00000335 /* R--1R */
#define LW_SR_SR_CAPABILITIES0_SR_CAPABLE                                             0:0 /* R-IVF */
#define LW_SR_SR_CAPABILITIES0_SR_CAPABLE_INIT                                 0x00000001 /* R-I-V */
#define LW_SR_SR_CAPABILITIES0_SR_CAPABLE_YES                                  0x00000001 /* R---V */
#define LW_SR_SR_CAPABILITIES0_SR_CAPABLE_NO                                   0x00000000 /* R---V */
#define LW_SR_SR_CAPABILITIES0_SR_ENTRY_REQ                                           2:1 /* R-IVF */
#define LW_SR_SR_CAPABILITIES0_SR_ENTRY_REQ_INIT                               0x00000003 /* R-I-V */
#define LW_SR_SR_CAPABILITIES0_SR_ENTRY_REQ_NOT_SUPPORTED                      0x00000000 /* R---V */
#define LW_SR_SR_CAPABILITIES0_SR_ENTRY_REQ_INBAND                             0x00000001 /* R---V */
#define LW_SR_SR_CAPABILITIES0_SR_ENTRY_REQ_SIDEBAND                           0x00000002 /* R---V */
#define LW_SR_SR_CAPABILITIES0_SR_ENTRY_REQ_BOTH                               0x00000003 /* R---V */
#define LW_SR_SR_CAPABILITIES0_SR_EXIT_REQ                                            4:3 /* R-IVF */
#define LW_SR_SR_CAPABILITIES0_SR_EXIT_REQ_INIT                                0x00000003 /* R-I-V */
#define LW_SR_SR_CAPABILITIES0_SR_EXIT_REQ_NOT_SUPPORTED                       0x00000000 /* R---V */
#define LW_SR_SR_CAPABILITIES0_SR_EXIT_REQ_INBAND                              0x00000001 /* R---V */
#define LW_SR_SR_CAPABILITIES0_SR_EXIT_REQ_SIDEBAND                            0x00000002 /* R---V */
#define LW_SR_SR_CAPABILITIES0_SR_EXIT_REQ_BOTH                                0x00000003 /* R---V */
#define LW_SR_SR_CAPABILITIES0_RESYNC_CAP                                             7:5 /* R-IVF */
#define LW_SR_SR_CAPABILITIES0_RESYNC_CAP_INIT                                 0x00000002 /* R-I-V */
#define LW_SR_SR_CAPABILITIES0_RESYNC_CAP_IMM                                  0x00000000 /* R---V */
#define LW_SR_SR_CAPABILITIES0_RESYNC_CAP_SS                                   0x00000001 /* R---V */
#define LW_SR_SR_CAPABILITIES0_RESYNC_CAP_FL                                   0x00000002 /* R---V */
#define LW_SR_SR_CAPABILITIES0_RESYNC_CAP_BS                                   0x00000004 /* R---V */
#define LW_SR_SR_CAPABILITIES1                                                 0x00000336 /* R--1R */
#define LW_SR_SR_CAPABILITIES1_SR_ENTRY_LATENCY                                       3:0 /* R-IVF */
#define LW_SR_SR_CAPABILITIES1_SR_ENTRY_LATENCY_INIT                           0x00000001 /* R-I-V */
#define LW_SR_SR_CAPABILITIES1_SR_ENTRY_LATENCY_1FRAME                         0x00000000 /* R---V */
#define LW_SR_SR_CAPABILITIES1_SR_ENTRY_LATENCY_2FRAME                         0x00000001 /* R---V */
#define LW_SR_SR_CAPABILITIES1_PANEL_DITHER                                           4:4 /* R-IVF */
#define LW_SR_SR_CAPABILITIES1_PANEL_DITHER_INIT                               0x00000000 /* R-I-V */
#define LW_SR_SR_CAPABILITIES1_PANEL_DITHER_SUPPORTED                          0x00000001 /* R---V */
#define LW_SR_SR_CAPABILITIES1_PANEL_DITHER_NOT_SUPPORTED                      0x00000000 /* R---V */
#define LW_SR_SR_CAPABILITIES1_TEMPORAL_DITHER                                        5:5 /* R-IVF */
#define LW_SR_SR_CAPABILITIES1_TEMPORAL_DITHER_INIT                            0x00000000 /* R-I-V */
#define LW_SR_SR_CAPABILITIES1_TEMPORAL_DITHER_SUPPORTED                       0x00000001 /* R---V */
#define LW_SR_SR_CAPABILITIES1_TEMPORAL_DITHER_NOT_SUPPORTED                   0x00000000 /* R---V */
#define LW_SR_SR_CAPABILITIES1_3DSTEREO                                               6:6 /* R-IVF */
#define LW_SR_SR_CAPABILITIES1_3DSTEREO_INIT                                   0x00000000 /* R-I-V */
#define LW_SR_SR_CAPABILITIES1_3DSTEREO_SUPPORTED                              0x00000001 /* R---V */
#define LW_SR_SR_CAPABILITIES1_3DSTEREO_NOT_SUPPORTED                          0x00000000 /* R---V */
#define LW_SR_SR_CAPABILITIES1_COMPRESSED_LFB                                         7:7 /* R-IVF */
#define LW_SR_SR_CAPABILITIES1_COMPRESSED_LFB_INIT                             0x00000000 /* R-I-V */
#define LW_SR_SR_CAPABILITIES1_COMPRESSED_LFB_YES                              0x00000001 /* R---V */
#define LW_SR_SR_CAPABILITIES1_COMPRESSED_LFB_NO                               0x00000000 /* R---V */
#define LW_SR_SR_CAPABILITIES2                                                 0x00000337 /* R--1R */
#define LW_SR_SR_CAPABILITIES2_SEPERATE_PCLK                                          0:0 /* R-IVF */
#define LW_SR_SR_CAPABILITIES2_SEPERATE_PCLK_INIT                              0x00000000 /* R-I-V */
#define LW_SR_SR_CAPABILITIES2_SEPERATE_PCLK_SUPPORTED                         0x00000001 /* R---V */
#define LW_SR_SR_CAPABILITIES2_SEPERATE_PCLK_NOT_SUPPORTED                     0x00000000 /* R---V */
#define LW_SR_SR_CAPABILITIES2_BUFFERED_REFRESH                                       1:1 /* R-IVF */
#define LW_SR_SR_CAPABILITIES2_BUFFERED_REFRESH_INIT                           0x00000000 /* R-I-V */
#define LW_SR_SR_CAPABILITIES2_BUFFERED_REFRESH_SUPPORTED                      0x00000001 /* R---V */
#define LW_SR_SR_CAPABILITIES2_BUFFERED_REFRESH_NOT_SUPPORTED                  0x00000000 /* R---V */
#define LW_SR_SR_CAPABILITIES2_FRAME_LOCK                                             2:2 /* R-IVF */
#define LW_SR_SR_CAPABILITIES2_FRAME_LOCK_INIT                                 0x00000000 /* R-I-V */
#define LW_SR_SR_CAPABILITIES2_FRAME_LOCK_SUPPORTED                            0x00000001 /* R---V */
#define LW_SR_SR_CAPABILITIES2_FRAME_LOCK_NOT_SUPPORTED                        0x00000000 /* R---V */
#define LW_SR_SR_BUFFER_CAP                                                    0x00000338 /* R--1R */
#define LW_SR_SR_BUFFER_CAP_BUFFER_SIZE                                               7:0 /* R-IVF */
#define LW_SR_SR_BUFFER_CAP_BUFFER_SIZE_INIT                                   0x00000050 /* R-I-V */
#define LW_SR_SR_BUFFER_CAP_BUFFER_SIZE_8MB                                    0x00000050 /* R---V */
#define LW_SR_SR_MAX_PCLK0                                                     0x00000339 /* R--1R */
#define LW_SR_SR_MAX_PCLK0_VAL                                                        7:0 /* R-IVF */
#define LW_SR_SR_MAX_PCLK0_VAL_INIT                                            0x00000048 /* R-I-V */
#define LW_SR_SR_MAX_PCLK1                                                     0x0000033a /* R--1R */
#define LW_SR_SR_MAX_PCLK1_VAL                                                        7:0 /* R-IVF */
#define LW_SR_SR_MAX_PCLK1_VAL_INIT                                            0x0000003f /* R-I-V */
#define LW_SR_SR_CACHE_LATENCY0                                                0x0000033b /* R--1R */
#define LW_SR_SR_CACHE_LATENCY0_VAL                                                   7:0 /* R-IVF */
#define LW_SR_SR_CACHE_LATENCY0_VAL_INIT                                       0x00000000 /* R-I-V */
#define LW_SR_SR_CACHE_LATENCY1                                                0x0000033c /* R--1R */
#define LW_SR_SR_CACHE_LATENCY1_VAL                                                   7:0 /* R-IVF */
#define LW_SR_SR_CACHE_LATENCY1_VAL_INIT                                       0x00000000 /* R-I-V */
#define LW_SR_NLT_CTL                                                          0x00000334 /* RW-1R */
#define LW_SR_NLT_CTL_NLT_START                                                       0:0 /* RWIVF */
#define LW_SR_NLT_CTL_NLT_START_INIT                                           0x00000000 /* RWI-V */
#define LW_SR_NLT_CTL_NLT_START_INITIATE                                       0x00000001 /* RW--V */
#define LW_SR_NLT_CTL_NLT_START_SYNCED                                         0x00000000 /* RW--V */
#define LW_SR_SR_CAPABILITIES3                                                 0x0000033F /* R--1R */
#define LW_SR_SR_CAPABILITIES3_SR_FB_RETENTION                                        0:0 /* R-IVF */
#define LW_SR_SR_CAPABILITIES3_SR_FB_RETENTION_SUPPORTED                       0x00000001 /* R-I-V */
#define LW_SR_SR_CAPABILITIES3_SR_FB_RETENTION_NOT_SUPPORTED                   0x00000000 /* R-I-V */
#define LW_SR_SR_CAPABILITIES3_SRAO                                                   1:1 /* R-IVF */
#define LW_SR_SR_CAPABILITIES3_SRAO_SUPPORTED                                  0x00000001 /* R-I-V */
#define LW_SR_SR_CAPABILITIES3_SRAO_NOT_SUPPORTED                              0x00000000 /* R-I-V */
#define LW_SR_SR_CAPABILITIES3_CRASH_SYNC                                             4:2 /* R-IVF */
#define LW_SR_SR_CAPABILITIES3_CRASH_SYNC_UNKNOWN                              0x00000000 /* R-I-V */
#define LW_SR_SR_CAPABILITIES3_CRASH_SYNC_BLANK_ONLY                           0x00000001 /* R-I-V */
#define LW_SR_SR_CAPABILITIES3_CRASH_SYNC_IMMEDIATE                            0x00000002 /* R-I-V */
#define LW_SR_SR_CAPABILITIES3_CRASH_SYNC_BLANK_ONLY_AND_UPDATE                0x00000003 /* R-I-V */
#define LW_SR_SR_CAPABILITIES3_CRASH_SYNC_IMMEDIATE_AND_UPDATE                 0x00000007 /* R-I-V */
#define LW_SR_SRC_CTL0                                                         0x00000340 /* RW-1R */
#define LW_SR_SRC_CTL0_SR_ENABLE_CTL                                                  0:0 /* RWIVF */
#define LW_SR_SRC_CTL0_SR_ENABLE_CTL_INIT                                      0x00000001 /* RWI-V */
#define LW_SR_SRC_CTL0_SR_ENABLE_CTL_ENABLED                                   0x00000001 /* RW--V */
#define LW_SR_SRC_CTL0_SR_ENABLE_CTL_DISABLED                                  0x00000000 /* RW--V */
#define LW_SR_SRC_CTL0_SR_ENABLE_MASK                                                 1:1 /* RWIVF */
#define LW_SR_SRC_CTL0_SR_ENABLE_MASK_INIT                                     0x00000000 /* R-I-V */
#define LW_SR_SRC_CTL0_SR_ENABLE_MASK_DISABLE                                  0x00000000 /* R---V */
#define LW_SR_SRC_CTL0_SR_ENABLE_MASK_ENABLE                                   0x00000001 /* -W--V */
#define LW_SR_SRC_CTL0_SR_RESYNC_DISABLE                                              2:2 /* RWIVF */
#define LW_SR_SRC_CTL0_SR_RESYNC_DISABLE_INIT                                  0x00000000 /* RWI-V */
#define LW_SR_SRC_CTL0_SR_RESYNC_DISABLE_YES                                   0x00000001 /* RW--V */
#define LW_SR_SRC_CTL0_SR_RESYNC_DISABLE_NO                                    0x00000000 /* RW--V */
#define LW_SR_SRC_CTL0_SR_RESYNC_MASK                                                 3:3 /* RWIVF */
#define LW_SR_SRC_CTL0_SR_RESYNC_MASK_INIT                                     0x00000000 /* R-I-V */
#define LW_SR_SRC_CTL0_SR_RESYNC_MASK_DISABLE                                  0x00000000 /* R---V */
#define LW_SR_SRC_CTL0_SR_RESYNC_MASK_ENABLE                                   0x00000001 /* -W--V */
#define LW_SR_SRC_CTL0_SR_ENTRY_REQ                                                   4:4 /* RWIVF */
#define LW_SR_SRC_CTL0_SR_ENTRY_REQ_INIT                                       0x00000000 /* R-I-V */
#define LW_SR_SRC_CTL0_SR_ENTRY_REQ_DONE                                       0x00000000 /* R---V */
#define LW_SR_SRC_CTL0_SR_ENTRY_REQ_PENDING                                    0x00000001 /* R---V */
#define LW_SR_SRC_CTL0_SR_ENTRY_REQ_YES                                        0x00000001 /* -W--V */
#define LW_SR_SRC_CTL0_SR_ENTRY_MASK                                                  5:5 /* RWIVF */
#define LW_SR_SRC_CTL0_SR_ENTRY_MASK_INIT                                      0x00000000 /* R-I-V */
#define LW_SR_SRC_CTL0_SR_ENTRY_MASK_DISABLE                                   0x00000000 /* R---V */
#define LW_SR_SRC_CTL0_SR_ENTRY_MASK_ENABLE                                    0x00000001 /* -W--V */
#define LW_SR_SRC_CTL0_SR_EXIT_REQ                                                    6:6 /* RWIVF */
#define LW_SR_SRC_CTL0_SR_EXIT_REQ_INIT                                        0x00000000 /* R-I-V */
#define LW_SR_SRC_CTL0_SR_EXIT_REQ_DONE                                        0x00000000 /* R---V */
#define LW_SR_SRC_CTL0_SR_EXIT_REQ_PENDING                                     0x00000001 /* R---V */
#define LW_SR_SRC_CTL0_SR_EXIT_REQ_YES                                         0x00000001 /* -W--V */
#define LW_SR_SRC_CTL0_SR_EXIT_MASK                                                   7:7 /* RWIVF */
#define LW_SR_SRC_CTL0_SR_EXIT_MASK_INIT                                       0x00000000 /* R-I-V */
#define LW_SR_SRC_CTL0_SR_EXIT_MASK_DISABLE                                    0x00000000 /* R---V */
#define LW_SR_SRC_CTL0_SR_EXIT_MASK_ENABLE                                     0x00000001 /* -W--V */
#define LW_SR_SRC_CTL1                                                         0x00000341 /* RW-1R */
#define LW_SR_SRC_CTL1_PT_TIMING_LATCH                                                0:0 /* RWIVF */
#define LW_SR_SRC_CTL1_PT_TIMING_LATCH_INIT                                    0x00000000 /* RWI-V */
#define LW_SR_SRC_CTL1_PT_TIMING_LATCH_VSYNC                                   0x00000000 /* RW--V */
#define LW_SR_SRC_CTL1_PT_TIMING_LATCH_ASYNC                                   0x00000001 /* RW--V */
#define LW_SR_SRC_CTL1_PT_TIMING_MASK                                                 1:1 /* RWIVF */
#define LW_SR_SRC_CTL1_PT_TIMING_MASK_INIT                                     0x00000000 /* R-I-V */
#define LW_SR_SRC_CTL1_PT_TIMING_MASK_DISABLE                                  0x00000000 /* R---V */
#define LW_SR_SRC_CTL1_PT_TIMING_MASK_ENABLE                                   0x00000001 /* -W--V */
#define LW_SR_SRC_CTL1_SR_TIMING_LATCH                                                2:2 /* RWIVF */
#define LW_SR_SRC_CTL1_SR_TIMING_LATCH_INIT                                    0x00000000 /* RWI-V */
#define LW_SR_SRC_CTL1_SR_TIMING_LATCH_VSYNC                                   0x00000000 /* RW--V */
#define LW_SR_SRC_CTL1_SR_TIMING_LATCH_ASYNC                                   0x00000001 /* RW--V */
#define LW_SR_SRC_CTL1_SR_TIMING_MASK                                                 3:3 /* RWIVF */
#define LW_SR_SRC_CTL1_SR_TIMING_MASK_INIT                                     0x00000000 /* R-I-V */
#define LW_SR_SRC_CTL1_SR_TIMING_MASK_DISABLE                                  0x00000000 /* R---V */
#define LW_SR_SRC_CTL1_SR_TIMING_MASK_ENABLE                                   0x00000001 /* -W--V */
#define LW_SR_SRC_CTL1_SIDEBAND_ENTRY_SEL                                             4:4 /* RWIVF */
#define LW_SR_SRC_CTL1_SIDEBAND_ENTRY_SEL_INIT                                 0x00000000 /* RWI-V */
#define LW_SR_SRC_CTL1_SIDEBAND_ENTRY_SEL_YES                                  0x00000001 /* RW--V */
#define LW_SR_SRC_CTL1_SIDEBAND_ENTRY_SEL_NO                                   0x00000000 /* RW--V */
#define LW_SR_SRC_CTL1_SIDEBAND_ENTRY_MASK                                            5:5 /* RWIVF */
#define LW_SR_SRC_CTL1_SIDEBAND_ENTRY_MASK_INIT                                0x00000000 /* R-I-V */
#define LW_SR_SRC_CTL1_SIDEBAND_ENTRY_MASK_DISABLE                             0x00000000 /* R---V */
#define LW_SR_SRC_CTL1_SIDEBAND_ENTRY_MASK_ENABLE                              0x00000001 /* -W--V */
#define LW_SR_SRC_CTL1_SIDEBAND_EXIT_SEL                                              6:6 /* RWIVF */
#define LW_SR_SRC_CTL1_SIDEBAND_EXIT_SEL_INIT                                  0x00000000 /* RWI-V */
#define LW_SR_SRC_CTL1_SIDEBAND_EXIT_SEL_YES                                   0x00000001 /* RW--V */
#define LW_SR_SRC_CTL1_SIDEBAND_EXIT_SEL_NO                                    0x00000000 /* RW--V */
#define LW_SR_SRC_CTL1_SIDEBAND_EXIT_MASK                                             7:7 /* RWIVF */
#define LW_SR_SRC_CTL1_SIDEBAND_EXIT_MASK_INIT                                 0x00000000 /* R-I-V */
#define LW_SR_SRC_CTL1_SIDEBAND_EXIT_MASK_DISABLE                              0x00000000 /* R---V */
#define LW_SR_SRC_CTL1_SIDEBAND_EXIT_MASK_ENABLE                               0x00000001 /* -W--V */
#define LW_SR_SRC_CTL2                                                         0x00000342 /* RW-1R */
#define LW_SR_SRC_CTL2_CAPTURE_FRAMES                                                 3:0 /* RWIVF */
#define LW_SR_SRC_CTL2_CAPTURE_FRAMES_INIT                                     0x00000000 /* RWI-V */
#define LW_SR_SRC_CTL2_3DSTEREO_ENABLED                                               4:4 /* RWIVF */
#define LW_SR_SRC_CTL2_3DSTEREO_ENABLED_INIT                                   0x00000000 /* RWI-V */
#define LW_SR_SRC_CTL2_3DSTEREO_ENABLED_YES                                    0x00000001 /* RW--V */
#define LW_SR_SRC_CTL2_3DSTEREO_ENABLED_NO                                     0x00000000 /* RW--V */
#define LW_SR_SRC_CTL2_BUFFERED_BURST_REFRESH_MODE_ENABLED                            5:5 /* RWIVF */
#define LW_SR_SRC_CTL2_BUFFERED_BURST_REFRESH_MODE_ENABLED_INIT                0x00000000 /* RWI-V */
#define LW_SR_SRC_CTL2_BUFFERED_BURST_REFRESH_MODE_ENABLED_YES                 0x00000001 /* RW--V */
#define LW_SR_SRC_CTL2_BUFFERED_BURST_REFRESH_MODE_ENABLED_NO                  0x00000000 /* RW--V */
#define LW_SR_SRC_CTL2_SRC_FRAME_LOCK_ENABLED                                         6:6 /* RWIVF */
#define LW_SR_SRC_CTL2_SRC_FRAME_LOCK_ENABLED_INIT                             0x00000000 /* RWI-V */
#define LW_SR_SRC_CTL2_SRC_FRAME_LOCK_ENABLED_YES                              0x00000001 /* RW--V */
#define LW_SR_SRC_CTL2_SRC_FRAME_LOCK_ENABLED_NO                               0x00000000 /* RW--V */
#define LW_SR_INTR0                                                            0x00000343 /* RW-1R */
#define LW_SR_INTR0_SR_ENTRY_FAIL                                                     0:0 /* RWIVF */
#define LW_SR_INTR0_SR_ENTRY_FAIL_INIT                                         0x00000000 /* RWI-V */
#define LW_SR_INTR0_SR_ENTRY_FAIL_ENABLED                                      0x00000001 /* RW--V */
#define LW_SR_INTR0_SR_ENTRY_FAIL_DISABLED                                     0x00000000 /* RW--V */
#define LW_SR_INTR0_SR_ENTRY_MASK                                                     1:1 /* RWIVF */
#define LW_SR_INTR0_SR_ENTRY_MASK_INIT                                         0x00000000 /* R-I-V */
#define LW_SR_INTR0_SR_ENTRY_MASK_DISABLE                                      0x00000000 /* R---V */
#define LW_SR_INTR0_SR_ENTRY_MASK_ENABLE                                       0x00000001 /* -W--V */
#define LW_SR_INTR0_SR_EXIT_RESYNC_DONE                                               2:2 /* RWIVF */
#define LW_SR_INTR0_SR_EXIT_RESYNC_DONE_INIT                                   0x00000000 /* RWI-V */
#define LW_SR_INTR0_SR_EXIT_RESYNC_DONE_ENABLED                                0x00000001 /* RW--V */
#define LW_SR_INTR0_SR_EXIT_RESYNC_DONE_DISABLED                               0x00000000 /* RW--V */
#define LW_SR_INTR0_SR_EXIT_RESYNC_MASK                                               3:3 /* RWIVF */
#define LW_SR_INTR0_SR_EXIT_RESYNC_MASK_INIT                                   0x00000000 /* R-I-V */
#define LW_SR_INTR0_SR_EXIT_RESYNC_MASK_DISABLE                                0x00000000 /* R---V */
#define LW_SR_INTR0_SR_EXIT_RESYNC_MASK_ENABLE                                 0x00000001 /* -W--V */
#define LW_SR_INTR0_SR_BUFFER_OVERFLOW                                                4:4 /* RWIVF */
#define LW_SR_INTR0_SR_BUFFER_OVERFLOW_INIT                                    0x00000000 /* RWI-V */
#define LW_SR_INTR0_SR_BUFFER_OVERFLOW_ENABLED                                 0x00000001 /* RW--V */
#define LW_SR_INTR0_SR_BUFFER_OVERFLOW_DISABLED                                0x00000000 /* RW--V */
#define LW_SR_INTR0_SR_BUFFER_OVERFLOW_MASK                                           5:5 /* RWIVF */
#define LW_SR_INTR0_SR_BUFFER_OVERFLOW_MASK_INIT                               0x00000000 /* R-I-V */
#define LW_SR_INTR0_SR_BUFFER_OVERFLOW_MASK_DISABLE                            0x00000000 /* R---V */
#define LW_SR_INTR0_SR_BUFFER_OVERFLOW_MASK_ENABLE                             0x00000001 /* -W--V */
#define LW_SR_INTR0_SR_VERT_BLANK                                                     6:6 /* RWIVF */
#define LW_SR_INTR0_SR_VERT_BLANK_INIT                                         0x00000000 /* RWI-V */
#define LW_SR_INTR0_SR_VERT_BLANK_ENABLED                                      0x00000001 /* RW--V */
#define LW_SR_INTR0_SR_VERT_BLANK_DISABLED                                     0x00000000 /* RW--V */
#define LW_SR_INTR0_SR_VERT_BLANK_MASK                                                7:7 /* RWIVF */
#define LW_SR_INTR0_SR_VERT_BLANK_MASK_INIT                                    0x00000000 /* R-I-V */
#define LW_SR_INTR0_SR_VERT_BLANK_MASK_DISABLE                                 0x00000000 /* R---V */
#define LW_SR_INTR0_SR_VERT_BLANK_MASK_ENABLE                                  0x00000001 /* -W--V */
#define LW_SR_INTR1                                                            0x00000344 /* RW-1R */
#define LW_SR_INTR1_EN                                                                0:0 /* RWIVF */
#define LW_SR_INTR1_EN_INIT                                                    0x00000000 /* RWI-V */
#define LW_SR_INTR1_EN_YES                                                     0x00000001 /* RW--V */
#define LW_SR_INTR1_EN_NO                                                      0x00000000 /* RW--V */
#define LW_SR_INTR1_EN_MASK                                                           1:1 /* RWIVF */
#define LW_SR_INTR1_EN_MASK_INIT                                               0x00000000 /* R-I-V */
#define LW_SR_INTR1_EN_MASK_DISABLE                                            0x00000000 /* R---V */
#define LW_SR_INTR1_EN_MASK_ENABLE                                             0x00000001 /* -W--V */
#define LW_SR_RESYNC_CTL                                                       0x00000346 /* RW-1R */
#define LW_SR_RESYNC_CTL_METHOD                                                       2:0 /* RWIVF */
#define LW_SR_RESYNC_CTL_METHOD_INIT                                           0x00000002 /* RWI-V */
#define LW_SR_RESYNC_CTL_METHOD_IMM                                            0x00000000 /* RW--V */
#define LW_SR_RESYNC_CTL_METHOD_SS                                             0x00000001 /* RW--V */
#define LW_SR_RESYNC_CTL_METHOD_FL                                             0x00000002 /* RW--V */
#define LW_SR_RESYNC_CTL_METHOD_BS                                             0x00000003 /* RW--V */
#define LW_SR_RESYNC_CTL_DELAY                                                        7:6 /* RWIVF */
#define LW_SR_RESYNC_CTL_DELAY_INIT                                            0x00000001 /* RWI-V */
#define LW_SR_RESYNC_CTL_DELAY_NO_DELAY                                        0x00000000 /* RW--V */
#define LW_SR_STATUS                                                           0x00000348 /* R--1R */
#define LW_SR_STATUS_SR_STATE                                                         2:0 /* R-IVF */
#define LW_SR_STATUS_SR_STATE_INIT                                             0x00000001 /* R-I-V */
#define LW_SR_STATUS_SR_STATE_OFFLINE                                          0x00000000 /* R---V */
#define LW_SR_STATUS_SR_STATE_IDLE                                             0x00000001 /* R---V */
#define LW_SR_STATUS_SR_STATE_SR_ENTRY_TRIG                                    0x00000002 /* R---V */
#define LW_SR_STATUS_SR_STATE_SR_ENTRY_CACHING                                 0x00000003 /* R---V */
#define LW_SR_STATUS_SR_STATE_SR_ENTRY_RDY                                     0x00000004 /* R---V */
#define LW_SR_STATUS_SR_STATE_SR_ACTIVE                                        0x00000005 /* R---V */
#define LW_SR_STATUS_SR_STATE_SR_EXIT_TRIG                                     0x00000006 /* R---V */
#define LW_SR_STATUS_SR_STATE_SR_EXIT_RESYNC                                   0x00000007 /* R---V */
#define LW_SR_STATUS_SR_FAIL                                                          4:3 /* R-IVF */
#define LW_SR_STATUS_SR_FAIL_INIT                                              0x00000000 /* R-I-V */
#define LW_SR_STATUS_SR_FAIL_NOERR                                             0x00000000 /* R---V */
#define LW_SR_STATUS_SR_FAIL_ENTRY                                             0x00000001 /* R---V */
#define LW_SR_STATUS_SR_FAIL_RESYNC                                            0x00000002 /* R---V */
#define LW_SR_STATUS_SR_FAIL_REENTER                                           0x00000003 /* R---V */
#define LW_SR_STATUS_SR_BURST_STATE                                                   6:5 /* R-IVF */
#define LW_SR_STATUS_SR_BURST_STATE_RESYNC                                     0x00000001 /* R---V */
#define LW_SR_STATUS_SR_BURST_STATE_IN_SR                                      0x00000000 /* R---V */
#define LW_SR_STATUS_BUFFER_OVERRUN                                                   7:7 /* R-IVF */
#define LW_SR_STATUS_BUFFER_OVERRUN_INIT                                       0x00000000 /* R-I-V */
#define LW_SR_STATUS_BUFFER_OVERRUN_YES                                        0x00000001 /* R---V */
#define LW_SR_STATUS_BUFFER_OVERRUN_NO                                         0x00000000 /* R---V */
#define LW_SR_INTR                                                             0x00000349 /* R--1R */
#define LW_SR_INTR_STAT                                                               0:0 /* RWIVF */
#define LW_SR_INTR_STAT_INIT                                                   0x00000000 /* RWI-V */
#define LW_SR_INTR_STAT_INTR_PENDING                                           0x00000001 /* R---V */
#define LW_SR_INTR_STAT_INTR_NOT_PENDING                                       0x00000000 /* R---V */
#define LW_SR_INTR_STAT_CLEAR_INTR                                             0x00000000 /* -W--V */
#define LW_SR_INTR_MASK                                                               1:1 /* RWIVF */
#define LW_SR_INTR_MASK_INIT                                                   0x00000000 /* R-I-V */
#define LW_SR_INTR_MASK_DISABLE                                                0x00000000 /* R---V */
#define LW_SR_INTR_MASK_ENABLE                                                 0x00000001 /* -W--V */
#define LW_SR_SRC_EXT_CAP                                                      0x0000034A /* RW-1R */
#define LW_SR_SRC_EXT_CAP_FB_RETENTION                                                1:0 /* R-IVF */
#define LW_SR_SRC_EXT_CAP_FB_RETENTION_DEFAULT                                 0x00000000 /* R-I-V */
#define LW_SR_SRC_EXT_CAP_FB_RETENTION_NO                                      0x00000000 /* R---V */
#define LW_SR_SRC_EXT_CAP_FB_RETENTION_POWER_DOWN                              0x00000001 /* R---V */
#define LW_SR_SRC_EXT_CAP_FB_RETENTION_POWER_DOWN_AUTO_POWER_SEQUENCE          0x00000002 /* R---V */
#define LW_SR_SRC_EXT_CAP_LCD_EXT_ILW_PATTERN                                         6:6 /* R-IVF */
#define LW_SR_SRC_EXT_CAP_LCD_ILW_PATTERN                                             7:7 /* R-IVF */
#define LW_SR_SRC_EXT_CAP_LCD_ILW_PATTERN_NEGATIVE                             0x00000000 /* R---V */
#define LW_SR_SRC_EXT_CAP_LCD_ILW_PATTERN_POSITIVE                             0x00000001 /* R---V */
#define LW_SR_SRMODE_PIXEL_CLOCK0                                              0x00000350 /* RW-1R */
#define LW_SR_SRMODE_PIXEL_CLOCK0_VAL                                                 7:0 /* RWIVF */
#define LW_SR_SRMODE_PIXEL_CLOCK0_VAL_INIT                                     0x0000001a /* RWI-V */
#define LW_SR_SRMODE_PIXEL_CLOCK1                                              0x00000351 /* RW-1R */
#define LW_SR_SRMODE_PIXEL_CLOCK1_VAL                                                 7:0 /* RWIVF */
#define LW_SR_SRMODE_PIXEL_CLOCK1_VAL_INIT                                     0x00000036 /* RWI-V */
#define LW_SR_SRMODE_TIMING0                                                   0x00000352 /* RW-1R */
#define LW_SR_SRMODE_TIMING0_HORZ_ACTIVE0                                             7:0 /* RWIVF */
#define LW_SR_SRMODE_TIMING0_HORZ_ACTIVE0_INIT                                 0x00000080 /* RWI-V */
#define LW_SR_SRMODE_TIMING1                                                   0x00000353 /* RW-1R */
#define LW_SR_SRMODE_TIMING1_HORZ_ACTIVE1                                             7:0 /* RWIVF */
#define LW_SR_SRMODE_TIMING1_HORZ_ACTIVE1_INIT                                 0x00000007 /* RWI-V */
#define LW_SR_SRMODE_TIMING2                                                   0x00000354 /* RW-1R */
#define LW_SR_SRMODE_TIMING2_HORZ_BLANK0                                              7:0 /* RWIVF */
#define LW_SR_SRMODE_TIMING2_HORZ_BLANK0_INIT                                  0x000000a0 /* RWI-V */
#define LW_SR_SRMODE_TIMING3                                                   0x00000355 /* RW-1R */
#define LW_SR_SRMODE_TIMING3_HORZ_BLANK1                                              7:0 /* RWIVF */
#define LW_SR_SRMODE_TIMING3_HORZ_BLANK1_INIT                                  0x00000000 /* RWI-V */
#define LW_SR_SRMODE_TIMING4                                                   0x00000356 /* RW-1R */
#define LW_SR_SRMODE_TIMING4_HORZ_FRONT_PORCH0                                        7:0 /* RWIVF */
#define LW_SR_SRMODE_TIMING4_HORZ_FRONT_PORCH0_INIT                            0x00000030 /* RWI-V */
#define LW_SR_SRMODE_TIMING5                                                   0x00000357 /* RW-1R */
#define LW_SR_SRMODE_TIMING5_HORZ_FRONT_PORCH1                                        7:0 /* RWIVF */
#define LW_SR_SRMODE_TIMING5_HORZ_FRONT_PORCH1_INIT                            0x00000000 /* RWI-V */
#define LW_SR_SRMODE_TIMING6                                                   0x00000358 /* RW-1R */
#define LW_SR_SRMODE_TIMING6_HORZ_BACK_PORCH0                                         7:0 /* RWIVF */
#define LW_SR_SRMODE_TIMING6_HORZ_BACK_PORCH0_INIT                             0x00000050 /* RWI-V */
#define LW_SR_SRMODE_TIMING7                                                   0x00000359 /* RW-1R */
#define LW_SR_SRMODE_TIMING7_HORZ_BACK_PORCH1                                         7:0 /* RWIVF */
#define LW_SR_SRMODE_TIMING7_HORZ_BACK_PORCH1_INIT                             0x00000000 /* RWI-V */
#define LW_SR_SRMODE_TIMING8                                                   0x0000035a /* RW-1R */
#define LW_SR_SRMODE_TIMING8_HSYNC                                                    7:0 /* RWIVF */
#define LW_SR_SRMODE_TIMING8_HSYNC_INIT                                        0x00000020 /* RWI-V */
#define LW_SR_SRMODE_TIMING9                                                   0x0000035b /* RW-1R */
#define LW_SR_SRMODE_TIMING9_HORZ_BORDER                                              6:0 /* RWIVF */
#define LW_SR_SRMODE_TIMING9_HORZ_BORDER_INIT                                  0x00000000 /* RWI-V */
#define LW_SR_SRMODE_TIMING9_HSYNC_POL                                                7:7 /* RWIVF */
#define LW_SR_SRMODE_TIMING9_HSYNC_POL_INIT                                    0x00000000 /* RWI-V */
#define LW_SR_SRMODE_TIMING9_HSYNC_POL_POS                                     0x00000001 /* RW--V */
#define LW_SR_SRMODE_TIMING9_HSYNC_POL_NEG                                     0x00000000 /* RW--V */
#define LW_SR_SRMODE_TIMING10                                                  0x0000035c /* RW-1R */
#define LW_SR_SRMODE_TIMING10_VERT_ACTIVE0                                            7:0 /* RWIVF */
#define LW_SR_SRMODE_TIMING10_VERT_ACTIVE0_INIT                                0x00000038 /* RWI-V */
#define LW_SR_SRMODE_TIMING11                                                  0x0000035d /* RW-1R */
#define LW_SR_SRMODE_TIMING11_VERT_ACTIVE1                                            7:0 /* RWIVF */
#define LW_SR_SRMODE_TIMING11_VERT_ACTIVE1_INIT                                0x00000004 /* RWI-V */
#define LW_SR_SRMODE_TIMING12                                                  0x0000035e /* RW-1R */
#define LW_SR_SRMODE_TIMING12_VERT_BLANK0                                             7:0 /* RWIVF */
#define LW_SR_SRMODE_TIMING12_VERT_BLANK0_INIT                                 0x0000001f /* RWI-V */
#define LW_SR_SRMODE_TIMING13                                                  0x0000035f /* RW-1R */
#define LW_SR_SRMODE_TIMING13_VERT_BLANK1                                             7:0 /* RWIVF */
#define LW_SR_SRMODE_TIMING13_VERT_BLANK1_INIT                                 0x00000000 /* RWI-V */
#define LW_SR_SRMODE_TIMING14                                                  0x00000360 /* RW-1R */
#define LW_SR_SRMODE_TIMING14_VERT_FRONT_PORCH0                                       7:0 /* RWIVF */
#define LW_SR_SRMODE_TIMING14_VERT_FRONT_PORCH0_INIT                           0x00000003 /* RWI-V */
#define LW_SR_SRMODE_TIMING15                                                  0x00000361 /* RW-1R */
#define LW_SR_SRMODE_TIMING15_VERT_FRONT_PORCH1                                       7:0 /* RWIVF */
#define LW_SR_SRMODE_TIMING15_VERT_FRONT_PORCH1_INIT                           0x00000000 /* RWI-V */
#define LW_SR_SRMODE_TIMING16                                                  0x00000362 /* RW-1R */
#define LW_SR_SRMODE_TIMING16_VERT_BACK_PORCH0                                        7:0 /* RWIVF */
#define LW_SR_SRMODE_TIMING16_VERT_BACK_PORCH0_INIT                            0x00000017 /* RWI-V */
#define LW_SR_SRMODE_TIMING17                                                  0x00000363 /* RW-1R */
#define LW_SR_SRMODE_TIMING17_VERT_BACK_PORCH1                                        7:0 /* RWIVF */
#define LW_SR_SRMODE_TIMING17_VERT_BACK_PORCH1_INIT                            0x00000000 /* RWI-V */
#define LW_SR_SRMODE_TIMING18                                                  0x00000364 /* RW-1R */
#define LW_SR_SRMODE_TIMING18_VERT_SYNC                                               7:0 /* RWIVF */
#define LW_SR_SRMODE_TIMING18_VERT_SYNC_INIT                                   0x00000005 /* RWI-V */
#define LW_SR_SRMODE_TIMING19                                                  0x00000365 /* RW-1R */
#define LW_SR_SRMODE_TIMING19_VERT_BORDER                                             6:0 /* RWIVF */
#define LW_SR_SRMODE_TIMING19_VERT_BORDER_INIT                                 0x00000000 /* RWI-V */
#define LW_SR_SRMODE_TIMING19_VSYNC_POL                                               7:7 /* RWIVF */
#define LW_SR_SRMODE_TIMING19_VSYNC_POL_INIT                                   0x00000000 /* RWI-V */
#define LW_SR_SRMODE_TIMING19_VSYNC_POL_POS                                    0x00000001 /* RW--V */
#define LW_SR_SRMODE_TIMING19_VSYNC_POL_NEG                                    0x00000000 /* RW--V */
#define LW_SR_SRMODE_CRASH_SYNC                                                0x00000366 /* RW-1R */
#define LW_SR_SRMODE_CRASH_SYNC_REQUEST                                               2:0 /* RWIVF */
#define LW_SR_SRMODE_CRASH_SYNC_REQUEST_NORMAL                                 0x00000000 /* RWI-V */
#define LW_SR_SRMODE_CRASH_SYNC_REQUEST_DELAY_RESET                            0x00000001 /* RWI-V */
#define LW_SR_SRMODE_CRASH_SYNC_REQUEST_IMM_RESET                              0x00000003 /* RWI-V */
#define LW_SR_SRMODE_CRASH_SYNC_REQUEST_DELAY_RESET_AND_UPDATE                 0x00000005 /* RWI-V */
#define LW_SR_SRMODE_CRASH_SYNC_REQUEST_IMM_RESET_AND_UPDATE                   0x00000007 /* RWI-V */
#define LW_SR_SRMODE_CRASH_SYNC_SRFP                                                  5:4 /* RWIVF */
#define LW_SR_SRMODE_CRASH_SYNC_SRFP_NORMAL                                    0x00000000 /* RWI-V */
#define LW_SR_SRMODE_CRASH_SYNC_SRFP_REPEAT                                    0x00000001 /* RWI-V */
#define LW_SR_PTMODE_PIXEL_CLOCK0                                              0x00000368 /* RW-1R */
#define LW_SR_PTMODE_PIXEL_CLOCK0_VAL                                                 7:0 /* RWIVF */
#define LW_SR_PTMODE_PIXEL_CLOCK0_VAL_INIT                                     0x0000001a /* RWI-V */
#define LW_SR_PTMODE_PIXEL_CLOCK1                                              0x00000369 /* RW-1R */
#define LW_SR_PTMODE_PIXEL_CLOCK1_VAL                                                 7:0 /* RWIVF */
#define LW_SR_PTMODE_PIXEL_CLOCK1_VAL_INIT                                     0x00000036 /* RWI-V */
#define LW_SR_PTMODE_TIMING0                                                   0x0000036a /* RW-1R */
#define LW_SR_PTMODE_TIMING0_HORZ_ACTIVE0                                             7:0 /* RWIVF */
#define LW_SR_PTMODE_TIMING0_HORZ_ACTIVE0_INIT                                 0x00000080 /* RWI-V */
#define LW_SR_PTMODE_TIMING1                                                   0x0000036b /* RW-1R */
#define LW_SR_PTMODE_TIMING1_HORZ_ACTIVE1                                             7:0 /* RWIVF */
#define LW_SR_PTMODE_TIMING1_HORZ_ACTIVE1_INIT                                 0x00000007 /* RWI-V */
#define LW_SR_PTMODE_TIMING2                                                   0x0000036c /* RW-1R */
#define LW_SR_PTMODE_TIMING2_HORZ_BLANK0                                              7:0 /* RWIVF */
#define LW_SR_PTMODE_TIMING2_HORZ_BLANK0_INIT                                  0x000000a0 /* RWI-V */
#define LW_SR_PTMODE_TIMING3                                                   0x0000036d /* RW-1R */
#define LW_SR_PTMODE_TIMING3_HORZ_BLANK1                                              7:0 /* RWIVF */
#define LW_SR_PTMODE_TIMING3_HORZ_BLANK1_INIT                                  0x00000000 /* RWI-V */
#define LW_SR_PTMODE_TIMING4                                                   0x0000036e /* RW-1R */
#define LW_SR_PTMODE_TIMING4_HORZ_FRONT_PORCH0                                        7:0 /* RWIVF */
#define LW_SR_PTMODE_TIMING4_HORZ_FRONT_PORCH0_INIT                            0x00000030 /* RWI-V */
#define LW_SR_PTMODE_TIMING5                                                   0x0000036f /* RW-1R */
#define LW_SR_PTMODE_TIMING5_HORZ_FRONT_PORCH1                                        7:0 /* RWIVF */
#define LW_SR_PTMODE_TIMING5_HORZ_FRONT_PORCH1_INIT                            0x00000000 /* RWI-V */
#define LW_SR_PTMODE_TIMING6                                                   0x00000370 /* RW-1R */
#define LW_SR_PTMODE_TIMING6_HORZ_BACK_PORCH0                                         7:0 /* RWIVF */
#define LW_SR_PTMODE_TIMING6_HORZ_BACK_PORCH0_INIT                             0x00000050 /* RWI-V */
#define LW_SR_PTMODE_TIMING7                                                   0x00000371 /* RW-1R */
#define LW_SR_PTMODE_TIMING7_HORZ_BACK_PORCH1                                         7:0 /* RWIVF */
#define LW_SR_PTMODE_TIMING7_HORZ_BACK_PORCH1_INIT                             0x00000000 /* RWI-V */
#define LW_SR_PTMODE_TIMING8                                                   0x00000372 /* RW-1R */
#define LW_SR_PTMODE_TIMING8_HSYNC                                                    7:0 /* RWIVF */
#define LW_SR_PTMODE_TIMING8_HSYNC_INIT                                        0x00000020 /* RWI-V */
#define LW_SR_PTMODE_TIMING9                                                   0x00000373 /* RW-1R */
#define LW_SR_PTMODE_TIMING9_HORZ_BORDER                                              6:0 /* RWIVF */
#define LW_SR_PTMODE_TIMING9_HORZ_BORDER_INIT                                  0x00000000 /* RWI-V */
#define LW_SR_PTMODE_TIMING9_HSYNC_POL                                                7:7 /* RWIVF */
#define LW_SR_PTMODE_TIMING9_HSYNC_POL_INIT                                    0x00000000 /* RWI-V */
#define LW_SR_PTMODE_TIMING9_HSYNC_POL_POS                                     0x00000001 /* RW--V */
#define LW_SR_PTMODE_TIMING9_HSYNC_POL_NEG                                     0x00000000 /* RW--V */
#define LW_SR_PTMODE_TIMING10                                                  0x00000374 /* RW-1R */
#define LW_SR_PTMODE_TIMING10_VERT_ACTIVE0                                            7:0 /* RWIVF */
#define LW_SR_PTMODE_TIMING10_VERT_ACTIVE0_INIT                                0x00000038 /* RWI-V */
#define LW_SR_PTMODE_TIMING11                                                  0x00000375 /* RW-1R */
#define LW_SR_PTMODE_TIMING11_VERT_ACTIVE1                                            7:0 /* RWIVF */
#define LW_SR_PTMODE_TIMING11_VERT_ACTIVE1_INIT                                0x00000004 /* RWI-V */
#define LW_SR_PTMODE_TIMING12                                                  0x00000376 /* RW-1R */
#define LW_SR_PTMODE_TIMING12_VERT_BLANK0                                             7:0 /* RWIVF */
#define LW_SR_PTMODE_TIMING12_VERT_BLANK0_INIT                                 0x0000001f /* RWI-V */
#define LW_SR_PTMODE_TIMING13                                                  0x00000377 /* RW-1R */
#define LW_SR_PTMODE_TIMING13_VERT_BLANK1                                             7:0 /* RWIVF */
#define LW_SR_PTMODE_TIMING13_VERT_BLANK1_INIT                                 0x00000000 /* RWI-V */
#define LW_SR_PTMODE_TIMING14                                                  0x00000378 /* RW-1R */
#define LW_SR_PTMODE_TIMING14_VERT_FRONT_PORCH0                                       7:0 /* RWIVF */
#define LW_SR_PTMODE_TIMING14_VERT_FRONT_PORCH0_INIT                           0x00000003 /* RWI-V */
#define LW_SR_PTMODE_TIMING15                                                  0x00000379 /* RW-1R */
#define LW_SR_PTMODE_TIMING15_VERT_FRONT_PORCH1                                       7:0 /* RWIVF */
#define LW_SR_PTMODE_TIMING15_VERT_FRONT_PORCH1_INIT                           0x00000000 /* RWI-V */
#define LW_SR_PTMODE_TIMING16                                                  0x0000037a /* RW-1R */
#define LW_SR_PTMODE_TIMING16_VERT_BACK_PORCH0                                        7:0 /* RWIVF */
#define LW_SR_PTMODE_TIMING16_VERT_BACK_PORCH0_INIT                            0x00000017 /* RWI-V */
#define LW_SR_PTMODE_TIMING17                                                  0x0000037b /* RW-1R */
#define LW_SR_PTMODE_TIMING17_VERT_BACK_PORCH1                                        7:0 /* RWIVF */
#define LW_SR_PTMODE_TIMING17_VERT_BACK_PORCH1_INIT                            0x00000000 /* RWI-V */
#define LW_SR_PTMODE_TIMING18                                                  0x0000037c /* RW-1R */
#define LW_SR_PTMODE_TIMING18_VERT_SYNC                                               7:0 /* RWIVF */
#define LW_SR_PTMODE_TIMING18_VERT_SYNC_INIT                                   0x00000005 /* RWI-V */
#define LW_SR_PTMODE_TIMING19                                                  0x0000037d /* RW-1R */
#define LW_SR_PTMODE_TIMING19_VERT_BORDER                                             6:0 /* RWIVF */
#define LW_SR_PTMODE_TIMING19_VERT_BORDER_INIT                                 0x00000000 /* RWI-V */
#define LW_SR_PTMODE_TIMING19_VSYNC_POL                                               7:7 /* RWIVF */
#define LW_SR_PTMODE_TIMING19_VSYNC_POL_INIT                                   0x00000000 /* RWI-V */
#define LW_SR_PTMODE_TIMING19_VSYNC_POL_POS                                    0x00000001 /* RW--V */
#define LW_SR_PTMODE_TIMING19_VSYNC_POL_NEG                                    0x00000000 /* RW--V */
#define LW_SR_LINK0                                                            0x00000380 /* R--1R */
#define LW_SR_LINK0_GPU_LANE_WIDTH                                                    3:0 /* R-IVF */
#define LW_SR_LINK0_GPU_LANE_WIDTH_INIT                                        0x00000001 /* R-I-V */
#define LW_SR_LINK0_GPU_LANE_WIDTH_1LANE                                       0x00000000 /* R---V */
#define LW_SR_LINK0_GPU_LANE_WIDTH_2LANE                                       0x00000001 /* R---V */
#define LW_SR_LINK0_GPU_LANE_WIDTH_3LANE                                       0x00000002 /* R---V */
#define LW_SR_LINK0_GPU_LANE_WIDTH_4LANE                                       0x00000003 /* R---V */
#define LW_SR_LINK0_GPU_GANGING                                                       4:4 /* R-IVF */
#define LW_SR_LINK0_GPU_GANGING_INIT                                           0x00000000 /* R-I-V */
#define LW_SR_LINK0_GPU_GANGING_SUPPORTED                                      0x00000001 /* R---V */
#define LW_SR_LINK0_GPU_GANGING_NOT_SUPPORTED                                  0x00000000 /* R---V */
#define LW_SR_LINK0_GPU_PXL_DEPTH                                                     7:5 /* R-IVF */
#define LW_SR_LINK0_GPU_PXL_DEPTH_INIT                                         0x00000000 /* R-I-V */
#define LW_SR_LINK0_GPU_PXL_DEPTH_18                                           0x00000000 /* R---V */
#define LW_SR_LINK0_GPU_PXL_DEPTH_24                                           0x00000001 /* R---V */
#define LW_SR_LINK0_GPU_PXL_DEPTH_30                                           0x00000002 /* R---V */
#define LW_SR_LINK1                                                            0x00000381 /* R--1R */
#define LW_SR_TCON_HDR_CAP                                                     0x00000381 /* R--1R */
#define LW_SR_TCON_HDR_CAP_RBAC                                                       0:0 /* R-IVF */
#define LW_SR_TCON_HDR_CAP_RBAC_NO                                             0x00000000 /* R---V */
#define LW_SR_TCON_HDR_CAP_RBAC_YES                                            0x00000001 /* R---V */
#define LW_SR_TCON_HDR_CAP_PQDC                                                       1:1 /* R-IVF */
#define LW_SR_TCON_HDR_CAP_PQDC_NO                                             0x00000000 /* R---V */
#define LW_SR_TCON_HDR_CAP_PQDC_YES                                            0x00000001 /* R---V */
#define LW_SR_TCON_HDR_CAP_TMOC                                                       2:2 /* R-IVF */
#define LW_SR_TCON_HDR_CAP_TMOC_NO                                             0x00000000 /* R---V */
#define LW_SR_TCON_HDR_CAP_TMOC_YES                                            0x00000001 /* R---V */
#define LW_SR_TCON_HDR_CAP_GMOC                                                       3:3 /* R-IVF */
#define LW_SR_TCON_HDR_CAP_GMOC_NO                                             0x00000000 /* R---V */
#define LW_SR_TCON_HDR_CAP_GMOC_YES                                            0x00000001 /* R---V */
#define LW_SR_TCON_HDR_CONTROL                                                 0x00000382 /* RW-1R */
#define LW_SR_TCON_HDR_CONTROL_RBAE                                                   0:0 /* R-IVF */
#define LW_SR_TCON_HDR_CONTROL_RBAE_NO                                         0x00000000 /* R---V */
#define LW_SR_TCON_HDR_CONTROL_RBAE_YES                                        0x00000001 /* R---V */
#define LW_SR_TCON_HDR_CONTROL_HDRO                                                   1:1 /* R-IVF */
#define LW_SR_TCON_HDR_CONTROL_HDRO_NO                                         0x00000000 /* R---V */
#define LW_SR_TCON_HDR_CONTROL_HDRO_YES                                        0x00000001 /* R---V */
#define LW_SR_TCON_HDR_CONTROL_PDQE                                                   2:2 /* R-IVF */
#define LW_SR_TCON_HDR_CONTROL_PDQE_NO                                         0x00000000 /* R---V */
#define LW_SR_TCON_HDR_CONTROL_PDQE_YES                                        0x00000001 /* R---V */
#define LW_SR_TCON_HDR_CONTROL_TMOE                                                   3:3 /* R-IVF */
#define LW_SR_TCON_HDR_CONTROL_TMOE_NO                                         0x00000000 /* R---V */
#define LW_SR_TCON_HDR_CONTROL_TMOE_YES                                        0x00000001 /* R---V */
#define LW_SR_TCON_HDR_CONTROL_GMOE                                                   4:4 /* R-IVF */
#define LW_SR_TCON_HDR_CONTROL_GMOE_NO                                         0x00000000 /* R---V */
#define LW_SR_TCON_HDR_CONTROL_GMOE_YES                                        0x00000001 /* R---V */
#define LW_SR_BLANK_TIMING0                                                    0x00000388 /* RW-1R */
#define LW_SR_BLANK_TIMING0_VBLANK_MIN0                                               7:0 /* RWIVF */
#define LW_SR_BLANK_TIMING0_VBLANK_MIN0_INIT                                   0x00000016 /* RWI-V */
#define LW_SR_BLANK_TIMING1                                                    0x00000389 /* RW-1R */
#define LW_SR_BLANK_TIMING1_VBLANK_MIN1                                               7:0 /* RWIVF */
#define LW_SR_BLANK_TIMING1_VBLANK_MIN1_INIT                                   0x00000000 /* RWI-V */
#define LW_SR_BLANK_TIMING2                                                    0x0000038a /* RW-1R */
#define LW_SR_BLANK_TIMING2_VBLANK_MAX0                                               7:0 /* RWIVF */
#define LW_SR_BLANK_TIMING2_VBLANK_MAX0_INIT                                   0x00000045 /* RWI-V */
#define LW_SR_BLANK_TIMING3                                                    0x0000038b /* RW-1R */
#define LW_SR_BLANK_TIMING3_VBLANK_MAX1                                               7:0 /* RWIVF */
#define LW_SR_BLANK_TIMING3_VBLANK_MAX1_INIT                                   0x00000002 /* RWI-V */
#define LW_SR_BLANK_TIMING4                                                    0x0000038c /* RW-1R */
#define LW_SR_BLANK_TIMING4_HBLANK_MIN0                                               7:0 /* RWIVF */
#define LW_SR_BLANK_TIMING4_HBLANK_MIN0_INIT                                   0x00000064 /* RWI-V */
#define LW_SR_BLANK_TIMING5                                                    0x0000038d /* RW-1R */
#define LW_SR_BLANK_TIMING5_HBLANK_MIN1                                               7:0 /* RWIVF */
#define LW_SR_BLANK_TIMING5_HBLANK_MIN1_INIT                                   0x00000000 /* RWI-V */
#define LW_SR_BLANK_TIMING6                                                    0x0000038e /* RW-1R */
#define LW_SR_BLANK_TIMING6_HBLANK_MAX0                                               7:0 /* RWIVF */
#define LW_SR_BLANK_TIMING6_HBLANK_MAX0_INIT                                   0x000000ec /* RWI-V */
#define LW_SR_BLANK_TIMING7                                                    0x0000038f /* RW-1R */
#define LW_SR_BLANK_TIMING7_HBLANK_MAX1                                               7:0 /* RWIVF */
#define LW_SR_BLANK_TIMING7_HBLANK_MAX1_INIT                                   0x00000000 /* RWI-V */
#define LW_SR_DEBUG0                                                           0x00000390 /* R--4R */
#define LW_SR_DEBUG0_LAST_SR_FRAME_CNT                                               30:0 /* R-IVF */
#define LW_SR_DEBUG0_LAST_SR_FRAME_CNT_INIT                                    0x00000000 /* R-I-V */
#define LW_SR_DEBUG0_ROLLOVER_DETECT                                                31:31 /* R-IVF */
#define LW_SR_DEBUG0_ROLLOVER_DETECT_INIT                                      0x00000000 /* R-I-V */
#define LW_SR_FRAME_LWRRENT_SCAN_LINE                                          0x00000394 /* R--3R */
#define LW_SR_DEBUG4_PANEL_TIMING_STAT                                                2:0 /* R-IVF */
#define LW_SR_DEBUG4_PANEL_TIMING_STAT_INIT                                    0x00000000 /* R-I-V */
#endif // _LW_REF_DEV_SR_H_
