---
- name: configure OpenMPI on servers
  hosts: localhost
  become: true
  vars:
  remote_user: root
  tasks:
   - name: install the required packages for OpenMPI
     action: apt package={{item}} state=present
     with_items:
     - openmpi-bin
     - openmpi-common
     - openmpi-doc
     - libopenmpi-dev
     - libopenmpi2