##############################################################################
# Copyright (c) 2019-2021, LWPU CORPORATION.  All rights reserved.
#
# LWPU CORPORATION and its licensors retain all intellectual property
# and proprietary rights in and to this software, related documentation
# and any modifications thereto.  Any use, reproduction, disclosure or
# distribution of this software and related documentation without an express
# license agreement from LWPU CORPORATION is strictly prohibited.
##############################################################################

##############################################################################
# tests/lwsciipc makefile
##############################################################################

##############################################################################
# Identify this module to lwCommon.lwmk so it can decide the build type
##############################################################################

LW_MODULE_BUILD_TYPE_ALIASES = test_lwsciipc
LW_MODULE_LOGGING_NAME = "test_lwsciipc"

include $(LW_SOURCE)/drivers/common/build/lwCommon.lwmk
include $(LW_SOURCE)/drivers/common/build/lwconfig.lwmk

##############################################################################
# Path shorthands
##############################################################################

LWSCI_PATH              = $(LW_SOURCE)/drivers/lwsci
LWSCIIPC_PATH           = $(LWSCI_PATH)/lwsciipc
LWSCI_TESTS_PATH        = $(LWSCI_PATH)/tests
LWSCIIPC_TESTS_PATH     = $(LWSCI_TESTS_PATH)/lwsciipc/src


##############################################################################
# define SOURCES
##############################################################################

LWSCIIPC_READ_TEST_SOURCES += src/test_lwsciipc_read.c
LWSCIIPC_WRITE_TEST_SOURCES += src/test_lwsciipc_write.c
LWSCIIPC_PERF_TEST_SOURCES += src/test_lwsciipc_perf.c

SOURCES += $(LWSCIIPC_READ_TEST_SOURCES) $(LWSCIIPC_WRITE_TEST_SOURCES) $(LWSCIIPC_PERF_TEST_SOURCES)

##############################################################################
# define LW_INCLUDES
##############################################################################

include $(LW_SOURCE)/drivers/unix/rmapi_tegra/mirror/rmapi_tegra_mirror.lwmk

LW_INCLUDES += $(LW_SOURCE)/sdk/lwpu/inc
LW_INCLUDES += $(LW_SOURCE)/drivers/common/inc
LW_INCLUDES += $(LWSCI_PATH)/inc/public
LW_INCLUDES += $(LWSCI_PATH)/inc/internal
LW_INCLUDES += $(LWSCI_PATH)/lwscicommon/inc
LW_INCLUDES += $(LWSCIIPC_PATH)/inc
LW_INCLUDES += $(LW_SOURCE)/sdk/lwpu/inc/class
LW_INCLUDES += $(LW_SOURCE)/drivers/lwsci/inc
LW_INCLUDES += $(LW_SOURCE)/drivers/lwsci/inc/public
LW_INCLUDES += $(LWSCIIPC_TESTS_PATH)/inc

LW_INCLUDES += $(RMAPI_TEGRA_MIRROR_INCLUDES)
LW_INCLUDES += $(OUTPUTDIR)

#############################################################################
# define DSO_STUBS
#############################################################################

include $(LWSCI_PATH)/lwsciipc/lwsciipc-dso-stub.lwmk
include $(LWSCI_PATH)/lwscievent/lwscievent-dso-stub.lwmk

STUB_DSO_DEPENDS += $(LWSCIIPC_DSO_STUB)
STUB_DSO_DEPENDS += $(LWSCIEVENT_DSO_STUB)

STUB_LDFLAGS += -llwsciipc-stub -llwscievent-stub

##############################################################################
# define LW_DEFINES
##############################################################################

# For lwmake builds, lwcfg feature flags are available to LWSCI.
ifdef LWCFG_INITIALIZED
  LW_DEFINES += LWCFG_ENABLED
endif

# Embedded defines this on the command line for their builds.
LW_BUILD_EMBEDDED ?= 0
LW_DEFINES += LW_BUILD_EMBEDDED=1
LW_NEEDS_UNSTRIPPED = 1
LW_SUPPORTS_SEPARATE_DEBUG_INFO = 1

##############################################################################
# library flags
##############################################################################

# Link in libpthread
LDFLAGS += $(PTHREAD_LDFLAGS)

LDFLAGS += -lm

ifneq ($(LW_TARGET_OS), QNX)
  # Link in Linux
  LDFLAGS += -lrt
  LDFLAGS += -lstdc++
else
  LDFLAGS += -lc++
endif

# library flags
LDFLAGS += -g
LDFLAGS += -lstdc++

LDFLAGS += -L $(OUTPUTDIR) $(STUB_LDFLAGS)
LDFLAGS += $(BIN_LDFLAGS)


# os specific flags
ifeq ($(LW_TARGET_OS),QNX)
  CFLAGS += -DQNX
else ifeq ($(LW_TARGET_OS),Linux)
  CFLAGS += -DLINUX
endif

##############################################################################
# link the binary
##############################################################################

LWSCIIPC_READ_TEST_OBJECTS = $(call BUILD_OBJECT_LIST,$(LWSCIIPC_READ_TEST_SOURCES))
LWSCIIPC_WRITE_TEST_OBJECTS = $(call BUILD_OBJECT_LIST,$(LWSCIIPC_WRITE_TEST_SOURCES))
LWSCIIPC_PERF_TEST_OBJECTS = $(call BUILD_OBJECT_LIST,$(LWSCIIPC_PERF_TEST_SOURCES))

READ_TESTAPP_BIN := test_lwsciipc_read
READ_TESTAPP := $(OUTPUTDIR)/$(READ_TESTAPP_BIN)
READ_TESTAPP_LD_TARGET = $(READ_TESTAPP).unstripped
READ_TESTAPP_DEBUG_INFO = $(READ_TESTAPP).debug
$(eval $(call LW_DEBUG_INFO_CMD, \
  $(READ_TESTAPP_LD_TARGET), \
  $(READ_TESTAPP), \
  $(READ_TESTAPP_DEBUG_INFO)))

build: $(READ_TESTAPP)

$(READ_TESTAPP_LD_TARGET): $(LWSCIIPC_READ_TEST_OBJECTS) $(STUB_DSO_DEPENDS)
	$(call quiet_cmd,LINK) $(LWSCIIPC_READ_TEST_OBJECTS) -o $(READ_TESTAPP_LD_TARGET) $(LDFLAGS)


WRITE_TESTAPP_BIN := test_lwsciipc_write
WRITE_TESTAPP := $(OUTPUTDIR)/$(WRITE_TESTAPP_BIN)
WRITE_TESTAPP_LD_TARGET = $(WRITE_TESTAPP).unstripped
WRITE_TESTAPP_DEBUG_INFO = $(WRITE_TESTAPP).debug
$(eval $(call LW_DEBUG_INFO_CMD, \
  $(WRITE_TESTAPP_LD_TARGET), \
  $(WRITE_TESTAPP), \
  $(WRITE_TESTAPP_DEBUG_INFO)))

build: $(WRITE_TESTAPP)


$(WRITE_TESTAPP_LD_TARGET): $(LWSCIIPC_WRITE_TEST_OBJECTS) $(STUB_DSO_DEPENDS)
	$(call quiet_cmd,LINK) $(LWSCIIPC_WRITE_TEST_OBJECTS) -o $(WRITE_TESTAPP_LD_TARGET) $(LDFLAGS)

PERF_TESTAPP_BIN := test_lwsciipc_perf
PERF_TESTAPP := $(OUTPUTDIR)/$(PERF_TESTAPP_BIN)
PERF_TESTAPP_LD_TARGET = $(PERF_TESTAPP).unstripped
PERF_TESTAPP_DEBUG_INFO = $(PERF_TESTAPP).debug
$(eval $(call LW_DEBUG_INFO_CMD, \
  $(PERF_TESTAPP_LD_TARGET), \
  $(PERF_TESTAPP), \
  $(PERF_TESTAPP_DEBUG_INFO)))

build: $(PERF_TESTAPP)

$(PERF_TESTAPP_LD_TARGET): $(LWSCIIPC_PERF_TEST_OBJECTS) $(STUB_DSO_DEPENDS)
	$(call quiet_cmd,LINK) $(LWSCIIPC_PERF_TEST_OBJECTS) -o $(PERF_TESTAPP_LD_TARGET) $(LDFLAGS)

##############################################################################
# include definitions of tools and build rules
##############################################################################

include $(LW_COMMON)/build/lwCommonRules.lwmk
