###############################################################################
#
# Copyright (c) 2019-2022 LWPU CORPORATION.  All Rights Reserved.
#
# LWPU CORPORATION and its licensors retain all intellectual property
# and proprietary rights in and to this software, related documentation
# and any modifications thereto.  Any use, reproduction, disclosure or
# distribution of this software and related documentation without an express
# license agreement from LWPU CORPORATION is strictly prohibited.
#
#
###############################################################################

##############################################################################
# drivers/lwsci/tests/lwscisync/makefile.lwmk
##############################################################################

##############################################################################
# Identify this module to lwCommon.lwmk so it can decide the build type
##############################################################################
include $(LW_SOURCE)/drivers/common/build/lwCommon.lwmk

LW_DIR_RELWRSION_ONLY := 1

##############################################################################
# define SUBDIRS
##############################################################################
SUBDIRS := api
SUBDIRS += kpi/kpi
SUBDIRS += kpi/fence_latency
build: $(addsuffix .build,$(SUBDIRS))

##############################################################################
include $(LW_SOURCE)/drivers/common/build/lwCommonRules.lwmk
