/* _LWRM_COPYRIGHT_BEGIN_
 *
 * Copyright 2020 by LWPU Corporation.  All rights reserved.  All information
 * contained herein is proprietary and confidential to LWPU Corporation.  Any
 * use, reproduction, or disclosure without the written permission of LWPU
 * Corporation is prohibited.
 *
 * _LWRM_COPYRIGHT_END_
 */

//*****************************************************
//
// clkga103.c - GA104 Clock lwwatch routines 
// 
//*****************************************************
#include "os.h"
#include "hal.h"
#include "clk.h"
#include "print.h"
#include "ampere/ga103/dev_trim.h"
#include "ampere/ga103/dev_trim_addendum.h"
#include "ctrl/ctrl2080/ctrl2080clk.h"

#include "g_clk_private.h"           // (rmconfig) implementation prototypes.

static CLK_FR_COUNTER_REG_INFO clkFrCounterRegInfo_GA103 = {
    LW_PTRIM_SYS_FR_CLK_CNTR_PEX_PAD_TCLKS_CFG,
    0,
    LW_PTRIM_SYS_FR_CLK_CNTR_PEX_PAD_TCLKS_CNT0,
    LW_PTRIM_SYS_FR_CLK_CNTR_PEX_PAD_TCLKS_CNT1,
};

static CLK_FR_COUNTER_SRC_INFO clkFrCounterSrcInfo_GA103[] = {
    {
        "DRAM",
        LW2080_CTRL_CLK_DOMAIN_MCLK,
        5,
        {
            {0, "MCLK[0]" },
            {1, "MCLK[1]" },
            {2, "MCLK[2]" },
            {3, "MCLK[3]" },
            {4, "MCLK[4]" },
        },
    },
    {
        "GPC",
        LW2080_CTRL_CLK_DOMAIN_GPCCLK,
        6,
        {
            {0, "GPCCLK[0]" },
            {1, "GPCCLK[1]" },
            {2, "GPCCLK[2]" },
            {3, "GPCCLK[3]" },
            {4, "GPCCLK[4]" },
            {5, "GPCCLK[5]" },
        },
    },
    {
        "HOST",
        LW2080_CTRL_CLK_DOMAIN_HOSTCLK,
        1,
        {
            {0, "HOSTCLK"},
        }
    },
    {
        "LWD",
        LW2080_CTRL_CLK_DOMAIN_LWDCLK,
        1,
        {
            {0,  "LWDCLK"},
        }
    },
    {
        "PWR",
        LW2080_CTRL_CLK_DOMAIN_PWRCLK,
        1,
        {
            {0,  "PWRCLK"},
        }
    },
    {
        "SYS",
        LW2080_CTRL_CLK_DOMAIN_SYSCLK,
        1,
        {
            {0,  "SYSCLK"},
        }
    },
    {
        "UTILS",
        LW2080_CTRL_CLK_DOMAIN_UTILSCLK,
        1,
        {
            {0,  "UTILSCLK"},
        },
    },
    {
        "XBAR",
        LW2080_CTRL_CLK_DOMAIN_XBARCLK,
        1,
        {
            {0, "XBARCLK"},
        },
    },
    {
        "DISP",
        LW2080_CTRL_CLK_DOMAIN_DISPCLK,
        1,
        {
            {0, "DISPCLK"},
        }
    },
    {
        "HUB",
        LW2080_CTRL_CLK_DOMAIN_HUBCLK,
        1,
        {
            {0,  "HUBCLK"},
        }
    },
    {
        "VCLK",
        LW2080_CTRL_CLK_DOMAIN_VCLK0,
        4,
        {
            {0,  "VCLK0"},
            {1,  "VCLK1"},
            {2,  "VCLK2"},
            {3,  "VCLK3"},
        },
    },
};

/*!
 * @brief Fetch the FR clock counter data
 *
 * @param[out]   ppClkFrCntrSrcInfo  Clock counter source info
 * @param[out]   ppClkFrCntrRegInfo  Clock counter register info
 * @param[out]   pNumCntrsToRead     Number of FR counters present
 */
LW_STATUS
clkGetFrCntrInfo_GA103
(
    CLK_FR_COUNTER_SRC_INFO** ppClkFrCntrSrcInfo,
    CLK_FR_COUNTER_REG_INFO** ppClkFrCntrRegInfo,
    LwU32*                    pNumCntrsToRead
)
{
    if ((ppClkFrCntrSrcInfo == NULL) &&
        (ppClkFrCntrRegInfo == NULL) &&
        (pNumCntrsToRead == NULL))
    {
        return LW_ERR_GENERIC;
    }

    if (ppClkFrCntrSrcInfo != NULL)
    {
        *ppClkFrCntrSrcInfo = clkFrCounterSrcInfo_GA103;
    }

    if (ppClkFrCntrRegInfo != NULL)
    {
        *ppClkFrCntrRegInfo = &clkFrCounterRegInfo_GA103;
    }

    if (pNumCntrsToRead != NULL)
    {
        *pNumCntrsToRead  = sizeof(clkFrCounterSrcInfo_GA103)/sizeof(clkFrCounterSrcInfo_GA103[0]);
    }

    return LW_OK;
}

/*!
 * @brief Set TCLKOUT source for given clock domain
 *
 * @param[in]   clkDomain   Clock domain LW2080_CTRL_CLK_DOMAIN_XX
 * @param[in]   srcIdx      Clock source srcIdx
 *
 * Generated by get_clk_domain_prog_seq_from_tclkout_pm.pl on 
 * chips_a/drivers/common/inc/hwref/<chip_family>/<chip>/tclkout_id.pm.
 * Refer https://confluence.lwpu.com/pages/viewpage.action?spaceKey=GPUC&title=TCLKOUT+Programming+Guide
 * for details.
 *
 * TODO: Auto generation of below chip specific source code by lwwatch-config
 */
LW_STATUS
clkSetSourceCntr_GA103
(
    LwU32 clkDomain,
    LwU32 srcIdx
)
{
    switch (clkDomain)
    {
        case LW2080_CTRL_CLK_DOMAIN_MCLK:
        {
            switch (srcIdx)
            {
                case 0:
                {
                    GPU_REG_WR32(LW_PTRIM_FBPA_TCLKOUT_CTRL_FBP(srcIdx), 0xc1020704);
                    GPU_REG_WR32(LW_PTRIM_SYS_TCLKOUT_CTRL_XBAR, 0xc1030101);
                    GPU_REG_WR32(LW_PTRIM_SYS_TCLKOUT_CTRL_SYS, 0xc10b0101);
                    break;
                }
                case 1:
                {
                    GPU_REG_WR32(LW_PTRIM_FBPA_TCLKOUT_CTRL_FBP(srcIdx), 0xc1020704);
                    GPU_REG_WR32(LW_PTRIM_SYS_TCLKOUT_CTRL_XBAR, 0xc1050601);
                    GPU_REG_WR32(LW_PTRIM_SYS_TCLKOUT_CTRL_SYS, 0xc10b0101);
                    break;
                }
                case 2:
                {
                    GPU_REG_WR32(LW_PTRIM_FBPA_TCLKOUT_CTRL_FBP(srcIdx), 0xc1020704);
                    GPU_REG_WR32(LW_PTRIM_SYS_TCLKOUT_CTRL_XBAR, 0xc1040401);
                    GPU_REG_WR32(LW_PTRIM_SYS_TCLKOUT_CTRL_SYS, 0xc10b0101);
                    break;
                }
                case 3:
                {
                    GPU_REG_WR32(LW_PTRIM_FBPA_TCLKOUT_CTRL_FBP(srcIdx), 0xc1020704);
                    GPU_REG_WR32(LW_PTRIM_SYS_TCLKOUT_CTRL_XBAR, 0xc1010101);
                    GPU_REG_WR32(LW_PTRIM_SYS_TCLKOUT_CTRL_SYS, 0xc10b0101);
                    break;
                }
                case 4:
                {
                    GPU_REG_WR32(LW_PTRIM_FBPA_TCLKOUT_CTRL_FBP(srcIdx), 0xc1020704);
                    GPU_REG_WR32(LW_PTRIM_SYS_TCLKOUT_CTRL_XBAR, 0xc1060701);
                    GPU_REG_WR32(LW_PTRIM_SYS_TCLKOUT_CTRL_SYS, 0xc10b0101);
                    break;
                }
                default:
                {
                    dprintf("lw: ERROR: clk Domain %x source %x not configured \n", clkDomain, srcIdx);
                    return LW_ERR_NOT_SUPPORTED;
                    break;
                }
            }
            break;
        }
        case LW2080_CTRL_CLK_DOMAIN_GPCCLK:
        {
            switch(srcIdx)
            {
                case 0:
                {
                    GPU_REG_WR32(LW_PTRIM_GPC_TCLKOUT_CTRL_GPC(srcIdx), 0xc1030401);
                    GPU_REG_WR32(LW_PTRIM_SYS_TCLKOUT_CTRL_XBAR, 0xc1050301);
                    GPU_REG_WR32(LW_PTRIM_SYS_TCLKOUT_CTRL_SYS, 0xc10b0101);
                    break;
                } 
                case 1:
                {
                    GPU_REG_WR32(LW_PTRIM_GPC_TCLKOUT_CTRL_GPC(srcIdx), 0xc1030401);
                    GPU_REG_WR32(LW_PTRIM_SYS_TCLKOUT_CTRL_XBAR, 0xc1050401);
                    GPU_REG_WR32(LW_PTRIM_SYS_TCLKOUT_CTRL_SYS, 0xc10b0101);
                    break;
                }
                case 2:
                {
                    GPU_REG_WR32(LW_PTRIM_GPC_TCLKOUT_CTRL_GPC(srcIdx), 0xc1030401);
                    GPU_REG_WR32(LW_PTRIM_SYS_TCLKOUT_CTRL_XBAR, 0xc1050501);
                    GPU_REG_WR32(LW_PTRIM_SYS_TCLKOUT_CTRL_SYS, 0xc10b0101);
                    break;
                }
                case 3:
                {
                    GPU_REG_WR32(LW_PTRIM_GPC_TCLKOUT_CTRL_GPC(srcIdx), 0xc1030401);
                    GPU_REG_WR32(LW_PTRIM_SYS_TCLKOUT_CTRL_XBAR, 0xc1040101);
                    GPU_REG_WR32(LW_PTRIM_SYS_TCLKOUT_CTRL_SYS, 0xc10b0101);
                    break;
                }
                case 4:
                {
                    GPU_REG_WR32(LW_PTRIM_GPC_TCLKOUT_CTRL_GPC(srcIdx), 0xc1030401);
                    GPU_REG_WR32(LW_PTRIM_SYS_TCLKOUT_CTRL_XBAR, 0xc1040201);
                    GPU_REG_WR32(LW_PTRIM_SYS_TCLKOUT_CTRL_SYS, 0xc10b0101);
                    break;
                }
                case 5:
                {
                    GPU_REG_WR32(LW_PTRIM_GPC_TCLKOUT_CTRL_GPC(srcIdx), 0xc1030401);
                    GPU_REG_WR32(LW_PTRIM_SYS_TCLKOUT_CTRL_XBAR, 0xc1040301);
                    GPU_REG_WR32(LW_PTRIM_SYS_TCLKOUT_CTRL_SYS, 0xc10b0101);
                    break;
                }
                default:
                {
                    dprintf("lw: ERROR: clk Domain %x source %x not configured \n", clkDomain, srcIdx);
                    return LW_ERR_NOT_SUPPORTED;
                    break;
                }
            }
            break;
        }
        case LW2080_CTRL_CLK_DOMAIN_HOSTCLK:
        {
            GPU_REG_WR32(LW_PTRIM_SYS_TCLKOUT_CTRL_SYS, 0xc10d0501);
            break;
        }
        case LW2080_CTRL_CLK_DOMAIN_LWDCLK:
        {
            GPU_REG_WR32(LW_PTRIM_SYS_TCLKOUT_CTRL_SYS, 0xc10d0701);
            break;
        }
        case LW2080_CTRL_CLK_DOMAIN_PWRCLK:
        {
            GPU_REG_WR32(LW_PTRIM_SYS_TCLKOUT_CTRL_SYS, 0xc10e0201);
            break;
        }
        case LW2080_CTRL_CLK_DOMAIN_SYSCLK:
        {
            GPU_REG_WR32(LW_PTRIM_SYS_TCLKOUT_CTRL_SYS, 0xc10d0901);
            break;
        }
        case LW2080_CTRL_CLK_DOMAIN_UTILSCLK:
        {
            GPU_REG_WR32(LW_PTRIM_SYS_TCLKOUT_CTRL_SYS, 0xc1090101);
            break;
        }
        case LW2080_CTRL_CLK_DOMAIN_XBARCLK:
        {
            GPU_REG_WR32(LW_PTRIM_SYS_TCLKOUT_CTRL_XBAR, 0xc1050101);
            GPU_REG_WR32(LW_PTRIM_SYS_TCLKOUT_CTRL_SYS, 0xc10b0101);
            break;
        }
        case LW2080_CTRL_CLK_DOMAIN_DISPCLK:
        {
            GPU_REG_WR32(LW_PTRIM_SYS_TCLKOUT_CTRL_SYS, 0xc1030323);
            break;
        }
        case LW2080_CTRL_CLK_DOMAIN_HUBCLK:
        {
            GPU_REG_WR32(LW_PTRIM_SYS_TCLKOUT_CTRL_SYS, 0xc1030201);
            break;
        }
        case LW2080_CTRL_CLK_DOMAIN_VCLK0:
        {
            switch(srcIdx)
            {
                case 0:
                {
                    GPU_REG_WR32(LW_PTRIM_SYS_TCLKOUT_CTRL_SYS, 0xc104020d);
                    break;
                }
                case 1:
                {
                    GPU_REG_WR32(LW_PTRIM_SYS_TCLKOUT_CTRL_SYS, 0xc104020e);
                    break;
                }
                case 2:
                {
                    GPU_REG_WR32(LW_PTRIM_SYS_TCLKOUT_CTRL_SYS, 0xc104020f);
                    break;
                }
                case 3:
                {
                    GPU_REG_WR32(LW_PTRIM_SYS_TCLKOUT_CTRL_SYS, 0xc1040210);
                    break;
                }
                default:
                {
                    dprintf("lw: ERROR: clk Domain %x source %x not configured \n", clkDomain, srcIdx);
                    return LW_ERR_NOT_SUPPORTED;
                    break;
                }
            }
            break;
        }
        default:
        {
            dprintf("lw: ERROR: clk Domain %x source %x not configured \n", clkDomain, srcIdx);
            return LW_ERR_NOT_SUPPORTED;
            break;
        }
    }

    return LW_OK;
}
