/* _LWRM_COPYRIGHT_BEGIN_
 *
 * Copyright 2003-2016 by LWPU Corporation.  All rights reserved.  All
 * information contained herein is proprietary and confidential to LWPU
 * Corporation.  Any use, reproduction, or disclosure without the written
 * permission of LWPU Corporation is prohibited.
 *
 * _LWRM_COPYRIGHT_END_
 */

#ifndef __cla06fsubch_h__
#define __cla06fsubch_h__
/* This file is autogenerated.  Do not edit */
#define LWA06F_SUBCHANNEL_2D                            3
#define LWA06F_SUBCHANNEL_3D                            0
#define LWA06F_SUBCHANNEL_COMPUTE                       1
#define LWA06F_SUBCHANNEL_COPY_ENGINE                   4
#define LWA06F_SUBCHANNEL_I2M                           2

//
// Temporary define to allow clients to synchronize colwersion to new LWA06F_SUBCHANNEL defines
//
#define LWA06F_USE_HARDCODED_SUBCHANNELS        1
#endif // {__cla06fsubch_h__}
