double4 dummy[100]: shared;
double2 x: shared;
int2 y : global;

void main()
{
  int2 t, u;
  double s;
  t = doubleToRawIntBits(-(-x.x - 4.6));
  t.y &= 0x7fffffff;
  x.x = intBitsToDouble(t);
  t = doubleToRawIntBits(x.y);
  t = abs(t);
  x.y = intBitsToDouble((-t*2));
  trap();
  t = doubleToRawIntBits(-x.x);
  y.x = t.x;
  trap();
  s = (x.x > 0) ? x.x + x.y : x.x + 4.5;
  t = doubleToRawIntBits(s);
  y.y = t.y;
}


