/* _LWRM_COPYRIGHT_BEGIN_
 *
 * Copyright 2018-2021 by LWPU Corporation.  All rights reserved.  All
 * information contained herein is proprietary and confidential to LWPU
 * Corporation.  Any use, reproduction, or disclosure without the written
 * permission of LWPU Corporation is prohibited.
 *
 * _LWRM_COPYRIGHT_END_
 */

/*
 * Please *DO NOT* list MODS-only IOCTLs in this file.
 *
 * This file defines IOCTLs that work with lwpu-lwswitchX (device) nodes.
 *
 * These IOCTLs are used by user-mode clients like Fabric Manager which rely on
 * driver ABI compatibility, and hence they contribute to the driver ABI version.
 *
 * These IOCTLs are used by privileged or fabric-mgmt capability user-mode
 * clients.
 */

#ifndef _IOCTL_DEVICE_LWSWITCH_H_
#define _IOCTL_DEVICE_LWSWITCH_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include "ioctl_common_lwswitch.h"
#include "ctrl_dev_lwswitch.h"

#define IOCTL_LWSWITCH_GET_INFO \
    LWSWITCH_IOCTL_CODE(LWSWITCH_DEV_IO_TYPE, CTRL_LWSWITCH_GET_INFO, LWSWITCH_GET_INFO, \
                        LWSWITCH_IO_WRITE_READ)

#define IOCTL_LWSWITCH_SET_SWITCH_PORT_CONFIG \
    LWSWITCH_IOCTL_CODE(LWSWITCH_DEV_IO_TYPE, CTRL_LWSWITCH_SET_SWITCH_PORT_CONFIG, LWSWITCH_SET_SWITCH_PORT_CONFIG, \
                        LWSWITCH_IO_WRITE_ONLY)

#define IOCTL_LWSWITCH_GET_INGRESS_REQUEST_TABLE \
    LWSWITCH_IOCTL_CODE(LWSWITCH_DEV_IO_TYPE, CTRL_LWSWITCH_GET_INGRESS_REQUEST_TABLE,  \
                        LWSWITCH_GET_INGRESS_REQUEST_TABLE_PARAMS, \
                        LWSWITCH_IO_WRITE_READ)

#define IOCTL_LWSWITCH_SET_INGRESS_REQUEST_TABLE \
    LWSWITCH_IOCTL_CODE(LWSWITCH_DEV_IO_TYPE, CTRL_LWSWITCH_SET_INGRESS_REQUEST_TABLE, LWSWITCH_SET_INGRESS_REQUEST_TABLE, \
                        LWSWITCH_IO_WRITE_ONLY)

#define IOCTL_LWSWITCH_SET_INGRESS_REQUEST_VALID \
    LWSWITCH_IOCTL_CODE(LWSWITCH_DEV_IO_TYPE, CTRL_LWSWITCH_SET_INGRESS_REQUEST_VALID, LWSWITCH_SET_INGRESS_REQUEST_VALID, \
                        LWSWITCH_IO_WRITE_ONLY)

#define IOCTL_LWSWITCH_GET_INGRESS_RESPONSE_TABLE \
    LWSWITCH_IOCTL_CODE(LWSWITCH_DEV_IO_TYPE, CTRL_LWSWITCH_GET_INGRESS_RESPONSE_TABLE, \
                        LWSWITCH_GET_INGRESS_RESPONSE_TABLE_PARAMS, \
                        LWSWITCH_IO_WRITE_READ)

#define IOCTL_LWSWITCH_SET_INGRESS_RESPONSE_TABLE \
    LWSWITCH_IOCTL_CODE(LWSWITCH_DEV_IO_TYPE, CTRL_LWSWITCH_SET_INGRESS_RESPONSE_TABLE, LWSWITCH_SET_INGRESS_RESPONSE_TABLE, \
                        LWSWITCH_IO_WRITE_ONLY)

#define IOCTL_LWSWITCH_SET_MC_RID_TABLE \
    LWSWITCH_IOCTL_CODE(LWSWITCH_DEV_IO_TYPE, CTRL_LWSWITCH_SET_MC_RID_TABLE, LWSWITCH_SET_MC_RID_TABLE_PARAMS, \
                        LWSWITCH_IO_WRITE_ONLY)

#define IOCTL_LWSWITCH_GET_MC_RID_TABLE \
    LWSWITCH_IOCTL_CODE(LWSWITCH_DEV_IO_TYPE, CTRL_LWSWITCH_GET_MC_RID_TABLE, LWSWITCH_GET_MC_RID_TABLE_PARAMS, \
                        LWSWITCH_IO_WRITE_READ)

#define IOCTL_LWSWITCH_SET_GANGED_LINK_TABLE \
    LWSWITCH_IOCTL_CODE(LWSWITCH_DEV_IO_TYPE, CTRL_LWSWITCH_SET_GANGED_LINK_TABLE, LWSWITCH_SET_GANGED_LINK_TABLE, \
                        LWSWITCH_IO_WRITE_ONLY)

#define IOCTL_LWSWITCH_GET_INTERNAL_LATENCY \
    LWSWITCH_IOCTL_CODE(LWSWITCH_DEV_IO_TYPE, CTRL_LWSWITCH_GET_INTERNAL_LATENCY, LWSWITCH_GET_INTERNAL_LATENCY, \
                        LWSWITCH_IO_WRITE_READ)

#define IOCTL_LWSWITCH_SET_LATENCY_BINS \
    LWSWITCH_IOCTL_CODE(LWSWITCH_DEV_IO_TYPE, CTRL_LWSWITCH_SET_LATENCY_BINS, LWSWITCH_SET_LATENCY_BINS, \
                        LWSWITCH_IO_WRITE_ONLY)

#define IOCTL_LWSWITCH_GET_LWLIPT_COUNTERS \
    LWSWITCH_IOCTL_CODE(LWSWITCH_DEV_IO_TYPE, CTRL_LWSWITCH_GET_LWLIPT_COUNTERS, LWSWITCH_GET_LWLIPT_COUNTERS, \
                        LWSWITCH_IO_WRITE_READ)

#define IOCTL_LWSWITCH_SET_LWLIPT_COUNTER_CONFIG \
    LWSWITCH_IOCTL_CODE(LWSWITCH_DEV_IO_TYPE, CTRL_LWSWITCH_SET_LWLIPT_COUNTER_CONFIG, LWSWITCH_SET_LWLIPT_COUNTER_CONFIG, \
                        LWSWITCH_IO_WRITE_ONLY)

#define IOCTL_LWSWITCH_GET_LWLIPT_COUNTER_CONFIG \
    LWSWITCH_IOCTL_CODE(LWSWITCH_DEV_IO_TYPE, CTRL_LWSWITCH_GET_LWLIPT_COUNTER_CONFIG, LWSWITCH_GET_LWLIPT_COUNTER_CONFIG, \
                        LWSWITCH_IO_WRITE_READ)

#define IOCTL_LWSWITCH_GET_ERRORS \
    LWSWITCH_IOCTL_CODE(LWSWITCH_DEV_IO_TYPE, CTRL_LWSWITCH_GET_ERRORS, LWSWITCH_GET_ERRORS_PARAMS, \
                        LWSWITCH_IO_WRITE_READ)

#define IOCTL_LWSWITCH_SET_REMAP_POLICY \
    LWSWITCH_IOCTL_CODE(LWSWITCH_DEV_IO_TYPE, CTRL_LWSWITCH_SET_REMAP_POLICY, LWSWITCH_SET_REMAP_POLICY, \
                        LWSWITCH_IO_WRITE_ONLY)

#define IOCTL_LWSWITCH_GET_REMAP_POLICY \
    LWSWITCH_IOCTL_CODE(LWSWITCH_DEV_IO_TYPE, CTRL_LWSWITCH_GET_REMAP_POLICY, LWSWITCH_GET_REMAP_POLICY_PARAMS, \
                        LWSWITCH_IO_WRITE_READ)

#define IOCTL_LWSWITCH_SET_REMAP_POLICY_VALID \
    LWSWITCH_IOCTL_CODE(LWSWITCH_DEV_IO_TYPE, CTRL_LWSWITCH_SET_REMAP_POLICY_VALID, LWSWITCH_SET_REMAP_POLICY_VALID, \
                        LWSWITCH_IO_WRITE_ONLY)

#define IOCTL_LWSWITCH_SET_ROUTING_ID \
    LWSWITCH_IOCTL_CODE(LWSWITCH_DEV_IO_TYPE, CTRL_LWSWITCH_SET_ROUTING_ID, LWSWITCH_SET_ROUTING_ID, \
                        LWSWITCH_IO_WRITE_ONLY)

#define IOCTL_LWSWITCH_GET_ROUTING_ID \
    LWSWITCH_IOCTL_CODE(LWSWITCH_DEV_IO_TYPE, CTRL_LWSWITCH_GET_ROUTING_ID, LWSWITCH_GET_ROUTING_ID_PARAMS, \
                        LWSWITCH_IO_WRITE_READ)

#define IOCTL_LWSWITCH_SET_ROUTING_ID_VALID \
    LWSWITCH_IOCTL_CODE(LWSWITCH_DEV_IO_TYPE, CTRL_LWSWITCH_SET_ROUTING_ID_VALID, LWSWITCH_SET_ROUTING_ID_VALID, \
                        LWSWITCH_IO_WRITE_ONLY)

#define IOCTL_LWSWITCH_SET_ROUTING_LAN \
    LWSWITCH_IOCTL_CODE(LWSWITCH_DEV_IO_TYPE, CTRL_LWSWITCH_SET_ROUTING_LAN, LWSWITCH_SET_ROUTING_LAN, \
                        LWSWITCH_IO_WRITE_ONLY)

#define IOCTL_LWSWITCH_GET_ROUTING_LAN \
    LWSWITCH_IOCTL_CODE(LWSWITCH_DEV_IO_TYPE, CTRL_LWSWITCH_GET_ROUTING_LAN, LWSWITCH_GET_ROUTING_LAN_PARAMS, \
                        LWSWITCH_IO_WRITE_READ)

#define IOCTL_LWSWITCH_SET_ROUTING_LAN_VALID \
    LWSWITCH_IOCTL_CODE(LWSWITCH_DEV_IO_TYPE, CTRL_LWSWITCH_SET_ROUTING_LAN_VALID, LWSWITCH_SET_ROUTING_LAN_VALID, \
                        LWSWITCH_IO_WRITE_ONLY)

#define IOCTL_LWSWITCH_GET_INGRESS_REQLINKID \
    LWSWITCH_IOCTL_CODE(LWSWITCH_DEV_IO_TYPE, CTRL_LWSWITCH_GET_INGRESS_REQLINKID, LWSWITCH_GET_INGRESS_REQLINKID_PARAMS, \
                        LWSWITCH_IO_WRITE_READ)

#define IOCTL_LWSWITCH_UNREGISTER_LINK \
    LWSWITCH_IOCTL_CODE(LWSWITCH_DEV_IO_TYPE, CTRL_LWSWITCH_UNREGISTER_LINK, LWSWITCH_UNREGISTER_LINK_PARAMS, \
                        LWSWITCH_IO_WRITE_ONLY)

#define IOCTL_LWSWITCH_RESET_AND_DRAIN_LINKS \
    LWSWITCH_IOCTL_CODE(LWSWITCH_DEV_IO_TYPE, CTRL_LWSWITCH_RESET_AND_DRAIN_LINKS, LWSWITCH_RESET_AND_DRAIN_LINKS_PARAMS, \
                        LWSWITCH_IO_WRITE_ONLY)

#define IOCTL_LWSWITCH_GET_LWLINK_STATUS\
    LWSWITCH_IOCTL_CODE(LWSWITCH_DEV_IO_TYPE, CTRL_LWSWITCH_GET_LWLINK_STATUS, LWSWITCH_GET_LWLINK_STATUS_PARAMS, \
                        LWSWITCH_IO_READ_ONLY)

#define IOCTL_LWSWITCH_ACQUIRE_CAPABILITY \
    LWSWITCH_IOCTL_CODE(LWSWITCH_DEV_IO_TYPE, CTRL_LWSWITCH_ACQUIRE_CAPABILITY, LWSWITCH_ACQUIRE_CAPABILITY_PARAMS, \
                        LWSWITCH_IO_WRITE_ONLY)

#define IOCTL_LWSWITCH_GET_TEMPERATURE \
    LWSWITCH_IOCTL_CODE(LWSWITCH_DEV_IO_TYPE, CTRL_LWSWITCH_GET_TEMPERATURE, LWSWITCH_CTRL_GET_TEMPERATURE_PARAMS, \
                        LWSWITCH_IO_WRITE_READ)

#define IOCTL_LWSWITCH_GET_THROUGHPUT_COUNTERS \
    LWSWITCH_IOCTL_CODE(LWSWITCH_DEV_IO_TYPE, CTRL_LWSWITCH_GET_THROUGHPUT_COUNTERS, LWSWITCH_GET_THROUGHPUT_COUNTERS_PARAMS, \
                        LWSWITCH_IO_WRITE_READ)

#define IOCTL_LWSWITCH_GET_BIOS_INFO \
    LWSWITCH_IOCTL_CODE(LWSWITCH_DEV_IO_TYPE, CTRL_LWSWITCH_GET_BIOS_INFO, LWSWITCH_GET_BIOS_INFO_PARAMS, \
                        LWSWITCH_IO_WRITE_READ)

#define IOCTL_LWSWITCH_BLACKLIST_DEVICE \
    LWSWITCH_IOCTL_CODE(LWSWITCH_DEV_IO_TYPE, CTRL_LWSWITCH_BLACKLIST_DEVICE, LWSWITCH_BLACKLIST_DEVICE_PARAMS, \
                        LWSWITCH_IO_WRITE_ONLY)

#define IOCTL_LWSWITCH_SET_FM_DRIVER_STATE \
    LWSWITCH_IOCTL_CODE(LWSWITCH_DEV_IO_TYPE, CTRL_LWSWITCH_SET_FM_DRIVER_STATE, LWSWITCH_SET_FM_DRIVER_STATE_PARAMS, \
                        LWSWITCH_IO_WRITE_ONLY)

#define IOCTL_LWSWITCH_SET_DEVICE_FABRIC_STATE \
    LWSWITCH_IOCTL_CODE(LWSWITCH_DEV_IO_TYPE, CTRL_LWSWITCH_SET_DEVICE_FABRIC_STATE, LWSWITCH_SET_DEVICE_FABRIC_STATE_PARAMS, \
                        LWSWITCH_IO_WRITE_ONLY)

#define IOCTL_LWSWITCH_SET_FM_HEARTBEAT_TIMEOUT \
    LWSWITCH_IOCTL_CODE(LWSWITCH_DEV_IO_TYPE, CTRL_LWSWITCH_SET_FM_HEARTBEAT_TIMEOUT, LWSWITCH_SET_FM_HEARTBEAT_TIMEOUT_PARAMS, \
                        LWSWITCH_IO_WRITE_ONLY)

#define IOCTL_LWSWITCH_REGISTER_EVENTS \
    LWSWITCH_IOCTL_CODE(LWSWITCH_DEV_IO_TYPE, CTRL_LWSWITCH_REGISTER_EVENTS, LWSWITCH_REGISTER_EVENTS_PARAMS, \
                        LWSWITCH_IO_WRITE_ONLY)

#define IOCTL_LWSWITCH_UNREGISTER_EVENTS \
    LWSWITCH_IOCTL_CODE(LWSWITCH_DEV_IO_TYPE, CTRL_LWSWITCH_UNREGISTER_EVENTS, LWSWITCH_UNREGISTER_EVENTS_PARAMS, \
                        LWSWITCH_IO_WRITE_ONLY)

#define IOCTL_LWSWITCH_SET_TRAINING_ERROR_INFO \
    LWSWITCH_IOCTL_CODE(LWSWITCH_DEV_IO_TYPE, CTRL_LWSWITCH_SET_TRAINING_ERROR_INFO, LWSWITCH_SET_TRAINING_ERROR_INFO_PARAMS, \
                        LWSWITCH_IO_WRITE_ONLY)

#define IOCTL_LWSWITCH_GET_FATAL_ERROR_SCOPE \
    LWSWITCH_IOCTL_CODE(LWSWITCH_DEV_IO_TYPE, CTRL_LWSWITCH_GET_FATAL_ERROR_SCOPE, LWSWITCH_GET_FATAL_ERROR_SCOPE_PARAMS, \
                        LWSWITCH_IO_READ_ONLY)

#define IOCTL_LWSWITCH_GET_LWLINK_COUNTERS \
    LWSWITCH_IOCTL_CODE(LWSWITCH_DEV_IO_TYPE, CTRL_LWSWITCH_GET_COUNTERS, LWSWITCH_LWLINK_GET_COUNTERS_PARAMS, \
                        LWSWITCH_IO_WRITE_READ)

#define IOCTL_LWSWITCH_GET_LWLINK_ECC_ERRORS \
    LWSWITCH_IOCTL_CODE(LWSWITCH_DEV_IO_TYPE, CTRL_LWSWITCH_GET_LWLINK_ECC_ERRORS, LWSWITCH_GET_LWLINK_ECC_ERRORS_PARAMS, \
                        LWSWITCH_IO_WRITE_READ)

#define IOCTL_LWSWITCH_I2C_SMBUS_COMMAND \
    LWSWITCH_IOCTL_CODE(LWSWITCH_DEV_IO_TYPE, CTRL_LWSWITCH_I2C_SMBUS_COMMAND, LWSWITCH_I2C_SMBUS_COMMAND_PARAMS, \
                        LWSWITCH_IO_WRITE_READ)

#if (!defined(LWRM_UNPUBLISHED_OPAQUE) || LWRM_UNPUBLISHED_OPAQUE == 1)
#define IOCTL_LWSWITCH_CCI_CMIS_PRESENCE \
    LWSWITCH_IOCTL_CODE(LWSWITCH_DEV_IO_TYPE, CTRL_LWSWITCH_CCI_CMIS_PRESENCE, LWSWITCH_CCI_CMIS_PRESENCE_PARAMS, \
                        LWSWITCH_IO_READ_ONLY)

#define IOCTL_LWSWITCH_CCI_CMIS_LWLINK_MAPPING \
    LWSWITCH_IOCTL_CODE(LWSWITCH_DEV_IO_TYPE, CTRL_LWSWITCH_CCI_CMIS_LWLINK_MAPPING, LWSWITCH_CCI_CMIS_LWLINK_MAPPING_PARAMS, \
                        LWSWITCH_IO_WRITE_READ)

#define IOCTL_LWSWITCH_CCI_CMIS_MEMORY_ACCESS_READ \
    LWSWITCH_IOCTL_CODE(LWSWITCH_DEV_IO_TYPE, CTRL_LWSWITCH_CCI_CMIS_MEMORY_ACCESS_READ, LWSWITCH_CCI_CMIS_MEMORY_ACCESS_READ_PARAMS, \
                        LWSWITCH_IO_WRITE_READ)

#define IOCTL_LWSWITCH_CCI_CMIS_MEMORY_ACCESS_WRITE \
    LWSWITCH_IOCTL_CODE(LWSWITCH_DEV_IO_TYPE, CTRL_LWSWITCH_CCI_CMIS_MEMORY_ACCESS_WRITE, LWSWITCH_CCI_CMIS_MEMORY_ACCESS_WRITE_PARAMS, \
                        LWSWITCH_IO_WRITE_READ)

#define IOCTL_LWSWITCH_CCI_CMIS_CAGE_BEZEL_MARKING \
    LWSWITCH_IOCTL_CODE(LWSWITCH_DEV_IO_TYPE, CTRL_LWSWITCH_CCI_CMIS_CAGE_BEZEL_MARKING, LWSWITCH_CCI_CMIS_CAGE_BEZEL_MARKING_PARAMS, \
                        LWSWITCH_IO_WRITE_READ)

#define IOCTL_LWSWITCH_CCI_GET_GRADING_VALUES \
    LWSWITCH_IOCTL_CODE(LWSWITCH_DEV_IO_TYPE, CTRL_LWSWITCH_CCI_GET_GRADING_VALUES, LWSWITCH_CCI_GET_GRADING_VALUES_PARAMS, \
                        LWSWITCH_IO_WRITE_READ)
#endif //(!defined(LWRM_UNPUBLISHED_OPAQUE) || LWRM_UNPUBLISHED_OPAQUE == 1)

#define IOCTL_LWSWITCH_GET_TEMPERATURE_LIMIT \
    LWSWITCH_IOCTL_CODE(LWSWITCH_DEV_IO_TYPE, CTRL_LWSWITCH_GET_TEMPERATURE_LIMIT, LWSWITCH_CTRL_GET_TEMPERATURE_LIMIT_PARAMS, \
                        LWSWITCH_IO_WRITE_READ)

#define IOCTL_LWSWITCH_GET_LWLINK_MAX_ERROR_RATES \
    LWSWITCH_IOCTL_CODE(LWSWITCH_DEV_IO_TYPE, CTRL_LWSWITCH_GET_LWLINK_MAX_ERROR_RATES, LWSWITCH_GET_LWLINK_MAX_CORRECTABLE_ERROR_RATES_PARAMS, \
                        LWSWITCH_IO_WRITE_READ)

#define IOCTL_LWSWITCH_GET_LWLINK_ERROR_COUNTS \
    LWSWITCH_IOCTL_CODE(LWSWITCH_DEV_IO_TYPE, CTRL_LWSWITCH_GET_LWLINK_ERROR_COUNTS, LWSWITCH_GET_LWLINK_ERROR_COUNTS_PARAMS, \
                        LWSWITCH_IO_WRITE_READ)

#define IOCTL_LWSWITCH_GET_ECC_ERROR_COUNTS \
    LWSWITCH_IOCTL_CODE(LWSWITCH_DEV_IO_TYPE, CTRL_LWSWITCH_GET_ECC_ERROR_COUNTS, LWSWITCH_GET_ECC_ERROR_COUNTS_PARAMS, \
                        LWSWITCH_IO_WRITE_READ)

#define IOCTL_LWSWITCH_GET_SXIDS \
    LWSWITCH_IOCTL_CODE(LWSWITCH_DEV_IO_TYPE, CTRL_LWSWITCH_GET_SXIDS, LWSWITCH_GET_SXIDS_PARAMS, \
                        LWSWITCH_IO_WRITE_READ)

#define IOCTL_LWSWITCH_GET_FOM_VALUES \
    LWSWITCH_IOCTL_CODE(LWSWITCH_DEV_IO_TYPE, CTRL_LWSWITCH_GET_FOM_VALUES, LWSWITCH_GET_FOM_VALUES_PARAMS, \
                        LWSWITCH_IO_WRITE_READ)

#define IOCTL_LWSWITCH_GET_LWLINK_LP_COUNTERS \
    LWSWITCH_IOCTL_CODE(LWSWITCH_DEV_IO_TYPE, CTRL_LWSWITCH_GET_LWLINK_LP_COUNTERS, LWSWITCH_GET_LWLINK_LP_COUNTERS_PARAMS, \
                        LWSWITCH_IO_WRITE_READ)

#define IOCTL_LWSWITCH_SET_RESIDENCY_BINS \
    LWSWITCH_IOCTL_CODE(LWSWITCH_DEV_IO_TYPE, CTRL_LWSWITCH_SET_RESIDENCY_BINS, LWSWITCH_SET_RESIDENCY_BINS, \
                        LWSWITCH_IO_WRITE_ONLY)

#define IOCTL_LWSWITCH_GET_RESIDENCY_BINS \
    LWSWITCH_IOCTL_CODE(LWSWITCH_DEV_IO_TYPE, CTRL_LWSWITCH_GET_RESIDENCY_BINS, LWSWITCH_GET_RESIDENCY_BINS, \
                        LWSWITCH_IO_WRITE_READ)

#define IOCTL_LWSWITCH_GET_RB_STALL_BUSY \
    LWSWITCH_IOCTL_CODE(LWSWITCH_DEV_IO_TYPE, CTRL_LWSWITCH_GET_RB_STALL_BUSY, LWSWITCH_GET_RB_STALL_BUSY, \
                        LWSWITCH_IO_WRITE_READ)

#ifdef __cplusplus
}
#endif

#endif //_IOCTL_DEVICE_LWSWITCH_H_
